### ISSUE TITLE
Help with clink.argmatcher

### ISSUE THREAD

**Issue by sebthom** [chrisant996/clink#100]
I am trying to create my first clink completion. I want to create auto-completion for java and I am struggling with the `-Dkey=value` flag.

I thought about doing this:
```lua
clink.argmatcher("java"):addflags(
  "-D"..clink.argmatcher():addarg("http.proxyHost=","http.proxyPort=")
)
```
However, when I do `<tab>` for completion, clink adds a whitespace after the `-D`, e.g. `-D http.proxyHost=` but it needs to be `-Dhttp.proxyHost=`.

How can I achieve this?

**Comment by chrisant996** [comment]
> I am trying to create my first clink completion. I want to create auto-completion for java and I am struggling with the `-Dkey=value` flag.
> 
> I thought about doing this:
> ```lua
> clink.argmatcher("java"):addflags(
>   "-D"..clink.argmatcher():addarg("http.proxyHost=","http.proxyPort=")
> )
> ```
> However, when I do `<tab>` for completion, clink adds a whitespace after the `-D`, e.g. `-D http.proxyHost=` but it needs to be `-Dhttp.proxyHost=`.
> 
> How can I achieve this?

If the set of `key` possibilities is relatively small, the simplest solution is to add `"-Dkey1=", "-Dkey2=",` etc.

Right now that's the only way to do it with an argmatcher (or even with a generator).

There's an entry in the TODO.md file about some improvements I'd like to make to give argmatchers more control over this sort of thing. But that's not coming in the near future, I don't think.

**Comment by sebthom** [comment]
Ok, thanks!
