### ISSUE TITLE
how to suppress clink output on command prompt load

### ISSUE THREAD

**Issue by wswind** [chrisant996/clink#104]
like the issue described below , I want to suppress the prompt too.
https://github.com/mridgers/clink/issues/430
Is it supported on this fork ?

**Comment by wswind** [comment]
autorun install should support the args of clink inject, but when I use `clink autorun install -q`
it returns: 
```
autorun: invalid option -- '-q'
```

I did as the help text says :
```
clink autorun install --help

Usage: autorun [options] <verb> [<string>] [-- <clink_args>]
Verbs:
  install <args...>  Installs a command to cmd.exe's autorun to start Clink
 All '<args>' that follow 'install' are passed to
Clink - see 'clink inject --help' for reference.
```
```
clink inject --help

Options:
  -s, --scripts <path>  Alternative path to load .lua scripts from.
  -p, --profile <path>  Specifies an alternative path for profile data.
  -q, --quiet           Suppress copyright output.
  -d, --pid <pid>       Inject into the process specified by <pid>.
  -l, --nolog           Disable file logging.
  -h, --help            Shows this help text.
```

**Comment by chrisant996** [comment]
It looks like the command is missing the `--` as indicated in the cited documentation.

> `Usage: autorun [options] <verb> [<string>] [-- <clink_args>]`

So this:

`clink autorun install -- -q`

Double minus signs is a common syntax that means that rest of the command line should be taken literally, without interpreting flags.  That's needed here in order prevent the -q from being interpreted as affecting the autorun install command, and allow it to be passed to the inject call.

**Comment by wswind** [comment]
Yeah, it works . Double minus is missing.  

BTW this repo is great , Thanks for the support.

**Comment by chrisant996** [comment]
The help text has been clarified now (#122 reported the same thing).
