### ISSUE TITLE
Copy/replace upgrade in cmder, Unable to inject Clink

### ISSUE THREAD

**Issue by tsimmons** [chrisant996/clink#107]
This may have been the case all along (failures to inject as cmder starts, I see that you have added logging when `clink inject` fails) but I am now seeing four instances of:

```
Unable to inject Clink.
See log file for details (C:\Users\***\AppData\Local\clink\clink.log).
```

When starting cmder. The contents of the log file are:

```
2564 initialise_clink          121 ---- 2021/04/23 09:09:14.710 -------------------------------------------------
2564 initialise_clink          122 Host process is 'cmd.exe' (pid 9572)
2564 initialise_clink          126 DLL path is 'C:\Program Files\cmder_mini\vendor\clink'
2564 initialise_clink          140 Windows version 10.0.19042 (x64)
2564 initialise_clink          143 Clink version 1.2.3.e9c3d7 (x64)
2564 initialise_clink          173 Host validation failed.
```

Reverting to 1.2.2 shows no errors on cmder startup (albeit it may be failing the same, but silently.)

I guess my real question is, is clink 1.2.3 working properly in cmder, what is the best way to check? Please advise. Thanks!

**Comment by tsimmons** [comment]
I have answered part of my own question, it appears to be injected (pressing CTRL-ALT-U moves up one directory) but the log message 

```
Unable to inject Clink.
See log file for details ...
```

appears over and over again as Clink operations are called.

**Comment by chrisant996** [comment]
Can you please confirm that Clink is installed for autorun?

I didn't realize that Clink has an optimization to skip injecting into a cmd.exe that it can see will never be interactive.  When it skips injection for that reason, it's still reporting it as a failure, but it should not.  Will fix that shortly.

**Comment by tsimmons** [comment]
I think so. It runs fine with cmd.exe (no error messages are logged at all, everything works as expected) ... only seeing it with cmder_mini (v1.3.18)
