### ISSUE TITLE
Setup causes "System error"

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#117]
At the end of the setup (`clink.1.2.8.516b24_setup.exe`) I get these system error message two times:

![image](https://user-images.githubusercontent.com/29235332/118928852-14094a80-b944-11eb-99b9-9cc58ba7566b.png)

("The code execution cannot continue because clink_dll_x86.dll was not found. Reinstalling the program may fix the problem.")

Maybe the problem is caused because I have setup clink autorun _for all users_, the setup routines are using some commandline stuff in background but the setup itself has removed the previous installation shortly before?

**Comment by chrisant996** [comment]
Oh, do you mean you did the following?
1. Installed an earlier version of Clink (before v1.2.8).
2. Manually ran `clink autorun install -a` in an elevated window to set up autorun for All Users.
3. Uninstalled the earlier version of Clink either before or after installing Clink v1.2.8.

That would indeed result in autorun being set up wrong for All Users.  The Clink uninstaller can't undo that because (1) it wasn't done by the installer program and (2) the uninstaller isn't elevated as Administrator so it couldn't change the All Users configuration.  One would have to manually use `clink autorun uninstall -a` in an elevated window to undo that, just like one had to manually use `clink autorun install -a` to set it up.

**Comment by bw1faeh0** [comment]
> 1. Installed an earlier version of Clink (before v1.2.8).

Exactly

> 2. Manually ran `clink autorun install -a` in an elevated window to set up autorun for All Users.

Exactly

> 3. Uninstalled the earlier version of Clink either before or after installing Clink v1.2.8.

Yes and no. 
I uninstalled the earlier version of Clink not by myself. The installer of Clink v1.2.8 did this automaticaly (it was listed in the log of the install process).
Maybe the uninstaller of future versions could check for the "autorun for all users" state and ask for elevated execution if "autorun for all users" is enabled to perform a clean uninstall?

**Comment by chrisant996** [comment]
I looked into this more, and the installer already uninstalls autorun for All Users.

It successfully uninstalls autorun for All Users for me.

Maybe this only occurs when upgrading from one version to another.

**Comment by bw1faeh0** [comment]
> Does it continue to happen?

I'll check it with your next release.

> What version of Windows is being used?

Windows 10 Enterprise | 1909 | 18363.1556

> Are any other programs set up for autorun?

Of course! (KeyCard Application, Citrix, DisplayLink stuff, Passwordmanager, Greenshot, LogiOptions, MS OneDrive, MS Teams, Ricoh stuff, Trend Micro, etc.)

> Any other ideas what could be different on the computer where the error happened?

My only idea is that it could relate to the fact that I switched from this
![image](https://user-images.githubusercontent.com/29235332/119608013-8d49e700-bdf5-11eb-96cb-88f869b2a6a2.png)
to this
![image](https://user-images.githubusercontent.com/29235332/119608182-d437dc80-bdf5-11eb-8018-9ca8cfce8e46.png)
manually.

**Comment by chrisant996** [comment]
> > Are any other programs set up for autorun?
> 
> Of course! (KeyCard Application, Citrix, DisplayLink stuff, Passwordmanager, Greenshot, LogiOptions, MS OneDrive, MS Teams, Ricoh stuff, Trend Micro, etc.)

I'm asking about the CMD AutoRun registry key that runs programs every time a new CMD.exe is started.

I think the list above is about programs configured to start when Windows starts, which is a different thing.

> My only idea is that it could relate to the fact that I switched from this
> ![image](https://user-images.githubusercontent.com/29235332/119608013-8d49e700-bdf5-11eb-96cb-88f869b2a6a2.png)
> to this
> ![image](https://user-images.githubusercontent.com/29235332/119608182-d437dc80-bdf5-11eb-8018-9ca8cfce8e46.png)
> manually.

I've tried many variations of the stated repro steps, and I can't get the error to happen.

Is the user account that uninstalls Clink and Administrator on the computer?

**Comment by bw1faeh0** [comment]
>I'm asking about the CMD AutoRun registry key that runs programs every time a new CMD.exe is started.

Sorry, I missunderstood

> Is the user account that uninstalls Clink and Administrator on the computer?

Yes

**Comment by chrisant996** [comment]
Ah, it looks like it's probably a timing issue with the `ExecShell` command in the installer.  I'm not sure when `ExecWait` became available in the installer API, but maybe it's more recent than when Martin made Clink's installer.

So it's random whether the issue will occur -- it's influenced by the CPU speed of the computer, the speed of the installation drive, and what other work the computer is doing in the background.

Anyway, it looks like changing to use `ExecWait` might resolve the timing issue.

**Comment by chrisant996** [comment]
Confirmed -- `ExecShellWait` fixes the issue.  Fixed by f4b6b4f5f87e8c1019222f6a0426b140e998c97d.
