### ISSUE TITLE
Does not always work in a Parallels virtual machine on Apple silicon

### ISSUE THREAD

**Issue by danielsteinmann** [chrisant996/clink#120]
I am running Windows 10 ARM as a Parallels VM on Apple silicon.

clink does not inject itself into a cmd, unless I get a cmd shell which runs as administrator that is launched by the utility [mqsicommandconsole](https://www.ibm.com/docs/en/integration-bus/10.0?topic=commands-mqsicommandconsole-command) provided by IBM. Just starting cmd as administrator also does not work.

When the injection works, I noticed following environment variables:
```
C:\Program Files\IBM\IIB\10.0.0.23>set PROC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=ARMv8 (64-bit) Family 8 Model 0 Revision   0, Apple
PROCESSOR_LEVEL=0
PROCESSOR_REVISION=0000
```

When the injection does not work, I see the following (notice the difference in `PROCESSOR_ARCHITECTURE`):
```
C:\Program Files\IBM\IIB\10.0.0.23>set PROC
PROCESSOR_ARCHITECTURE=ARM64
PROCESSOR_IDENTIFIER=ARMv8 (64-bit) Family 8 Model 0 Revision   0, Apple
PROCESSOR_LEVEL=0
PROCESSOR_REVISION=0000
```

I see that `clink.bat` uses the architecture flag, so I tried the following:
```
C:\Program Files (x86)\clink\1.2.8.516b24>set PROCESSOR_ARCHITECTURE=AMD64

C:\Program Files (x86)\clink\1.2.8.516b24>clink.bat inject --autorun --profile ~\clink
Unable to inject Clink.
See log file for details (C:\Users\daniel\AppData\Local\clink\clink.log).

C:\Program Files (x86)\clink\1.2.8.516b24>type C:\Users\daniel\AppData\Local\clink\clink.log
1bf4 inject                    463 ---- 2021/05/25 10:40:47.486 -------------------------------------------------
1bf4 inject                    464 Injecting Clink...
1bf4 inject_dll                203 Version: 1.2.8.516b24
1bf4 inject_dll                204 Arch: x64
1bf4 inject_dll                205 DLL: C:\Users\daniel\AppData\Local\Temp\clink\dll_cache\1.2.8.516b24_11ab1f5d\clink_dll_x64.dll
1bf4 inject_dll                207 Parent pid: 8288
1bf4 check_dll_version         159 DLL version: 00010002 00080000
```

What else can I try to get it working for normal shells?

**Comment by chrisant996** [comment]
Clink requires x86 or x64. There is not an ARM version of Clink.

**Comment by danielsteinmann** [comment]
> Clink requires x86 or x64. There is not an ARM version of Clink.

I know, but interestingly enough it works when cmd gets started with the IBM command `mqsicommandconsole`. I was just wondering if you could give me some tips to find out why it works there, but not when I start plain `cmd`.

**Comment by danielsteinmann** [comment]
Just found a workaround: From a regular `cmd` start another `cmd` like this:
```
Microsoft Windows [Version 10.0.21387.1]
(c) Microsoft Corporation. All rights reserved.

C:\Users\daniel>powershell -Command "Start-Process 'cmd.exe'"
```
Then `clink` is loaded started:
```
Microsoft Windows [Version 10.0.21387.1]
(c) Microsoft Corporation. All rights reserved.

Clink v1.2.8.516b24
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2021 Christopher Antos
https://github.com/chrisant996/clink

C:\Users\daniel>
```
I don't understand why this indirection via Powershell is necessary, but it works.
