### ISSUE TITLE
`onfiltermatches()` receives one fewer matches than it should

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#124]
Hi!

I was trying to use the example script mentioned in the docs here https://chrisant996.github.io/clink/clink.html#filtering-match-completions

But I think there's a bug there that I'm facing. When my inputrc contains `"\t": complete`, this is what I get on pressing Tab:

```
81% 12:02:08 - RashilGandhi in [cmd] ~
❯ dir AppData\
 Volume in drive C is Windows
 Volume Serial Number is C403-7EF9

 Directory of C:\Users\RashilGandhi\AppData

26-05-2021  02:52    <DIR>          Local
25-05-2021  13:13    <DIR>          LocalLow
31-05-2021  12:10    <DIR>          Roaming
               0 File(s)              0 bytes
               3 Dir(s)  32,172,535,808 bytes free


81% 12:02:15 - RashilGandhi in [cmd] ~
❯ nano AppData\
Local\     LocalLow\  Roaming\

81% 12:02:15 - RashilGandhi in [cmd] ~
❯ nano AppData\

```

3 completion items are shown, as expected. But when I put `TAB: "luafunc:fzf_complete"` in inputrc:

```
84% 12:05:25 - RashilGandhi in [cmd] ~
❯ dir AppData\
 Volume in drive C is Windows
 Volume Serial Number is C403-7EF9

 Directory of C:\Users\RashilGandhi\AppData

26-05-2021  02:52    <DIR>          Local
25-05-2021  13:13    <DIR>          LocalLow
31-05-2021  12:10    <DIR>          Roaming
               0 File(s)              0 bytes
               3 Dir(s)  32,174,206,976 bytes free


84% 12:05:27 - RashilGandhi in [cmd] ~
❯ nano AppData\
>
  2/2
> AppData\Local\
  AppData\LocalLow\
  
```

This list is only showing 2 items. I have observed this behaviour in all files/directories. Always 1 less item is shown. The last item is not shown.

I don't think the bug is in Fzf as `dir /b AppData\ | fzf` correctly shows 3 items.

**Comment by chrisant996** [comment]
It's not a bug in the script.  The script only receives 2 matches.  Looks like something is going wrong inside Clink, resulting in one fewer matches than there should be.

**Comment by rashil2000** [comment]
Thanks for the fix!
