### ISSUE TITLE
[Feature Request] Last command duration

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#131]
Bash has the ability to execute `precmd` hooks - that run before every typed command. This allows us to capture a 'before' time and an 'after' time, effectively telling us how long a command took. 

PowerShell stores history as objects, and those objects have the `Duration` parameter built-in.

Is this something that's possible under Clink's purview?

**Comment by chrisant996** [comment]
We discussed `clink.onendedit()` and `clink.onbeginedit()` recently.
Does it make sense how to use them?

**Comment by rashil2000** [comment]
> I'm not going to build a history database with fields about commands that have run.

This wasn't what I was suggesting. Even bash doesn't.

> But we discussed clink.onendedit() and clink.onbeginedit() recently. 

This sounds similar to bash's precmd. I'll see if I can write a script to calculate time, and then close the issue.

**Comment by rashil2000** [comment]
I wrote this:

```lua
-- Enable Starship prompt
os.setenv('STARSHIP_SHELL', 'cmd')
local custom_prompt = clink.promptfilter(5)
local starship_exe = "C:\\Users\\RashilGandhi\\.cargo\\bin\\starship.exe"

local function unix_time()
  return tonumber(io.popen(starship_exe.." time"):read("*a"))
end

start_time = unix_time()
end_time = 0

clink.onbeginedit(function () end_time = unix_time() end)
clink.onendedit(function () start_time = unix_time() end)

function custom_prompt:filter(prompt)
  return io.popen(starship_exe.." prompt --cmd-duration="..(end_time - start_time)):read("*a")
end
```

This slows down prompts a bit, but it works!
