### ISSUE TITLE
[BUG] 1.2.14 Prompt is not visible

### ISSUE THREAD

**Issue by char101** [chrisant996/clink#132]
Hi,

With 1.2.14, the prompt initially is not visible other than `>`. I have to press Enter to show the prompt.

![2021-06-22 11_12_02-Window](https://user-images.githubusercontent.com/71255/122862050-b739ef00-d34a-11eb-8ee3-2124a78a8bc7.png)

I tested:
1. not setting `PROMPT` or promptfilter, prompt is displayed as `[DRIVE]>`
2. setting `PROMPT` or promptfilter, prompt is only displayed as `>`. I have to press enter to show the prompt.

I tested with 1.2.13 and the prompt is displayed initially. So this seems to be a regression with 1.2.14.

**Comment by char101** [comment]
Futher info:

* I am using ConsoleZ as the host
* It only happens when restoring a workspace (File -> Save Workspace, then load the workspace using `Console.exe -ws default.workspace`)

**Comment by chrisant996** [comment]
Is Clink set up for autorun?

**Comment by char101** [comment]
No,

In ConsoleZ settings, I use `cmd.exe /k C:\Apps\Utils\Console\startup.bat` as the Shell command.

In startup.bat, I have

```
set clink_inputrc=%~dp0clink\profile
%~dp0clink\clink_x64.exe inject --profile %~dp0clink\profile --quiet
```

**Comment by chrisant996** [comment]
I can't reproduce that yet.  But I can reproduce that resizing the width of the console window causes similar problems.  So ConsoleZ behaves differently with respect to resizing.

I'll either come up with a fix tonight, or back out some/all of the changes for handling terminal resize.  That's the thing in 1.2.14 that has introduced the regression.

**Comment by char101** [comment]
So a hack I just found is to add `timeout /t 5 /nobreak` in `startup.bat` before loading clink, so it seems to be because of some async operation maybe where either click is processing it too early while the data is not ready.

**Comment by char101** [comment]
I can also reproduce that resizing ConsoleZ window causes the prompt to disappear.

**Comment by chrisant996** [comment]
Interesting -- thanks for the additional info.

Another interesting thing:  when using a Debug build of Clink (compiler optimizations turned off), the problem does not occur.

**Comment by char101** [comment]
I tried changing my prompt filter to only show one line. There is no problem if the prompt only consists of one line. 

So maybe the computation when resizing the windows does not consider the height of the prompt?

**Comment by chrisant996** [comment]
Thank you -- yes it's indeed connected to whether the prompt is more than one line -- when using a Debug build, I default to a simple one line prompt.  I tested multiple line prompts in the Debug build, so it must be some final "finishing touch" change escaped full validation.

**Comment by chrisant996** [comment]
Oh goodness.  ::pounds head against desk::  Yep, such a dumb last minute mistake.

I should be able to get a fix out soon.  Sorry for the inconvenience, and thank you very much for reporting the issue quickly (and helping to troubleshoot, too).

**Comment by char101** [comment]
Thank you for the prompt response. I'm specifically looking to use the startup script feature in 1.2.14.

**Comment by chrisant996** [comment]
Fixed by e0077ef61966b9afc521a628a9b4faddd9673a51.  Sheesh.

**Comment by chrisant996** [comment]
1.2.15 is published and should resolve the issue -- please confirm when you get a chance.

Thank you again!

**Comment by char101** [comment]
I can confirm that 1.2.15 works great. Thanks!

**Comment by chrisant996** [comment]
Awesome, thanks so much, @char101 !
