### ISSUE TITLE
cmd.auto_answer = answer_yes not working in German cmd

### ISSUE THREAD

**Issue by dschulten** [chrisant996/clink#137]
Having executed `clink set cmd.auto_answer 1`:

```
C:\Users\Schulten\Documents\projekte\example (develop -> origin) (kojo@1.0.0)
λ npm test

> kojo@1.0.0 test C:\Users\Schulten\Documents\projekte\example
> cypress run --browser chrome


Batchvorgang abbrechen (J/N)?
```

Hangs forever in Clink v1.1.45.1c3985 (which comes with the latest cmder 1.3.18.1106)

The older `clink set terminate_autoanswer 1` says 

```
λ clink set terminate_autoanswer 1
ERROR: Setting 'terminate_autoanswer' not found.
```

**Comment by chrisant996** [comment]
> Having executed `clink set cmd.auto_answer 1`:
> 
> ```
> C:\Users\Schulten\Documents\projekte\example (develop -> origin) (kojo@1.0.0)
> λ npm test
> 
> > kojo@1.0.0 test C:\Users\Schulten\Documents\projekte\example
> > cypress run --browser chrome
> 
> 
> Batchvorgang abbrechen (J/N)?
> ```
> 
> Hangs forever in Clink v1.1.45.1c3985 (which comes with the latest cmder 1.3.18.1106)

1.1.45 is pretty old.
What happens with the current version?

> The older `clink set terminate_autoanswer 1` says
> 
> ```
> λ clink set terminate_autoanswer 1
> ERROR: Setting 'terminate_autoanswer' not found.
> ```

Again 1.1.45 is pretty old (and is a pre-release version).
Newer versions support backward compatibility to recognize obsolete names for settings.

**Comment by chrisant996** [comment]
Also, can you share the `clink.log` file?  It should contain some log entries related to the cmd.auto_answer feature.

**Comment by chrisant996** [comment]
v1.2.17 now prints the auto-answer response to the screen (e.g. `j` or `y`) and avoids responding more than once to the same "Terminate batch job" prompt.

I expect this won't make the feature work successfully on the machine where it's failing, but I do expect that it will (1) help diagnose what's going wrong and (2) won't get stuck hanging forever anymore.

Please let me know how it works with v1.2.17.  You can [download it](https://github.com/chrisant996/clink/releases/download/v1.2.17/clink.1.2.17.b5751c.zip) and copy the files into the `%CMDER_ROOT%\vendor\clink` directory.

Please share the `clink.log` file to help diagnose what's going wrong.

Thanks!

**Comment by chrisant996** [comment]
`cmd.auto_answer = answer_yes` seems to be working for me in both "English (United States)" and "Deutsch (Deutschland)":
- Standalone CMD/Clink, pressing <kbd>^C</kbd> to break a long-running script auto-answers the prompt and stops.
- Windows Terminal with CMD/Clink, pressing <kbd>^C</kbd> to break a long-running script auto-answers the prompt and stops.
- Cmder with CMD/Clink 1.1.45, pressing <kbd>^C</kbd> to break a long-running script auto-answers the prompt and stops.
- Cmder with CMD/Clink 1.2.17, pressing <kbd>^C</kbd> to break a long-running script auto-answers the prompt and stops.

Is there any additional information, or logs, or troubleshooting information that can be shared?

**Comment by bw1faeh0** [comment]
I just tested this feature in a german env using windows terminal with clink 1.2.17:

````
> clink set cmd.auto_answer
        Name: cmd.auto_answer
 Description: Auto-answer terminate prompt
     Options: off,answer_yes,answer_no
       Value: answer_yes
````

````
> test.bat

ping -n 100 google.de

Ping wird ausgeführt für google.de [142.250.186.35] mit 32 Bytes Daten:
Antwort von 142.250.186.35: Bytes=32 Zeit=23ms TTL=119
Antwort von 142.250.186.35: Bytes=32 Zeit=21ms TTL=119
Antwort von 142.250.186.35: Bytes=32 Zeit=21ms TTL=119
Antwort von 142.250.186.35: Bytes=32 Zeit=22ms TTL=119
Antwort von 142.250.186.35: Bytes=32 Zeit=22ms TTL=119

Ping-Statistik für 142.250.186.35:
    Pakete: Gesendet = 5, Empfangen = 5, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 21ms, Maximum = 23ms, Mittelwert = 21ms
STRG-C
^CBatchvorgang abbrechen (J/N)? J

````

looks good.

**Comment by chrisant996** [comment]
@dschulten when you get a chance, please let me know how a newer version of Clink works.  If there is still a problem, please reopen the issue and share additional information.  Thanks!
