### ISSUE TITLE
Incremental history search is case insensitive

### ISSUE THREAD

**Issue by Uxorious** [chrisant996/clink#139]
I can't find a way to make ctrl-r be case sensitive (as it was in the original clink).
Personally I prefer it to be case sensitive, but I can't find any option to change the behavior.

**Comment by chrisant996** [comment]
https://chrisant996.github.io/clink/clink.html#new-configuration-variables

`search-ignore-case`

**Comment by chrisant996** [comment]
I will consider whether to change the default to off.  I realize that Clink is sometimes used to give a somewhat Unix-y feel when working with Windows.

But I think on Windows case-insensitive is an appropriate default.

**Comment by Uxorious** [comment]
Oh I missed that.
"clink set" didn't print the option. (I guess that's a bug?)

**Comment by chrisant996** [comment]
As described in the linked documentation, it is a Readline variable, not a Clink setting.

See https://chrisant996.github.io/clink/clink.html#configuring-readline for information on configuring Readline variables.
