### ISSUE TITLE
[Feature Request] fzf-like history view

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#142]
Hi,

I don't know if it realistic to implement/change the presentation of the command history, but I suggest to display a list without using a windows pop-up like the current one, but with a list of selectable commands direclty displayed in the terminal.

Currently it looks like this:
![image](https://user-images.githubusercontent.com/29235332/124867343-34f23180-dfbe-11eb-97e9-01520061b042.png)
The popup is very disruptive in terms of the whole gui look & feel (window decoration, background, X to close, scrollbar).

Maybe it could be to look like this somehow:
![image](https://user-images.githubusercontent.com/29235332/124867580-a3cf8a80-dfbe-11eb-85ea-0309f2c4bb8a.png)
(using [fzf](https://github.com/junegunn/fzf) and hitting `Ctrl+R` after typing `ping`)

You see the command history is rendered as text directly within the console application and you can use the arrow keys to navigate and select an item you like.

**Comment by rashil2000** [comment]
You can use [this](https://github.com/chrisant996/clink/issues/89#issuecomment-803523925) Lua script to achieve this.

**Comment by bw1faeh0** [comment]
wow, cool!
thanks!
