### ISSUE TITLE
crash on start since 1.2.19 when `terminal.raw_esc` is set to true

### ISSUE THREAD

**Issue by u01jmg3** [chrisant996/clink#143]
Hello!

Thanks for taking on Clink and improving it.

Since 1.2.19 (issue remains in 1.2.20) Clink crashes as soon as I open my command prompt. I have its dump file but I guess it contains identifiable info so let me know how I can get it to you if indeed you're happy to debug.

Cheers

**Comment by chrisant996** [comment]
Oh that's bad. Can you maybe attach an encrypted .zip file, and send me the password via email to sparrowhawk996? It's a Gmail dot com address.

And/or can you attach a .zip file with the Lua scripts you have? Based on a guess that it might be related to some script you have that I don't.

**Comment by chrisant996** [comment]
Do you have the `debug.log_terminal` setting enabled?  If so, try turning it off.  There's a change in .19 that could potentially crash if that setting is enabled.  But also, probably don't leave that setting enabled for very long anyway, because it emits a ton of log output.

**Comment by u01jmg3** [comment]
You have mail 📨

**Comment by chrisant996** [comment]
Thanks!

Upgrading to v1.2.21 will resolve the crash. The crash happened when `terminal.raw_esc` is set to true, so it can be worked around by setting that to false (the default, and why I missed the bug).

**Comment by u01jmg3** [comment]
Super! 💫
