### ISSUE TITLE
[feature request] "transient" prompt

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#151]
I saw a nice feature realized in a zsh [theme](https://github.com/romkatv/powerlevel10k):

A prompt that was trimmed down after accepting a commandline:

![transient-prompt](https://user-images.githubusercontent.com/29235332/130968321-c4173340-7bbf-4b5b-ab61-9915aa793db3.gif)
In this gif the two line prompt was replaced by a short single line.

So if you have some free time and don't know what do hack - this would be a nice feature 😉

**Comment by chrisant996** [comment]
> Maybe this short recording from one of my installations answers your question.

On closer examination, I can't tell whether the recording includes the specific case of interest.

In Clink (and bash), pressing Alt+= lists the possible completions and then shows a new prompt.

So these are my questions:
1. In the recording, it looks like either Alt+= wasn't used OR the equivalent in zsh lists possible completions below the prompt but doesn't show a new prompt.  Can you clarify which one?
2. If zsh doesn't show a new prompt in that case, then what happens when there are too many possible completions to fit on the screen -- does it list them all and then start a new prompt?  Does the old prompt get collapsed, or is the theme not able to catch that situation?
3. What if there are so many completions available that <kbd>Tab</kbd> (or whatever is the `complete` binding) prompts whether to display them?  Does the prompt get collapsed _before_ prompting?  Or after prompting?  Or is the theme not able to catch that situation?

Thanks!

**Comment by bw1faeh0** [comment]
> In Clink (and bash), pressing Alt+= lists the possible completions and then shows a new prompt.

`alt + =` does nothing on my zsh setups

> 1

zsh does not show a new prompt after listing possible completions. The current prompt is still active and usable/editable. Even if zsh is asking wheater to display all possible completions the prompt stays "active". If the screenheight is high enough the prompt is still active above the complete list, if it is not high enough a 'copy' of the prompt is displayed after the completion list. But no collapsed prompt, because the original "input prompt" is still active. 

![zsh](https://user-images.githubusercontent.com/29235332/131338552-eddb213f-8c39-48d5-8d53-3b126e164545.gif)

**Comment by chrisant996** [comment]
I installed Ubuntu and zsh on my Windows machine.
- The closest equivalent to bash's `possible-completions` in zsh is called `list-choices`, but even it behaves very differently.  The recordings are showing the equivalent to `clink-select-complete`; an interactive list from which a completion can be selected using the arrow keys.
- As far as I can tell, zsh simply doesn't have the cases I was asking about from bash/Readline.  But I found how powerlevel10k handles similar things, and it's indeed how I expected it would.

Anyway, the transient prompt capability seems to be working well in Clink.  I'm updating the documentation and testing it a bit more, before a new release.

A `clink.promptfilter()` object can have a `:transientfilter()` and/or `:transientrightfilter()` function added to it to filter the transient prompt (i.e. building the transient prompt works just like building the normal prompt, but just with different function names).  The `CLINK_TRANSIENT_PROMPT` and `CLINK_TRANSIENT_RPROMPT` environment variables define the initial transient prompt input to the prompt filters (just like `PROMPT` and `CLINK_RPROMPT` define the initial normal prompt input).

So with Clink, the transient prompt capability is part of Clink itself, and available for all prompt themes (vs being exclusively part of the powerlevel10k theme for zsh).

**Comment by chrisant996** [comment]
Here is a custom build if you want to try it out in advance of the next release.
[clink.1.2.29.5a8085.zip](https://github.com/chrisant996/clink/files/7087112/clink.1.2.29.5a8085.zip)

Look in the clink.html documentation for "transient prompt".  There's documentation and an example.

**Comment by bw1faeh0** [comment]
looks very good!

![image](https://user-images.githubusercontent.com/29235332/131728679-54b66fe1-220f-42e2-85b7-8d977e1f5151.png)

**Comment by chrisant996** [comment]
I'm working on a customizable prompt script, which will be customizable without any actual Lua programming (just setting a few strings in a .lua file).  It's similar to powerlevel10k, but works in Clink.  It's also possible to add custom prompt modules with a very small amount of Lua programming.

The project is here: https://github.com/chrisant996/clink-flex-prompt.  It requires Clink v1.2.29 or higher, and currently lacks {git} and {npm} modules and a configuration wizard -- and documentation.  Those are coming soon.

It's how I'm validating that the transient prompt and related things are complete enough to release.  Once both Clink and clink-flex-prompt are ready, I'll update both.

**Comment by chrisant996** [comment]
[clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) now works on Clink v1.2.10 and higher, and additional features light up in newer versions (e.g. errorlevel and transient prompt).

The documentation isn't complete yet, but I think all the functionality is working, including the configuration wizard.
