### ISSUE TITLE
ESC key and Ctrl-F fails to work

### ISSUE THREAD

**Issue by David-Maisonave** [chrisant996/clink#156]
Using Clink version **v1.2.28**.

I originally posted a list of DOS keys that don't work with Clink. Since that might have been a big ask, I'm concentrating this issue to just the ESC key and the Ctrl-F.

### Summary
1. ESC key: Nothing happens when this key is pressed.  
    - Expected behavior: The current command line should get cleared (erased).
2. Ctrl-F: Nothing happens when this key combo is used.
    - Expected behavior: It should display the popup window to find text on the screen.

### Details
1. The ESC key is important because this is a function that users have been using for years with DOS console, and IMHO, that's the first thing they'll see wrong with Clink.  That was the first thing I notice. The ESC key works when using Ctrl-R and it works for clink-popup-complete. It would be more consistent behavior if it works in general. 
    - Readline uses the ESC key as an alternative to the ALT key. 
      - Solution 1: Modify the code so when the user press the ESC key twice issue a **kill-whole-line**. 
      - Solution 2: A better fix would be to have the option to disable ESC key as the meta-key.  Everyone has ALT keys on there windows computer, so the ESC as the meta-key is an obsolete requirement.  
      - Either of these solutions would most likely have to be done in the C\C++ code.
    - I tried playing around with the inputrc file, but the best workaround I got working was the below lines:
      ````
      # Best workarounds for DOS ESC key
      "\e[Z": kill-whole-line    # Shift+Tab to clear current line.
      "`":  kill-whole-line        # ` (tic key) to clear current line. 
      "\M-z": kill-whole-line   # Alt-z to clear current line.
      ````
    - In any case Clink should have a shortcut key to clear the current line, and it would be best if it was a single key stroke, or a combination that's easy to use and remember.

2. The CTRL-F is a more recent feature, which I think most users are not aware of, but if you let this key pass through, you can post this as a feature Clink supports.  I think more users would find Clink appealing seeing this feature listed on the intro page.
    - I can access this feature by right clicking the title-bar, and selecting [Edit]->Find.  If you can let this key combination go to windows, it should be able to handle it.

**Comment by chrisant996** [comment]
Please don't add new issues that are the same as closed issues.  We can carry on a conversation in the original issue.
