### ISSUE TITLE
Add beginner section in the documentation

### ISSUE THREAD

**Issue by David-Maisonave** [chrisant996/clink#160]
When I saw the examples folder, I was hoping that it would have example inputrc files, but it doesn't.
There's nothing on the main page that discuss the inputrc file. It is in the documentation, but IMHO, I think this feature is important enough that it should be directly accessible from the main page.
You gave me some great tips for added shortcut keys to my inputrc file, and I think that should be information that other Clink users can easily find.
I'm sure there are other useful shortcut keys used by Clink users. It would be very helpful if users can contribute their inputrc files so that others can use it.

1. Can you please add a folder at the top level for inputrc files that have additional shortcut keys or functionality that is not already included in Clink? Here's some possible names for the folder:
    - inputrc
    - inputrc-addons
    - inputrc-extensions
    - inputrc-examples
    - inputrc-contributions
2. Can you please allow other users to contribute to this folder?
3. Can you add a README.cmd file that has the following:
    - **basic** information on what is an inputrc, with a link for more details.
    - **basic** information on how to create an inputrc file on their Clink installation.
    - Information on how to use the inputrc files listed in the folder.
    - Information on how users can contribute their inputrc files (like minimum requirements).

Here's an example README.cmd file for the new folder.

# Overview
This folder contains **inputrc** files with additional shortcut keys and functionality which can be added to Clink.
The folder includes user contributed inputrc, for use with Clink version 1.2 or higher.

### What's an inputrc file and what does it do
The inputrc file is the user configuration file used by readline, which provides customizable keybindings and macros.
Users can map shortcut keys to perform common task.
For more information see [Clink Documentation](https://chrisant996.github.io/clink/clink.html) or [Readline Manual](https://tiswww.cwru.edu/php/chet/readline/rltop.html#Documentation).

### How to use an inputrc file on Clink installation
For Readline to find the inputrc file it must have the name **.inputrc** or **_inputrc**
The file needs to be stored in one of the following paths:
- %USERPROFILE%
  - Examples:
    - C:\Users\<username>\.inputrc
    - C:\Users\<username>\_inputrc
- **%LOCALAPPDATA%\clink**
  - Examples:
    - C:\Users\<username>\AppData\Local\clink\.inputrc
    - C:\Users\<username>\AppData\Local\clink\_inputrc
- %LOCALAPPDATA%
  - Examples:
    - C:\Users\<username>\AppData\Local\.inputrc
    - C:\Users\<username>\AppData\Local\_inputrc
- %APPDATA%
  - Examples:
    - C:\Users\<username>\AppData\Roaming\.inputrc
    - C:\Users\<username>\AppData\Roaming\_inputrc

If inputrc is not in any of the above paths, a new inputrc can be created with the following command line:
``
notepad %USERPROFILE%\.inputrc
``
### Usage
- If you see an inputrc file with functionality you like, you can do one of the following:
  - Copy the section you like, and append it to your existing file
  - Replace your existing file with your preferred file.
    - First make sure to backup the existing file.
    - When you download the new file, make sure to rename it to .inputrc
### How to contribute
- If you have an inputrc file which you think others would find useful, you submit a request to add your inputrc file to this collection.
- Submission Requirements
    - At the top of the inputrc file, Add a **short summary** one line sentence describing the features in your inputrc.
    - Shortcut keys needs to have an appended comment with a short description and plain text key combination.
      - Examples:
        - "\C-a": cua-select-all    # Select all on the current line (ctrl+a)
        - "\C-f": clink-find-conhost    # Get the find dialog to find text in the screen. (ctrl-f)
        - "\e[Z": "cd  %USERPROFILE%\\Documents\n"  # cd to user's document folder (shift+tab)
    - Create a new issue with title **Inputrc Submission:** [**short summary**]
    - Rename the inputrc file to inputrc_[**short summary**]
    - Attached the rename file to your new issue.
    - Give an overview (readme content) describing the features.

**Comment by chrisant996** [comment]
> Can you please add a folder at the top level for inputrc files that have additional shortcut keys or functionality that is not already included in Clink?

There is already a whole section in the documentation about the inputrc file and key bindings.  It includes a sample inputrc file content, which is (most of) the bindings I personally use.  I don't want to have multiple different documentation files in multiple different locations.

> Can you please allow other users to contribute to this folder?

I don't believe that the Clink _product_ repo is the right place to start a community library of random scripts.

But is the request for me me to allow contributions to the Clink product without moderating them?
Or is the request for me to suggest how to learn about git and github, and how forking and pull requests work?

> Can you add a README.cmd file that has the following:

First, can you offer constructive criticism about the existing documentation?

I spent a lot of time putting together documentation, and it's confusing to receive a request to build a separate alternative documentation strategy, when it sounds like the existing documentation has not been read.

E.g.
https://chrisant996.github.io/clink/clink.html#configuring-readline
https://chrisant996.github.io/clink/clink.html#key-bindings

Also, to clarify:
- `.cmd` is the extension for CMD batch scripts -- so, no, a document should never be named ending in `.cmd`.
- `.md` is the extension for Markup documents -- I imagine the suggested name was a typo.

**Comment by David-Maisonave** [comment]
I think you did a great job on the documentation, moreover I plan to emulate it for my application (RegexAssistant).

I consider the ability to create shortcut keys a big deal, and the documentation has it under miscellaneous.

Before using this version of Clink I never heard of Readline.
IMHO, the documentation is written at high technical level, which assumes the reader is familiar with Readline and Lua. 
I don't know what is Lua exactly and it look like too much time to invest reading it without knowing if I'm ever going to use it.  For the average user, the same could be said for Readline.
I only invested my time reading about Readline because I saw the customizable shortcut key feature.

I think there should be a beginners section, where things are explained as if the user doesn't know readline or Lua.  The readline and Lua sections should go under an Advance section.

I think the average user would be interested in creating shortcut keys if they had a simple explanation on how to do it.  And I don't think you really need to know Readline in order to make some simple shortcut keys.

The documentation leaves a few things out for of the Clink search path.
When I installed Clink 0.49, it created the inputrc file in the %LOCALAPPDATA%\clink, but in your document you refer to %LOCALAPPDATA% and %APPDATA%.  So I assume when using the %APPDATA% it would have to go in %APPDATA%\clink.
When I tested it, it didn't work.
After some testing I realize the inputrc file can go in either %LOCALAPPDATA% or %LOCALAPPDATA%\clink, and for %APPDATA% it can only be used at the root level.

I also determine that %LOCALAPPDATA%\clink path takes president over the root path %LOCALAPPDATA%.
That means if a user doesn't know that there is an inputrc file in the %LOCALAPPDATA%\clink, and they try to create one in %LOCALAPPDATA%, they'll be wildly confused as to why readline is not reading their file.

When I entered command clink info, it showed %clink_inputrc% as unset.  Shouldn't Clink have set this value in the install process?

Maybe I over looked it, but I didn't see it stating that .inputrc takes president over _inputrc.

To help clarify it all, I recommend there be a list showing the presidents more explicitly to include the file name.
Example:
````		
	C:\Users<username>.inputrc
	C:\Users<username>_inputrc
	C:\Users<username>\AppData\Local\clink.inputrc
	C:\Users<username>\AppData\Local\clink_inputrc
	C:\Users<username>\AppData\Local.inputrc
	C:\Users<username>\AppData\Local_inputrc
	C:\Users<username>\AppData\Roaming.inputrc
	C:\Users<username>\AppData\Roaming_inputrc
````

But again, I think this level of details should be in an advance section.
The beginner section should just discuss the default highest president path (C:\Users<username>.inputrc), and refer to the advance section for more details.

**Comment by David-Maisonave** [comment]
I forgot to mention that when I did clink info, it shows the %home% path as being the same as the %userprofile% path.
That can be confusing because the document shows the %home% path as having the lowest president.  But if these paths are the same, then %home% path would actually have the highest default president.

I don't include %CLINK_INPUTRC%, because on my new install of Clink, it has this path as undefined.  With that absence, that makes %userprofile% the highest president.

**Comment by chrisant996** [comment]
Great, thanks, that helped me understand the core feedback:  you would like a section to help new users quickly be able to get started with common simple configurations.

I'll do something about that.  I may use some portions of the suggested text you shared, since you've clearly spent time and effort to think about how to present information to new users.  I appreciate the help, thanks!

> The documentation leaves a few things out for of the Clink search path.

I view it differently:  The documentation is too technical and literal, and is confusing if there is not familiarity with several things (e.g. how Windows special folders work, how HOME works in Unix and how Clink synthesizes a fake HOME variable if not present since Readline needs it, and several other things).

You would like a section that tells you only what a beginner needs to know to quickly set up a brand new inputrc file, instead of telling all about how the whole thing works.

That's great feedback, thanks.

> When I entered command clink info, it showed %clink_inputrc% as unset. Shouldn't Clink have set this value in the install process?

No, you would only set that if you want to forcibly block Clink from looking for the inputrc file in the usual, and only look in one specific place.

**Comment by David-Maisonave** [comment]
Thanks for your time.

Slightly off topic:
I googled how to create shortcut key using the shift + ctrl or shift + tab.  I couldn't find an answer. Some posted that it's not possible.
However I have a shortcut key that uses shift+tab.
"\e[Z": "cd %USERPROFILE%\Documents\n" # cd to user's document folder (shift+tab)

So I'm thinking it has to be possible.  But I can't make any sense of "\e[Z" as to what logic is being used to determine the format.

Do you know how to include the shift key in a combination shortcut key, or how to decipher "\e[Z"?

**Comment by David-Maisonave** [comment]
I feel dumb.  I spent 2 days off and on looking for this information, and it was already in your help file. :-)
I also just realized I could've gotten that information by using clink echo.
I misunderstood that commands functionality.  I thought it did the same thing as (alt-shift-?), which tells you if a shortcut key is in use.
When I used clink echo, I couldn't figure out how to exit (other then pressing ctrl-C).
- [ ] **Is there a way to gracefully exit Clink echo?**

The documentation refers to using Alt+Shift+H as alternative to **clink echo**.  However, that shortcut key doesn't work for me. When entering alt-shift-H, I get the help text (same results as when I press alt-h).
To make things more confusing, I used **alt-shift-?** to see what A-S-H was assigned to, and I got the following results:
````
A-S-H : do-lowercase-version -- If the metafied character X is upper case, run the command that is bound to the corresponding metafied lower case character.  The behavior is undefined if X is already lower case
````
I don't understand that.
- [ ] **Is the A-S-H key broken for "Clink echo"?**
I've attached my inputrc and clink.log if you're interested in looking.
[AltShiftH_Issue.zip](https://github.com/chrisant996/clink/files/7247707/AltShiftH_Issue.zip)

I'm updating my NotePad++ Run Script, which allows me to run most common script files and programming languages by using the same run shortcut execution key.
I was trying to add .lua as a file type to handle, but I'm not sure how to run it on Windows. I was hoping Clink would allow me to run a lua file on the command line.
- [ ] **Is there a way I could use Clink to run a lua file without having to put it in the startup path?**

I was following the [transient-prompt](https://chrisant996.github.io/clink/clink.html#transient-prompt) instructions, and I couldn't get the **clink set prompt.transient** to work.
Here's my results:
````
 C:\Users\david\AppData\Local\clink  > clink set prompt.transient always                            9/28/2021 6:52:01 PM
ERROR: Setting 'prompt.transient' not found.
````
- [ ] **Am I doing something wrong in trying to set prompt.transient?**

Again, thanks for your time.

**Comment by chrisant996** [comment]
> When I used clink echo, I couldn't figure out how to exit (other then pressing ctrl-C).

Ctrl-C is the way exit.  I suppose I can add a line of output to remind about that.

> The documentation refers to using Alt+Shift+H as alternative to **clink echo**. However, that shortcut key doesn't work for me. When entering alt-shift-H, I get the help text (same results as when I press alt-h).

Thanks, I will remove that mention of Alt+Shift+H.  It is leftover from an early version of the Alt+H help, which was not yet able to show friendly names for all the keys, and so since it was showing confusing key names anyway, it made to have a mode that showed the literal key binding sequences (but who can make sense of those? 😄).

> I'm updating my NotePad++ Run Script, which allows me to run most common script files and programming languages by using the same run shortcut execution key. I was trying to add .lua as a file type to handle, but I'm not sure how to run it on Windows. I was hoping Clink would allow me to run a lua file on the command line.

Lua is just a language.  Clink's built in Lua interpreter allows it to run embedded scripts, using Lua as the language.

"Run a Lua file on the command line" could be meant two different ways:

1. Launch a Lua interpreter to run the Lua file as a Lua program.
2. Intercept attempts to run Lua files as Lua programs, and instead load them into Clink as an embedded part of Clink, and then run the script inside Clink.

The first option is how to run Lua files.  There are a variety of Lua interpreters you could use, but those are independent from Clink.

The second option sounds good on the surface, but it can break the Lua program, and it can break Clink -- neither of whom are expecting to operate in that way.

But if you mean that you want to bind a key in Clink to run some Lua code as part of Clink, then read up on the "luafunc" stuff in the documentation.

> I was following the [transient-prompt](https://chrisant996.github.io/clink/clink.html#transient-prompt) instructions, and I couldn't get the **clink set prompt.transient** to work. Here's my results:
> ```
>  C:\Users\david\AppData\Local\clink  > clink set prompt.transient always                            9/28/2021 6:52:01 PM
> ERROR: Setting 'prompt.transient' not found.
> ```

It looks like you are somehow invoking an older version of Clink that does not have the transient prompt feature yet.
Maybe you have multiple versions of Clink on the machine.
Run `clink info` to find out what version of Clink you're accidentally invoking and where it's located.
Then find and use the version of Clink that you had intended to launch, instead.

**Comment by David-Maisonave** [comment]
Clink info is showing version  : 1.2.28.f398a1.
Was that feature added after 1.2.28?
I'll install the latest, and let you know what happens.

**Comment by David-Maisonave** [comment]
It works on v1.2.35.
Thanks

**Comment by chrisant996** [comment]
The documentation now includes a Getting Started section.
