### ISSUE TITLE
clink command completion shows "word classifier failed"

### ISSUE THREAD

**Issue by dodmi** [chrisant996/clink#162]
Clink version: v1.2.31.75c011
Settings: Default (completely deleted settings dir)
Installed scripts: None

If I enter `clink set match.sort_dirs b`, clink will throw the error:
"word classifier failed: ?:0: attempt to index a nil value"
![image](https://user-images.githubusercontent.com/4572946/133141533-db6d6214-16fb-42bd-a036-f79e416ceec8.png)

**Comment by chrisant996** [comment]
Uh oh. Thanks for reporting this. I'll investigate later today.

**Comment by chrisant996** [comment]
v1.2.32 has been released with the fix for this.
