### ISSUE TITLE
Useful script if you're doing Lua programming for Clink 😎

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#163]
_**This has been moved to discussion #230 -- please visit there for the latest.**_

Naturally, I've been doing a lot of Lua programming and debugging for Clink.

I made the following script to help with that.
~~V1: [luaexec.lua.txt](https://github.com/chrisant996/clink/files/7159419/luaexec.lua.txt)~~
~~V2: [luaexec.lua.txt](https://github.com/chrisant996/clink/files/7193025/luaexec.lua.txt)~~
~~V3: [luaexec.lua.txt](https://github.com/chrisant996/clink/files/7213749/luaexec.lua.txt)~~
More:  see discussion #230 for the latest.
 
To use it, copy it into your Clink scripts folder as `luaexec.lua`.

Add the following key bindings in your `.inputrc` file:
```inputrc
# Use Ctrl+X,Ctrl+L to toggle Lua Execute mode.
"\C-x\C-l": "luafunc:clink_execute_lua"		# ctrl+x,ctrl+l

# Use Ctrl+X,Ctrl+K to expand the value of the Lua variable under the cursor.
"\C-x\C-k": "luafunc:clink_expand_lua_var"	# ctrl+x,ctrl+k

# In Lua Execute mode, Home (and also Shift+Home) jumps back and forth between
# the beginning of the Lua code or the beginning of the line.
"\e[H": "luafunc:luaexec_begin_line"            # Home
"\e[1;2H": "luafunc:luaexec_shift_begin_line"   # Shift+Home

# In Lua Execute mode, Ctrl+A selects only the Lua code, otherwise it selects
# the whole input line.
C-a: "luafunc:luaexec_select_all"               # Ctrl+A
```

Once the key bindings above have been added and Clink has been reloaded, then pressing <kbd>Ctrl</kbd>+<kbd>X</kbd>,<kbd>Ctrl</kbd>+<kbd>L</kbd> toggles "Lua Execute" mode in the command prompt.  When a command line starts with "rem lua:" then the rest of the text will be executed as Lua code.  This only works at the interactive input prompt; it cannot be used in batch files.

In Lua Execute mode, there is some simple completion support for Lua variables.

There is also a `dumpvar(value, depth)` function that dumps the value, recursing into tables to the specified depth (default is 1).  It also color codes value types for easy reference.  The colors are configurable.

For more information, refer to the script source code.

**Comment by pukkandan** [comment]
this should probably go in the docs instead of as an issue? It would atleast be useful to pin the issue

**Comment by chrisant996** [comment]
There are many conflicting opinions about where scripts should go. I'm sharing a script here. I'll discuss the script here, but this is not where to discuss strategies for how to organize and curate collections of scripts.

**Comment by chrisant996** [comment]
The script in the [original post](https://github.com/chrisant996/clink/issues/163) has been updated:
- `"luafunc:clink_expand_lua_var"` can expand the variable name under the cursor, and replace it with the variable's value.

For example, if you want to edit the value of a string variable:
1. Ctrl+X,Ctrl+L to activate Lua Execute mode.
2. Type `global.variable.name = global.variable.name` and press Ctrl+X,Ctrl+K.
3. The line becomes `global.variable.name = "the value"`.

So, for example, I can change the [flexprompt](https://github.com/chrisant996/clink-flex-prompt) prompt string on the fly like this:
1. Ctrl+X,Ctrl+L
2. Type `flex` <kbd>Tab</kbd> `.set` <kbd>Tab</kbd> `.left_p` <kbd>Tab</kbd>
3. Ctrl+A then Ctrl+C to select and copy the variable name.
4. Type ` = ` then Ctrl+V to paste the variable name again.
5. Ctrl+X,Ctrl+K to replace the variable name with its value.
6. Now edit the string.

Very handy for changing variable contents on the fly for testing Lua scripts in Clink.

**Comment by chrisant996** [comment]
V3 fixes cursor positioning in the commands.
