### ISSUE TITLE
Right arrow key does not work when clink.default_bindings = windows

### ISSUE THREAD

**Issue by char101** [chrisant996/clink#168]
Steps to reproduce:

1. autocomplete a file name using `Tab`: `C:\>a<Tab> → C:\>a.txt|`
2. press Home -> cursor is positioned at the beginning of the line: `C:\>|a.txt`
3. press Right Arrow -> cursor does not move: `C:\>|a.txt`

This happens when `clink.default_bindings = windows`.

**Comment by chrisant996** [comment]
Yes, thanks for reporting it.  I fixed it last night in da97d741856af2486bb8db9eaff2211342a7a0e7.  Next release will include the fix, probably today or tomorrow.

A workaround for now is to manually add a binding.
```inputrc
"\e[C": win-cursor-forward
```
