### ISSUE TITLE
Directory symlink completion missing last character

### ISSUE THREAD

**Issue by char101** [chrisant996/clink#170]
How to reproduce:

```
> mkdir abc

> mklink /D def abc
symbolic link created for def <<===>> abc

> cd d<Tab>

> cd de
```

Pressing tab after typing `cd d` only expands `def` to `de`.

**Comment by chrisant996** [comment]
I'll take a look, thanks for reporting this!

**Comment by chrisant996** [comment]
I can't reproduce this.

Can you share your `clink_settings` and your `.inputrc` files?

There are settings in those that can affect how this might behave, and knowing your settings would save me a lot of trial and error time trying to figure out the configuration on that computer.

Thanks!

**Comment by chrisant996** [comment]
Luckily I found it on the first try.
You have `set mark-directories    off` in the .inputrc file, right?

**Comment by char101** [comment]
You are right, I have `set mark-directories off` in my .inputrc. Thank you for the quick fix.

**Comment by chrisant996** [comment]
> You are right, I have `set mark-directories off` in my .inputrc. Thank you for the quick fix.

Thanks for the confirmation.  Once I get this other hooking issue resolved, I'll post a new release.
