### ISSUE TITLE
Setup procedure: use current installation dir when upgrading clink

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#176]
Hi,

every time I upgrade clink I have to change the destination folder. It would be cool, if the setup can read the current installation dir of clink and use this as destionation dir:

![image](https://user-images.githubusercontent.com/29235332/136323177-b284eeb7-debd-4188-8cc4-448d10b7ff60.png)

![image](https://user-images.githubusercontent.com/29235332/136323191-107c3332-1738-40e7-ba46-2ef0f86cccf6.png)

![image](https://user-images.githubusercontent.com/29235332/136323231-9b71e1bf-eb05-487f-8025-622280ecac52.png)

**Comment by chrisant996** [comment]
I'm looking at adding an auto-update option in Clink itself, which would periodically use the github API to check for updates, and automatically apply them.  Configurable, of course.  That would likely make an installer change unnecessary.

I don't know how to make NSIS have the suggested behavior.  Knowledgeable suggestions (or a PR!) are welcome.

**Comment by d-faure** [comment]
Some hints on the installation dir persistence here:
https://nsis-dev.github.io/NSIS-Forums/html/t-198204.html

**Comment by chrisant996** [comment]
Fixed by 1f99d577de465a2e38fde2862053d05137ed1f36.
