### ISSUE TITLE
TCC problem

### ISSUE THREAD

**Issue by neradp** [chrisant996/clink#177]
Hello, i a have a problem with TCC. Look at:

[https://github.com/mridgers/clink/issues/108](https://github.com/mridgers/clink/issues/108)

**Comment by chrisant996** [comment]
What version of Clink are you using?

For me, current versions of Clink report:
```
Unable to inject Clink.
See log file for details (C:\Users\chrisant\AppData\Local\clink\clink.log).
```

I think you're asking for Clink to suppress the warning message if it occurs during AutoRun and the host is tcc.exe (or 4nt.exe).

**Comment by neradp** [comment]
Yes you are right. Im using the latest version of Clink.

**Comment by chrisant996** [comment]
In Martin's v1.0 rewrite, the TCC detection got lost.

The next published release will include TCC detection again.

Here is a pre-release build that you can test and/or use in the meantime:
[clink.1.2.37.673605.zip](https://github.com/chrisant996/clink/files/7316023/clink.1.2.37.673605.zip)
