### ISSUE TITLE
Completion Treats Some OneDrive Directories as Symlinks

### ISSUE THREAD

**Issue by trozzi1** [chrisant996/clink#178]
I recently upgraded to Windows 11 and reinstalled Clink. I've been using Clink well before upgrading, and it has always treated directories in my OneDrive identically to normal directories. However, I noticed that the completion for directories that are greater than 1 directory deep into OneDrive didn't autocomplete with TAB normally. It does not append the trailing slash.

ex: 

C:\Users\\&lt;username>\OneDrive\MyDirec &rarr;  <kbd>Tab</kbd> &rarr; C:\Users\\&lt;username>\OneDrive\MyDirectory\

but

C:\Users\\&lt;username>\OneDrive\MyDirectory\InnerDir &rarr;  <kbd>Tab</kbd> &rarr; C:\Users\\&lt;username>\OneDrive\MyDirectory\InnerDirectory

After digging around in the code for a while, I found out that this is normal behavior for <i>symlinks</i>. I also noticed that the default match generators will prepend their file suggestions with a single character to indicate the type of file so that ```stat``` doesn't have to be run again. I wrote a small program to test if ```stat``` was actually identifying these as symlinks:

```C++
#include <stdio.h>
#include <sys/stat.h>

// these definitions are pulled from one of clink's header files
# define _S_IFLNK       0x0800
# define S_IFLNK        _S_IFLNK
# undef S_ISLNK
# define S_ISLNK(m) (((m) & S_IFLNK) == S_IFLNK)

// Assumes little endian
void printBits(size_t const size, void const *const ptr)
{
	unsigned char *b = (unsigned char *) ptr;
	unsigned char byte;
	int i, j;

	for(i = size - 1; i >= 0; i--) {
		for(j = 7; j >= 0; j--) {
			byte = (b[i] >> j) & 1;
			printf("%u", byte);
		}
	}
	puts("");
}

int main(int argc, char *argv[])
{
	if(argc == 1)
	{
		puts("Missing required argument.");
		return -1;
	}
	struct stat fileinfo;
	if(stat(argv[1], &fileinfo))
	{
		printf("Couldn't access file %s", argv[1]);
		return -2;
	}
	printf("Is a directory file:                   %s\n", S_IFDIR & fileinfo.st_mode ? "true": "false");
	printf("Is a regular file:                     %s\n", S_IFREG & fileinfo.st_mode ? "true": "false");
	printf("Is a a character-oriented device file: %s\n", S_IFCHR & fileinfo.st_mode ? "true": "false");
	printf("Is a block-oriented device file:       %s\n", S_IFBLK & fileinfo.st_mode ? "true": "false");
	printf("Is a symbolic link:                    %s\n", S_IFLNK & fileinfo.st_mode ? "true": "false");
	printf("Is a FIFO or pipe:                     %s\n", S_IFIFO & fileinfo.st_mode ? "true": "false");
	printBits(sizeof(fileinfo.st_mode), &(fileinfo.st_mode));
	return 0;
}

```

What I got was this:
```
> getstat "OneDrive/MyDirectory"
Is a directory file:                   true
Is a regular file:                     false
Is a a character-oriented device file: false
Is a block-oriented device file:       true
Is a symbolic link:                    false
Is a FIFO or pipe:                     false
0100000101101101

> getstat "OneDrive/MyDirectory/InnerDirectory"
Is a directory file:                   true
Is a regular file:                     false
Is a a character-oriented device file: false
Is a block-oriented device file:       true
Is a symbolic link:                    false
Is a FIFO or pipe:                     false
0100000111111111
```

Neither of them are shown as symlinks. In fact, AND-ing them with the stat.h flags show them as identical. The raw bits are different, though.

I kept digging through the code for a (long) while until I found the function ```static char** alternative_matches(const char* text, int start, int end)``` in ```rl_module.cpp```, where it actually does the prepending. I suspected that the issue was in this block:
```C++
...
        match_type type = past_flag ? iter.get_match_type() : match_type::none;
        match_type masked_type = type & match_type::mask;

        ++count;
        if (!ensure_matches_size(matches, count, reserved))
        {
            --count;
            break;
        }

        const char* match = iter.get_match();
        int match_len = strlen(match);
        int match_size = past_flag + match_len + 1;
        matches[count] = (char*)malloc(match_size);

        if (past_flag)
            matches[count][0] = (char)type;
...
```
The local variable ```masked_type```  is never used in this function, which set off a few alarms. I edited the code to use the masked type instead. 
```C++
if (past_flag)
    // matches[count][0] = (char)type;
    matches[count][0] = (char)masked_type;
```

It was able to fix the issue, but I don't know if this is a cure or just a Band-Aid.

**Comment by chrisant996** [comment]
Some important things to note:
1. The local variable `masked_type` became unused in commit 9c7dd8be07343e04212fbce84c9dd21cb65122b1.  It should be removed.
2. The change you made is neither cure nor Band-Aid; it breaks all behaviors and coloring for files or dirs and that readonly, hidden, orphaned, or symlinks.
3. The test program you made uses the CRT `stat()` function.  That's not what Clink uses, and the MSVC implementation of `stat()` (the whole family of stat functions) knows nothing about symlinks.  Clink instead uses `hooked_stat()` and `hooked_lstat()` and `hooked_fstat()` in `readline\compat\hooks.c`.
4. The main thing responsible for detecting symlinks in Clink is [this line](https://github.com/chrisant996/clink/blob/6736059892f4ed98bd83fe1e8697dfc38bb2a009/clink/core/src/globber.cpp#L169) (and another place, but you get the idea).

The problem is checking `FILE_ATTRIBUTE_REPARSE_POINT` is not sufficient.
It's necessary to also check whether `dwReserved0` == `IO_REPARSE_TAG_SYMLINK`.

A fix is coming.

Thanks for reporting this!

**Comment by chrisant996** [comment]
The next release will include the fix.

Here is a pre-release build that you can test and/or use in the meantime:
[clink.1.2.37.4267e2.zip](https://github.com/chrisant996/clink/files/7316624/clink.1.2.37.4267e2.zip)
