### ISSUE TITLE
Use clink's readline configurations in programming consoles like R's, Lua's, or Python's

### ISSUE THREAD

**Issue by 3N4N** [chrisant996/clink#184]
Is there any way I could use clink's keybindings in consoles provided by R, Lua, or Python? All those use readline config in Linux, but none use that in Windows.

First I thought those programs need to be programmed with readline, so there is no way. But cmd isn't programmed with readline, right? If clink can hook itself to cmd and control the io, then why can't it the R console (or Lua/Python consoles)?

**Comment by chrisant996** [comment]
A program might be able to inject into other console programs, depending on how they are written.  But each console is going to have specialized behaviors.  And it takes experimentation and reverse engineering to figure out how to hook them, and whether it's even possible.

Clink is designed to integrate specifically with CMD.  The prompt, the commands, the argmatchers, the generators, the syntax, and many other things are all very specific to CMD.

Someone could certainly try to make programs that hook various other consoles, but that's not a direction that Clink is going to pursue.  It's not a small task.  But reading the Clink source code could be a place to start, to get familiar with what would be involved.
