### ISSUE TITLE
How could I get the last arg on the cmdline in order to use that as input to a function to generate another parser

### ISSUE THREAD

**Issue by ben-may** [chrisant996/clink#185]
Hi,

I have a situation where I want to use the last argument as input into a function to help generate results for the next parser.

As an example I have something like this:
```lua
optionsList = { "option1", "option2", "option3", "option4", "option5" }


function option_based_argparser(word)
	results = clink.execute("custom tool", 2000)
	if results ~= nil and #results > 0 then
		return results
	end

	return {}
end


local function run_sub_parser()
	local parser = clink.argmatcher()
	parser:addarg({ option_based_argparser })
	parser:nofiles()
	return parser
end

local run = clink.argmatcher("run")
run:nofiles()
run:addarg(
	{
		{ optionsList } .. run_sub_parser(),
	}
)
```
How could I inside of option_based_argparser() get the previous argument (option1, option2 etc.) in order to be able to pass it onto my "custom tool" command line?

Any thoughts or ideas around this that don't suggest copy-pasting somthing for each option? 😄 

Thanks!

**Comment by chrisant996** [comment]
**UPDATE:**  Clink v1.3.10 will introduce an easy-to-use way to initialize (or re-initialize) an argmatcher on the fly.

Essentially it's this:

1. Create an argmatcher.
2. Set a callback function for (re)initializing it on demand (i.e. defer initialization until the argmatcher is actually used).
    - The callback function decides whether (re)initialization is needed (e.g. Premake5 actions and flags need to be re-initialized when the current directory changes).
    - The callback function can reset the argmatcher and initialize the argmatcher.

For example, the callback function could use `io.popen("premake5 --help 2>nul")` and parse the help text, and use `:addflags()` and `:addarg()` to initialize the argmatcher with the appropriate flags and arguments.

Note: The callback function is always executed as a coroutine. This means any `os.execute()` and `io.popen()` calls automatically allow typing input to remain responsive.

**Comment by ben-may** [comment]
This sounds great, any chance you can post an example of this?

**Comment by ben-may** [comment]
ah even better thanks!

**Comment by chrisant996** [comment]
Also, when v1.3.10 is released, I'll also post a sample `premake.lua` script that uses the delayinit stuff to parse the actions and flags from `premake5 --help` (and re-inits itself when the cwd is different than the previous init, since actions and flags in premake depend on the cwd).

**Comment by ben-may** [comment]
Awesome!  thanks for adding these features and improvements!

**Comment by chrisant996** [comment]
v1.3.10 is published, and the `premake_argmatcher.lua` script is in the Discussions section.
