### ISSUE TITLE
`--profile "dir\"` has problems

### ISSUE THREAD

**Issue by depler** [chrisant996/clink#188]
Here is sample: [clink with space.zip](https://github.com/chrisant996/clink/files/7440630/clink.with.space.zip)

Usage:
- unpack somewhere, preserve `clink with space` folder
- run `clink.bat`

Result: file `clink_errorlevel_338C.txt` created in profile folder, command history is not working

Interesting, that `--profile "%root%\profile\"` is failing, but `--profile "%root%\profile"` (without backslash) is working OK.

**Comment by chrisant996** [comment]
P.S.  the clink_errorlevel file is unrelated to this.  It's just how clink gets the %ERRORLEVEL% value, which is not a real environment variable.  The file is always present when `cmd.get_errorlevel` is true, which it is by default.

**Comment by chrisant996** [comment]
Also, commit 24a643336c62a73f85631a0efedd29dd875b3719 on Jan 26 2022 made Clink v1.3.4 and higher compensate for this issue when it occurs in the `--profile` flag.
