### ISSUE TITLE
Won't Install on Windows 11--Virus Warning

### ISSUE THREAD

**Issue by mfreeman-xtivia** [chrisant996/clink#190]
Have to tried to install on Windows 11, both through winget and by downloading the artifact directly from the Releases section here.

Windows Defender is reporting that the installer contains the Trojan:Win32/Wacatac.B!ml virus and refuses to install.

This is a relatively fresh copy of Windows 11

**Comment by chrisant996** [comment]
It's a false positive. There's nothing Clink can do to prevent that.

Please report the false positive to the anti-malware software's publisher so they can analyze and fix the false positive.

(I'll update the Troubleshooting Tips section of the Clink docs to make sure that's listed as what needs to be done.)

**Comment by chrisant996** [comment]
Also, you may or may not be able to download the .ZIP file instead and extract the files without getting a false positive.

There are two key spots where anti-malware software can get confused:  the installer program, and the `clink inject` command.  Either or both could get flagged as a false positive.  Typically the inject command is what gets flagged incorrectly, but sometimes the installer gets flagged incorrectly.
