### ISSUE TITLE
Question: How to enable rprompt

### ISSUE THREAD

**Issue by JanDeDobbeleer** [chrisant996/clink#195]
I configured clink to render the normal prompt. Now I want to also display an `rprompt` but somehow I can't figure out how to get it work (also not with the sample in the docs).

What am I missing?

```lua
-- oh-my-posh.lua
local p = clink.promptfilter(1)
function p:filter(prompt)
    prompt = io.popen("oh-my-posh.exe --config Z:\\.jandedobbeleer.omp.json"):read("*a")
    return prompt, false
end
function p:rightfilter(prompt)
    prompt = io.popen("oh-my-posh.exe --config Z:\\.rprompt.omp.json"):read("*a")
    return prompt
end
```

**Comment by chrisant996** [comment]
Per docs:

> If the filter function returns a string and a boolean, then if the boolean is false the prompt filtering is done and no further filter functions are called.

Returning `prompt, false` causes no further filter functions to be called.  So `p:rightfilter()` is not called, because first the left prompt is filtered, then the right prompt is filtered.

Move the `,false` from `:filter()` to `:rightfilter()`.

**Comment by chrisant996** [comment]
I will consider how to update the Right Side Prompt documentation section to point this out explicitly.

**Comment by JanDeDobbeleer** [comment]
I knew I was missing something obvious!

![image](https://user-images.githubusercontent.com/2492783/141515905-d289a436-22e7-4d8f-89ee-7eab51e98eea.png)

**Comment by chrisant996** [comment]
By the way, if you want to pass the exit code to oh-my-posh, you can:

```lua
prompt = io.popen("oh-my-posh.exe --config somefile.json --error "..os.geterrorlevel()):read("*a")
```

**Comment by JanDeDobbeleer** [comment]
@chrisant996 nice, now that we're here, any way to get execution time as well? I'm adding this to the oh-my-posh docs (maybe it gives some deserved traction here as well).

**Comment by chrisant996** [comment]
Execution time is not tracked directly by Clink, and some users have pointed out it is subject to interpretation, and they have different views on what it should cover.

But it's easy to use `clink.onbeginedit(func)` and `clink.onendedit(func)` to register callback functions when a prompt begins/ends.  Execution time would typically be considered the time from previousEnd to currentBegin.

E.g.
- https://github.com/chrisant996/clink-flex-prompt/blob/7822fe34d101de6771bb1c98fa5dbc75ee179cb5/flexprompt_modules.lua#L260
- https://github.com/chrisant996/clink-flex-prompt/blob/7822fe34d101de6771bb1c98fa5dbc75ee179cb5/flexprompt_modules.lua#L893

**Comment by JanDeDobbeleer** [comment]
@chrisant996 this is amazing:

![image](https://user-images.githubusercontent.com/2492783/141612021-e430e780-aab6-4c0d-be24-b7cd7d73f902.png)

**Comment by JanDeDobbeleer** [comment]
@chrisant996 I have some news. As of the latest version of oh-my-posh, we have native support for CMD with Clink. Enabling the prompt is as simple as using the following:

```lua
load(io.popen("oh-my-posh --config=\"C:/Users/jan/jandedobbeleer.omp.json\" --init --shell cmd"):read("*a"))()
```

I'll create a PR to update the docs here.

**Comment by chrisant996** [comment]
Oh, clever!  I see wut u did there.  😊

**Comment by chrisant996** [comment]
> @chrisant996 no it does not, I can add a disclaimer that we only support as of version `v1.2.45`? Might be more straightforward than validating everything we use? We have the same issue for Bash for example, but we ask to update before complaining :-). I'm open to add the checks so the `load` doesn't crash, maybe you can help out (my Lua skills are rusty)?

Sure, I'm happy to suggest changes to the script. They'll be very minor. I'll clone your repo and make a PR there.

**Comment by chrisant996** [comment]
I noticed two things in the script:

1. I would like for oh-my-posh to use Clink's internal duration support in Clink builds with the fix for the 40-ish day failure.  It's only necessary to launch oh-my-posh once per prompt, but the script currently launches oh-my-posh 3 times per prompt.
2. There appears to be unfinished support for `--rprompt`.  The string.format call has 3 `%s`, but only passes 2 arguments, so the `--rprompt=%s` always ends up empty.

**Comment by JanDeDobbeleer** [comment]
The first one isn't an issue per se as it only returns the format we need (it's a super fast call), unless there's a structural issue with what you mentioned.

I'll check the second remark as I was certain I validated that change (also in the terminal).

**Comment by JanDeDobbeleer** [comment]
```lua
string.format("::OMP:: --config=\"::CONFIG::\" --execution-time %s --error %s --rprompt=%s", last_duration, os.geterrorlevel(), rprompt)
```

There's 3 times `%s`:
- last_duration
- os.geterrorlevel()
- rprompt

`rprompt` is passed as a function argument: `get_posh_prompt(false)`

**Comment by chrisant996** [comment]
> The first one isn't an issue per se as it only returns the format we need (it's a super fast call), unless there's a structural issue with what you mentioned.

The former is an issue to me.  Launching processes unnecessarily is something to avoid.  I think you're launching omp because you want milliseconds and `os.clock()` is in seconds.  But it's a float with microsecond precision.  Multiply by 1000 to get milliseconds.

> rprompt

Doh!  My mistake.  Check out what the line looked like on my screen:
![image](https://user-images.githubusercontent.com/17440311/141656919-2e17bf7c-28fd-49f4-8c1a-7b3647bc1b15.png)

I totally missed that the line extended past the edge.  Since the file is so short, the "thumbnail view" next to the scrollbar was empty there, and I misread the blank space as meaning the line ended.

**Comment by chrisant996** [comment]
I noticed an unrelated drawing quirk in OMP.

Notice the mismatched colors in the ">>" blank segments:
![image](https://user-images.githubusercontent.com/17440311/141657548-26010a1e-9b10-45cf-976a-fd7d9a63a435.png)

The end of one segment uses `49` as the background color, and the beginning of the next segment uses `30` as the text color.  It's clearly expecting that the background color is always black, i.e. that `49` will end up having the same effect as `40`.

That doesn't hold true in two cases:
1. When the background color is not black.
2. When the terminal program uses a custom background image (or see-thru blur effect of windows behind the terminal) for character cells where `49` is the background color.

**Comment by JanDeDobbeleer** [comment]
@chrisant996 that shouldn't be black but inverted ANSI (transparent foreground doesn't exist). But Windows Terminal can't handle that yet.

**Comment by chrisant996** [comment]
I can't figure out how to build OMP, and I don't have a Go compiler yet anyway.

So here is a patch file:

```
diff --git a/src/init/omp.lua b/src/init/omp.lua
index eb80b91..99063d9 100644
--- a/src/init/omp.lua
+++ b/src/init/omp.lua
@@ -3,10 +3,21 @@
 local endedit_time
 local last_duration
 
+local function os_clock_millis()
+    -- Clink v1.2.30 has a fix for Lua's os.clock() implementation failing after
+    -- the program has been running more than 24 days.  In older versions, call
+    -- OMP to get the time in milliseconds.
+    if (clink.version_encoded or 0) >= 10020030 then
+        return math.floor(os.clock() * 1000)
+    else
+        return io.popen("::OMP:: --millis"):read("*n")
+    end
+end
+
 local function duration_onbeginedit()
     last_duration = 0
     if endedit_time then
-        local beginedit_time = io.popen("::OMP:: --millis"):read("*n")
+        local beginedit_time = os_clock_millis()
         local elapsed = beginedit_time - endedit_time
         if elapsed >= 0 then
             last_duration = elapsed
@@ -15,13 +26,27 @@ local function duration_onbeginedit()
 end
 
 local function duration_onendedit()
-    endedit_time = io.popen("::OMP:: --millis"):read("*n")
+    endedit_time = os_clock_millis()
 end
 
 -- Prompt functions
 
+local function execution_time_option()
+    if last_duration ~= nil then
+        return "--execution-time "..last_duration
+    end
+    return ""
+end
+
+local function error_level_option()
+    if os.geterrorlevel ~= nil and settings.get("cmd.get_errorlevel") then
+        return "--error "..os.geterrorlevel()
+    end
+    return ""
+end
+
 local function get_posh_prompt(rprompt)
-    local prompt_exe = string.format("::OMP:: --config=\"::CONFIG::\" --execution-time %s --error %s --rprompt=%s", last_duration, os.geterrorlevel(), rprompt)
+    local prompt_exe = string.format("::OMP:: --config=\"::CONFIG::\" %s %s --rprompt=%s", execution_time_option(), error_level_option(), rprompt)
     prompt = io.popen(prompt_exe):read("*a")
     return prompt
 end
@@ -45,6 +70,7 @@ local function builtin_modules_onendedit()
     duration_onendedit()
 end
 
-
-clink.onbeginedit(builtin_modules_onbeginedit)
-clink.onendedit(builtin_modules_onendedit)
+if clink.onbeginedit ~= nil and clink.onendedit ~= nil then
+    clink.onbeginedit(builtin_modules_onbeginedit)
+    clink.onendedit(builtin_modules_onendedit)
+end
```

**Comment by JanDeDobbeleer** [comment]
I'll validate it 😁

**Comment by JanDeDobbeleer** [comment]
Validated and [live](https://github.com/JanDeDobbeleer/oh-my-posh/commit/2a44dca8981f2498ad361d490ce95d01d1fdb26d).

**Comment by JanDeDobbeleer** [comment]
PS: These are the exact same configs, just the color scheme which is different (so there shouldn't be black triangles):

![image](https://user-images.githubusercontent.com/2492783/141658292-5cf9fb0a-e44d-4a54-bc41-31e94d1ea4b8.png)

![image](https://user-images.githubusercontent.com/2492783/141658304-49d296f6-a585-489e-bab4-ce4b70262293.png)

**Comment by chrisant996** [comment]
I just noticed that oh-my-posh appears to maybe support Transient Prompt?
Clink supports Transient Prompt as well.  https://chrisant996.github.io/clink/clink.html#transient-prompt

**Comment by JanDeDobbeleer** [comment]
@chrisant996 yes, that was on my list to look at now that we got this working. Same for tooltips.

**Comment by chrisant996** [comment]
I'm not aware of any way to do tooltips on console output in Windows.  If e.g. Windows Terminal has an ANSI code for that then it could be done by Windows Terminal itself.  Is there such an ANSI code in Linux?  I haven't been able to find any articles about that.

**Comment by JanDeDobbeleer** [comment]
@chrisant996 tooltips is a different name for a contextual rprompt. It works like this: I type git + space and if applicable, my rprompt get swapped with a git segment. It triggers in space and then looks at the current string in the console to determine if it should render a contextual rprompt. Handy for info that doesn't require to be in your face all the time.

**Comment by chrisant996** [comment]
> @chrisant996 tooltips is a different name for a contextual `rprompt`.

Oh, I get it, thanks for explaining.

Clink can't do that at the moment, but it shouldn't be very hard to add. As usual the hardest part will be designing how to fit it into Clink's Lua APIs.

**Comment by chrisant996** [comment]
> Clink can't do that at the moment, but it shouldn't be very hard to add. As usual the hardest part will be designing how to fit it into Clink's Lua APIs.

Actually, it's possible already, but is a bit messy/involved and requires using a particular undocumented function.  I'll think through how to provide native support for it.

**Comment by chrisant996** [comment]
The OMP [Toolips](https://ohmyposh.dev/docs/config-tooltips) doc page calls outs:

> Keep in mind that this is a blocking call, meaning that if the segment renders slow, you can't type until it's visible. Optimizations in this space are being explored.

In Clink, the `prompt.async` setting (enabled by default) means the call can be async and you can continue to type.
