### ISSUE TITLE
installer checkboxes not working correctly

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#196]
@chrisant996: something doesn't look to be correct with the new "Use versioned install directory" setting introduced in `v1.2.44`. I have this **ticked** (the default) yet it installs to a `bin/` dir. Equally, I have "Add shortcuts to Start menu" **unticked** yet it creates them.

<img width="314" alt="screenshot" src="https://user-images.githubusercontent.com/1266205/141465797-2f6844d3-9d2b-49d0-b46f-ae463fd5dff0.png">

_Originally posted by @u01jmg3 in https://github.com/chrisant996/clink/issues/171#issuecomment-967067165_

**Comment by chrisant996** [comment]
What shortcuts does it add to Start menu?  For me, it added only the Uninstaller.  I guess it should not even add the uninstaller.

**Comment by chrisant996** [comment]
I can reproduce the problem with the "Use versioned install directory" checkbox, and will investigate.

**Comment by u01jmg3** [comment]
All working for me - thanks for fixing
