### ISSUE TITLE
contextual right side prompt

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#199]
@chrisant996 tooltips is a different name for a contextual `rprompt`. It works like this: I type `git + space` and if applicable, my `rprompt` get swapped with a git segment. It triggers on the `space` and then looks at the current string in the console to determine if it should render a contextual `rprompt`. Handy for info that doesn't require to be in your face all the time.

_Originally posted by @JanDeDobbeleer in https://github.com/chrisant996/clink/issues/195#issuecomment-968359015_

**Comment by chrisant996** [comment]
I'll think through how to support that in the Clink Lua API.

**Comment by chrisant996** [comment]
In v1.2.46 you can hook it up essentially the same way you did for PowerShell.

```lua
local tip_word

function ohmyposh_space(rl_buffer)
    rl_buffer:insert(" ")
    local words = string.explode(rl_buffer:getbuffer(), ' ', [["]])
    if words[1] ~= tip_word then
        tip_word = words[1] -- remember the first word for use when filtering the prompt
        clink.refilterprompt() -- invoke the prompt filters so omp can update the prompt per the tip word
    end
end

if rl.setbinding then
    clink.onbeginedit(function () tip_word = nil end)
    rl.setbinding(' ', [["luafunc:ohmyposh_space"]], 'emacs')
end
```

And when `tip_word ~= nil` then pass it to `oh-my-posh` in the prompt `:filter()` function.

**Comment by JanDeDobbeleer** [comment]
@chrisant996 I did the changes, do you know when that version will be available?

**Comment by chrisant996** [comment]
Here is a pre-release build, for testing purposes:
[clink.1.2.46.d511ff.zip](https://github.com/chrisant996/clink/files/7562676/clink.1.2.46.d511ff.zip)

**Comment by JanDeDobbeleer** [comment]
And here's a PR: https://github.com/JanDeDobbeleer/oh-my-posh/pull/1250

**Comment by chrisant996** [comment]
Wow! It works! (My surprise because I shared the sample code above without testing it first. 👀)

But there seems to be a problem with the transient prompt implementation.  If the theme doesn't have a transient prompt defined, then there ends up being no transient prompt.  So pressing <kbd>Enter</kbd> by itself erases the prompt and redraws the new prompt in the same location.

I'll add a note in the PR about a potential fix.

**Comment by JanDeDobbeleer** [comment]
All of the changes have been implemented. Works like a charm.

**Comment by chrisant996** [comment]
Can you make another tweak?

The omp.lua script can experience compilation errors if the user specifies a config file that uses backslashes.  This is because of the type of string quoting that is being used around the `::OMP::` and `::CONFIG::` placeholders.  Using the `[[`..`]]` quoting resolves the compilation errors.

I factored the placeholders into functions to further simplify the Lua script.

```patch
diff --git a/src/init/omp.lua b/src/init/omp.lua
index eceed4b..e8032f7 100644
--- a/src/init/omp.lua
+++ b/src/init/omp.lua
@@ -4,6 +4,14 @@ local endedit_time
 local last_duration
 local tip_word
 
+local function omp_exe()
+    return [[::OMP::]]
+end
+
+local function omp_config()
+    return [[::CONFIG::]]
+end
+
 local function os_clock_millis()
     -- Clink v1.2.30 has a fix for Lua's os.clock() implementation failing after
     -- the program has been running more than 24 days.  In older versions, call
@@ -11,7 +19,7 @@ local function os_clock_millis()
     if (clink.version_encoded or 0) >= 10020030 then
         return math.floor(os.clock() * 1000)
     else
-        return io.popen("::OMP:: --millis"):read("*n")
+        return io.popen(omp_exe().." --millis"):read("*n")
     end
 end
 
@@ -47,7 +55,7 @@ local function error_level_option()
 end
 
 local function get_posh_prompt(rprompt)
-    local prompt_exe = string.format('::OMP:: --shell=cmd --config="::CONFIG::" %s %s --rprompt=%s', execution_time_option(), error_level_option(), rprompt)
+    local prompt_exe = string.format('%s --shell=cmd --config="%s" %s %s --rprompt=%s', omp_exe(), omp_config(), execution_time_option(), error_level_option(), rprompt)
     prompt = io.popen(prompt_exe):read("*a")
     return prompt
 end
@@ -60,7 +68,7 @@ function p:rightfilter(prompt)
     if tip_word == nil then
         return get_posh_prompt(true), false
     end
-    local prompt_exe = string.format('::OMP:: --shell=cmd --config="::CONFIG::" --command="%s"', tip_word)
+    local prompt_exe = string.format('%s --shell=cmd --config="%s" --command="%s"', omp_exe(), omp_config(), tip_word)
     tooltip = io.popen(prompt_exe):read("*a")
     if tooltip ~= "" then
         return tooltip, false
@@ -68,7 +76,8 @@ function p:rightfilter(prompt)
     return get_posh_prompt(true), false
 end
 function p:transientfilter(prompt)
-    prompt = io.popen('::OMP:: --shell=cmd --config="::CONFIG::" --print-transient'):read("*a")
+    local prompt_exe = string.format('%s --shell=cmd --config="%s" --print-transient', omp_exe(), omp_config())
+    prompt = io.popen(prompt_exe):read("*a")
     if prompt == "" then
         prompt = nil
     end
```

**Comment by JanDeDobbeleer** [comment]
Done.

**Comment by chrisant996** [comment]
Introduced by 4648a59dcd7771bf6b6f4bdb1f6b01723336988b and 5f68dec1515a3a5ef661362a769606f94ab2d687.
