### ISSUE TITLE
how can a lua script use a path with spaces?

### ISSUE THREAD

**Issue by dchornbaker** [chrisant996/clink#201]
here is my workaround (this is my first lua script)
local onedrive = os.expandenv("%onedrive%") .. "/ompThemes/daveho.json"
local poshpath = os.getshortpathname(os.expandenv("%localappdata%")) .. "\\programs\\oh-my-posh\\bin\\oh-my-posh.exe"
local cmd = poshpath .. " --config " .. onedrive .." --init --shell cmd"
--print(cmd) 
--print (xx)
load(io.popen(cmd):read("*a"))()

**Comment by chrisant996** [comment]
The oh-my-posh.lua sample script does not reference %homepath%.

Please show the script that encountered problems.

Also, it works fine with spaces in the path name when I try.  So I anticipate there is probably a syntax error in the modifications that were made to the sample script.
