### ISSUE TITLE
History changes

### ISSUE THREAD

**Issue by pmbnecc** [chrisant996/clink#202]
When I type history, the history is presented.  When I run a bang command, the history changes.  This is not normal behavior for history.  The history order should not be altered:

E:\Roger\Documents\Rainmeter\Skins\CAPRadio>history
    1  e:
    2  cd Roger\Documents\Rainmeter\Skins\CAPRadio\
    3  python capradio.py

E:\Roger\Documents\Rainmeter\Skins\CAPRadio>!1

E:\Roger\Documents\Rainmeter\Skins\CAPRadio>history
    1  cd Roger\Documents\Rainmeter\Skins\CAPRadio\
    2  python capradio.py
    3  e:

**Comment by chrisant996** [comment]
See `clink set history.dupe_mode`.

Sounds like you want to use `clink set history.dupe_mode add`.

**Comment by pmbnecc** [comment]
Thanks.  That worked.  I am used to how bash history works, so I was really confused buy this!
