### ISSUE TITLE
crash with chinses path

### ISSUE THREAD

**Issue by imazes** [chrisant996/clink#203]
when clink run with a chinese path it will not work,but clink0.49 work right

+ `clink.1.2.46.69fc92`work wrong
![image](https://user-images.githubusercontent.com/13517533/143217038-1a24ffca-0c08-48a4-8e33-5a88e105c67a.png)

+ but clink 0.49 work wright
![image](https://user-images.githubusercontent.com/13517533/143217280-79374ae1-d746-4e0c-9dc9-97df8a13fb85.png)

**Comment by imazes** [comment]
here is the log
```
0b60 inject                    545 ---- 2021/11/24 18:04:56.417 -------------------------------------------------
0b60 inject                    546 Injecting Clink...
0b60 copy_dll                  122 *** ERROR ***
0b60 copy_dll                  122 Failed to copy DLL to 'C:\Users\imazes\AppData\Local\Temp\clink\dll_cache\1.2.46.69fc92_5611a907\clink_dll_x64.dll'
0b60 copy_dll                  122 (last error = 2)
0b60 inject_dll                264 Version: 1.2.46.69fc92
0b60 inject_dll                265 Arch: x64
0b60 inject_dll                266 DLL: D:\clink.1.2.46.69fc92 space 中文\clink_dll_x64.dll
0b60 inject_dll                268 Parent pid: 12412
0b60 check_dll_version         154 *** ERROR ***
0b60 check_dll_version         154 Unable to get DLL version for 'D:\clink.1.2.46.69fc92 space 中文\clink_dll_x64.dll'
0b60 check_dll_version         154 (last error = 2)
0b60 inject_dll                273 EXE version: 00010002 0000002e
```

**Comment by chrisant996** [comment]
A workaround is to set the system code page to UTF8.

But the issue should be fixed in this build:
[clink.1.2.47.dfb717.zip](https://github.com/chrisant996/clink/files/7598046/clink.1.2.47.dfb717.zip)

Can you please confirm?
After confirmation, I will publish an official update.

**Comment by imazes** [comment]
+ first of all:its work right with the chinese path,but thers are some `tiny error`

tiny error:
+ `clink autorun show` show the wrong path
![image](https://user-images.githubusercontent.com/13517533/143338708-9f1dbde4-2984-4f01-ae68-ac6b5973c916.png)

**Comment by chrisant996** [comment]
Great!  Thanks for confirming.

I'll fix the `clink autorun show` issue as well.

There may be other places where Clink was still relying on the system code page being UTF8.  If you run into other issues, please report them, and I'll fix them as well.
