### ISSUE TITLE
Can I disable intercept_directory?

### ISSUE THREAD

**Issue by elieux** [chrisant996/clink#204]
Looks like there's no configuration to disable this, or specifically the "just directory" lines.

**Comment by chrisant996** [comment]
Can you share more context?

What problem is occurring?

**Comment by elieux** [comment]
Wow, quick.  Not exactly a problem yet, but I didn't expect this feature to exist and it feel like I'm gonna bump into it unknowingly and be confused for a minute at some point.

**Comment by chrisant996** [comment]
Have you ever typed a directory name by itself before in plain cmd.exe?  It results in a syntax error.

If you've never encountered that before, maybe this feature isn't going to be a problem?

I suggest we wait and see whether there's a problem, before making any change.

**Comment by elieux** [comment]
I'm sure I did, but yes, probably extremely rarely.  And yes, I would expect an error.

It's nothing critical for me, I was just reading the change logs and found this interesting.  You can close this ticket.

**Comment by elieux** [comment]
Thanks for the quick response.
