### ISSUE TITLE
Script validation for Starship

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#206]
Hi!

After making a ton of feature requests to Clink, I feel this is the way to contribute back 😅

I'm working on adding Clink support to Starship. It was requested by someone last year on their repo - https://github.com/starship/starship/issues/1766. 

The code part is already done - see https://github.com/rashil2000/starship/commit/f83d15f99cbf80ebc86e167fec4113d044eae180.

Starship works in a similar way to OhMyPosh, by printing an init script. I have written an init script, which I would like to run through by you before making a PR in the Starship repo.

The `starship prompt` command accepts the following arguments:
- **--cmd-duration**: see below for this implementation.
- **--jobs**: Cmd doesn't have jobs.
- **--keymap**: this accepts the current keymap. I saw a function called `rl.getbinding()` in Clink's docs, but as far as I understand, it doesn't return the current editing mode ('emacs', 'vi-command' or 'vi-insert'). Is there a way to get this information?
- **--pipestatus**: Cmd doesn't have this.
- **--status**: I used `os.geterrorlevel()` for this.
- **--terminal-width**: I used `console.getwidth()` for this.

Here's the init script:

```lua
if (clink.version_encoded or 0) < 10020030 then
  error("Starship requires a newer version of Clink; please upgrade to Clink v1.2.30 or later.")
end

local starship_prompt = clink.promptfilter(5)

start_time = os.clock()
end_time = 0
curr_duration = 0
is_line_empty = true

clink.onbeginedit(function ()
  end_time = os.clock()
  if not is_line_empty then
    curr_duration = end_time - start_time
  end
end)

clink.onendedit(function (curr_line)
  if starship_precmd_user_func ~= nil then
    starship_precmd_user_func(curr_line)
  end
  start_time = os.clock()
  if string.len(string.gsub(curr_line, '^%s*(.-)%s*$', '%1')) == 0 then
    is_line_empty = true
  else
    is_line_empty = false
  end
end)

function starship_prompt:filter(prompt)
  if starship_preprompt_user_func ~= nil then
    starship_preprompt_user_func(prompt)
  end
  return io.popen([[::STARSHIP::]].." prompt"
    .." --status="..os.geterrorlevel()
    .." --cmd-duration="..math.floor(curr_duration*1000)
    .." --terminal-width="..console.getwidth()
    .." --keymap="..rl.getvariable('keymap')
  ):read("*a")
end

function starship_prompt:rightfilter(prompt)
  return io.popen([[::STARSHIP::]].." prompt --right"
    .." --status="..os.geterrorlevel()
    .." --cmd-duration="..math.floor(curr_duration*1000)
    .." --terminal-width="..console.getwidth()
    .." --keymap="..rl.getvariable('keymap')
  ):read("*a")
end

local characterset = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
local randomkey = ""
math.randomseed(os.time())
for i = 1, 16 do
  local rand = math.random(#characterset)
  randomkey = randomkey..string.sub(characterset, rand, rand)
end

os.setenv('STARSHIP_SHELL', 'cmd')
os.setenv('STARSHIP_SESSION_KEY', randomkey)
```

**Comment by rashil2000** [comment]
**Edit:** I've just pushed a commit to add pre-cmd and pre-prompt support for Clink - https://github.com/rashil2000/starship/commit/7585505de1a144e6944d9c767db3dca49ce70da8. Updated the init script accordingly.

**Comment by chrisant996** [comment]
> --pipestatus

Cmd does not have this.

> --keymap

It's not enough to get the keymap. It's also necessary to re-filter the prompt whenever the keymap changes (it always starts in emacs mode on every new prompt).

There is not currently a way to do either. I have been exploring some way for scripts to maybe hook "before input" and "after input", but I don't yet have any plan for that.

**Note:** currently neither oh-my-posh nor starship support asynchronous prompt filtering. I'm spoiled by asynchronous prompt filtering -- instant prompts are so nice! I've been talking with Jan DeDobbeleer (oh-my-posh author) about asynchronous prompts; there is a chance that oh-my-posh might be able to support them in the future. The tricky part is getting a new prompt to temporarily reuse info from the previous prompt.

**Comment by rashil2000** [comment]
> It's also necessary to re-filter the prompt whenever the keymap changes (it always starts in emacs mode on every new prompt).

I agree. Currently, the keymap functionality in Starship is only employed by zsh and fish. However, only zsh supports redrawing the prompt when keymap is changed on-the-fly (like from vi-insert to vi-command). The fish implementation is static AFAIK, which means it only displays if the preset keymap is emacs or vi (and doesn't change dynamically). I was thinking maybe Clink can have this type of limited functionality for the time being.

**Comment by rashil2000** [comment]
Regarding asynchronous prompts, it has been requested multiple times in Starship, and there's even a PR open - https://github.com/starship/starship/pull/2223. However it turned out to be a pretty major refractor and has been sitting stale for a while.

Other than that, does the init script look good to go?

**Comment by chrisant996** [comment]
All Readline variables, including `keymap` can be retrieved via `rl.getvariable()`.

P.S.  I misspoke -- Clink remembers the keymap between input lines.

**Comment by chrisant996** [comment]
I recommend for you to take a look at the init script that oh-my-posh emits.  Jan and I worked together to get a bunch of issues addressed.

I see some of the same issues likely exist in this starship script.  For example:
- the `::STARSHIP::` placeholders are probably going to be replaced in a way that will cause Lua compilation errors if the input path contains backslashes.
- there are several compatibility issues where this script relies on new features of Clink.  Ideally the script should either have some backward compatibility, or detect and fail gracefully when it's used with a too-old version of Clink.

**Comment by rashil2000** [comment]
> the ::STARSHIP:: placeholders are probably going to be replaced in a way that will cause Lua compilation errors if the input path contains backslashes.

I spent a good amount of time working on this. If you see [this](https://github.com/rashil2000/starship/commit/f83d15f99cbf80ebc86e167fec4113d044eae180#diff-019ec691c7aaefec4353fdd214565b8b3a28621ce706ac378d609138bb85ce3e) file in the first commit, I've written a `sprint_cmd()` function that escapes backslashes and encloses the binary filepath in backslash+doublequote pair, in a way that Lua can understand. Tested manually with both long paths and paths with spaces. A couple of tests are written in the same file too.

> It's also necessary to re-filter the prompt whenever the keymap changes

I have a question. When I put `set show-mode-in-prompt on` in my inputrc, I can see the mode being changed on the fly. How is Clink doing that?

![2](https://user-images.githubusercontent.com/46838874/143539124-c8ed87a6-4b52-4352-8c65-73aa32cd6b38.gif)

 > there are several compatibility issues where this script relies on new features of Clink. Ideally the script should either have some backward compatibility, or detect and fail gracefully when it's used with a too-old version of Clink.

I can look into this, but wouldn't it be alright if I just mentioned a recent enough version of Clink in the Starship docs as the minimum necessary?

**Comment by chrisant996** [comment]
> > the ::STARSHIP:: placeholders are probably going to be replaced in a way that will cause Lua compilation errors if the input path contains backslashes.
> 
> I spent a good amount of time working on this. If you see [this](https://github.com/rashil2000/starship/commit/f83d15f99cbf80ebc86e167fec4113d044eae180#diff-019ec691c7aaefec4353fdd214565b8b3a28621ce706ac378d609138bb85ce3e) file in the first commit, I've written a `sprint_cmd()` function that escapes backslashes and encloses the binary filepath in backslash+doublequote pair, in a way that Lua can understand. Tested manually with both long paths and paths with spaces. A couple of tests are written in the same file too.

Oh.  None of that was needed.  Lua has the `[[`..`]]` string quoting that makes that unnecessary.  That's why I said to look at what Jan and I did.  I still think you should look at what we did.

> > It's also necessary to re-filter the prompt whenever the keymap changes
> 
> I have a question. When I put `set show-mode-in-prompt on` in my inputrc, I can see the mode being changed on the fly. How is Clink doing that?
> 
> ![2](https://user-images.githubusercontent.com/46838874/143539124-c8ed87a6-4b52-4352-8c65-73aa32cd6b38.gif)

That's built into Readline; it inserts it at the beginning of the last line of the prompt.  Refer to the documentation for the `show-mode-in-prompt` config variable.

> > there are several compatibility issues where this script relies on new features of Clink. Ideally the script should either have some backward compatibility, or detect and fail gracefully when it's used with a too-old version of Clink.
> 
> I can look into this, but wouldn't it be alright if I just mentioned a recent enough version of Clink in the Starship docs as the minimum necessary?

You should find that it's very (very) simple to do.  Please don't produce a script that will fail with compile errors, because people will come to me for help.  I wouldn't appreciate that.  🙃

For example, putting this at the beginning of the script is very simple, and is very informative to a user.
```lua
if (clink.version_encoded or 0) < 10020046 then
    error("Starship requires a newer version of Clink; please upgrade Clink.")
end
```

**Comment by rashil2000** [comment]
> Oh. None of that was needed. Lua has the `[[`..`]]` string quoting that makes that unnecessary. That's why I said to look at what Jan and I did. I still think you should look at what we did.

I was not aware of `[[..]]`. Thanks, will definitely change it if it makes stuff simpler.

> You should find that it's very (very) simple to do. Please don't produce a script that will fail with compile errors, because people will come to me for help. I wouldn't appreciate that. 🙃
> 
> For example, putting this at the beginning of the script is very simple, and is very informative to a user.
> 
> ```lua
> if (clink.version_encoded or 0) < 10020046 then
>     error("Starship requires a newer version of Clink; please upgrade Clink.")
> end
> ```

I apologize. I thought you asked me to put a version check for each of the APIs used in the init script. This global check is a much cleaner method. Will make this change.

**Comment by chrisant996** [comment]
> I thought you asked me to put a version check for each of the APIs used in the init script. 

That was one of the options. I said either that, "or detect and fail gracefully when it's used with a too-old version of Clink."

> This global check is a much cleaner method. Will make this change.

Thanks!

**Comment by rashil2000** [comment]
I use these APIs in the init script:
```
1.1.6  - rl.getvariable()
1.1.11 - clink.onbeginedit()
1.1.20 - clink.onendedit(), console.getwidth()
1.2.14 - os.geterrorlevel()
1.2.16 - clink.onendedit() [breaking change]
1.2.24 - :rightfilter
1.2.30 - os.clock()
```

Hence, I chose 1.2.30 as the minimum version instead of 1.2.46. Updated the init script above.

Also made a commit - https://github.com/rashil2000/starship/commit/2d4d588c3d11e18da33655a8576cea28de3ae3b8 - to use `[[...]]`.

**Comment by chrisant996** [comment]
Quite reasonable!  Looks good to me.  I didn't do a detailed review, and I've never used starship, but I didn't notice any other issues.

**Comment by rashil2000** [comment]
Great! Closing this now.

Thank you soo much for your time!

**Comment by chrisant996** [comment]
Can you make a PR to update the "popular scripts" section in the `clink.md` documentation, to include a section on setting up the starship lua script?  It can be very short, just like the one for oh-my-posh.

**Comment by rashil2000** [comment]
Sure, but we should wait for the Starship PR to get merged first.

**Comment by rashil2000** [comment]
In a recent commit, I added support for TransientPrompt and TransientRightPrompt, see https://github.com/starship/starship/pull/3277#issuecomment-986829468

**Comment by rashil2000** [comment]
The PR has been merged. Needless to say, the maintainers are [pretty impressed](https://github.com/starship/starship/pull/3277#issuecomment-1003509312) by what Clink can do :)

**Comment by chrisant996** [comment]
Cool, thanks!
