### ISSUE TITLE
[Bug]  `clink-popup-show-help` gives error `attempt to index field rl_buffer`

### ISSUE THREAD

**Issue by pukkandan** [chrisant996/clink#209]
`clink-popup-show-help` is not working for me at all

#### Steps to reproduce:
* Create a new clink profile with an `.inputrc` file containing just `"\C-H": clink-popup-show-help` (I tried with multiple keybindings, all give same issue)
* Open cmd, press the key binding, and select any item from the popup

The action doesn't happen and instead I just get the output 
```
?:0: attempt to index field 'rl_buffer' (a nil value)
```

#### Version info
Windows 10.0.19043.1348
Clink v1.2.46.69fc92
Can reproduce this issue with both latest Windows terminal and the normal cmd

Let me know if any additional details are needed

**Comment by chrisant996** [comment]
Confirmed.  Looks like there was a last minute change in the command that wasn't tested well enough.
