### ISSUE TITLE
Scoop autoupdate breaks because of tag mismatch

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#214]
Scoop didn't update Clink today, because there's a mismatch in the tag in the URL.

This is the manifest:

```json
{
    "version": "1.2.50",
    "description": "Powerful Bash-style command line editing for cmd.exe",
    "homepage": "https://chrisant996.github.io/clink/",
    "license": "GPL-3.0-only",
    "notes": [
        "Run 'clink inject' to start clink on the current cmd",
        "Run 'clink autorun install' to auto start clink"
    ],
    "url": "https://github.com/chrisant996/clink/releases/download/v1.2.50/clink.1.2.50.f9e6ce.zip",
    "hash": "5992bc390f0f61b8f4901589347ce1f353e73c847fa6012fa8f65422d89c5800",
    "bin": "clink.bat",
    "persist": "profile",
    "checkver": {
        "github": "https://github.com/chrisant996/clink",
        "regex": "clink\\.([\\d.]+)\\.(?<commit>[\\w.]+)\\.zip"
    },
    "autoupdate": {
        "url": "https://github.com/chrisant996/clink/releases/download/v$version/clink.$version.$matchCommit.zip"
    }
}
```

The current download link is https://github.com/chrisant996/clink/releases/download/v1.3/clink.1.3.0.f070e4.zip which uses two different variants of the tag, one `1.3` and the other `1.3.0`. This is the reason autoupdate fails. See the logs here:
 
![image](https://user-images.githubusercontent.com/46838874/146222368-338d8ad7-5164-467f-9e68-06f5d8013468.png)

(Full logs here - https://github.com/ScoopInstaller/Main/runs/4533929886?check_suite_focus=true#step:3:196)

Can you please make the tags consistent?

**Comment by chrisant996** [comment]
Can the scoop manifest be updated?

v1.2 did the same, by the way.
I do version numbers like this in all my projects.

**Comment by rashil2000** [comment]
> Can the scoop manifest be updated?
> v1.2 did the same, by the way. 

It can be, but for next release it will need to be updated (manually) again.

The manifest was manually updated to use $majorVersion and $minorVersion in this commit - https://github.com/ScoopInstaller/Main/commit/8e8e12ac1dc5e25010da42e6fffe7c92c50bef02 - but this change was soon reverted manually in the next release itself - https://github.com/ScoopInstaller/Main/commit/153f502f4d4bd8dc29583ee4ea6ca5d8545bf036 - probably because the author of that commit felt that versioning is consistent again.

> I do version numbers like this in all my projects.

I understand. So the other option is to make the filename reflect `1.3` too, like `clink.1.3.f070e4.zip`. This works too because in the next release of Clink, Scoop will update both the tag and filename itself, consistently.

**Comment by chrisant996** [comment]
> > Can the scoop manifest be updated?
> > v1.2 did the same, by the way.
> 
> It can be, but for next release it will need to be updated (manually) again.

It is impossible in scoop to have an expression that accepts variations on a format??

> For v1.2, the manifest was manually updated to use $majorVersion and $minorVersion in this commit - [ScoopInstaller/Main@8e8e12a](https://github.com/ScoopInstaller/Main/commit/8e8e12ac1dc5e25010da42e6fffe7c92c50bef02) - but this change was soon reverted manually in the next release itself - [ScoopInstaller/Main@153f502](https://github.com/ScoopInstaller/Main/commit/153f502f4d4bd8dc29583ee4ea6ca5d8545bf036) - probably because the author of that commit felt that versioning is consistent again.

That makes it sound like it may be possible for scoop to recognize a format with optional fields.

> > I do version numbers like this in all my projects.
> 
> I understand. So the other option is to make the filename reflect `1.3` too, like `clink.1.3.f070e4.zip`. This works too because in the next release of Clink, Scoop will update both the tag and filename itself, consistently, i.e. `1.3.1` and `clink.1.3.1.abcdefg.zip`.

That's worse.  It is common to drop trailing ".0" in version numbers, after the minor number (e.g. v1.0 instead of v1.0.0.0 in schemes like maj.min.rev.hotfix).  But in "1.3.0.f070e4" the ".0" is not trailing.  Omitting the ".0" there causes problems -- for example, it breaks sorting files in version order, it puts one field in another field's spot in the naming convention making it harder to parse the name (both by humans and by tools), and several other subtle problems.

**Comment by rashil2000** [comment]
I have updated the manifest to capture tag as an extra regex variable
