### ISSUE TITLE
v1.3.0 compilation issue

### ISSUE THREAD

**Issue by ben-may** [chrisant996/clink#215]
Hi,
When taking v1.3.0 I hit a compilation issue where bcrypt.h include is missing from clink/process/src/process.cpp.  This include is needed for the definition of NTSTATUS.  The reason I may see this and you don't is because I build clink with pch disabled.  I was going to send you a pull request, but I don't seem to have permission to push to this repo, and I didn't want to make a fork and everything for a simple one-liner :) 

-Ben

**Comment by chrisant996** [comment]
How are you disabling pch?
And why?

**Comment by ben-may** [comment]
We have our own proprietary build-system that I ported clink to instead of using premake, and the pch setup was causing problems so I just didn't bother.  clink is a fairly small codebase in Comparission to our other codebases so the build-times are quite acceptable without pch enabled :) 
I will make a note to try and enable pch again now that I have this all setup and working fine, pch was just in the way of making progress before.

**Comment by ben-may** [comment]
So not sure if you want to commit my fix or not to the repo, that I suppose is up to you 😄

**Comment by chrisant996** [comment]
What I'm getting at is that precompiled headers on/off does (should) not by itself change what is included.

I want to know specifically how pch was turned off, so that I can troubleshoot what is happening.  Maybe I can suggest a different way of turning them off.

**Comment by ben-may** [comment]
I found it, I have WIN32_LEAN_AND_MEAN defined, that seems to make the standard #includes not include bcrypt.h, causing the compile error.  So I guess this is 100% on my side, unless you wanted to build clink in Lean and Mean mode 😃 

Sorry for wasting your time,

-Ben

**Comment by chrisant996** [comment]
Aha!  Cool, thanks.  Actually yes I think maybe I do want to use WIN32_LEAN_AND_MEAN.  I normally use that in my projects, but Martin had not, and I didn't notice.  I expect it may even affect the overall build time, though probably not by much.

**Comment by ben-may** [comment]
Yeah we use it quite a lot, (which is why it was set automatically by our build system) so if you do add that to clink then you'll need to fix that one file's includes I suppose.

Anyhow as always thanks for being so quick to respond/support!

**Comment by chrisant996** [comment]
Clink used WIN32_LEAN_AND_MEAN in some places, but not in others.
1. Made Clink consistent about when it defines `NOMINMAX`, `VC_EXTRALEAN`, and `WIN32_LEAN_AND_MEAN`.
2. Removed redundant `#include <Windows.h>`.

This shaved off 15% from the build time when building serially -- 27s instead of 32s.  (All timings used a hot disk cache, though it's a high performance SSD so the hot/cold numbers are almost the same anyway).

Sweet!  Thanks for the heads-up.

**Comment by ben-may** [comment]
Wow that's a pretty awesome improvement!

**Comment by ben-may** [comment]
I've enabled pch now locally also, and things build fine now, so that should remove differences between my setup and the premake setup.
