### ISSUE TITLE
Feature request: Add command aliases

### ISSUE THREAD

**Issue by baseely** [chrisant996/clink#219]
It will be very helpful to add command aliases same as *nix systems. 

for example: Common terminal commands such as clearing the screen (I can do this in `.bashrc` file easily) and listing the directory contents (`alias ll='ls -latr'`).

I don't know how this could be implemented, may be we can have an interactive script that one can run to define the corresponding `macros` in cmd.exe and add it to a temp file on the filesystem.

**Comment by pukkandan** [comment]
The Windows equivalent of `alias` is [`doskey`](https://en.wikipedia.org/wiki/DOSKEY) which you can set up inside [clink's startup script](https://chrisant996.github.io/clink/clink.html#gettingstarted_startupcmdscript)

**Comment by chrisant996** [comment]
Exactly, thanks @pukkandan. This is a Windows question, not specifically a Clink question.

**Comment by baseely** [comment]
Thanks @chrisant996 and @pukkandan. Great project, I use it daily now and eases my life !
