### ISSUE TITLE
Thank You Dear Dev!

### ISSUE THREAD

**Issue by aavramch** [chrisant996/clink#22]
I cannot express enough how excited I am about this project being resurrected. HUGE respect to you, @chrisant996 for giving a new life to this awesome app. Keep up the good work!!!

**Comment by chrisant996** [comment]
You're welcome!  I imagine we are probably similarly excited about that.  😁

**Comment by fronoske** [comment]
Dear @chrisant996 ,
​I also want to express my great gratitude to you.
​I have suffered from clink to improperly handle Japanese path names,
but that is a thing of the past thanks to this fork.

Thank you a lot!

**Comment by chrisant996** [comment]
> ​I have suffered from clink to improperly handle Japanese path names, but that is a thing of the past thanks to this fork.

Thank you, I'm very happy to hear confirmation that it works now for Japanese as well!

**Comment by isanych** [comment]
I was not able to make Ctrl-D and history work in original clink in latest server insider builds and here both are working, thank you so much 👍
