### ISSUE TITLE
How to change the codepage permanantly?

### ISSUE THREAD

**Issue by noisnemid** [chrisant996/clink#220]
when run chcp, it shows cp936, even if I change the CodePage of CMD.exe in regedit.
How to change the codepage to 65001 permanantly?

**Comment by garoto** [comment]
Perhaps adding "chcp 65001" to cmd's AutoRun entry under the registry key "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" might work.

**Comment by chrisant996** [comment]
> when run chcp, it shows cp936, even if I change the CodePage of CMD.exe in regedit.
> How to change the codepage to 65001 permanantly?
> 

How are you changing the codepage of cmd.exe in the registry?

(This issue isn't about Clink, but maybe we can help find an answer for the general Windows codepage management question.)

**Comment by noisnemid** [comment]
> 

Although it's some lucky that I have found some workaround for this issue, I post how it's solved and what I did before this:

```
Control Panel
> system's Language settings
> select Administrative language settings
> click Change system locale...
> check the Beta: Use Unicode UTF-8 for worldwide language support box>
> reboot the computer.

Then everywhere of consoles such as cmd, powershell, vscode's terminal emulator, xshell's conversations, and , of course, tabby/clink's console tabs are all said their code-pages are all 65001.

```

Before that, I did like this:

If the windows 10's release no is > 1903, then there's not a entry for CMD.exe in registry, but you can add it manually(not recommended) or generated it with some tricks:

run CMD, click the top-left icon of the opened window, and select 'Properties', and check 'Use legacy console... box, then re-open regedit, you'll find the CMD.EXE's entry at:

```
HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe
```

inside it, create a new DWORD32BIT, with name 'CodePage' and value '65001' in decimal.

then all cmd's code page will be 65001, even if you uncheck the 'Use legacy console' box.(If it was checked ,WSL/WSL2 might report errors).

Why didn't I use autorun? Because in fact I was using node.js' execSync to call some external commands and I want its stdout messages. About this communication between node.js and other programs in windows, it's another topic but here is a tip for doing that (even it's nothing about issue) in case someone else might wanted it:

```
let msg = execSync('cmd /c chcp 65001>null &&'+'dir /a {HERE YOU COULD ADD YOUR OWN COMMANDS}');
```

**Comment by chrisant996** [comment]
It sounds like you figured out how to solve whatever problem you were encountering.

It doesn't seem to have anything to do with Clink, so I'll close the issue.
