### ISSUE TITLE
some key bindings not working with Hyper terminal

### ISSUE THREAD

**Issue by ch-gz** [chrisant996/clink#223]
I just used clink with Hyper, currently found `ctrl`+`space` not working. Windows Terminal works.

**Comment by chrisant996** [comment]
> I just used clink with Hyper, currently found `ctrl`+`space` not working. Windows Terminal works.

Terminal programs often have built in key bindings. Hyper may have something bound to Ctrl+Space and intercepts it before Clink ever sees it.

Clink can't do anything about that.  It's an issue with Hyper.
