### ISSUE TITLE
Should clink stop removing "clink" and "history" aliases after exiting nested cmds?

### ISSUE THREAD

**Issue by nguyenduy4321** [chrisant996/clink#224]
I ran the command `clink autorun install` with the aim of injecting clink into the cmd as usual. Until one day, I encountered the following case:

1. Run cmd (clink works fine, `doskey /macros` sees aliases "_clink_" and "_history_")
2. Type cmd in cmd of step 1 (nested cmd, clink still work normally)
3. `Ctrl+D` to exit cmd (this cmd of step 2)... This time try `doskey /macros` and clink has removed the "_clink_" and "_history_" aliases.
4. `Ctrl+D` to exit cmd of step 1 (last cmd)... See that, `Ctrl+D` in step 4 still works, which means clink is still injected into cmd. But the aliases was accidentally removed.

Sorry for your eyes (because of my english), hope you try the above steps to see the same problem as me and add functionality to clink. I love clink.

**Comment by chrisant996** [comment]
What version of Clink are you using?  It sounds like you are using an old version.

Commit 1178ae16c07c4e863488fd2d488799fa4b1c8fe3 on 5/31/2021 resolved the symptom you describe, and the fix was published in v1.2.10 on 6/6/2021.

**Comment by nguyenduy4321** [comment]
Omg, sorry for the omission while I looked into the issue. I used `clink` (old version) in `cmder`
