### ISSUE TITLE
How to change ctrl+left and ctrl+right behavior?

### ISSUE THREAD

**Issue by sindzicat** [chrisant996/clink#225]
Hello!

I'm new to clink. Just install it today.

Let's say we have some link in conemu (tab cmd):

```
https://download.manjaro.org/kde/21.2.1/manjaro-kde-21.2.1-minimal-220103-linux515.iso.torrent
```

In clean Conemu <kbd>ctrl</kbd>+<kbd>→</kbd> and <kbd>ctrl</kbd>+<kbd>←</kbd> move to the right end or to the left end of this link. After I installed clink these keys move me between words inside link. Is it possible to revert such behavior? I believe this may be changed by user in settings.

Best regards,
Sindzicat.

**Comment by chrisant996** [comment]
There is no way in bash or Clink to make spaces be the only word break characters.

You could write a Lua function to advance to the next or previous space, and bind it to the corresponding keys.

**Comment by sindzicat** [comment]
Is it possible to just unbind any actions from ctrl+→ and ctrl+←?

**Comment by chrisant996** [comment]
> Is it possible to just unbind any actions from ctrl+→ and ctrl+←?

Unbinding the keys will make them do nothing at all.  The documentation describes how to bind and unbind keys.
