### ISSUE TITLE
clink crashed while tabbing for suggestion/completion when Terminal Window is maximized

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#228]
Hi,

clink crashed while using the autosuggestion feature (pressing `tab` after typing `git checkout`):
![image](https://user-images.githubusercontent.com/29235332/151135484-f410cb21-0053-4d09-ae27-0f1316d95154.png)

Dump file is attached:  [clink.dmp.zip](https://github.com/chrisant996/clink/files/7940345/clink.dmp.zip)

**Clink only crashes, if the Terminal App (Windows Terminal Preview and traditional cmd.exe) ist running as maxmimized window!** In normal mode auto suggestion is working without problems.

It is reproducable.\
I'm using [this](https://github.com/vladimir-kotikov/clink-completions) completion lua scripts.

**Comment by chrisant996** [comment]
(A clarification: <kbd>tab</kbd> doesn't accept an autosuggestion.)

OOOOPS; thanks for reporting this!

Look at 7fc76b01c6933; an argument was meant to be by reference, but was accidentally by value.  This caused the caller to not know that the number of columns to consider had been capped, and the caller ran off the end of the array.

The crash occurs when `match.fit_columns` is true and the terminal width is greater than 150 characters.  For performance (both CPU and memory consumption), the number of fitted columns is capped at 50 (i.e. max of 50 columns of auto-fit-width matches on the same line).  The limit itself is ok:  it is so large that if you reach it you're going to have trouble reading the matches anyway.  But the caller wasn't informed that the limit had been imposed, and that is much less ok.  😜

You can work around it by `clink set match.fit_columns false`.
