### ISSUE TITLE
old-menu-complete command not seeing .bat files

### ISSUE THREAD

**Issue by dougbenham** [chrisant996/clink#23]
If I'm not mistaken, using the old-menu-complete command should cycle through any .bat files.

**Comment by chrisant996** [comment]
Can you share more information?

`old-menu-complete` is my most-used completion command, and it cycles through .bat files for me.

- What is the `%PATHEXT%` environment variable set to?  (`set PATHEXT`)
- What is the `exec.enable` clink setting?  (`clink set exec.enable`)
- What are the other `exec.*` clink settings?  (`clink set`)
- How is `old-menu-complete` being used?
  - What was typed as the string to be completed?
  - Was it the first character on the line?  Or were there any spaces before it?
- What does happen when using `old-menu-complete`?

Thanks!

**Comment by dougbenham** [comment]
`clink set exec.cwd true` fixed it thanks! Strange that it wasn't set to true by default.

**Comment by chrisant996** [comment]
> `clink set exec.cwd true` fixed it thanks! Strange that it wasn't set to true by default.

Hm, yes, I'm not sure what Martin's reasoning was for making it false by default.
I've changed the default to true, for consistency with v0.4.x.

Thank you for reporting this!
