### ISSUE TITLE
Arrow Key Command History Navigation Not Working Using Windows 10's Built-in 'Touch Keyboard'

### ISSUE THREAD

**Issue by richaardvark** [chrisant996/clink#234]
Hello,

My main, everyday Windows machine is a tablet PC with a touchscreen and does not have a built-in keyboard. This tablet PC is connected to an LCD television and is typically operated from my couch. While there is a physical, wireless USB keyboard (and also a mouse) connected to my computer, it is frequently misplaced (also, I'm lazy) and thus I find myself most frequently using the built-in "Touch Keyboard" from the Windows 10 taskbar, operating it from the wireless mouse.

With a command prompt open, nothing happens when I click the Up and Down arrow keys on the on-screen Touch Keyboard - no command history is displayed. However, it is properly shown if I press the up and down arrow keys on the physical, USB-connected keyboard. Why does the virtual keyboard not work? Many people use convertible/"2-in-1" tablet PCs these days especially when traveling or when working out in the field and may not always have a physical keyboard available and are dependent on the on-screen virtual touch keyboard.

I am running Clink v1.3.5.f378c8 on Windows 10 version 10.0.19044.1503.

[(Originally posted here by accident.)](https://github.com/mridgers/clink/issues/571)

**Comment by chrisant996** [comment]
The virtual keyboard works perfectly for me with Clink on Windows 10 and on Windows 11.  Up, Down, and everything else work as expected.

Try running `clink echo` and then press <kbd>Up</kbd> and <kbd>virtual-Up</kbd> to see how each key gets reported.

Also, are you using the built-in ConHost terminal?  Or are you using a third party terminal program such as ConEmu or Cmder or ConsoleZ or etc?  Or are you using Windows Terminal?  Could your terminal program be intercepting the virtual keyboard input and preventing Clink from ever receiving it?

**Comment by chrisant996** [comment]
@richaardvark have you had a chance to try the suggestions from my previous response?

**Comment by chrisant996** [comment]
Closing the issue for now.  Will reopen if additional information becomes available, or if there are other similar reports.
