### ISSUE TITLE
Mouse input in Clink

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#235]
_Originally opened by @Remiol as [mridgers #572](https://github.com/mridgers/clink/issues/572) in the abandoned repo._

After some investigation, it looks like there are some tricks I can play to get mouse input to work in ConEmu, Windows Terminal, and plain default Conhost (it might work in other terminal hosts as well, but that will just be a happy accident).

The intent is to make clicking set the cursor position in the edit line (just like it does in GUI programs).  When clicking is enabled for Clink, then clicking to select text will not work by default, but will still be available by adding Shift, Ctrl, or Alt to the click.

- **ConEmu:**  I expect mouse input for Clink will always work in ConEmu, because ConEmu provides Quick Edit mode even when it's actually disabled.
- **Windows Terminal:**  mouse input will work for Clink when Quick Edit mode is off, which might end up needing to be a Clink setting.  When mouse input is enabled for Clink, the normal Windows Terminal click behaviors are still available by adding Shift, Ctrl, or Alt to the click.
- **Conhost:**  mouse input will work for Clink when Quick Edit mode is off.  There is already a checkbox in the console Properties dialog to control Quick Edit.  If Windows Terminal ends up needing a Clink setting to control Quick Edit mode, then the same setting will also affect Conhost.
    - It looks like Clink will be able to make the normal Quick Edit behaviors work (even when it's turned off) by adding Shift, Ctrl, or Alt to the click.  If that works as expected, it will be a nice enhancement to Conhost.

**Comment by chrisant996** [comment]
If Clink accepts mouse input, then:
- in Windows Terminal the mouse wheel stops working.
- in Conhost the mouse wheel stops working and the right-click context menu stops working when Quick Edit mode is Off.

However, holding Shift or Ctrl or Alt allows the mouse wheel to work in Windows Terminal.
And I'm able to play some tricks with Conhost so that the right-click context menu works when Quick Edit mode is Off, and holding Shift or Ctrl or Alt when left-or-right clicking makes the text selection and right-click Paste work, even when Quick Edit mode is Off!  And I should be able to emulate mouse wheel scrolling in Conhost.

So, mouse input should work very well in ConEmu, and will work pretty well in Conhost.
Mouse input will work ok in Windows Terminal, except that the mouse wheel will be unable to scroll the terminal, except when holding Shift or Ctrl or Alt.

So, there will be a setting for mouse mode in Clink, with probably 3 options:  On, Off, and Auto.

Auto will behave like this:
- In ConEmu, full mouse input support.
- In Conhost, full mouse input support in any window where Quick Edit mode is disabled.
- In Windows Terminal, Auto will not enable mouse input.

On will behave like this:
- In ConEmu, full mouse input support.
- In Conhost, disable Quick Edit mode and enable mouse input, but temporarily re-enable Quick Edit mode when holding Shift or Ctrl or Alt.
- In Windows Terminal, enable mouse input (which disables mouse wheel scrolling), and holding Shift or Ctrl or Alt activates normal Windows Terminal mouse support.

It's unfortunate that Windows Terminal gets the worst behavior of the 3.  I'll try to work with the Windows Terminal team to see if that can be improved in the future.

**Comment by Remiol** [comment]
Great, thank you very much!

**Comment by pukkandan** [comment]
> I'll try to work with the Windows Terminal team to see if that can be improved in the future.

Hope that pans out. I was excited for this feature, but the limitations in WT is too much, atleast for me.

If this cannot be improved, would it be possible to have clink's mouse input work only with `shift` pressed and have the normal operations work without a modifier?

**Comment by chrisant996** [comment]
> Hope that pans out. I was excited for this feature, but the limitations in WT is too much, atleast for me.

Which of the limitations are too much for you?

- The mouse wheel being unable to scroll?
- Or text selection (Quick Edit mode) only working with a modifier key?

Windows Terminal dropped support for scrolling, and for reading the scrollback buffer.  On the basis that Linux can't do those. That is a big irritant for me.  And it seems strange for Microsoft to cut a differentiating feature because "Linux can't do it".  But it is only a differentiating feature for some specialized niche usage.

I use many console programs that accept mouse input, and I click on a window to activate it.  So I have always turned off Quick Edit mode in console windows, because it was too disruptive for me.  So, having always needed to use a context menu to access text selection, being able to just hold `Shift` to get text selection is a bonus, for me.

The complete lack of programmatic scrolling at all in Windows Terminal is what I find frustrating.  😭😠

> If this cannot be improved, would it be possible to have clink's mouse input work only with `shift` pressed and have the normal operations work without a modifier?

That might be technically possible.  It is problematic because different modifier keys already activate different modes for mouse input in Windows Terminal.  So no matter what modifier key (or none) is chosen, it still means making some Window Terminal features unusable.

So far I've observed these special behaviors:
- `Ctrl` click follows a hyperlink.
- `Ctrl` wheel zooms.
- `Alt` click does column block text selection.
- `Shift` right click copies to clipboard without line break detection.
- _There may be other behaviors as well._

There _might_ be some way via `DECSET` codes to get Windows Terminal to only send click input (I'm skeptical, and haven't found one yet).  But with `DECSET` codes then Windows Terminal only supports clicks in the leftmost 80 columns.  😕

**Comment by pukkandan** [comment]
> Which of the limitations are too much for you?
> The mouse wheel being unable to scroll?
> Or text selection (Quick Edit mode) only working with a modifier key?

Both tbh. I use both of these features extremely often. (I didn't realize how much I scroll on console till tried using this!)

> Shift right click copies to clipboard without line break detection.

I did not even know about this 😓 .

> So no matter what modifier key (or none) is chosen, it still means making some Window Terminal features unusable.

For me, the `alt` and `shift` functionality are much less important than quickedit + scrolling and I wouldn't mind losing them. But I can see how others may not agree

**Comment by chrisant996** [comment]
And `shift`+`click` in Windows Terminal starts a new text selection, or if a text selection already exists then it extends the text selection.

So basically, each of `alt`, `ctrl`, and `shift` + `click` already have specific special behaviors in Windows Terminal.

I've added a `%CLINK_MOUSE_MODIFIER%` environment variable that allows specifying the set of modifier keys to activate Clink mouse input.  So e.g. `set CLINK_MOUSE_MODIFIER=ctrl shift` makes Clink mouse input only work while holding _both_ `ctrl` and `shift` and clicking or using the wheel mouse.  Or if Quick Edit is turned off in a plain Conhost terminal window, then Clink mouse input will also work when holding no modifier keys, or when holding `ctrl` and `shift` (or whatever `%CLINK_MOUSE_MODIFIER%` is set to).

This more than Linux/Unix programs are able to achieve, so I guess on the one hand we are fortunate to get this much.  On the other hand, things that have worked flawlessly for decades suddenly are no longer supported in Windows Terminal, and that feels harsh.  In exchange, we get tabs and emoji and acrylic.  Tradeoffs.  🤷‍♂️

**Comment by pukkandan** [comment]
> I've added a %CLINK_MOUSE_MODIFIER% environment variable that allows specifying the set of modifier keys to activate Clink mouse input. 

tysm. Will check it out as soon as a new release rolls out

Shouldn't this be a setting rather than an env var? I don't mind either way, just asking

**Comment by chrisant996** [comment]
> > I've added a %CLINK_MOUSE_MODIFIER% environment variable that allows specifying the set of modifier keys to activate Clink mouse input.
> 
> tysm. Will check it out as soon as a new release rolls out
> 
> Shouldn't this be a setting rather than an env var? I don't mind either way, just asking

Needs to be an environment variable so that you can e.g. use a startup script to use different key combinations for different terminal programs.  Windows Terminal is the super limited one.  ConEmu and plain Conhost can work with full functionality.

If Windows Terminal hadn't cut support for `ScrollConsoleScreenBuffer`, then a setting could potentially have been reasonable.

**Comment by pukkandan** [comment]
> And shift+click in Windows Terminal starts a new text selection, or if a text selection already exists then it extends the text selection. And shift+ctrl has a meaning, and shift+alt has a meaning.

Do you know if these are documented anywhere? https://docs.microsoft.com/en-us/windows/terminal/tips-and-tricks#mouse-interaction does not mention them

**Comment by chrisant996** [comment]
They are standard behavior for selection in general. Except that column block selections are not widely supported in programs.
