### ISSUE TITLE
Typing delay at command prompt

### ISSUE THREAD

**Issue by skeeler** [chrisant996/clink#236]
Clink 1.3.5.f378c8 installed on 2 different machines via installer. No custom settings on either system. Everything works, but... on one system, there is a **4 second delay** when I press [Space] after typing a command name, e.g. `dir `, `git `, etc. On the other system there is no delay. I've run `clink set` on both systems, comparing the results, and they are identical. I have checked for invalid entries in the %PATH% environment variables (thinking perhaps Clink was "waiting" to access/check a non-existent location), but all entries are valid and accessible. Only difference between the 2 systems that I can see is the problematic one is running latest version of Windows 10 with all available updates, while the one working normally is running the latest version of Windows 11 with all available updates. I've checked for configuration settings that might help here <https://chrisant996.github.io/clink/clink.html>, but don't see anything obvious.

Here is the `clink.log` contents:
====================================================
15280 start_logger              154 ---- 2022/02/08 10:02:11.410 -------------------------------------------------
15280 start_logger              160 Host process is 'cmd.exe' (pid 86656)
15280 start_logger              164 DLL path is 'C:\Program Files (x86)\clink'
15280 start_logger              178 Windows version 10.0.19044 (x64)
15280 start_logger              181 Clink version 1.3.5.f378c8 (x64)
15280 host_cmd::validate        293 Host is not interactive; cancelling inject.
14608 history_db::compact      1499 History:  202 active, 66 deleted

Here is the `clink info` output:
====================================================
version          : 1.3.5.f378c8
session          : 83464
binaries         : C:\Program Files (x86)\clink
state            : C:\Users\skeeler\AppData\Local\clink
log              : C:\Users\skeeler\AppData\Local\clink\clink.log
default settings : C:\Program Files (x86)\clink\default_settings
settings         : C:\Users\skeeler\AppData\Local\clink\clink_settings
history          : C:\Users\skeeler\AppData\Local\clink\clink_history
scripts          : C:\Program Files (x86)\clink ; C:\Users\skeeler\AppData\Local\clink
default_inputrc  : C:\Program Files (x86)\clink\default_inputrc
inputrc          : %clink_inputrc%
                     (unset)
                 : state directory
                     C:\Users\skeeler\AppData\Local\clink\.inputrc
                     C:\Users\skeeler\AppData\Local\clink\_inputrc
                 : %userprofile%
                     C:\Users\skeeler\.inputrc
                     C:\Users\skeeler\_inputrc
                 : %localappdata%
                     C:\Users\skeeler\AppData\Local\.inputrc
                     C:\Users\skeeler\AppData\Local\_inputrc
                 : %appdata%
                     C:\Users\skeeler\AppData\Roaming\.inputrc
                     C:\Users\skeeler\AppData\Roaming\_inputrc
                 : %home%
                     C:\Users\skeeler\.inputrc
                     C:\Users\skeeler\_inputrc

**Comment by chrisant996** [comment]
Probably it is caused by a match generator that is doing something expensive.

If you installed from .zip or from the setup exe with "Use enhanced defaults" checked, then the `autosuggest.enable` setting is turned on.  That runs match generators while you type, to produce suggestions.  The match generators run in the background, but depending on specifically what they do, they might not fully support running in the background.

The best thing to do is figure out which match generator is causing it, and why.  Then either the match generator can be fixed, or maybe Clink can be extended to somehow compensate.

It's possible to turn off autosuggest.enable, of course, but that will hide the problem, and won't help towards fixing the problem for others as well.

Try this:
1. Press CTRL+X,CTRL+Z.  That will list the Lua scripts and line numbers that have match generators registered.
2. If you can send me those files, and the line numbers, I can probably find what is being slow.

**Comment by chrisant996** [comment]
Also, the clink.log file indicates that Clink is likely installed for AutoRun, which suggests you have likely installed via the setup exe file.  Probably "Use enhanced default settings" was checked, so probably the issue is indeed a match generator doing something non-optimally.

Do you ever experience a delay when using match completion, e.g. pressing when TAB?

Does the current directory contain symlinks to networked drives?
Any information about the current directory and its contents might be useful as well.

**Comment by skeeler** [comment]
@chrisant996 , correct I installed via setup.exe and checked the "Use enhanced default settings" option.

I do not experience any delays when using match completion (i.e. using TAB), only after entering a command and pressing SPACE.

Same problem exists for any directory I'm in (with or without git files, different drives, etc.).

No symlinks in the directories. I do have subst'd drives configured in the registry, but have the same thing on both systems (one experiencing delay, one not), so I'd imagine that is not the issue.

Pressing CTRL+x,CTRL+Z yields the following output:
===================================================
version:
  version       1.3.5.f378c8
  binaries      C:\Program Files (x86)\clink
session:
  session       115476
  profile       C:\Users\skeeler\AppData\Local\clink
  scripts       C:\Program Files (x86)\clink ; C:\Users\skeeler\AppData\Local\clink

(Use a numeric argument for additional diagnostics; e.g. press Alt+1 first.)
===================================================

Interesting that the above output doesn't seem to report on the following lua I have installed (both systems):
===================================================
 Directory of c:\Users\skeeler\AppData\Local\clink

02/07/2022  09:18 PM               114 oh-my-posh.lua
               1 File(s)            114 bytes
               0 Dir(s)  166,335,713,280 bytes free
===================================================

The contents of this file are:
===================================================
load(io.popen('oh-my-posh --config="C:/Users/skeeler/jandedobbeleer.omp.json" --init --shell cmd'):read("*a"))()
===================================================

I have the same configuration on both systems (with OhMyPosh installed on both of course), so again not sure if this is related to the delay experienced on just one system.

One additional bit of information that may be useful: I have noticed that in addition to the 4 second delay after typing a command followed by a space (before I can continue typing & see input), there also appears to be roughly a 3 second delay **after** the command has finished running before the next command prompt is displayed.

**Comment by skeeler** [comment]
@chrisant996 , I tried the following in order:
- clink set autosuggest.enable false => no change in behavior
- clink set color.executable "" => no change in behavior
- clink set color.unrecognized "" => no change in behavior

I set the above values back to original after noting no improvement.

I tried using the SysInternals `procdump` utility to capture a dump file, and ran into some issues getting the `cmd.exe` process loaded with procdump. After trying several variations, I happened to notice that the typing delay under clink had reduced noticeably; it had gone from 4 seconds down to approximately 500 milliseconds. The other system still has zero typing delay so the reduced delay of 500 ms is still slightly jarring - not fluid but I could probably live with it. Ideally I'd like to find the root cause and eliminate it so there is zero typing delay. If you could, would you share some details on the easiest/best way to capture a process dump we can use to investigate further?

**Comment by chrisant996** [comment]
Also, was v1.3.5 the first version you installed?  Was there a recent earlier version of Clink that didn't have a delay?

**Comment by chrisant996** [comment]
Oh, and try `clink set lua.debug true` and then CTRL+X,CTRL+Z.  I forgot that the `lua.debug` setting has to be enabled for it to list the registered Lua match generators and events and prompt filters and etc.

**Comment by skeeler** [comment]
> Oh, and try `clink set lua.debug true` and then CTRL+X,CTRL+Z. I forgot that the `lua.debug` setting has to be enabled for it to list the registered Lua match generators and events and prompt filters and etc.
> 
> Also, try turning off the ohmyposh prompt filter to see if that makes a difference.

After setting `lua.debg true` and running some commands, pressing `CTRL+X, CTRL+Z` yields:

    version:
      version       1.3.5.f378c8
      binaries      C:\Program Files (x86)\clink
    session:
      session       91128
      profile       C:\Users\skeeler\AppData\Local\clink
      scripts       C:\Program Files (x86)\clink ; C:\Users\skeeler\AppData\Local\clink
    events:
      onbeginedit:
            [string "-- Duration functions..."]:92
            [string "-- Duration functions..."]:118
      onendedit:
            [string "-- Duration functions..."]:97

Not sure if this helps - especially considering the lag is sub-second.

More interesting perhaps, I disabled OhMyPosh (renamed the .lua file), restarted the command shell, and clink exhibited **no delay whatsoever**. So based on this, I suspect the issue is likely in OhMyPosh. I checked version numbers and see there was an update to OhMyPosh (I have a scheduled task to run `winget upgrade --all` daily), so that probably explains why the original typing delay dropped from 4000 ms down to 500 ms.

Appreciate the detailed guidance you provided on capturing a process dump above. Given the delay is minimal and only present when OhMyPosh is active, we can probably close this issue.

**Comment by chrisant996** [comment]
Here is what is happening:

- **Slow when showing a new prompt:**  Oh-my-posh is taking a while to run.  This is an issue in oh-my-posh and/or your local oh-my-posh configuration.
- **Slow when pressing <kbd>Space</kbd>:**  Oh-my-posh hooks the <kbd>Space</kbd> key and runs oh-my-posh to figure out if it wants to change the right prompt (a sort of "tooltip"-like behavior).  This is an issue in oh-my-posh and/or your local oh-my-posh configuration.

Oh-my-posh has not yet hooked up support for asynchronous prompt filtering.  So it can't return quickly with an initial prompt (and follow up later with the more expensive background updates).

[clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) supports asynchronous prompt filtering, which makes showing the prompt instantaneous, even in huge git repos (the git status command runs in the background, and when it finishes, the prompt is refreshed with the results).
