### ISSUE TITLE
Re-running installer does not maintain previously selected "Autorun when cmd.exe starts"

### ISSUE THREAD

**Issue by u01jmg3** [chrisant996/clink#237]
- When I installed `v1.3.5`, "Autorun when cmd.exe starts" was ticked. Installing `v1.3.6` and the option is not selected as it should be (if my previous installer settings are loaded correctly).
- Worth noting I saw the same issue bumping from `v1.3.4` to `v1.3.5`

  <img width="374" alt="autorun" src="https://user-images.githubusercontent.com/1266205/153574585-c7c3ab4c-62b9-4667-bd7e-34c747eff36f.png">

**Comment by chrisant996** [comment]
Interesting, thanks.  I must have accidentally broken it when I converted the installer to use the Modern UI.

**Comment by chrisant996** [comment]
Oh -- actually -- this almost certainly got broken by fixing the timing bug in the installer, which had been why the install went to a versioned install folder.
