### ISSUE TITLE
Clink crashes while deleting history (F7, DEL)

### ISSUE THREAD

**Issue by wolfie-cz** [chrisant996/clink#239]
Hi,
thank you for this perfect tool! Clink the first thing I install on a new PC.

I am struggling though with all releases 1.3.4 and higher (tried them all one by one). When trying to delete some parts of history by pressing F7 and then DEL or CTRL-D, clink always crashes.  
I am not able to selective delete history  on all versions higher than 1.3.3.
![crash01](https://user-images.githubusercontent.com/99830179/154346626-b2aaad59-f385-46fc-ad07-eabe51f08de6.png)
 Without clink (the old pure command line) F7 and DEL works fine, but not any more after running clink.bat (or installing autorun for current user or for all users).

First I suspected advanced lua settings, then flexprompt, so I removed every addon but no change...
Then I thought maybe the non-english version of windows could be the issue,  so I installed a clean English Windows version but the result was the same.  I also tried these steps on Virtualbox without success.

Attaching zip file with logs, settings, screenshots, dmps and info files from WIN 10 and WIN 11. If needed, I can also upload TimeTravelDebugging trace file (about 80MB). 
[clink_crashes_on__DEL_history.zip](https://github.com/chrisant996/clink/files/8083169/clink_crashes_on__DEL_history.zip)

**Comment by chrisant996** [comment]
Such a high quality bug report!  Thank you for all the analysis and dump files.  You enabled it to take me only a moment to track down the issue and fix it.

The `win-history-list` command (bound by default to <kbd>F7</kbd>) indeed crashes when pressing <kbd>Del</kbd>.
The `clink-popup-history` command shows the same list but has some enhancements (such as incremental search, filtering based on what was typed in the input line before invoking it, and etc), and in the `clink-popup-history` command <kbd>Del</kbd> works without crashing.

So a workaround could be to bind the following in your .inputrc file:
```inputrc
"\e[18~":    clink-popup-history    # F7
```

I'll publish an updated release sometime in the next few days, which will include this fix plus a few minor other things.

P.S.  The `win-history-list` command doesn't filter the list, so it doesn't have the filtering data that `clink-popup-history` does.  In the code I missed accounting for when the filtering data is not present.

**Comment by wolfie-cz** [comment]
Thank you for a superfast reaction
working like a charm!
