### ISSUE TITLE
Compile error with VS2022

### ISSUE THREAD

**Issue by ben-may** [chrisant996/clink#240]
Hi, building v1.3.7 with Visual Studio 2022, produces this compiler error:
```
clink\src\clink\app\src\loader\inject.cpp(666,19): error C7664: '>': ordered comparison of pointer and integer zero ('void *' and 'int')
clink\src\clink\app\src\loader\inject.cpp(668,24): error C7664: '<': ordered comparison of pointer and integer zero ('void *' and 'int')
```
We can work around it locally for now, but wanted to let you know, so it can be fixed in future releases.
This compiler error does not show up when building with VS2019 so seems to be related to the newer compiler in VS2022.
Thanks!

**Comment by chrisant996** [comment]
I am not supporting VS 2022 yet.

I've added an `INT_PTR` cast, though.

But I don't plan to keep the code base compiling cleanly for compilers that I'm not using.  When I eventually start using VS 2022, then I'll support that compiler ... and will stop supporting VS 2019.

You might end up needing to do VS 2022 maintenance yourself in a branch.  You can send pull requests if you would like to see the changes get into the main repo.

**Comment by chrisant996** [comment]
If you are using builds compiled in-house directly from the main branch, then be aware you are using unsupported unreleased builds with potentially incomplete features.  It is equivalent to alpha-testing and I wouldn't recommend it unless you are willing to help with bleeding-edge regressions, malfunctions, and incomplete features.  I generally try to keep the main branch in good enough working order for me to personally use it, but every once in a while that doesn't turn out to be possible.  And sometimes it takes a couple days to notice crashes in edge cases.

I welcome the alpha-testing help!  I only want to make sure you know what you are signing up for.  😇

**Comment by ben-may** [comment]
Yep I totally understand, which is why we tend to keep to the official releases.  But we do like to compile it ourselves so we can easily debug things if something is funky.  We can send pull requests if we have VS2022 fixes.  I highly recommend switching to VS2022 though, its 64bit and quite a bit nicer than VS2019 :)
