### ISSUE TITLE
Need to open clink in windows terminal ?

### ISSUE THREAD

**Issue by ifelixculpa** [chrisant996/clink#242]
hi, want the clink to open in the windows terminal?
what shall be the path here?
the one I am using opens a separate terminal

![image](https://user-images.githubusercontent.com/13099434/154862028-cc35995d-a861-44dc-861e-833626a71912.png)

**Comment by chrisant996** [comment]
Clink attaches to a cmd.exe.

Clink.bat with no arguments starts a new cmd.exe window and then injects Clink.

Start cmd.exe (not clink.bat) in Windows Terminal.  Then invoke Clink to inject itself.

`cmd.exe /k {path_to_clink}\clink inject`

See the docs on `clink inject`, and search the docs for "inject" in general.

**Comment by chrisant996** [comment]
https://chrisant996.github.io/clink/clink.html

The third usage in the Usage section near the beginning of the documentation.

**Comment by ifelixculpa** [comment]
> https://chrisant996.github.io/clink/clink.html
> 
> The third usage in the Usage section near the beginning of the documentation.

thankyou but this needs to be done every time i open cmd in terminal?
