### ISSUE TITLE
Can I keep completion style both bash and windows?

### ISSUE THREAD

**Issue by 836454543** [chrisant996/clink#245]
Hi, I'm confused about it now.
Although I used to bash style, I sometimes want to use  windows style completion. 
I try to do this
`clink set clink.default_bindings bash`
set .inputrc file
`"\eq": old-menu-complete` and `"\eQ": old-menu-complete-backward`
`old-menu-complete` will show possible completion, which I don't want.
How can I make `alt+q` just like windows style completion?

**Comment by chrisant996** [comment]
Maybe you are trying to find the [Init File](https://chrisant996.github.io/clink/clink.html#init-file) and [New Commands](https://chrisant996.github.io/clink/clink.html#new-commands) sections in the documentation?
Maybe you are looking for the `clink-select-complete` command?

If those aren't what you're looking for, then please describe what you mean by "windows style completion".
What do you want to happen?
What do you mean by "`old-menu-complete` will show possible completion, which I don't want"?

**Comment by 836454543** [comment]
I'm sorry for my poor description.
`old-menu-complete` complete like Windows style, but it will list all possible completions above the current line just like Bash style. The cmd.exe just complete word, it will not display all possible completions above the current line. That is what I want.

**Comment by chrisant996** [comment]
I think you are saying:
- You want <kbd>Tab</kbd> to do bash-like completion (the `complete` command).
- You want <kbd>Alt+Q</kbd> to do a different kind of completion.
    - You want it to list all possible completions.
    - And you want it to also replace the current word each time with the next option from the list of possible completions.

I'm not sure if I understand accurately, though.

I think you are looking for the `clink-select-complete` command, as I mentioned earlier.
Have you tried that?

**Comment by 836454543** [comment]
You want `Tab` to do bash-like completion (the complete command).---------------------Yes Yes Yes
You want `Alt+Q` to do a different kind of completion------------------------------Yes Yes Yes
* You want it to list all possible completions.-----------------------------------NO NO NO!!!!!!!
* And you want it to also replace the current word each time.-----------------------------------Yes Yes Yes
* with the next option from the list of possible completions.------------------------NO NO NO!!!!!
* `clink-select-complete`--------------I konw it. It like PSReadLine. I set `Ctrl+Space` to do this.
Thanks for your patient answer

**Comment by chrisant996** [comment]
> * You want it to list all possible completions.-----------------------------------NO NO NO! I don't need it, but `old-menu-complete` do this.

No, `old-menu-complete` never lists anything.  It is the same as <kbd>Tab</kbd> in plain cmd.exe without Clink.

> * with the next option from the list of possible completions.------------------------NO NO NO!!!!!

That sounds like it contradicts the previous statement.
Here is an animated GIF file of how `old-menu-complete` works:
![old-menu-complete](https://user-images.githubusercontent.com/17440311/155828115-34a8c872-3a0b-4a02-ab43-39154daff3fd.gif)

Can you paste your entire `.inputrc` file here?
Maybe there is something else later in the file that's interfering?

**Comment by 836454543** [comment]
My `.inputrc` file
```
set completion-ignore-case on
set show-all-if-ambiguous on
set colored-completion-prefix on
set colored-stats on
set bell-style none
set editing-mode emacs

# ↑
"\e[A": history-search-backward
# ↓
"\e[B": history-search-forward
# alt + z
"\ez": undo
# alt + q
"\eq": old-menu-complete
# alt + Q
"\eQ": old-menu-complete-backward
"\t": complete
# ctrl + l，清除一整行内容
"\C-l": kill-whole-line

$if bash
    # cmd风格的操作
    # ctrl + ←
    "\e[1;5D": backward-word
    # ctrl + →
    "\e[1;5C": forward-word
    # Cmder中的alt + del
    "\e[3;3~": backward-kill-word
    # MobaXterm中的alt + del
    "\e\e[3~": backward-kill-word
    # ctrl + home
    "\e[1;5H": unix-line-discard
    # ctrl + end
    "\e[1;5F": kill-line
$endif

$if clink
    # 每次查询历史指令时，光标跳到指令的最末尾
    set history-point-at-end-of-anchored-search on
    # 跳转到父目录
    "\ep": clink-up-directory
    # ctrl + space选择补全
    "\e[27;5;32~": clink-select-complete 
    "\C-z": undo
    "\C-y": redo
    "\C-a": beginning-of-line
    "\C-e": end-of-line
    # alt + `设为文本%USERPROFILE%的快捷键，方便输入
    "\e`": "%USERPROFILE%"
$endif
```
My `clink set`:
![QQ图片20220226122850](https://user-images.githubusercontent.com/51070268/155828924-e79dd6ba-7e03-4a3c-a7a5-eaa15df86184.png)
![QQ图片20220226123038](https://user-images.githubusercontent.com/51070268/155829007-19ec15c2-093c-47cd-9199-19172d9ba710.png)

![a](https://user-images.githubusercontent.com/51070268/155829165-02ad50f2-e599-4e06-884e-71a6def4154f.gif)
