### ISSUE TITLE
tab completion not working for directories with spaces

### ISSUE THREAD

**Issue by jtnord** [chrisant996/clink#260]
possibly user error however.

since re-installing my machine and installing clink  `v1.3.11.0c8196`  tab completion does not work correctly for `cd` to options where there are multiple matches with spaces.

For example  `cd C:\pro`  <tab> completes to `cd "c:\Program` and has match suggestions of `Program Files\`  `Program Files (x86)\`  and `ProgramData\`
if you enter the next part of the directory to limit futher by typing a `<space>` then you end up with no suggestions at all.

Furthermore if you use `<ctrl>+<space>` to do the tab completion and select the `Program Files\` option then you have `cd "C:\Program Files\` at which point no further tab completion is possible.

Not in the above cases there is a single `"` before the `C:` added by the initial tab.

**Comment by chrisant996** [comment]
It's a regression in v1.3.11.  A fix is coming in v1.3.12 in the next day or two.
