### ISSUE TITLE
clear the info that show by clink I start cmd.exe

### ISSUE THREAD

**Issue by qwert-f** [chrisant996/clink#264]
![image](https://user-images.githubusercontent.com/50124761/161912558-daf9b41e-2d2d-4811-b3ea-e34991c649e3.png)
I want to konw what I can do to make the information clink added not show while I star my cmd, whether I can  use a setting file like the .hushlogin in linux to set it

**Comment by chrisant996** [comment]
I recommend reading the documentation.

Look in the sections about configuring Clink.  The Clink Settings section, in particular.

`clink set clink.logo none`

Name | Default | Description
-|-|-
`clink.logo`	| `full` | Controls what startup logo to show when Clink is injected. `full` = show full copyright logo, `short` = show abbreviated version info, `none` = omit the logo.
