### ISSUE TITLE
Clink doesn't propagate key press event in case of char 'c'

### ISSUE THREAD

**Issue by ReznicencuBogdan** [chrisant996/clink#265]
Never used clink before. I studied the documentation and it doesn't seem to be a problem related to misconfiguration. I noticed while using ConEmu that the lowercase character 'c' wasn't propagated to clink on key press. I thought the issue is related to ConEmu. However the same symptoms can be observed in command prompt. Did several tests with fresh installs; the problem persists. 
Note: uppercase 'C' is captured as it should.

Expected behaviour:
- on key - 'c' - press the letter 'c' is displayed

**Comment by chrisant996** [comment]
Hi, thanks for reporting this.  Being unable to type basic letters is very problematic!  I've never heard of a problem like this before, so some troubleshooting will be needed to figure out what's going on.

Hopefully you can type commands into Notepad and copy/paste them into CMD/Clink to get around the misbehaving 'c'.

Can you post the following info in a reply?

- What keyboard layout are you using?  "Romania (Moldova)", "Romania (Romania)", "English (United States) - International", etc?  Is there a separate `C` key on the keyboard, or is there a keyboard more or combination of keys that are necessary to type 'c'?
- Press <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>/</kbd> to invoke the `what-is` command, and then type <kbd>c</kbd>.  What command does Clink report is bound to the 'c' key?  (Depending on your keyboard layout `what-is` might be bound to a different key -- press <kbd>Alt</kbd> plus whatever keys are required for typing <kbd>?</kbd>.)
- Run `clink echo` and then press `c` and see what gets reported.
- Include the output from `clink info`.
- Find the ".inputrc" file mentioned above, and include its contents in the reply.

These questions are likely to find something we can investigate further.  Or if not, then there are some additional things we can try.

Again, thanks for reporting this, and I look forward to helping figure out what's going on.

**Comment by ReznicencuBogdan** [comment]
Oh! Never mind! Thank you for the quick response. After quite some time I realized it was some internal tool messing with the console.

**Comment by chrisant996** [comment]
> Oh! Never mind! Thank you for the quick response. After quite some time I realized it was some internal tool messing with the console. 

Oh, that's good news. Thank you for reporting the issue, and thank you for posting a follow-up with the outcome!
