### ISSUE TITLE
autocompletion for any file in current folder

### ISSUE THREAD

**Issue by bumbaras** [chrisant996/clink#266]
how to configure clink for any file autocomplete?

**Comment by chrisant996** [comment]
> Thank You, i figured it out. But if this is so simple why there are so many opened threads under cmder project without reliable solution? And i don't know why but autocompletion for py files without `exec.files` is not working as well. I added py to PATHEXT but still it doesn't work. Rest of `exec.*`. Is `exec_match_style` still valid settings?

The "without reliable solution" part is inaccurate.  The problem you were experiencing isn't a Clink issue.  It was a typo in how you updated PATHEXT:  `,` was used instead of `;`.

> OK, i read everything on cmder issues. No need to update this thread anymore. Link is: ([cmderdev/cmder#2686](https://github.com/cmderdev/cmder/issues/2686))

(This is the issue you added in the Clink repo, and so it should be updated to include the resolution.)
