### ISSUE TITLE
How do I make each cmd have separate history?

### ISSUE THREAD

**Issue by yar999** [chrisant996/clink#267]
Running `wsl` invalidates the `history.sticky_search`, 

The `ssh` command has the same problem, My ssh command is an alias for ssh in WSL

```sh
ssh=wsl ssh $*
```

Details are shown below:

![GIF 2022-4-14 10-22-53](https://user-images.githubusercontent.com/7338900/163331713-497ecef9-77a9-415c-8dd9-adf5a08abefe.gif)

`clink set`:

```
> clink set
autosuggest.async                 True
autosuggest.enable                True
autosuggest.original_case         True
autosuggest.strategy              match_prev_cmd history completion
clink.autostart
clink.colorize_input              True
clink.default_bindings            bash
clink.gui_popups                  False
clink.logo                        full
clink.paste_crlf                  crlf
clink.path
clink.promptfilter                True
cmd.admin_title_prefix
cmd.auto_answer                   off
cmd.ctrld_exits                   True
cmd.get_errorlevel                True
color.arg                         bold
color.arginfo                     yellow
color.argmatcher
color.cmd                         bold
color.cmdredir                    bold
color.cmdsep                      bold
color.comment_row                 bright white on cyan
color.description                 bright cyan
color.doskey                      bold cyan
color.executable
color.filtered                    bold
color.flag                        default
color.git.star                    bright green
color.hidden
color.horizscroll
color.input
color.interact                    bold
color.message                     default
color.modmark
color.popup
color.popup_desc
color.prompt
color.readonly
color.selected_completion
color.selection
color.suggestion                  bright black
color.unexpected                  default
color.unrecognized
debug.log_terminal                False
doskey.enhanced                   True
exec.aliases                      True
exec.commands                     True
exec.cwd                          True
exec.dirs                         True
exec.enable                       True
exec.files                        False
exec.path                         True
exec.space_prefix                 True
files.hidden                      True
files.system                      False
history.dont_add_to_history_cmds  exit history
history.dupe_mode                 add
history.expand_mode               not_quoted
history.ignore_space              True
history.max_lines                 0
history.save                      True
history.shared                    True
history.sticky_search             True
lua.break_on_error                False
lua.break_on_traceback            False
lua.debug                         False
lua.path
lua.reload_scripts                False
lua.strict                        True
lua.traceback_on_error            False
match.expand_envvars              False
match.fit_columns                 True
match.ignore_accent               True
match.ignore_case                 relaxed
match.max_fitted_matches          0
match.max_rows                    0
match.preview_rows                5
match.sort_dirs                   with
match.substring                   True
match.translate_slashes           system
match.wild                        True
prompt.async                      True
prompt.transient                  off
readline.hide_stderr              False
terminal.adjust_cursor_style      True
terminal.differentiate_keys       False
terminal.east_asian_ambiguous     auto
terminal.emulation                auto
terminal.mouse_input              auto
terminal.mouse_modifier
terminal.raw_esc                  False
terminal.use_altgr_substitute     False
```

**Comment by chrisant996** [comment]
I will try to interpret the screen recording.  In the future, it would help if a text description could be provided, so that I don't have to dust off my mind reading skills.  😉  Also, indicating "expected:" and "actual:" behavior are very helpful for understanding a problem report.

I think the screen recording shows the following:

1. **In the first cmd window:**
2. Type `echo 1` and press <kbd>Enter</kbd>.
3. Type `wsl` and press <kbd>Enter</kbd>.
4. **In the second cmd window:**
5. Type `echo 2` and press <kbd>Enter</kbd>.
6. That adds `echo 2` to the end of the shared history.
7. **In first cmd window:**
8. Press <kbd>Enter</kbd> or maybe <kbd>Ctrl</kbd>+<kbd>C</kbd> -- something to end the `wsl` command.
9. That reloads the shared history.
10. Press <kbd>Up</kbd>.

ACTUAL:  It pulls up the last history entry (`echo 2`).
EXPECTED:  I'm not sure exactly what you expect to have happened; maybe you expected it to pull up `wsl` or maybe you expected it to pull up `echo 1`.

As far as I can tell, the steps don't use the history search position until step 10.
So I don't understand how `history.sticky_search` would be relevant.

Here is the description of `history.sticky_search`:

```
❯ clink set history.sticky_search
        Name: history.sticky_search
 Description: Makes it easy to replay a series of commands
       Value: False

When enabled, reusing a history line does not add the reused line to the end
of the history, and it leaves the history search position on the reused line
so next/prev history can continue from there (e.g. replaying commands via Up
many times, Enter, Down, Enter, Down, Enter, etc).
```

"Reusing" a command means using history search (e.g. <kbd>Up</kbd> or <kbd>PgUp</kbd> or any other history search command) to recall a history entry into the line editor, and then using <kbd>Enter</kbd> to accept the recalled history line.

In the steps, the history search position was at the end the whole time, so no history entry was "reused", and `history.sticky_search` shouldn't have any effect.

**Comment by chrisant996** [comment]
In contrast, this is when `history.sticky_search` is relevant:

1. Type `clink set history.dupe_mode add` and press <kbd>Enter</kbd>.
2. Type `clink set history.sticky_search true` and press <kbd>Enter</kbd>.
3. Type `echo 1` and press <kbd>Enter</kbd>.
4. Type `dir` and press <kbd>Enter</kbd>.
5. Type `echo 2` and press <kbd>Enter</kbd>.
6. Press <kbd>Up</kbd> twice, to recall `dir` into the line editor, and press <kbd>Enter</kbd>.
7. Press <kbd>Up</kbd> twice.

EXPECTED:  It should recall `echo 1` into the line editor (not `echo 2`).

Typing commands doesn't make use of history search.
Cycling through next/prev history entries with the history search commands makes use of history search.

Hopefully that helps clarify what history search is.  The Readline documentation and History documentation may be able to further clarify how history works.

**Comment by yar999** [comment]
Sorry, I didn't add a description before

1. **In the first cmd window:**
2. Type `echo 1` and press Enter.
3. Type `wsl` and press Enter.
4. **In the second cmd window:**
5. Type `echo 2` and press Enter.
6. That adds `echo 2` to the end of the shared history.
7. **In first cmd window:**
8. Press  `Ctrl+D`  to end the `wsl` command.
9. That reloads the shared history.
10. Press Up.



ACTUAL: It pulls up the last history entry (`echo 2`).  
EXPECTED:  After pressing the Up key, the `wsl` should be pulled Up



Step 9 above is the cause of pulling `echo 2`

The share history is reloaded after the `wsl` command is executed, The `ssh` command in the WSL also has the same problem.

My `ssh` command is an alias for ssh in WSL (`ssh=wsl ssh $*`)

This problem can be solved by not reloading the share history after wsL-related commands are executed ?



```cmd
D:\Users\ys\Desktop
> clink set history.sticky_search
        Name: history.sticky_search
 Description: Makes it easy to replay a series of commands
       Value: True

When enabled, reusing a history line does not add the reused line to the end
of the history, and it leaves the history search position on the reused line
so next/prev history can continue from there (e.g. replaying commands via Up
many times, Enter, Down, Enter, Down, Enter, etc).

D:\Users\ys\Desktop
> clink set history.dupe_mode
        Name: history.dupe_mode
 Description: Controls how duplicate entries are handled
     Options: add,ignore,erase_prev
       Value: add

If a line is a duplicate of an existing history entry Clink will erase
the duplicate when this is set to 'erase_prev'.  A value of 'ignore' will
not add a line to the history if it already exists, and a value of 'add'
will always add lines.
Note that history is not deduplicated when reading/writing to disk.
```

Complete Clink configuration:

```cmd
D:\Users\ys\Desktop
> clink set
autosuggest.async                 True
autosuggest.enable                True
autosuggest.original_case         True
autosuggest.strategy              match_prev_cmd history completion
clink.autostart
clink.colorize_input              True
clink.default_bindings            bash
clink.gui_popups                  False
clink.logo                        full
clink.paste_crlf                  crlf
clink.path
clink.promptfilter                True
cmd.admin_title_prefix
cmd.auto_answer                   off
cmd.ctrld_exits                   True
cmd.get_errorlevel                True
color.arg                         bold
color.arginfo                     yellow
color.argmatcher
color.cmd                         bold
color.cmdredir                    bold
color.cmdsep                      bold
color.comment_row                 bright white on cyan
color.description                 bright cyan
color.doskey                      bold cyan
color.executable
color.filtered                    bold
color.flag                        default
color.git.star                    bright green
color.hidden
color.horizscroll
color.input
color.interact                    bold
color.message                     default
color.modmark
color.popup
color.popup_desc
color.prompt
color.readonly
color.selected_completion
color.selection
color.suggestion                  bright black
color.unexpected                  default
color.unrecognized
debug.log_terminal                False
doskey.enhanced                   True
exec.aliases                      True
exec.commands                     True
exec.cwd                          True
exec.dirs                         True
exec.enable                       True
exec.files                        False
exec.path                         True
exec.space_prefix                 True
files.hidden                      True
files.system                      False
history.dont_add_to_history_cmds  exit history
history.dupe_mode                 add
history.expand_mode               not_quoted
history.ignore_space              True
history.max_lines                 0
history.save                      True
history.shared                    True
history.sticky_search             True
lua.break_on_error                False
lua.break_on_traceback            False
lua.debug                         False
lua.path
lua.reload_scripts                False
lua.strict                        True
lua.traceback_on_error            False
match.expand_envvars              False
match.fit_columns                 True
match.ignore_accent               True
match.ignore_case                 relaxed
match.max_fitted_matches          0
match.max_rows                    0
match.preview_rows                5
match.sort_dirs                   with
match.substring                   True
match.translate_slashes           system
match.wild                        True
prompt.async                      True
prompt.transient                  off
readline.hide_stderr              False
terminal.adjust_cursor_style      True
terminal.differentiate_keys       False
terminal.east_asian_ambiguous     auto
terminal.emulation                auto
terminal.mouse_input              auto
terminal.mouse_modifier
terminal.raw_esc                  False
terminal.use_altgr_substitute     False
```

**Comment by chrisant996** [comment]
> ACTUAL: It pulls up the last history entry (`echo 2`).
> EXPECTED: After pressing the Up key, the `wsl` should be pulled Up

If that is the expectation, then it has nothing to do with `history.sticky_search`.  The steps don't involve any history search.

It seems you are looking for `history.shared`.

```
❯ clink set history.shared
        Name: history.shared
 Description: Share history between instances
       Value: False
```

You want to run `clink set history.shared false` so that history is not reloaded at every prompt.

**Comment by yar999** [comment]
`history.shared`  is not the main reason, other commands such as `ls` `cd` `pwd`, etc. do not have this problem as long as they are not WSL related

1. **In the first cmd window:**
2. Type `echo 1` and press Enter.
3. Type `pwd` and press Enter.
4. **In the second cmd window:**
5. Type `echo 2` and press Enter.
6. That adds `echo 2` to the end of the shared history.
7. **In first cmd window:**
8. Press Up.
9. It pulls up the last history entry (`pwd`) . `history.sticky_search` works fine.



do not have this problem as long as they are not WSL related

**Comment by pukkandan** [comment]
This is because the prompt was created before `echo 2` was run. To demonstrate this, change step 3 in your above example to `timeout 10000` (instead of `pwd`). Then only break the timeout after echo 2 has been run (at step 7)

**Comment by chrisant996** [comment]
> `history.shared`  is not the main reason, other commands such as `ls` `cd` `pwd`, etc. do not have this problem as long as they are not WSL related
> 
> 1. **In the first cmd window:**
> 2. Type `echo 1` and press Enter.
> 3. Type `pwd` and press Enter.
> 4. **In the second cmd window:**
> 5. Type `echo 2` and press Enter.
> 6. That adds `echo 2` to the end of the shared history.
> 7. **In first cmd window:**
> 8. Press Up.
> 9. It pulls up the last history entry (`pwd`) . `history.sticky_search` works fine.

The `pwd` command exits immediately, and the history has already reloaded in step 3, long before steps 6 or 8.

If you change step 8 to "press Enter, then Up" you will see `echo 2`.

Because this is about `history.shared`, not about `history.sticky_search`, nor about `wsl`.

The reason it appears as though wsl is involved, is because wsl does not return until you press Ctrl+D, which you are not doing until after you've already entered `echo 2` in the other cmd window.

If you change the original step 3 to also include Ctrl+D, then wsl would return before step 4, just like pwd does. Then the same problem will occur with wsl. Because it has nothing to do with wsl 🙃 -- it is only about when the command exits and returns control to cmd, which is when history gets reloaded when `history.shared` is True.

**Comment by yar999** [comment]
Ok, thank you for your patient reply @chrisant996
