### ISSUE TITLE
Crash after entering copy in Command Prompt

### ISSUE THREAD

**Issue by slhussey** [chrisant996/clink#268]
pushd to a network share: pushd \\fqdn of server\tss
cd to target directory: cd document
copy file: copy c:\Users\xxxxxxx\git_repos\tss_cf\document\P203060.pdf z:

Response:
Overwrite z:P203060.pdf? (Yes/No/All):
[process exited with code 3221225477 (0xc0000005)]

Version 1.3.13.24b02e on Win 10 Enterprise build 19042.1586 (20H2)

**Comment by chrisant996** [comment]
Ouch, it's a regression in v1.3.13.  It crept in during a last minute cleanup after validation testing.

I'll get a fix out today.

Here is the bug:

**host_cmd.cpp**
```cpp
        // Default behaviour.
        if (!hc->dequeue_char(chars))
            return TRUE;
        return __Real_ReadConsoleW(input, chars, max_chars, read_in, control);
```

The `!` is backwards.

**Comment by chrisant996** [comment]
v1.3.14 has been published with the fix.  Thanks for reporting this!
