### ISSUE TITLE
Windows 8.1+ansicon+cmd.exe: ANSI escapes aren't rendered with `type` and when part of a `doskey macro`

### ISSUE THREAD

**Issue by garoto** [chrisant996/clink#272]
Hello @chrisant996,

Clink version: 1.3.15.6e6e45

Simple text file with ANSI color escape sequences:

![screenshot-0727-16-04-2022_02](https://user-images.githubusercontent.com/11768175/163693278-ac81962c-65ca-43f5-bec0-a8e110aa20d9.png)

Doskey macro with ANSI color sequences:

![screenshot-0728-16-04-2022_02](https://user-images.githubusercontent.com/11768175/163693363-eb3b66e5-0833-415d-a890-8970253b14e4.png)

Log:
[clink.log](https://github.com/chrisant996/clink/files/8500733/clink.log)

Using default settings for testing purposes:

<details>
      <summary>Click to expand!</summary>

	autosuggest.async                 True
	autosuggest.enable                False
	autosuggest.original_case         True
	autosuggest.strategy              match_prev_cmd history completion
	clink.autostart                   
	clink.colorize_input              True
	clink.default_bindings            bash
	clink.gui_popups                  False
	clink.logo                        full
	clink.paste_crlf                  crlf
	clink.path                        
	clink.promptfilter                True
	cmd.admin_title_prefix            
	cmd.auto_answer                   off
	cmd.ctrld_exits                   True
	cmd.get_errorlevel                True
	color.arg                         bold
	color.arginfo                     yellow
	color.argmatcher                  
	color.cmd                         bold
	color.cmdredir                    bold
	color.cmdsep                      bold
	color.comment_row                 bright white on cyan
	color.description                 bright cyan
	color.doskey                      bold cyan
	color.executable                  
	color.filtered                    bold
	color.flag                        default
	color.hidden                      
	color.horizscroll                 
	color.input                       
	color.interact                    bold
	color.message                     default
	color.modmark                     
	color.popup                       
	color.popup_desc                  
	color.prompt                      
	color.readonly                    
	color.selected_completion         
	color.selection                   
	color.suggestion                  bright black
	color.unexpected                  default
	color.unrecognized                
	debug.log_terminal                False
	doskey.enhanced                   True
	exec.aliases                      True
	exec.commands                     True
	exec.cwd                          True
	exec.dirs                         True
	exec.enable                       True
	exec.files                        False
	exec.path                         True
	exec.space_prefix                 True
	files.hidden                      True
	files.system                      False
	history.dont_add_to_history_cmds  exit history
	history.dupe_mode                 erase_prev
	history.expand_mode               not_quoted
	history.ignore_space              True
	history.max_lines                 10000
	history.save                      True
	history.shared                    False
	history.sticky_search             False
	lua.break_on_error                False
	lua.break_on_traceback            False
	lua.debug                         False
	lua.path                          
	lua.reload_scripts                False
	lua.strict                        True
	lua.traceback_on_error            False
	match.expand_envvars              False
	match.fit_columns                 True
	match.ignore_accent               True
	match.ignore_case                 relaxed
	match.max_fitted_matches          0
	match.max_rows                    0
	match.preview_rows                5
	match.sort_dirs                   with
	match.substring                   False
	match.translate_slashes           system
	match.wild                        True
	prompt.async                      True
	prompt.transient                  off
	readline.hide_stderr              False
	terminal.adjust_cursor_style      True
	terminal.differentiate_keys       False
	terminal.east_asian_ambiguous     auto
	terminal.emulation                auto
	terminal.mouse_input              auto
	terminal.mouse_modifier           
	terminal.raw_esc                  False
	terminal.use_altgr_substitute     False

</details>

**Comment by chrisant996** [comment]
Do those work without Clink on WIn 8.1 with ansicon?

Clink is not involved in the execution of the `type` command, or in the execution of other programs.  I think by "doskey macro", you mean a program that happens to be invoked by a doskey macro, and that the same behavior occurs regardless whether a doskey macro or the program name is used to invoke the program.

This doesn't seem related to Clink.  Have I misunderstood something?

**Comment by chrisant996** [comment]
Oh ... or this is the problem about how ansicon hooks APIs, which isn't fully compatible with Clink.

Is this only happening because you set `terminal.emulation` to `native`?  The `native` mode isn't compatible with Win 8.1, which is why `auto` (the default) selects emulation instead of native.

**Comment by garoto** [comment]
I think I managed to make some progress with the troubleshooting: if `ansicon` is injected after `clink`, what I described above will happen, like when using the below to launch a cmd.exe instance:

```
%COMSPEC% /k "C:\Apps\Diversos\Clink\clink_x64.exe inject && ansicon -p"
```
The log generated with the above indicates Clink detects `ANSI64.dll` is loaded:
[clink.log](https://github.com/chrisant996/clink/files/8502135/clink.log)

If the injection order is reverted:
```
%COMSPEC% /k "ansicon -p && C:\Apps\Diversos\Clink\clink_x64.exe inject"
```

Then `type AnsiColors16.ans` works everytime, but then the below happens:

![screenshot-0730-17-04-2022](https://user-images.githubusercontent.com/11768175/163726368-a34862dc-f9b7-4f7f-af84-97b9b021514b.png)

Hope this helps. I'm finding kinda hard to troubleshoot this, many variables going on.

All the testing was done with Clink and ansicon defaults. I have nothing on my cmd.exe AutoRun registry entry.

**Comment by chrisant996** [comment]
Yes.  Ansicon does hooking in a way that isn't fully compatible with Clink.  And the order in which different programs install their hooks can make a difference in how the hooks actually behave.  Clink can't do anything about that.

This seems to have all started after you ran `clink set terminal.emulation native`, right?  That mode is not recommended on Windows 8.1, and may be what's causing the problems.  Consider going back to `auto` mode (which will use terminal emulation on Win 8.1).

It sounds like you found how to make it work.  I would recommend to use it the way that works, and/or set the `terminal.emulation` mode back to `auto`.

**Comment by garoto** [comment]
> This seems to have all started after you ran clink set terminal.emulation native, right?

No no, this has being going for a while now and I've tinkered with `terminal.emulation` options since the beginning.

>It sounds like you found how to make it work.

Alright, thanks for looking into it.
