### ISSUE TITLE
Change the order of suggestions

### ISSUE THREAD

**Issue by nguyenduy4321** [chrisant996/clink#278]
Seems to suggest feature not work as expected. I hope `clink` to firstly suggest executable files (`cmd`, `bat`, `exe`, ...) in current path, after that suggest others.

**Comment by nguyenduy4321** [comment]
Sorry, I mean `clink` should firstly suggest ~~excutable~~ files in current path.

For example, my `D:\` directory looks like:
```
D:.
+---readme.txt
|
+---main.cpp
|
+---make.bat
|
+---exportAll.config
```
If I type **`m`** and then  `TAB`, `clink` will firstly suggest `Magnify.exe` but not `make.bat` or `main.cpp`.

**Comment by chrisant996** [comment]
Please read the documentation at [How Completion Works] (https://chrisant996.github.io/clink/clink.html#how-completion-works).

You dislike the executable competition feature. You can turn it off, or configure it to your liking.

Clink is behaving as documented, and as intended.
