### ISSUE TITLE
feature request: better hot key for accepting suggestion

### ISSUE THREAD

**Issue by EvanCui** [chrisant996/clink#280]
Clink is great!

Currently Ctrl+Right to accept the suggestion by filling the suggested content to the line.
The key "Right" is far from the main keyboard area, so that the user has to hold the left ctrl using the left hand and move the right hand to the direction keys area and press "right".

Feature request:
1. Change the default key binding of accepting the suggestion to **"Ctrl + Tab" or "Shift + Tab".**
2. Add a new key binding **"Ctrl + Enter"**, which accepts the current suggestion and then execute the command, equivalent to accept and enter.

**Comment by chrisant996** [comment]
Why not set your custom key bindings how you like them?  See [Customizing Key Bindings](https://chrisant996.github.io/clink/clink.html#customizing-key-bindings).

(Also, there are several reasons why Ctrl-Tab and Shift-Tab and Ctrl-Enter aren't good candidates for those as universal default key bindings.)

**Comment by EvanCui** [comment]
Thanks for the quick reply!
After some investigation, it resulted in the following .inputrc file, which does exactly what I expect:

```
# Shift-Enter: Right (accept the suggestion)
"\e[27;2;13~":  win-cursor-forward
# Ctrl-Enter: Right + Enter (accept the suggestion and hit enter to execute)
"\e[27;5;13~":  "\e[C\r"
```

Agree that Ctrl-Tab / Shift-Tab aren't good candidates, so I changed to use Shift-Enter to accept the suggestion, and Ctrl-Enter to accept the suggestion **AND** execute.

The reason why I thought adding the **DEFAULT** hotkeys is a feature request, is that customizing the key bindings requires quite some learning and experimenting with how the configuration works, especially the discovering the representation of the key sequences, and the representation for the command, even though there is a document about them all.

My opinion might not apply so well given that I didn't dig into the clink's design, neither did I have rich experience in the underlying technologies of terminals, consoles, command lines, etc. I just share my 2 cents here:

**DEFAULT behavior is something 90% of the software users experience.** Users seldom do deep customization for a software. In case of the default behavior doesn't work as expected, most users would just abort, while others would search on the internet, read, check and experiment the solutions online, or read and learn the document of the software to cook it themselves. Among those, a small portion succeed while others fail to find a workable solution. So making the DEFAULT behavior perfect is worth doing, and is even more valuable than inventing cool features for geeks.

**Why is it a good candidate for making it a default key binding?** User's attention is usually attracted by what the UI display. When the first time I installed clink and see the suggestion in the line, I was attracted by the powerfulness of this feature, and my instinct is just complete it. I thought it was a completion suggestion which I can use tab key to complete or iterate though a candidate list, like the normal completion does. But after some test, I found that the suggestion feature is different than the tab completion, and I have to use the "right" key to complete the suggestion, "tab" works for another set of completion candidates, and I thought it's correct to separate them, but **"right"** key is not the **"right"** key.
It's a high frequent action to accept the suggestion given that the suggestion usually contains the whole command line I just typed in the history. While typing, the user would suddenly see a full command line in the suggestion, and the voice in the head is **"yeah! that's what I want to execute"**. The suggestion feature is the feature attracting the user's sight, but now it gives the user an impression that **"I am JUST HERE, you don't know how to complete me"**.
The only thing left is how to give it a new key. Since I knew it is most likely feasible by some customization, so I first posted the feature request here and spent some time digging into the document. When I investigate for the customization of key bindings, I also found that Ctrl-Tab, Shift-Tab is not good, but I found Shift-Enter and Ctrl-Enter is perfect. Reason:
Enter is for the meaning of "commit"/"accept", and by default enter commits what was typed so far, we shouldn't change it apparently.
Shift usually means "a convenient alternative" to what is shifted, like Shift+a means A. So, Shift+Enter to accept the suggestion is straightforward.
Ctrl usually means "an action/command", so it is bound to "execution after accept" behavior in my customization.

Maybe there are some obvious reasons why the default key bounding cannot be like that, just I don't know.

At last, clink is one of the best software I've used, even though this issue is closed with "won't fix", I still think it's better than best.

**Comment by chrisant996** [comment]
One criteria for choosing key bindings is the distance fingers must be moved.

Some other criteria include:
- How frequently a command is used.
- Similarity or "common theme" among key bindings for related commands.
- Familiarity with other applications with the same key bindings.
- Interference with key bindings from other software, such as terminal hosts (Cmder, ConEmu, Windows Terminal, etc).
- Avoiding key bindings that other applications use for other purposes.
- Discoverability.
- Memorability or mnemonic device.
- How far apart the keys in the key binding, or in the multi-key sequence.
- And sometimes other criteria.

The suggestions feature comes from the [fish](https://fishshell.com) shell.  The key bindings match the fish shell.  The common theme between the keys is apparent.  The effects of various modifier keys seem reasonable, and are easy to remember.

There are several other reasons.  There are also several reasons why Tab variations are not good choices -- one of the most compelling is that some terminal hosts have key bindings for Ctrl-Tab.  And Shift-Tab already has a meaning when Windows default key bindings are set in Clink.

I appreciate the interest and the motivation.  At the same time, there is a lot more to consider than what was called out, and I believe the current key bindings are appropriate.
