### ISSUE TITLE
Feature request: Self-Update via a 'clink update' command

### ISSUE THREAD

**Issue by iamMG** [chrisant996/clink#282]
Is it possible to add a command to initiate check and update clink?

**Comment by chrisant996** [comment]
I have a prototype for an auto-updater and `clink update` command.

They have some restrictions:
1. They require Windows 10 or higher (because they use `curl` and `powershell`).
2. They can't work when Clink is installed to a protected file such as `Program Files` that requires Administrator access.

The setup exe will be updated to mention that for the auto-updater to work Clink can't be installed to `Program Files`.

**Comment by pukkandan** [comment]
> 1. They require Windows 10 or higher (because they use `curl` and `powershell`

Out of curiosity, why the `curl` requirement? powershell can download files

**Comment by chrisant996** [comment]
> > 1. They require Windows 10 or higher (because they use `curl` and `powershell`
> 
> Out of curiosity, why the `curl` requirement? powershell can download files

True. I can take a look at using Powershell for that as well as extracting files from the zip file.

**Comment by chrisant996** [comment]
PowerShell's `Invoke-WebRequest` and similar cmdlets format the output very differently than `curl.exe` does.  It's not as conducive to regex parsing, but it works out ok for now.

**Comment by chrisant996** [comment]
Commit 311ceb903dc9516856e9141e5b3ac1992a13aeb5 adds automatic updates.  Automatic updates can be turned off/on, and the frequency can be set (default is 5 days).  A new `clink update` command is able to check for an update regardless whether automatic updates are enabled.

**Comment by chrisant996** [comment]
Some changes to the updater:
- Checking for updates is automatic.
- Run `clink update` to apply an available update.
- The updater will automatically request elevation when necessary (e.g. when installed under the "Program Files" directory).

v1.3.18 will include the updater, and will likely be released in the new few days.

**Comment by chrisant996** [comment]
v1.3.18 is released.

**Comment by iamMG** [comment]
Thanks Chris!

**Comment by UweKeim** [comment]
On some systems, calling `clink update` results in an error message:

> Unable to find latest release zip file.

The systems seems to have nothing special. E.g. internet access is possible without a proxy.

Any idea what causes this and how to resolve?

**Comment by chrisant996** [comment]
> On some systems, calling `clink update` results in an error message:
> 
> > Unable to find latest release zip file.

See #300.
