### ISSUE TITLE
repeating epilouge

### ISSUE THREAD

**Issue by facile-aliquidron** [chrisant996/clink#283]
'native' is not recognized as an internal or external command,
operable program or batch file.
          continuious repeating...
at startup and during command implication

-----------------------------------------------------------------

*clink autorun install -a
          *Clink successfully installed to run when cmd.exe starts (for all users).
oh-my-posh works good..., alittle buggy, if you know what i mean, for dev themes

**Comment by garoto** [comment]
And here am I, thinking I generated lazy issues all this time...

**Comment by chrisant996** [comment]
Please show the output from `clink autorun show`.
Please show the output from `clink info`.

The word "native" is not something that Clink produces, except in the output from the `clink autorun show` command.

It sounds to me like probably you have a command in the AutoRun regkey which is either explicitly or implicitly invoking another copy of cmd, which runs the AutoRun regkey again, and invokes another copy of cmd, and so on.

Or maybe you have a `clink_start.cmd` file that is invoking another copy of cmd, etc.

See #243 also, in case it has some useful ideas.

**Comment by chrisant996** [comment]
> oh-my-posh works good..., alittle buggy, if you know what i mean, for dev themes

This is the clink repo, here.  Feedback about oh-my-posh is more likely to be seen by its author in the oh-my-posh repo.  If you open an issue there, consider describing the specific issue so that the author can know what you mean.

Also, perhaps you might prefer [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt).

**Comment by facile-aliquidron** [comment]
oh, sorry dude clink works good. I forgot to update clink on my other computer. I initially installed first, then got carrired away with confiurations to update clink on my second laptop. The update on my first laptop didn't have any bugs. smooth as butter

**Comment by chrisant996** [comment]
Ok. Good luck.
