### ISSUE TITLE
Git command causes the command prompt to not re-appear

### ISSUE THREAD

**Issue by slhussey** [chrisant996/clink#285]
After issuing a git command that produces more output than will fit in the window, causing the colon (:) prompt to display more; after hitting the space bar and the (END) sentinel displays; then q to clear that, the command prompt does not appear to allow entering another command.  I have to close the tab and doing so loses the command history for that session. This is on Windows 10 Enterprise running clink v1.3.16.023688.

**Comment by chrisant996** [comment]
I can't reproduce that.

What troubleshooting have you done?
Have you tried without clink?
Have you checked taskmgr or tasklist (or other process explorer tool) to determine whether git exited?
Have you tried pressing Ctrl-C and Ctrl-Break?
Etc.

What was the last version of clink where git's pager worked for you?

How do you have clink configured?
- `clink info`
- `clink set`
- Find the `clink.log` file and upload it here (`clink info` will say where it's located).

What can you think of that might be different about your computer/configuration?

Have you tried using the latest version of clink?  (I can't reproduce the problem with v1.3.16, nor with v1.3.18 which is the current version at this time.)

**Comment by slhussey** [comment]
You identified the issue – git is not exiting.  Found it still running in Task Manager and terminated it.  The command prompt appeared.  I am using git 2.36.0.windows.1.  I will pursue with git contacts.
