### ISSUE TITLE
where to save doskey aliases?  (i tried several options)

### ISSUE THREAD

**Issue by berrytsakala** [chrisant996/clink#286]
The documentation doesn't mention it precisely or explicitly.

I tried to put an alias  (e.g. `doskey.exe aaa=bbb` ) in the following places:

.inputrc   as     doskey.exe aaa=bbb

registry, 
```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor]
"AutoRun"="\"C:\\Program Files (x86)\\clink\\clink.bat\" inject --autorun --profile ~\\clink && doskey.exe /macrofile=%LOCALAPPDATA%\\clink\\aliases"
```
and then in aliases:

`doskey aaa=ccc`
or
`doskey aaa ddd`   # like in fish shell

but either this line is ignored or ends up with an error:
```
Clink v1.3.17.0a95d0
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink
**Invalid macro definition.**
```

I installed clink via the setup.

I saw in the docs also a reference to _portable_ installation, which looks like batch voodoo, and I didn't try that (yet).

1. what is the definitive guide for aliases?
2. can it be added to the docs?

**Comment by pukkandan** [comment]
> what is the definitive guide for aliases?
> can it be added to the docs?

`doskey` is a part of Windows, not clink. See https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/doskey for documentation.

> doskey aaa=ccc
> or
> doskey aaa ddd # like in fish shell
> but either this line is ignored or ends up with an error:

The aliases file should contain:

    aaa=ccc $*

Note that there is no `doskey ` prefix. The `$*` makes sure any arguments are propagated
