### ISSUE TITLE
wrong default key binding for copy/paste

### ISSUE THREAD

**Issue by ristiisa** [chrisant996/clink#292]
In every other program in windows:
`ctrl+ins` is copy
`shift+ins` is paste
`shift+del` is cut

But in clink `shift+ins` is bound to copy and `ctrl+ins` does nothing. `shift+del` is bound to cut and that is correct.

Is this intentional?

**Comment by chrisant996** [comment]
Thanks for reporting that.  I'm well aware of the CUA key definitions, so I'm not sure how I managed to hook up the <kbd>Ins</kbd> variations incorrectly!  Fixed by c6002449996f6678c6e2158e06c09ecf908ece14, and will appear in the next update.

**Comment by ristiisa** [comment]
> Thanks for reporting that. I'm well aware of the CUA key definitions, so I'm not sure how I managed to hook up the Ins variations incorrectly! Fixed by [c600244](https://github.com/chrisant996/clink/commit/c6002449996f6678c6e2158e06c09ecf908ece14), and will appear in the next update.

WOW! Thanks for the quick response. Have a nice day!
