### ISSUE TITLE
Question on directory history

### ISSUE THREAD

**Issue by ericsunplus** [chrisant996/clink#297]
Hi there, just switch from CLink 0.49 to here. Loves the new feature introduced which opens a world of more efficiency to me.

The pop up history window is a great feature for me. However I find that the entries won't do any processing on duplicate entries. like `history.dupe_mode` do to command history. A experiment using `cd -` continuously will make the pop up window filled with duplicate items

![image](https://user-images.githubusercontent.com/7379534/172354579-2403be66-0704-438c-8440-e648b0b1c837.png)

Is it possible that a similar option can be added for the directory history?

**Comment by chrisant996** [comment]
Seems reasonable. I've added a setting. See recent commits for details. Will be available in the next release, probably in a few days.

**Comment by chrisant996** [comment]
Added in commit 9d11834a1528232d680b49be35568fac96f30eb9. v1.3.19 is available now.

**Comment by ericsunplus** [comment]
Works perfectly，thank you for the quick enhancement!
