### ISSUE TITLE
Windows Defender Virus Warning

### ISSUE THREAD

**Issue by chiwou** [chrisant996/clink#298]
When trying to install the latest version, the Windows Defender pops up and blocks the installation.

Trojan:Win32/Wacatac.B!ml

![image](https://user-images.githubusercontent.com/686192/172914795-57028dca-a51b-42f0-9226-5fda1b1403a8.png)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.B!ml&threatid=2147735505

**Comment by garoto** [comment]
Snake oil.

**Comment by chrisant996** [comment]
Report it to Windows Defender.

It is a false positive.

Clink cannot do anything about this.

**Comment by chiwou** [comment]
the new version "fixed" the issue
