### ISSUE TITLE
Error 'Unable to find latest release zip file' while trying to update.

### ISSUE THREAD

**Issue by iamMG** [chrisant996/clink#300]
Title self-explanatory. :)
What to do?
![image](https://user-images.githubusercontent.com/22472867/173202736-0457cd67-ff3f-4eeb-a5ec-3b927d48c893.png)

**Comment by iamMG** [comment]
Same error occurs with Admin CMD.
![image](https://user-images.githubusercontent.com/22472867/173202780-8422442d-2918-4267-8878-2b2cd49e1857.png)

**Comment by chrisant996** [comment]
Most likely one of these is happening:
- Problem launching powershell.
- Problem reaching the github web site to check for an update.

Please try running the following:

```cmd
%systemroot%\system32\windowspowershell\v1.0\powershell.exe -Command "$ProgressPreference='SilentlyContinue' ; Invoke-WebRequest https://api.github.com/repos/chrisant996/clink/releases/latest | Select-Object -ExpandProperty Content" > result.txt
```

And then upload the `result.txt` file here.  That's the same command that Clink runs to check for the latest release.  The `result.txt` file will contain the response from github.

**Comment by MagicAndre1981** [comment]
I have this too in Windows 10 x64 German. The command tells me something about missing Internet Explorer-Module:

```
Invoke-WebRequest : Der Antwortinhalt kann nicht analysiert werden, da das Internet Explorer-Modul nicht verfgbar ist, oder die 
Konfiguration beim ersten Start von Internet Explorer ist nicht abgeschlossen. Geben Sie den UseBasicParsing-Parameter an, und 
wiederholen Sie den Vorgang. 
In Zeile:1 Zeichen:42
+ ... Continue' ; Invoke-WebRequest https://api.github.com/repos/chrisant99 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 

```

When I add this `-UseBasicParsing` parameter I see all data:

`{"url":"https://api.github.com/repos/chrisant996/clink/releases/69226797","assets_url":"https://api.github.com/repos/chrisant996/clink/releases/69226797/assets","upload_url":"https://uploads.github.com/repos/chrisant996/clink/releases/69226797/assets{?name,label}","html_url":"https://github.com/chrisant996/clink/releases/tag/v1.3.21","id":69226797,"author":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"node_id":"RE_kwDOEZT_vc4EIFEt","tag_name":"v1.3.21","target_commitish":"master","name":"v1.3.21","draft":false,"prerelease":false,"created_at":"2022-06-11T19:48:09Z","published_at":"2022-06-11T20:12:54Z","assets":[{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68209418","id":68209418,"node_id":"RA_kwDOEZT_vc4EEMsK","name":"clink.1.3.21.5eb05f.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":1721590,"download_count":201,"created_at":"2022-06-11T20:12:34Z","updated_at":"2022-06-11T20:12:35Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f.zip"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68209420","id":68209420,"node_id":"RA_kwDOEZT_vc4EEMsM","name":"clink.1.3.21.5eb05f_setup.exe","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-msdownload","state":"uploaded","size":1436526,"download_count":80,"created_at":"2022-06-11T20:12:35Z","updated_at":"2022-06-11T20:12:35Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f_setup.exe"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68209421","id":68209421,"node_id":"RA_kwDOEZT_vc4EEMsN","name":"clink.1.3.21.5eb05f_symbols.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":7724380,"download_count":3,"created_at":"2022-06-11T20:12:35Z","updated_at":"2022-06-11T20:12:36Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f_symbols.zip"}],"tarball_url":"https://api.github.com/repos/chrisant996/clink/tarball/v1.3.21","zipball_url":"https://api.github.com/repos/chrisant996/clink/zipball/v1.3.21","body":"Recent highlights:  The v1.3.13 release added features that make the [i.lua](https://github.com/chrisant996/clink/discussions/263) script possible.  Argmatchers can now be written to do match completion in directories other than the current directory.  Argmatchers can also be written to take a whole command line as an argument:  for example the built-in `cmd` argmatcher (`cmd some_command`).\r\n\r\n#### v1.3.21\r\n- Improved the auto-updater when there are multiple copies of Clink on a computer; it no longer needs to download the .zip update file multiple times.\r\n- Fixed mouse input when the console is scrolled.\r\n- Fixed [#299](https://github.com/chrisant996/clink/issues/299); update shown even though up to date.\r\n"}`

**Comment by MagicAndre1981** [comment]
under Windows 8.1 x64 German, the provided command fails with SSL/TLS channel issue:

```
Invoke-WebRequest : Die Anfrage wurde abgebrochen: Es konnte kein geschtzter SSL/TLS-Kanal erstellt werden..
In Zeile:1 Zeichen:42
+ $ProgressPreference='SilentlyContinue' ; Invoke-WebRequest https://api.github.co ...
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], W 
   ebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by jpelner** [comment]
I just installed (1.3.21), forked and cloned. 

C:\git>clink update
Checking latest version...
No update available; local version v1.3.21 is not older than latest release v1.3.21.

No issue seen.

**Comment by chrisant996** [comment]
> under Windows 8.1 x64 German, the provided command fails with SSL/TLS channel issue:
> 
> ```
> Invoke-WebRequest : Die Anfrage wurde abgebrochen: Es konnte kein gesch�tzter SSL/TLS-Kanal erstellt werden..
> In Zeile:1 Zeichen:42
> + $ProgressPreference='SilentlyContinue' ; Invoke-WebRequest https://api.github.co ...
> +                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], W 
>    ebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> ```

@MagicAndre1981 do you mean even with `-UseBasicParsing` it fails on Win 8.1?

**Comment by UweKeim** [comment]
Having a Windows Server 2016 Datacenter running at AWS EC2 (English UI with German keyboard layout), I also get this error message:

```
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:42
+ ... Continue' ; Invoke-WebRequest https://api.github.com/repos/chrisant99 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 ```

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 do you mean even with `-UseBasicParsing` it fails on Win 8.1?

yes, both commands fail under Windows 8.1

**Comment by chrisant996** [comment]
Does the following command work?  It attempts to select TLS 1.2.

Github requires TLS 1.2, but PowerShell defaults to TLS 1.0.

```cmd
%systemroot%\system32\windowspowershell\v1.0\powershell.exe -Command "$ProgressPreference='SilentlyContinue' ; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 ; Invoke-WebRequest -UseBasicParsing https://api.github.com/repos/chrisant996/clink/releases/latest | Select-Object -ExpandProperty Content"
```

**Comment by UweKeim** [comment]
Calling this results in:

```json
{"url":"https://api.github.com/repos/chrisant996/clink/releases/69226797","assets_url":"https://api.github.com/repos/chrisant996/clink/releases/69226797/assets","upload_url":"https://uploads.github.com/repos/chrisant996/clink/releases/69226797/assets{?name,label}","html_url":"https://github.com/chrisant996/clink/releases/tag/v1.3.21","id":69226797,"author":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"node_id":"RE_kwDOEZT_vc4EIFEt","tag_name":"v1.3.21","target_commitish":"master","name":"v1.3.21","draft":false,"prerelease":false,"created_at":"2022-06-11T19:48:09Z","published_at":"2022-06-11T20:12:54Z","assets":[{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68209418","id":68209418,"node_id":"RA_kwDOEZT_vc4EEMsK","name":"clink.1.3.21.5eb05f.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":1721590,"download_count":314,"created_at":"2022-06-11T20:12:34Z","updated_at":"2022-06-11T20:12:35Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f.zip"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68209420","id":68209420,"node_id":"RA_kwDOEZT_vc4EEMsM","name":"clink.1.3.21.5eb05f_setup.exe","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-msdownload","state":"uploaded","size":1436526,"download_count":149,"created_at":"2022-06-11T20:12:35Z","updated_at":"2022-06-11T20:12:35Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f_setup.exe"},{"url":"https://api.github.com/repos/chrisant996/clink/releases/assets/68209421","id":68209421,"node_id":"RA_kwDOEZT_vc4EEMsN","name":"clink.1.3.21.5eb05f_symbols.zip","label":null,"uploader":{"login":"chrisant996","id":17440311,"node_id":"MDQ6VXNlcjE3NDQwMzEx","avatar_url":"https://avatars.githubusercontent.com/u/17440311?v=4","gravatar_id":"","url":"https://api.github.com/users/chrisant996","html_url":"https://github.com/chrisant996","followers_url":"https://api.github.com/users/chrisant996/followers","following_url":"https://api.github.com/users/chrisant996/following{/other_user}","gists_url":"https://api.github.com/users/chrisant996/gists{/gist_id}","starred_url":"https://api.github.com/users/chrisant996/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrisant996/subscriptions","organizations_url":"https://api.github.com/users/chrisant996/orgs","repos_url":"https://api.github.com/users/chrisant996/repos","events_url":"https://api.github.com/users/chrisant996/events{/privacy}","received_events_url":"https://api.github.com/users/chrisant996/received_events","type":"User","site_admin":false},"content_type":"application/x-zip-compressed","state":"uploaded","size":7724380,"download_count":6,"created_at":"2022-06-11T20:12:35Z","updated_at":"2022-06-11T20:12:36Z","browser_download_url":"https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f_symbols.zip"}],"tarball_url":"https://api.github.com/repos/chrisant996/clink/tarball/v1.3.21","zipball_url":"https://api.github.com/repos/chrisant996/clink/zipball/v1.3.21","body":"Recent highlights:  The v1.3.13 release added features that make the [i.lua](https://github.com/chrisant996/clink/discussions/263) script possible.  Argmatchers can now be written to do match completion in directories other than the current directory.  Argmatchers can also be written to take a whole command line as an argument:  for example the built-in `cmd` argmatcher (`cmd some_command`).\r\n\r\n#### v1.3.21\r\n- Improved the auto-updater when there are multiple copies of Clink on a computer; it no longer needs to download the .zip update file multiple times.\r\n- Fixed mouse input when the console is scrolled.\r\n- Fixed [#299](https://github.com/chrisant996/clink/issues/299); update shown even though up to date.\r\n","reactions":{"url":"https://api.github.com/repos/chrisant996/clink/releases/69226797/reactions","total_count":1,"+1":1,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0}}
```

So I think this seems to be a TLS issue.

**Comment by chrisant996** [comment]
Perfect, thanks for confirming!

> To me this looks like the correct response. So I do think this actually seems to be a TLS issue.

Yes, exactly.  Since forcing Tls12 indeed works on Win8.1, the fix is easy.  I'll publish an update sometime this week.  Of course, this next update must be installed manually.  But once it's installed, then future updates should work as expected.

**Comment by MagicAndre1981** [comment]
> Does the following command work? It attempts to select TLS 1.2.

yes, this command works fine in Windows 8.1

**Comment by chrisant996** [comment]
Fixed in v1.3.22.

**Comment by chrisant996** [comment]
Tell me more, please.  I applied both of the fixes that were discussed so far (TLS 1.2 and -UseBasicParsing).

Feedback so far had indicated that with those two additions, the Powershell command succeeds.

Can you please try the full Powershell command, and indicate the results?

**Comment by chrisant996** [comment]
Aw, man.  😢  It is indeed a copy/paste typo.

**Comment by MagicAndre1981** [comment]
works now fine:

```
Clink v1.3.23.5d5aed
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\WINDOWS\system32>clink update
Checking latest version...
No update available; local version v1.3.23 is not older than latest release v1.3.23.
```

**Comment by chrisant996** [comment]
Thanks for confirming!  You tested it before I could even add an update here to say v1.3.23 is available.  🙂

**Comment by UweKeim** [comment]
Works here for me, too.

We Germans are always _fast_ 😄

**Comment by MagicAndre1981** [comment]
tested on 8.1 and Windows 10, both works and I see message that version is up to date. I'll check if updating works when .24 is released. 

I subscribe to releases so I got an email and checked it very fast 🤓

**Comment by chrisant996** [comment]
Awesome, thanks, everyone! ♥️

**Comment by MagicAndre1981** [comment]
downloading works, but [unzip fails for what ever reason](https://github.com/chrisant996/clink/issues/303)
