### ISSUE TITLE
Feature Request : add global directory history

### ISSUE THREAD

**Issue by ericsunplus** [chrisant996/clink#302]
Hi there,

There are "command history“ and "directory history" in clink. For the "command history", there is a file recording command executed anywhere, so the history is global visible to each other. For the "directory history", it seems it is only valid in a living session. Once the command window closed, the history is lost.

Can we also add a file to recording directory history too? So we can navigate to previous directories even we open a new command window.

**Comment by chrisant996** [comment]
There are many options involved in maintaining history across multiple sessions -- what to do with duplicates, and whether to merge directory lists immediately or when sessions end, limiting the number of entries, pruning excess old entries, and so on.

But, it's possible to use a Lua script to add recent directories to a file, and it's possible to use a Lua script to pop up a list of recent directories.

**Comment by chrisant996** [comment]
Also, have you considered using [z.lua](https://github.com/skywind3000/z.lua) for global directory history?

It has many fancy features, and integrates with Clink.  It even integrates with [fzf](https://github.com/junegunn/fzf) for interactive selection from directory history.  E.g. set up a `zf` alias for `z -I` and then `zf .` uses fzf to interactively select from the directory history list.  Or `zf foo` jumps to a directory that fuzzy-matches "foo" or uses fzf to interactively select from directories matching "foo".  Or `z` lists the directory history, or `z foo` goes to the highest ranked directory that fuzzy-matches "foo".  Etc.

(There is also a Lua script [here](https://github.com/chrisant996/clink-fzf) that provides Clink integration for fzf, if you like fzf and want to use it for more things.)

And a simple Lua script can convert the `z` directory history list into a Clink popup list, and replace the default Ctrl-PgUp key binding:

#### z_dir_popup.lua
```lua
if not clink.popuplist or not rl.setbinding then
    print("z_dir_popup.lua requires a newer version of Clink; please upgrade.")
    return
end

function z_dir_popup(rl_buffer)
    local r = io.popen('z.cmd -l')
    if not r then
        rl_buffer:ding()
        return
    end

    local dirs = {}
    for line in r:lines() do
        table.insert(dirs, line)
    end
    r:close()

    local selected = clink.popuplist('Directories', dirs)
    if not selected then
        return
    end

    local dir = selected:match("^ *[0-9.]+ +(.+)$")
    if not dir or dir == "" then
        rl_buffer:ding()
        return
    end

    rl_buffer:remove(1, -1)
    rl_buffer:setcursor(1)
    rl_buffer:insert("cd /d ")
    rl_buffer:insert(dir)
    rl.invokecommand('accept-line')
end
```

**Comment by ericsunplus** [comment]
Thanks @chrisant996 for the great advice , this really opens a new world to me, will explore it and let you know.

**Comment by chrisant996** [comment]
@ericsunplus I think this is what you were asking for:

The [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo now includes a `cwdhistory.lua` script, which provides a global directory history saved across sessions, and a popup list to choose from.  The default key binding is <kbd>Alt</kbd>-<kbd>Ctrl</kbd>-<kbd>PgUp</kbd>.  In the popup list, <kbd>Enter</kbd> uses `cd` to change to the selected directory, or <kbd>Ctrl</kbd>-<kbd>Enter</kbd> or <kbd>Shift</kbd>-<kbd>Enter</kbd> uses `pushd` to change to the selected directory.

**Comment by ericsunplus** [comment]
Thanks @chrisant996 for the creation, I was busy on company project recently so just saw your recommendation :)

**Comment by ericsunplus** [comment]
@chrisant996 , I tried the `cwdhistory.lua`. It do save cross session directory history to a file. However, when I use `A-C-PgUp`, the log file seems don't take effect. Is there any extra dependency for this script? I am not installing the whole directory of `
clink-gizmos` because is seems conflict with `clink-fzf`, I only extract the `cwdhistory.lua` to a separate directory and install it to clink

![image](https://user-images.githubusercontent.com/7379534/193535348-63cb4659-fc0a-4a42-a750-44fa37ebd9cc.png)

**Comment by chrisant996** [comment]
> @chrisant996 , I tried the `cwdhistory.lua`. It do save cross session directory history to a file. However, when I use `A-C-PgUp`, the log file seems don't take effect.

That is not the cwdhistory popup.  `A-C-PgUp` is bound to something else.  cwdhistory only binds `A-C-PgUp` if it isn't already bound to something else.  Use `A-S-/` to invoke `what-is`, and then press `A-C-PgUp` to find out what it is currently bound to.

> I am not installing the whole directory of ` clink-gizmos` because is seems conflict with `clink-fzf`, 

clink-gizmos contains clink-fzf.  If you use clink-gizmos then you don't need a separate clink-fzf.

**Comment by ericsunplus** [comment]
```
A-C-PgUp : clink-popup-directories -- Show recent directories in a popup list and 'cd /d' to a selected directory
```
But I definitely not configuring this in my `.inputrc`. What I should I do next to unbound it?

**Comment by chrisant996** [comment]
True, `A-C-PgUp` is bound by default, so the script never applies the key binding.  I'll figure out a good way to clear that up.

In the meantime, set a key binding.  See [Key Bindings](https://chrisant996.github.io/clink/clink.html#gettingstarted_keybindings) in the [Getting Started](https://chrisant996.github.io/clink/clink.html#getting-started) section of the docs.

```inputrc
"\e[5;7~": "luafunc:cwdhistory_popup"
```

**Comment by ericsunplus** [comment]
Thank you @chrisant996 , maybe document this luafunction for user to customize themselves is good enough (I am overriding `C-f` with this luafunction and it works like a charm). 

One more thing, do you think of adding a configuration parameter to limit the length of the cwd history entries so it will not grow forever.

**Comment by chrisant996** [comment]
> Thank you @chrisant996 , maybe document this luafunction for user to customize themselves is good enough (I am overriding `C-f` with this luafunction and it works like a charm). 

Documentation for each Lua script is at the top of each Lua script.  The documentation at the top of cwdhistory.lua is sparse and I'll add to it.

> One more thing, do you think of adding a configuration parameter to limit the length of the cwd history entries so it will not grow forever.

Refer to the `cwdhistory.limit` setting.

**Comment by chrisant996** [comment]
The documentation at the top of https://github.com/chrisant996/clink-gizmos/blob/main/cwdhistory.lua has more info now.

The documentation in https://github.com/chrisant996/clink-gizmos/blob/main/README.md is more clear that every script has documentation inside it.
