### ISSUE TITLE
typing starting with system "prohibited" names (like con, aux, com1...) cause perma freeze to console

### ISSUE THREAD

**Issue by TSlex** [chrisant996/clink#304]
[v1.3.24](https://github.com/chrisant996/clink/releases/tag/v1.3.24)

Steps to recreate:

1. Open cmd (or Windows Terminal app)
2. Type con (or aux or any from [here](https://answers.microsoft.com/en-us/windows/forum/all/why-cant-i-create-a-folder-with-con-name/23c86662-4988-4c7d-9c2d-3e33d4413de3))
3. Console is frozen

Tried different settings, no luck
Removing clink solves the problem

Probably it tries to scan somehow command being typed and crashes uppon prohibited (secured/system) names

**Comment by chrisant996** [comment]
Those aren't prohibited names -- they are device names. Clink isn't crashing, it's accidentally trying to read from the device, which has no data to read, so it hangs.

I tested with `lpt1` and `nul`, but apparently some other device names have issues.

I'll address that probably today or tomorrow.

**Comment by chrisant996** [comment]
Fixed by 8c50f87a484b4519960aad7e30c5ca1e44bb7f45; fix will appear in v1.3.25.
