### ISSUE TITLE
Is there a way to configure the history and logs file location separately?

### ISSUE THREAD

**Issue by EvanCui** [chrisant996/clink#310]
I configured the profile path to a folder in my onedrive, but by this configuration, the history and logs files are also saved there.
Thus each time I type a command, my OneDrive will try to sync the changed files, and usually pops up a window at the right bottom corner.

Is there a way to configure the locations separately?

**Comment by chrisant996** [comment]
See [FIle Locations](https://chrisant996.github.io/clink/clink.html#file-locations) and [Location of Lua Scripts](https://chrisant996.github.io/clink/clink.html#location-of-lua-scripts).

#233 is about separate locations for settings and history.  The motivation was to sync only some things via OneDrive.

**Comment by chrisant996** [comment]
Closing this as answered.
