### ISSUE TITLE
start up speed

### ISSUE THREAD

**Issue by MassimoCastell** [chrisant996/clink#312]
I updated a while ago from clink.1.3.25.080a5d to clink.1.3.28.4e895f and today to clink.1.3.31.f14c84. With both versions the start up decreased in Windows Terminal and CMD.

Something changed not to the best.

version, first start, second start
1.3.25.080a5d, 1 sec, no wait time
1.3.28.4e895f, 6 sec, 4 sec
1.3.31.f14c84, 5, sec, 4 sec

Please tell me how to help debugging.

**Comment by MagicAndre1981** [comment]
disable update check, maybe internet is slow:

`clink set clink.autoupdate false`

**Comment by chrisant996** [comment]
@MassimoCastell for me, v1.3.32 now takes about 2 milliseconds for the updater check.

Try v1.3.32 (published just now) and see how much of an improvement it makes for the startup time.  If it's still slow, let me know and I'll look for more possible issues, but this one likely accounts for the whole slowdown.

**Comment by MassimoCastell** [comment]
I didn't think, that my Notebook with SSD is slow. But it's managed by our business IT. So probably there are many programs installed, and the check is somehow "monitored". I saw that clink.1.3.33 was release and just test this version. Now it's running perfect.
Thank you very much for the support and this awesome tool.

**Comment by chrisant996** [comment]
> I didn't think, that my Notebook with SSD is slow. But it's managed by our business IT. So probably there are many programs installed, and the check is somehow "monitored".

Or maybe you have Clink configured for AutoRun, and maybe that was slowing it down (hundreds of times injecting Clink in the reg.exe invocations that were happening, and then cancelling because it's not an interactive session).

I don't personally use AutoRun, because it is slow and has a small potential for introducing strange problems.  But I haven't removed that feature, either, because I know many people love it.

> I saw that clink.1.3.33 was release and just test this version. Now it's running perfect.

Excellent! Thank you for sharing the confirmation.

**Comment by chacoff** [comment]
> disable update check, maybe internet is slow:
> 
> `clink set clink.autoupdate false`

if any one get to read this, as of August 2024 :

`clink set clink.autoupdate off`

"off" instead of "false"

**Comment by chrisant996** [comment]
> > disable update check, maybe internet is slow:
> > 
> > `clink set clink.autoupdate false`
> 
> if any one get to read this, as of August 2024 :
> 
> `clink set clink.autoupdate off`
> 
> "off" instead of "false"

@chacoff are you experiencing slowness that goes away when turning off the auto update check?

If so, I wasn't aware there was still any issue there.  If so, can you share additional info?

**Comment by chacoff** [comment]
> > > disable update check, maybe internet is slow:
> > > `clink set clink.autoupdate false`
> > 
> > 
> > if any one get to read this, as of August 2024 :
> > `clink set clink.autoupdate off`
> > "off" instead of "false"
> 
> @chacoff are you experiencing slowness that goes away when turning off the auto update check?
> 
> If so, I wasn't aware there was still any issue there. If so, can you share additional info?

Hello Chrisant996!, yes, but in my PC/Internet at work, because of the very restrictive firewall we have, as a matter of fact, I cannot even "git clone" at work. In my pc at home is very okay. Although, if i see anything related to slowness i'll definitely be reporting, thank you in advance!
