### ISSUE TITLE
Update to 1.3.32 successful, but after starting a new cmd.exe, I still see that .31 is installed and get the update offered

### ISSUE THREAD

**Issue by MagicAndre1981** [chrisant996/clink#313]
Update to 1.3.32 successful, but after starting a new cmd.exe, I still see that .31 is installed and get the update offered

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

Clink v1.3.31.f14c84
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

Clink v1.3.32 is available.
- To apply the update, run 'clink update'.
- To stop checking for updates, run 'clink set clink.autoupdate false'.
- To view the release notes, visit the Releases page:
  https://github.com/chrisant996/clink/releases

C:\WINDOWS\system32>clink update
Checking latest version...
Expanding zip file...
Updating registry keys...
Updated Clink to v1.3.32.

C:\WINDOWS\system32>
```

Showing the used modules of cmd.exe, I see that cmd.exe still uses the old .31 from temp, not from install location:

![image](https://user-images.githubusercontent.com/8274816/176755761-c8ca8d3c-8d2c-47e4-8012-93b383873c2b.png)

**Comment by chrisant996** [comment]
Thanks.  Github kept having trouble creating the new release, and in the one that finally succeeded, I uploaded 1.3.31 into the 1.3.32 release by mistake.

I deleted the v1.3.32 release and posted a v1.3.33 release instead (I had to bump the version number again so the updater didn't keep reinstalling the cached zip file it had already downloaded for v1.3.32).

**Comment by MagicAndre1981** [comment]
> I deleted the v1.3.32 release and posted a v1.3.33 release instead (I had to bump the version number again so the updater didn't keep reinstalling the cached zip file it had already downloaded for v1.3.32).

ok, .33 works fine 👍

**Comment by chrisant996** [comment]
Great! Ok, things _should_ be smooth moving forward from here... 🤞
