### ISSUE TITLE
Can we set the color of the completation? 

### ISSUE THREAD

**Issue by benyaminl** [chrisant996/clink#314]
Hello, I change my background color to white, and the dir command auto complete show white, make me confused. 

Could we change the color? 

![image](https://user-images.githubusercontent.com/2817332/177009177-28905c04-271e-4290-ad0b-a63d15909e49.png)

Thank you

**Comment by chrisant996** [comment]
Yes. There is a whole section on how, in the documentation. Have you read it? Do you have questions about what it says?

**Comment by benyaminl** [comment]
@chrisant996 I did, sorry I forgot to mention it. I tried both `color.selected_completion` and `color.selection`, seems not what I looking for,

**Comment by benyaminl** [comment]
anyway I will close, this, there are already discussion section, so this should be out of issue scope. I apologize.

**Comment by chrisant996** [comment]
Selection is not completion. Selection means the same as it does in a word processor or text box.

The documentation lists a whole bunch of different colors. Explore more of them. You'll figure it out! 🙃

**Comment by actforjason** [comment]
The documentation is very long and some indistinct

**Comment by chrisant996** [comment]
> The documentation is very long and some indistinct

What do you want to know?

**Comment by actforjason** [comment]
Fail to change the color of completation after changing all color.* in ConEmu with latest version.

**Comment by actforjason** [comment]
And now how to reset all color only and keep other setting because it looks messy.

**Comment by chrisant996** [comment]
What color are you trying to change?

It sounds like you are asking about colors of file names listed when displaying competitions.

That's not what this question was about.

For your question, refer to the section [Completion Colors](https://chrisant996.github.io/clink/clink.html#completioncolors).

For resetting all colors, either reset them one by one, or delete the `clink_settings` file to reset all settings, or write a script to loop through the color.* settings and reset them one by one, or (but be very careful with this one) edit the `clink_settings` file.

**Comment by actforjason** [comment]
I want to change the color of clink-popup-complete as follow. It seems there isn't a color.* for it.
![image](https://user-images.githubusercontent.com/57058325/184544226-b49ccafd-6e8f-4166-bd29-ff35c56a94d1.png)

**Comment by chrisant996** [comment]
I shared a link to the section of documentation that covers Completion Colors.

You're doing something else. The Completion Colors section explains.

**Comment by actforjason** [comment]
I got it. First we need add these commands to the .inputrc file (%userprofile%\.inputrc)
```
# Some common Readline config settings.

set colored-stats                 on   # Turn on completion colors.
set colored-completion-prefix     on   # Color the typed completion prefix.
```
then set LS_COLORS as System Environment Variable  on windows instead of typing them every time the terminal is opened
```
setx "LS_COLORS" "so=90:fi=91:di=96:ex=93:no=92:*.pdf=30;105"
```

**Comment by chrisant996** [comment]
Yes.  And if you install with "Use enhanced defaults" then the `colored-stats` and `colored-completion-prefix` will be on by default.
