### ISSUE TITLE
Failsafe separated history sessions proposal

### ISSUE THREAD

**Issue by clinkist** [chrisant996/clink#317]
Currently, `history.shared` set to True updates the history file after every command, which makes it resilient to any crashes the process may encounter. However, `history.shared` set to False doesn't simply separate the sessions — it will make Clink wait with updating the file until the end of the session. This, of course, has an unintended effect of enabling history loss in event of crash.

I would therefore propose the following: when `history.shared` is set to False, the entries are still saved immediately, but with some kind of session identifier to separated the sessions. When the session ends, those entries can be added to main history. Every now and then (or maybe after invoking a special command, like `clink history restore_crashed`) Clink should check if there are any entries which correspond to non-existent sessions, and add them to main history as well.

**Comment by chrisant996** [comment]
> However, `history.shared` set to False doesn't simply separate the sessions — it will make Clink wait with updating the file until the end of the session. This, of course, has an unintended effect of enabling history loss in event of crash.

What makes you say there is history loss?  I think it's a hypothetical statement, which hasn't been tested empirically.

> I would therefore propose the following: when `history.shared` is set to False, the entries are still saved immediately, but with some kind of session identifier to separated the sessions. When the session ends, those entries can be added to main history. Every now and then (or maybe after invoking a special command, like `clink history restore_crashed`) Clink should check if there are any entries which correspond to non-existent sessions, and add them to main history as well.

That is already how it works.

```
C:\Users\chrisant>dir /b \Users\chrisant\AppData\Local\clink\clink*
clink.log
clink_history
clink_history_17724
clink_history_17724.removals
clink_history_28204
clink_history_28204.removals
clink_history_35260
clink_history_35260.removals
clink_settings
```

**Comment by clinkist** [comment]
"Enhancement" label is incorrect, it should be changed to "stupid", rather.
You're completely right, my testing was wrong. It works like a charm. A nice change after 0.4.9 — now I'm confident I won't lose anything.
I'm sorry for wasting your time.

**Comment by chrisant996** [comment]
> You're completely right, my testing was wrong. It works like a charm. A nice change after 0.4.9 — now I'm confident I won't lose anything.
> I'm sorry for wasting your time.

Ok, great, thanks for confirming it was just a misunderstanding.

I appreciate the report/suggesting! Keep 'em coming. Perhaps with a little more verification first, but an occasional false alarm isn't a problem. An occasional incorrect report is better than not reporting a real issue. 🙃
