### ISSUE TITLE
clink-popup-history is same as win-history-list

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [chrisant996/clink#321]
I set `win-history-list` in `.inputrc` for some key but get same results as `win-history-list (F7)`. I use Cmder/ConEmu and last Clink 1.3.34. I cannot incrementally search this list. Is something missing in my setup?
![image](https://user-images.githubusercontent.com/2730894/177889347-dab55a19-d26b-4f01-a86c-b547bd1a5b1b.png)

Ref:
https://chrisant996.github.io/clink/clink.html#popup-windows

**Comment by chrisant996** [comment]
Whups.  Incremental search in `clink-popup-history` got broken in v1.3.19.  Will slip a fix into the v1.3.35 that's coming soon.
