### ISSUE TITLE
rl.expandtilde does not expand tilde

### ISSUE THREAD

**Issue by HeyItsJono** [chrisant996/clink#326]
I've been using [HomeClink](https://github.com/HeyItsJono/HomeClink/blob/main/HomeClink.lua) to approximate automatic tilde expansion and allow commands like `cd ~` to cd to the user's home directory.

Unfortunately upon updating to the latest clink version, `rl.expandtilde()` is no longer expanding the tilde in this expression. For example, when I print the result of `rl.expandtilde('cd ~')`, the result is `cd ~` and expanded is `false`. This has been happening since I upgraded from `v1.3.17` to `v1.3.36`.

Is there any way to restore the functionality of `rl.expandtilde()`? I could just change the functionality of HomeClink to manually replace `~` with `%HOME%`, but I just wanted to make sure this wasn't a bug first.

**Comment by chrisant996** [comment]
Ugh.

The problem is that Readline's logic for expanding tilde is overly simplistic, and it wrongly expands some inputs. Fixing that has introduced the opposite problem where now it doesn't expand all tildes in an entire command line that's passed in at once.

Basically, there will need to be two different modes for the function:
1. Expand for an entire command line. Expand the old way, which can expand multiple tildes, but doesn't respect quotes and can also incorrectly mangle certain kinds of filenames.
2. Expand for a single filename input. Expand tilde only at beginning of the input, this guaranteeing correct treatment when the input is a single filename.

Replacing all tildes with `%HOME%` would create other problems. I would recommend against that!

**Comment by chrisant996** [comment]
As you can see in the [documentation for rl.expandtilde()](https://chrisant996.github.io/clink/clink.html#rl.expandtilde), the function is intended to be used with a single pathname as the input.

When used according to the documentation (such as in match generators), it is incorrect for the function to behave the way you expected it to.  But the old behavior can still be useful in some special cases, so I'm adding a second argument to the function to request the old behavior.

In v1.3.37 and higher, passing `true` as the second argument will cause the function to treat the input as an entire command line, and behave the way it used to.  Passing true in older versions is safe (and is ignored), so a script can safely use `rl.expandtilde(line, true)` in any version of Clink to expand the input as though it is a whole command line (except in v1.3.36).

**Comment by HeyItsJono** [comment]
Thanks for looking into this, I'll be very glad to see this functionality returned! Definitely streamlines my shell experience.

**Comment by chrisant996** [comment]
This new behavior is available in v1.3.37 now.


You can update the following line in [HomeClink.lua](https://github.com/HeyItsJono/HomeClink/blob/b0a733c6b8e71c51b3cb835ebc241afe28ef8450/HomeClink.lua#L16) from this:
```lua
	local expanded_input, was_expanded = rl.expandtilde(escaped_input)
```

To this:
```lua
	local expanded_input, was_expanded = rl.expandtilde(escaped_input, true)
```

**Comment by HeyItsJono** [comment]
That's fixed it :) Thank you for all your hard work on the project! As an aside, is there any active repo where we can submit clink completions?

**Comment by chrisant996** [comment]
> is there any active repo where we can submit clink completions?

clink-gizmos could be a good place, depending on what the script is.

**Comment by chrisant996** [comment]
Well, what does it mean to have an official repo for all Clink extensions?

Should everyone load 1000 extensions if they only use 10 of them?
What about when people have different opinions about how something should work?

It's easy to make a quick and dirty hack that's good enough for my own needs, and push it into a repo where everyone else is forced to use it.
But that's optimizing for authors having minimal responsibility -- people want high quality scripts, which means any "official" repo needs to be curated, and someone has to maintain standards of quality.

That's what I'm trying to do with clink-gizmos.

What you're looking for is not a repo, really. You're looking for a catalog, where you can find things and choose whether to use them. Git repos aren't well suited to that role.

Anyway, as I've mentioned in other posts on this topic, I already invest a large amount of time into programming Clink. I'm not going to also build a catalog web site. Someone else is welcome to do so, of course.

**Comment by chrisant996** [comment]
> I think I've seen at least 4 different implementations of a `git` completion extension).

The one in clink-completions is pretty good. Especially the PR that is pending. But Vladimir seems to have abandoned it, so I may have to promote my fork as the new active repo.
