### ISSUE TITLE
Tab autocomplete, auto-quoting paths doesn't seem to work as in Clink 0.4.9

### ISSUE THREAD

**Issue by tsimmons** [chrisant996/clink#33]
Not sure if this is by design or not, but one thing about the clink 0.4.9 I found immensely convenient was the tab autocomplete auto-quoting that seemed to happen but appears missing in your v1.1.11.

For example, while using 0.4.9, typing
```
C:\Users\username> cd \program
```

Followed by the TAB key results in the following change:
```
C:\Users\username> cd "\Program
```

Note the inserting the opening quote symbol. This now allows you to type a space character and hit TAB again to reveal paths that match.

However, using your v1.1.11 and typing
```
C:\Users\username> cd \program
```

Followed by the TAB key doesn't quote and typing space also doesn't autofill paths with spaces.

In addition, using your version and typing
```
C:\Users\username> cd \program(space)fi
```

Followed by the TAB key doesn't autofill matching paths.

Am I missing something?

**Comment by chrisant996** [comment]
I see.  `menu-complete` had a problem with too much quoting.  Fixing that problem accidentally introduced this problem.
