### ISSUE TITLE
[Help] I want to expand aliases when i press <space>, but then it no longer inserts the character.

### ISSUE THREAD

**Issue by Zakaria-ouertani** [chrisant996/clink#330]
I prefer **aliases** to be expanded after i type them so i tried binding <***space***> to ***clink-expand-doskey-alias*** but then it doesn't insert the <***space***> character.
Please how can i achieve it.
Thanks in advance.

**Comment by chrisant996** [comment]
Make a Lua function and use [Lua key bindings](https://chrisant996.github.io/clink/clink.html#luakeybindings),  [rl.invokecommand](https://chrisant996.github.io/clink/clink.html#rl.invokecommand) will also be helpful for doing what you want.

**Comment by Zakaria-ouertani** [comment]
> Make a Lua function and use [Lua key bindings](https://chrisant996.github.io/clink/clink.html#luakeybindings). And [rl.invokecommand](https://chrisant996.github.io/clink/clink.html#rl.invokecommand) will also be helpful for doing what you want.

Ok thanks.

**Comment by Zakaria-ouertani** [comment]
Figured it out

For anyone interested here's what i ended up with
```
function aliasExpand(rl_buffer)
	rl.invokecommand("clink-expand-doskey-alias")
	rl_buffer:insert(" ")
end
```
