### ISSUE TITLE
Question: Can we get "old" cmd.exe auto-complete behavior somehow?

### ISSUE THREAD

**Issue by reFX-Mike** [chrisant996/clink#331]
Apologies, but I couldn't find the answer online. I vastly prefer the original cmd.exe behavior when it comes to auto-complete. Now I'm getting nothing on the first tab, and on the second tab, I get a list of suggestions. I would prefer that the prompt simply cycles through all possibilities, and I just have to hit enter to start the selected program.

Motivation: in one folder, I have four different "update_something.bat" scripts, and an "updates" folder. When I now type "up" and then hit tab, first nothing happens, then when I hit tab again, I get a list of possible commands, but at the end of the day, I still have to type more and more to get the one I want. Also, it lists at least four (!) *.exe that do not even exist in that folder, and it's sub-folders, that do not even exist! Where are ```UpgradeResultsUI.exe, UPPrinterInstaller.exe, upfc.exe, and upnpcont.exe``` even coming from?

![image](https://user-images.githubusercontent.com/2496353/183262730-2b1beb04-a8d5-452d-91ca-9ecb32687cb7.png)

**Comment by chrisant996** [comment]
Yes, I believe it's mentioned in the Getting Started section.

There is a setting to choose Windows style key binding defaults, rather than bash style key bindings.

"Use enhanced defaults" sets that, in addition to several other settings.

**Comment by reFX-Mike** [comment]
Sorry. I didn't see that. I had no idea it was a keybinding I was looking for. I've searched for "autocomplete", and similar and couldn't find it. Sorry for the waste of time.

**Comment by chrisant996** [comment]
As for the *.exe files from other folders, that's a feature, controlled by the `exec.enable` and `exec.*` family of settings.

I would encourage to read the Getting Started section, and share feedback on anything that can be improved about the documentation.

The first section under Getting Started explains how completion works, and how to configure how `Tab` behaves.
