### ISSUE TITLE
Completing auto-suggestions with Tab instead of right arrow key/End

### ISSUE THREAD

**Issue by JeffreyCA** [chrisant996/clink#332]
Is this possible to configure in clink?

From the docs:
> To turn on automatic suggestions, run clink set autosuggest.enable true. When the cursor is at the end of the input line, a suggestion may appear in a muted color. If the suggestion isn't what you want, just ignore it. **Or accept the whole suggestion with the Right arrow or End key**, accept the next word of the suggestion with Ctrl-Right, or accept the next full word of the suggestion up to a space with Shift-Right.

**Comment by chrisant996** [comment]
Relevant doc topics:
- [Customizing Key Bindings](https://chrisant996.github.io/clink/clink.html#keybindings)
- [Bindable Commands](https://chrisant996.github.io/clink/clink.html#bindable-commands)
- [Clink Commands](https://chrisant996.github.io/clink/clink.html#clink-commands)

Bind <kbd>Tab</kbd> key to the `clink-insert-suggestion` command.

**Comment by JeffreyCA** [comment]
Thanks, I set my `.inputrc` to the following, but it's not completing the suggestion when I press `Tab`:

```rc
"\t": clink-insert-suggestion
```

I'm using Windows Terminal with the Command Prompt profile. Am I missing something?

**Comment by chrisant996** [comment]
> Thanks, I set my `.inputrc` to the following, but it's not completing the suggestion when I press `Tab`:
> 
> ```rc
> "\t": clink-insert-suggestion
> ```
> 
> I'm using Windows Terminal with the Command Prompt profile. Am I missing something?

I think probably you are missing something.

But you haven't shown the steps that are being followed, or what happens.  That makes it almost impossible to help.

Have you confirmed the `.inputrc` file that was edited is the same one being loaded by Clink?
`clink info` shows which one was loaded.

Have you tried binding TAB to a different command and confirmed the other command gets executed?

Is there a suggestion provided?  If there's no suggestion then the change won't insert anything.

Does END do what you want, but TAB doesn't?

Or maybe what you want is not really "make TAB insert the auto-suggest suggestion"?  Maybe what you want to insert is something else?

**Comment by chrisant996** [comment]
If you're trying to make TAB cycle through inserting completions, then that's the first thing covered in the Getting Started section, and it has nothing to do with auto-suggest or END or Arrow keys.

**Comment by JeffreyCA** [comment]
Sorry, here are some more details after some more testing. Yes I can confirm that my `inputrc` is being loaded by clink. 

Binding `Tab` to other commands like `beginning-of-line` or `previous-history` works. Binding other shortcuts to `clink-insert-suggestion` hasn't worked for me (I tried binding `\t`, `C-g` to name a few).

`End` and `Right` both complete the suggestion as expected. Basically I want `Tab` to do the same thing as `End` and `Right`.

**Comment by JeffreyCA** [comment]
Ok, so I tried mapping `Tab` to `end-of-line` instead and it seems to do I want. I am a bit confused about what `clink-insert-suggestion` and `clink-accept-suggestion` are supposed to do though.

**Comment by chrisant996** [comment]
@JeffreyCA You have found a documentation bug!

I had failed to update the documentation with the final command names.
The docs will be updated soon.

Here are the correct command names:

Command | Description
-|-
`clink-accept-suggested-line` | If there is a suggestion, insert the suggestion and accept the input line (like `accept-line`).
`clink-insert-suggested-full-word` | If there is a suggestion, insert the next full word from the suggested line.
`clink-insert-suggested-line` | If there is a suggestion, insert the suggested line.
`clink-insert-suggested-word` | If there is a suggestion, insert the next word from the suggested line.

That should resolve the problem, I hope.

Try
```inputrc
"\t": clink-insert-suggested-line
```

The difference is that if the cursor is not already at the end of the line, then `end-of-line` will move the cursor to the end of the line, but `clink-insert-suggested-line` will ding the bell and do nothing.

**Comment by JeffreyCA** [comment]
That was it, thank you 🙂 I'll close this out now
