### ISSUE TITLE
[Feature request] Use `pushd` for "Directory shortcuts"

### ISSUE THREAD

**Issue by pukkandan** [chrisant996/clink#333]
As far as I know, Clink's [Directory shortcuts](https://chrisant996.github.io/clink/clink.html#directory-shortcuts) are not currently configurable. I prefer to use `pushd`/`popd` instead of `cd /d` for directory navigation. Would it be possible to implement this?

Even better if you can make this customizable so that custom batch files can be used

**Comment by chrisant996** [comment]
How about using `clink.onfilterinput()` to replace `cd /d` usage with `pushd`?

**Comment by pukkandan** [comment]
Just to clarify, this is what I am talking about
![image](https://user-images.githubusercontent.com/6623388/184556290-0a9df2b1-4480-493c-877d-c02f9dcd4754.png)


The `cd` here is sent by clink internally, not typed by me. I didn't think `onfilterinput` will get the full command line in this case. Does it? If so, that would be acceptable solution.

Technically, this would mean I can never intentionally send a `cd /d`, but that's fine. If I really need to, there's always `chdir`

**Comment by chrisant996** [comment]
`intercept_directory()` happens before `onfilterinput`:

https://github.com/chrisant996/clink/blob/6d8ab1d36eb73106a1eb16068acf9a8e4d697426/clink/app/src/host/host.cpp#L1120-L1146

(It also happens after `onfilterinput`, in case something filters the input to turn it into a directory shortcut.)

Directory shortcuts are translated into:

<code>&nbsp;cd /d "<em>directory</em>"</code>

Note the leading space.

So you could still use `cd /d blah`, without a leading space.
Or even <code> cd /d blah</code>, without quotes.

**Comment by pukkandan** [comment]
ah, nice. I should be able to implement this. Thanks as always

**Comment by chrisant996** [comment]
Cool.  If something more sophisticated or simpler to configured is needed, then I can look into making some kind of change.  But if a change isn't needed then I'd lean towards using the existing mechanisms.

**Comment by chrisant996** [comment]
Hi @pukkandan, your custom script will need to be updated:

Issues #569 and #570 are about failures in Clink when command extensions are disabled.
`cd /d` requires command extensions, so Clink needs to avoid using `cd /d`.

So, places that previously used ` cd /d dir` now use ` cd dir`, or ` X: & cd dir` if the drive needs to change as well.

**Comment by pukkandan** [comment]
Thanks for the heads up.

The space at the start is still present, right? If so, I just need to adjust my regex. No big deal

**Comment by chrisant996** [comment]
> The space at the start is still present, right? If so, I just need to adjust my regex. No big deal

Yup, two kinds of commands possible now, and both still start with a space:
- ` X: & cd somedir`
- ` cd somedir`

Also, some .lua scripts may use 2 leading spaces.  E.g. cwdhistory.lua, and there are others as well.  And fzf.lua's `luafunc:fzf_directory` command uses no leading spaces (and it already didn't), but it's intentionally inserting a command into the input line as though it was typed.
