### ISSUE TITLE
Error: Unable to inject Clink

### ISSUE THREAD

**Issue by slhussey** [chrisant996/clink#335]
Window contents:
Microsoft Windows [Version 10.0.19044.1889]
(c) Microsoft Corporation. All rights reserved.
**Unable to inject Clink.**
See log file for details (C:\Users\s0050466\AppData\Local\clink\clink.log).

Logfile contents:
2ea8 inject                    563 ---- 2022/08/25 14:14:06.225 -------------------------------------------------
2ea8 inject                    564 Injecting Clink...
2ea8 inject_dll                269 Version: 1.3.40.1901c2
2ea8 inject_dll                270 Arch: x64
2ea8 inject_dll                271 DLL: C:\Users\s0050466\AppData\Local\Temp\clink\dll_cache\1.3.40.1901c2_99c250e2\clink_dll_x64.dll
2ea8 inject_dll                273 Parent pid: 20768
2ea8 check_dll_version         168 DLL version: 00010003 00280000
2ea8 process::remote_call_internal  270 *** ERROR ***
2ea8 process::remote_call_internal  270 Unable to create remote thread in process 20768.
2ea8 process::remote_call_internal  270 (last error = 5)

Windows environment:
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎7/‎28/‎2022
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

This is a fresh install.

**Comment by chrisant996** [comment]
Error 5 is "access denied".

Looks like your anti-virus suite doesn't like Clink.  Unfortunately there is nothing Clink can do about that.

Check your AV logs, and report the false positive to the AV software's authors.  They can assess and allow it.
