### ISSUE TITLE
%CD% is not expanded as environment variable

### ISSUE THREAD

**Issue by rmccampbell** [chrisant996/clink#339]
The "special" variable %CD% holds the current working directory, but clink doesn't expand it with clink-expand-line or the match.expand_envvars setting.

**Comment by chrisant996** [comment]
Clink currently does not synthesize values for the following "special" variables:

- `CD`
- `DATE`
- `TIME`
- `RANDOM`
- `CMDEXTVERSION`
- `CMDCMDLINE`
- `HIGHESTNUMANODENUMBER`

Those are not actually environment variables.  CMD treats them specially and fills in values for them, but they don't actually exist in the environment block.

`CD`, `RANDOM`, and `CMDCMDLINE` are straightforward and simple to support, and I'll add them in Clink.

The others are not straightforward, and I won't add support for them until/unless a strong need for them can be described.
