### ISSUE TITLE
history command can't display CJK chars

### ISSUE THREAD

**Issue by gotounix** [chrisant996/clink#344]
![image](https://user-images.githubusercontent.com/18606632/190534703-69a0b330-642a-4708-aaf8-19ff893c920b.png)

![image](https://user-images.githubusercontent.com/18606632/190534743-1674ac2c-a133-4668-8840-eb4618ebdea6.png)

![image](https://user-images.githubusercontent.com/18606632/190536112-e1f61c82-7719-4bce-a8d9-0c78ec53ce70.png)

![image](https://user-images.githubusercontent.com/18606632/190540729-21acfa57-dd8e-4061-991f-63f48fff1bf2.png)

**Comment by chrisant996** [comment]
@gotounix Thank you for reporting this!

**Comment by gotounix** [comment]
@chrisant996 When will a release version be compiled.

I added [AdditionalOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vcprojectengine.vcclcompilertool.additionaloptions) `/utf-8` then compiled the `master` branch codes on VS2019 and VS2022 success, but when I run in cmder get errors:

![image](https://user-images.githubusercontent.com/18606632/191429186-cbf07996-35a8-46dc-b833-c2b9be42c37b.png)

**Comment by chrisant996** [comment]
> @chrisant996 When will a release version be compiled?
> 
> I added [AdditionalOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vcprojectengine.vcclcompilertool.additionaloptions) `/utf-8` then compiled the `master` branch codes on VS2019 and VS2022 success, but when I run in cmder get errors:

Don't do that. That's not related to the problem.

If you're building it yourself, the fix was already committed. Just compile.

**Comment by gotounix** [comment]
@chrisant996 

If don't add `/utf-8`, compile failed:

![image](https://user-images.githubusercontent.com/18606632/191442746-1194de07-61a1-4731-8dfb-f8fb52bd06d4.png)

I used 1.3.42 codes and patch your commit, compiled success and works fine.

When I use the `maser` codes, compiled success, but works failed, the errors is the picture replied above.

**Comment by chrisant996** [comment]
> If don't add `/utf-8`, compile failed:
> 
> _... screen shot ..._
> 
> The file contains a character that cannot be represented in the current code page (number). Save the file in Unicode format to prevent data loss.

The screen shot wasn't helpful, because it didn't indicate which files encountered the errors.

I manually tracked down the files.
- clink\core\include\core\bldopts.h
- clink\core\src\str_compare.cpp
- clink\lib\src\textlist_impl.cpp
- clink\lua\src\unicode_api.cpp
- clink\terminal\src\cielab.cpp

I've added a BOM to the files.

**Comment by gotounix** [comment]
@chrisant996 I check out your newest commits, and fixed all the above questions, thanks.
