### ISSUE TITLE
Using in a Terminal Server environment possible?

### ISSUE THREAD

**Issue by UweKeim** [chrisant996/clink#347]
Just installed newest Clink with an administrative account into a Windows 2022 Terminal Server.

Even after logging off and on again, the normal user accounts do _not_ see Clink being active in a command line.

### Question

What steps do I have to follow to make Clink accessible to normal users (i.e. non-admins) in a Terminal Server environment?

**Comment by chrisant996** [comment]
I think you mean you want to configure Clink for all users on the machine to force always injecting Clink into every cmd.exe.

See `clink autorun --help`.

You need to use the flag for All Users.
