### ISSUE TITLE
Crash when click on clink.bat

### ISSUE THREAD

**Issue by skywind3000** [chrisant996/clink#35]
System: Windows 10 - 10.0.19042.685
Clink: 1.1.11 bd8deb

Sometimes it works, but later when I start your new clink by clicking clink.bat:

![图片](https://user-images.githubusercontent.com/3035071/102980240-3b4d1e80-4542-11eb-9682-32ee4fef93c2.png)

see the attatchment for detail:

[clink_crash_report.zip](https://github.com/chrisant996/clink/files/5734293/clink_crash_report.zip)

Hope it could be fixed.

**Comment by chrisant996** [comment]
It's a regression from the Windows 7 fix.  It's somehow accidentally hooking both ReadConsoleW APIs, and something goes horribly wrong and it ends up landing in the middle of completely unrelated code.  I don't understand yet what's happening once the double-hooking occurs, but that shouldn't matter once it's fixed to only hook once.

**Comment by chrisant996** [comment]
Out of curiosity, do you also have Clink 0.4.x installed, and is 0.4.x set up for auto-inject?

**Comment by skywind3000** [comment]
There is a clink 0.4.x installed in my computer, but auto-inject has not been enabled. 

And at the same time this clink crashed, there wasn't any running instance of clink 0.4.x.

**Comment by chrisant996** [comment]
v1.1.12 has a speculative fix for this.  Please try it when you get a chance.

**Comment by skywind3000** [comment]
Using 1.1.13 for one day, no crash encountered.

**Comment by chrisant996** [comment]
Closing this issue, but please reopen if it happens again.

Thank you!
