### ISSUE TITLE
Add ability to disable AutoRun / skip clink injection

### ISSUE THREAD

**Issue by cristianadam** [chrisant996/clink#361]
At https://bugreports.qt.io/browse/QTCREATORBUG-27906 I've noticed that Qt Creator would take 21s to start, instead of 7s.

The main reason for this slowdown was clink that gets injected in the `vcvarsall.bat` calls that Qt Creator does in order to find out details about the build environment.

We thought that starting cmd.exe wit `/D` (_Disable execution of AutoRun commands from registry_) it would fix the problem, unfortunately `vcvarsall.bat` does its own cmd calls without `/D` and the result is the same.

Mabye an environment variable named `CLINK_SLIP_INJECTION`, which then checked in `"c:\Program Files (x86)\clink\clink.bat"` it would help, in the hope that the chid process will get the environment from the parent.

**Comment by cristianadam** [comment]
Ok, found the `CLINK_NOAUTORUN` environment variable, but this is checked inside [clink code](https://github.com/chrisant996/clink/blob/f164c68ae47936b7c3ab7517831bee3cbb943282/clink/app/src/loader/inject.cpp#L526) which is a bit too late.

Here are some benchmarks of Qt Creator started with `-tcs -profile`:

# Normal clink setup

```
17.94s
16.23s
17.81s
```

# With CLINK_NOAUTORUN environment variable set

```
12.70s
13.64s
12.93s
```


# with quick exit in clink.bat

```
10.15s
9.05s
10.34s
```

# With the AutoRun registry key renamed

```
8.99s
8.65s
8.68s
```

**Comment by chrisant996** [comment]
Right, I haven't had a chance to add a check in clink.bat yet, but it came up in another issue which I think is still open.

**Comment by chrisant996** [comment]
See #349 which discusses the performance of autorun  and why CLINK_NOAUTORUN isn't intended as a performance aid.

@cristianadam you've shown a scenario where checking it in the clink.bat file could be beneficial, so I'll look into how to do that safely and correctly.  The PR linked here accidentally entirely disables all Clink usage if the env var is set, even when not being invoked through autorun, so it isn't ready as a viable fix.

**Comment by chrisant996** [comment]
@cristianadam I want to thank you for reporting this and investigating approaches that could potentially mitigate the issue.

While the PR itself has some problems and I can't merge it, this exercise was nevertheless helpful for me: it explored multiple possibilities and served as a very constructive brainstorming conversation.

I apologize that I can't merge the PR (I know github keeps track of "credit" that way). However, this did result in helping me find a simple and viable solution, which I'll commit later today.

**Comment by chrisant996** [comment]
@cristianadam v1.3.49 now detects non-interactive CMD.EXE instances earlier, before loading the DLL into the CMD process.  This should improve the speed during autorun somewhat, in the general case where CLINK_NOAUTORUN was not manually set.
