### ISSUE TITLE
ARM64 release

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#364]
Clink is able to build and run as ARM64 now, per #363.

But I can't yet commit to producing and maintaining official ARM64 builds of Clink.

There are several things that need to be dealt with before official builds can be published.

### Embedded Lua scripts
- [x] What to do about ARM64 and embedded Lua scripts, for release builds?  _[Conclusion: arm64 and x64 produce the same  precompiled script binaries, so arm64 doesn't need to produce a special version.]_

### .zip file
- [x] Decide whether one .zip file contains x86/x64/arm64, or if there will be a new second .zip file that includes arm64.  _[Conclusion: one .zip file that contains everything, so that scoop and chocolatey and etc can work for arm64.]_

### .exe installer
- [x] Decide whether one .exe contains x86/x64/arm64, or if there will be a new second .exe file that includes arm64.  _[Conclusion: one setup .exe, but it will only install arm64 binaries on an arm64 device.]_
- [x] Update the installer to install arm64, but only on arm64 devices.

### auto-updater
- [x] Depending on the .zip file decision, the auto-updater might become more complicated.  _[Conclusion: no work needed, because there will be only one .zip file.]_
- [x] The auto-updater does not know about arm64; it could potentially take up to 2 separate updates to get arm64 installed for the first time through the auto-updater.

**Comment by chrisant996** [comment]
@cristianadam This is a problem. 🤔

```cmd
> premake embed
Running action 'embed'...

clink/app/scripts/lua_scripts.cpp
   clink/app/scripts/cmd.lua
This version of c:\repos\clink\.build\vs2019\bin\final\luac_arm64.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Error: c:/repos/clink/embed.lua:86: attempt to index a nil value (local 'bin_in')
```

The ARM64 changes have accidentally made it so that Clink releases can _only_ be produced by an ARM64 computer.  This is due to a limitation of how the Lua language works.

I have to back out part of that change, sorry.

This is going to require more sophisticated engineering to solve.  I may have to embed the raw .lua files in ARM64 builds (i.e. no precompiling).  That would cause minor inconsistencies between ARM64 Clink versus other platforms, especially when Lua errors occur and in the `clink-diagnostics` command, as well as a minor performance degradation, but for the most part the differences won't be noticeable.

**Comment by chrisant996** [comment]
@cristianadam Some good news:  it turns out #363 was overly complicated.  Precompiled Lua scripts are sensitive to certain aspects of chipsets.  But x64 and arm64 produce identical byte code, because they're both 64 bit and they're both little-endian and they both have the same `int` size, etc.

So, the precompiled 64 bit scripts in fact work on both x64 and arm64.  This means official builds for arm64 can be produced on an x64 machine, after all.

I've made changes accordingly, and this should make it possible to produce an official Clink arm64 version.  There are still several work items that must be done to achieve that, but the good news is that it's _possible_ now, and the effort is not _blocked_ anymore.

**Comment by chrisant996** [comment]
@cristianadam Can you please try [clink_setup_with_arm64.zip](https://github.com/chrisant996/clink/files/10304855/clink_setup_with_arm64.zip)?

Extract the setup .exe program from the .zip file, and then run the setup .exe program.
- Can you please confirm whether on an arm64 system it installs the arm64 files and whether Clink works as expected for arm64 cmd.exe instances?
- I've already confirmed that on an x86 or x64 system it does not install the arm64 files.

**Comment by cristianadam** [comment]
Looks good.  🎉

Here is the result from 🪟+ R and then `cmd.exe`:

```
Microsoft Windows [Version 10.0.22621.963]
(c) Microsoft Corporation. All rights reserved.

Clink v1.4.7.4597ff
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\Users\Cristian
$ set | findstr ARCH
PROCESSOR_ARCHITECTURE=ARM64
```

**Comment by chrisant996** [comment]
Commit 87a4440ebc718963890e369ded450907ea2ecb85 makes the official builds include ARM64. The .zip and setup .exe files now include ARM64 executables.
