### ISSUE TITLE
clink filter to edit Prompt current path

### ISSUE THREAD

**Issue by alanlivio** [chrisant996/clink#365]
Hi. Clink is an amazing tool. 
I was able to match.translate_slashes to slash and feel like bash.
```
C:\> cd /Users/alan
C:\Users\alan>
```

To increase even more my bash experience, I would like to know if possible also change the Prompt current path to also make the such a translation.
My desired experience is like this: 

````
/> cd /Users/alan
/Users/alan>
```

**Comment by chrisant996** [comment]
See [Customizing The Prompt](https://chrisant996.github.io/clink/clink.html#customisingtheprompt) to get started with writing prompt filters.

You'll also want to use the Lua `string.gsub()` function.

**Comment by chrisant996** [comment]
Please feel free to ask further questions.  For now I will close this question.
