### ISSUE TITLE
A bug that you type a TAB when you Input a var

### ISSUE THREAD

**Issue by winstonkenny** [chrisant996/clink#370]
```batchfile
@echo off
set /p flag=^>^>^>
echo %flag%
```
If you type a str with TAB to flag, you will get a empty str.

eg. no clink
``` text
>>>ABC[Press a tab]
ABC
```
eg. use clink
``` text
>>>ABC[Press a tab]
ECHO is off.
```

**Comment by winstonkenny** [comment]
Clink v1.3.46.d6fdd0

**Comment by chrisant996** [comment]
Yes, that's a good find.  Thank you for reporting it.

<kbd>Tab</kbd> should do filename completion there, but it accidentally discarded the input instead.
