### ISSUE TITLE
The Ctrl selection behavior

### ISSUE THREAD

**Issue by sunvis0r** [chrisant996/clink#373]
Clink changed behavior of deletion via Backspace with Ctrl key. I have not found a setting to change it back. Can this be added as a small feature? =)
![Анимация](https://user-images.githubusercontent.com/94429755/199049357-7f4e62c4-9a01-48e9-bc8a-d93edd8fa483.gif)

**Comment by chrisant996** [comment]
See [Customizing Key Bindings](https://chrisant996.github.io/clink/clink.html#keybindings) and [Bindable Commands](https://chrisant996.github.io/clink/clink.html#bindable-commands) and [Killing and Yanking](https://chrisant996.github.io/clink/clink.html#killing-and-yanking-1) and the `unix-word-rubout` command.  (Bound to <kbd>Ctrl</kbd>-<kbd>W</kbd> by default.)
