### ISSUE TITLE
Cmder 1.3.21 + Clink got output ERROR: Clink initilization has failed with error code: 0

### ISSUE THREAD

**Issue by BackSpace54** [chrisant996/clink#390]
Hi,

since i've updated to the latest Cmder version to date (v1.3.21) and with Clink 1.4.4, i've an error at terminal startup:
Clink v1.4.4.7fe1ca
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink
ERROR: Clink initilization has failed with error code: 0

Here's the two clink.log:
4bdc start_logger              160 ---- 2022/12/20 14:24:18.838 -------------------------------------------------
4bdc start_logger              166 Host process is 'cmd.exe' (pid 19420)
4bdc start_logger              170 DLL path is 'C:\Program Files (x86)\clink'
4bdc start_logger              185 Windows version 10.0.22621 (x64)
4bdc start_logger              188 Clink version 1.4.4.7fe1ca (x64)
4bdc host_lua::load_scripts    158 Loaded 6 Lua scripts in 206 ms
4bdc =?                          0 Clink updater: too soon to check for updates (1671534652 vs 1671542659).
4bdc history_db::initialise   1264 master bank ctag: |CTAG_1639573367_463125_18248_0
4bdc history_db::compact      1526 History:  1342 active, 1126 deleted
4bdc reset_handle              144 resetting mismatched stdout handle
4bdc reset_handle              144 resetting mismatched stderr handle
4bdc history_db::compact      1526 History:  1342 active, 1126 deleted

49bc inject                    599 ---- 2022/12/20 14:29:49.596 -------------------------------------------------
49bc inject                    600 Injecting Clink...
49bc copy_dll                  122 *** ERROR ***
49bc copy_dll                  122 Failed to copy DLL to 'C:\Temp\clink\dll_cache\1.4.4.7fe1ca_99c250e2\clink_dll_x64.dll'
49bc copy_dll                  122 (last error = 32)
49bc inject_dll                269 Version: 1.4.4.7fe1ca
49bc inject_dll                270 Arch: x64
49bc inject_dll                271 DLL: C:\Program Files (x86)\clink\clink_dll_x64.dll
49bc inject_dll                273 Parent pid: 3192
49bc check_dll_version         168 DLL version: 00010004 00040000
49bc inject_dll                341 Host is not interactive; cancelling inject.

Before Cmder 1.3.21 and with the exact same configuration i've no troubles.

Have you an idea of what is the problem?

Bye.

**Comment by chrisant996** [comment]
Thanks for including the clink.log contents!

Error 32 is a sharing violation; another program has the file opened exclusively.

It might be the "from" file, or the "to" file.

That's pretty strange to see while copying the DLL.  I've never seen that before in that context, so I don't have a specific suggestion about what might be happening.

Does it happen every time?
Has the computer been rebooted yet? (That can sometimes fix sharing violations.)

**Comment by BackSpace54** [comment]
Well, didn't see your P.S. in github mail. I've tried on two differents computer both in Windows 11 22H2 + december updates with Cmder 1.3.21 used in Windows Terminal 1.15.3466.0, yep it's happen every time and computers were rebooted (with shutdown command).
Now i can't find the Error 32 in log files but got ERROR: Clink initilization has failed with error code: 0 at every start of Cmder.
Will post an issue on Cmder github, i close this one.
Thanks.

**Comment by chrisant996** [comment]
> Well, didn't see your P.S. in github mail.

I edited the reply to add a P.S. after I discovered that the message is from Cmder, not from Clink.

> Cmder 1.3.21 

It's a new bug in Cmder, and was introduced on 2022/10/18.  See cmderdev/cmder#2800 for details.
