### ISSUE TITLE
Lua error when trying to call `git <anything>`

### ISSUE THREAD

**Issue by papstchaka** [chrisant996/clink#393]
When trying to call any git command via (e.g.) `git status`, I encounter the following error after typing `git s`:

```
word classifier failed:
{arguments.lua}:0: attempt to call method '_is_flag' (a nil value)
stack traceback:
        {arguments.lua}: in function 'update'
        {arguments.lua}: in function 'classify'
        {classifier.lua}: in function <{classifier.lua}:62>
        [C]: in function 'xpcall'
        {classifier.lua}: in function <{classifier.lua}:61>
s
getting word break info failed:
{arguments.lua}:0: attempt to index field '_args' (a nil value)
stack traceback:
        {arguments.lua}: in function 'getwordbreakinfo'
        {generator.lua}: in function <{generator.lua}:275>
        {generator.lua}: in function <{generator.lua}:271>
        [C]: in function 'xpcall'
        {generator.lua}: in function <{generator.lua}:270>

match generator failed:
{arguments.lua}:0: attempt to call method '_generate' (a nil value)
stack traceback:
        {arguments.lua}: in function <{arguments.lua}:2246>
        (...tail calls...)
        {generator.lua}: in function <{generator.lua}:217>
        [C]: in function 'xpcall'
        {generator.lua}: in function '_generate'
        {generator.lua}: in function <{generator.lua}:142>
```

I had CLink 0.4.9 (on Windows 10) installed and updated to Clink 1.4.6 because old version wasn't working on Windows 11 anymore. I did not uninstall the old version before downloading and installing the new version (maybe this is causing the error)

**Comment by chrisant996** [comment]
One of your scripts must be directly modifying an argmatcher improperly (probably the "git" argmatcher).  Or maybe has tried to manually simulate constructing an argmatcher instead of using the Clink Lua APIs for creating argmatchers.

If you can make a .zip file containing your Lua scripts, I should be able to find what's corrupting the Clink internal objects.

You don't need to uninstall Clink v0.4.9, but if scripts have tried to directly manipulate internals of Clink objects then they'll likely malfunction.  It's never safe to directly modify internals of an object; it has a good chance of breaking things in the future (which has arrived now, from Clink v0.4.9's perspective).

**Comment by chrisant996** [comment]
P.S.  are you using [vladimir-kotikov/clink-completions](https://github.com/vladimir-kotikov/clink-completions), or are you using a custom git argmatcher (parser)?

**Comment by papstchaka** [comment]
tbh I am not sure whether I understood you correctly.

Everything I did was downloading the `[clink.1.4.6.8b1dec_setup.exe](https://github.com/chrisant996/clink/releases/download/v1.4.6/clink.1.4.6.8b1dec_setup.exe)` file and execute it. As far as I know, I don't have any Lua installed

**Comment by chrisant996** [comment]
@papstchaka What you've encountered is not normal, and I've never seen anything like it before.  It looks like there is a Lua script that is causing some kind of problem.

Let me ask some things to help track down what's happening:

Here is what I understand the situation to be:
- Clink v0.4.9 was installed, and then Clink v1.4.6 was installed without uninstalling v0.4.9 first. (That should be fine, so something more is going on than just that.)
- As far as you know, you have never installed or written any Lua scripts.
- Typing `git s` results in a Lua error.

But for `git s` to hit that error means there is definitely a Lua script set up to provide completions for `git`.  So there's a Lua script somewhere, even if as far as you know there aren't any.  We need to track down where that script is, and investigate what it's doing.

Please try the following:
1. Please run `clink autorun show` and share its output.
2. Please run `clink info` and share its output.
3. In the output from `clink info` please do the following:
    - Find the "scripts   :" line.
    - For each of the script directories listed, please run <code>dir <em>dirname</em></code> and share the output from the `dir` commands.
4. Also, the following should be able to directly pinpoint the script that is registered for `git` completions:
    - Press <kbd>Alt<kbd>-<kbd>2</kbd> then <kbd>Ctrl<kbd>-<kbd>X</kbd> then <kbd>Ctrl<kbd>-<kbd>Z</kbd>.
    - Clink will list a bunch of diagnostic info.
    - Look for the section "argmatches:".
    - In that section, look for a listing for "git".
    - The filename for the script that is registered for "git" completions should be listed on that line.
    - Is possible, please attach that actual script file to your reply.

**Comment by papstchaka** [comment]
okay, I found the problem causing lua script. It was in `C:\Users\<username>\AppData\Local\clink`, named `git-autocomplete.lua` with following content:

```
local branchAliases = {}
local checkoutAliases = {}
local diffAliases = {}
local fetchAliases = {}
local mergeAliases = {}
local pullAliases = {}
local pushAliases = {}
local rebaseAliases = {}
local resetAliases = {}
local showAliases = {}
local showBranchAliases = {}
local switchAliases = {}

function startsWith(str, start)
	return string.sub(str, 1, string.len(start)) == start
end

function endsWith(str, _end)
	return string.sub(str, string.len(str) - string.len(_end) + 1) == _end
end

function isAlias(text)
	if startsWith(text, "git branch") then
		return true
	end

	for i, _alias in ipairs(branchAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git checkout") then
		return true
	end

	for i, _alias in ipairs(checkoutAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git diff") then
		return true
	end

	for i, _alias in ipairs(diffAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git fetch") then
		return true
	end

	for i, _alias in ipairs(fetchAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git merge") then
		return true
	end

	for i, _alias in ipairs(mergeAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git pull") then
		return true
	end

	for i, _alias in ipairs(pullAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git push") then
		return true
	end

	for i, _alias in ipairs(pushAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git rebase") then
		return true
	end

	for i, _alias in ipairs(rebaseAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git reset") then
		return true
	end

	for i, _alias in ipairs(resetAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git show") then
		return true
	end

	for i, _alias in ipairs(showAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git show-branch") then
		return true
	end

	for i, _alias in ipairs(showBranchAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	if startsWith(text, "git switch") then
		return true
	end

	for i, _alias in ipairs(switchAliases) do
		if startsWith(text, "git ".._alias) then
			return true
		end
	end

	return false
end

function getBranches()
	local handle = io.popen("git branch -a 2>&1")
	local result = handle:read("*a")
	handle:close()

	local branches = {}

	if startsWith(result, "fatal") == false then
		for branch in string.gmatch(result, "[* ]%s.%S+") do
			if string.sub(branch, 0, 1) == "*" then
				branch = string.gsub(branch, "* ", "")
			elseif startsWith(branch, "  remotes/") == true then
				branch = string.gsub(branch, "  remotes/", "")
			else
				branch = string.gsub(branch, "  ", "")
			end
			table.insert(branches, branch)
		end
	end

	return branches
end

function getRemotes()
	local handle = io.popen("git remote -v 2>&1")
	local result = handle:read("*a")
	handle:close()

	local remotes = {}

	if startsWith(result, "fatal") == false then
		for remote in string.gmatch(result, "%S+") do
			if string.sub(remote, 0, 1) ~= "(" then
				table.insert(remotes, remote)
			end
		end
	end

	return remotes
end

function gitAutocomplete(text)
	local matchCount = 0

	if isAlias(rl_state.line_buffer) then
		local branches = getBranches()
		for i, branch in ipairs(branches) do
			if startsWith(branch, text) then
				clink.add_match(branch)
				matchCount = matchCount + 1
			end
		end

		local remotes = getRemotes()
		for i, remote in ipairs(remotes) do
			if startsWith(remote, text) then
				clink.add_match(remote)
				matchCount = matchCount + 1
			end
		end
	end

	return matchCount > 0
end

local handle = io.popen("git config --get-regex alias")
local result = handle:read("*a")
handle:close()

for alias in string.gmatch(result, "%.(%S+ %S+)") do
	if endsWith(alias, " branch") then
		table.insert(branchAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " checkout") then
		table.insert(checkoutAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " diff") then
		table.insert(diffAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " fetch") then
		table.insert(fetchAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " merge") then
		table.insert(mergeAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " pull") then
		table.insert(pullAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " push") then
		table.insert(pushAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " rebase") then
		table.insert(rebaseAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " reset") then
		table.insert(resetAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " show") then
		table.insert(showAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " show-branch") then
		table.insert(showBranchAliases, string.gmatch(alias, "%S+")())
	end
	if endsWith(alias, " switch") then
		table.insert(switchAliases, string.gmatch(alias, "%S+")())
	end
end

local aliases = {}

for alias in string.gmatch(result, "%.(%S+)") do
  table.insert(aliases, alias)
end

clink.arg.register_parser("git", aliases)
clink.register_match_generator(gitAutocomplete, 1)
```

I guess it came with the old 0.4.9 version of CLink. When deleting it, I get rid of the error. However, I need a new git-autocomplete then. Do you have any ideas?

**Comment by chrisant996** [comment]
@papstchaka It looks like git-autocomplete.lua is from the [git-autocomplete-for-windows](https://github.com/ztomm/git-autocomplete-for-windows) repo.

> I need a new git-autocomplete then. Do you have any ideas?

Yes, the one I mentioned earlier.  The [clink-completions](https://github.com/vladimir-kotikov/clink-completions) repo has completion scripts for many programs, including git.  Also, the git script there has a ton more functionality than the git-autocomplete.lua script.

Also, it looks like the backward compatibility for `clink.register_match_generator()` can probably be improved, and I'll look into that.
