### ISSUE TITLE
Maintain a list of useful lua scripts ?

### ISSUE THREAD

**Issue by skywind3000** [chrisant996/clink#396]
Clink is becoming super extensible now, is there a place to share or get user scripts now ?
Like a market-place or just a simple list in the wiki-pages / README.md.

And tell users in the documentation that they can submit their script links by creating a PR or issue.

For example, someone may already created a git completion script, it would be very helpful
if he can share it with others.

And maybe adding a new command if possible:

    clink fetch scriptname

It will clone the script repository in the pre-defined location, and load the script in the top-level directory of the repository.

And this will list available scripts in the list

    clink list

At this point, the user scripts can be maintained in a separated Github repository like `clink-scripts`, each script can be defined as a json file:

```json
{
    "name" : "Git completion script",
    "desc": "............",
    "repo": "https://github.com/xxx/xxx"
}
```

**Comment by chrisant996** [comment]
Links to the info that already exists:

https://chrisant996.github.io/clink/clink.html#sample-scripts

https://github.com/chrisant996/clink/discussions/categories/scripts

https://github.com/chrisant996/clink/issues/157

**Comment by skywind3000** [comment]
thanks

**Comment by chrisant996** [comment]
@skywind3000 this is slightly related to the original question:

The [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo now includes an [autopull.lua](https://github.com/chrisant996/clink-gizmos/commit/7773e8af25a37ac2d8a81e2b6ce12b54a581dc44) script.

The script has some configurable settings (via `clink set`).  When configured with a list of directories, it will automatically periodically run `git pull` in each of the directories.  This can be handy for updating repos that contain Lua scripts, or any other repos that the user wants to keep up-to-date.

If any errors occur during the `git pull`, it logs them in the clink.log file and reports them when the next prompt is displayed.
