### ISSUE TITLE
cls and ctrl+L  first line positions are not the same

### ISSUE THREAD

**Issue by wswind** [chrisant996/clink#398]
Hi. I use clink inject --quiet with windows terminal. My clink version is 1.4.6.8b1dec . 
When the terminal started , the first line position is the same with cls, you can see a blank line at the beginning.
![image](https://user-images.githubusercontent.com/18399096/210165401-cac70dde-ecbe-4901-beac-df4363265339.png)

But if you use ctrl+L to clear the screen, the blank line is missing.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/18399096/210165104-606f0787-7b0d-4a0c-ba52-dbacc32fe5d2.png">

It would be nice if the behavior of ctrl+L is the same with other operations.

**Comment by chrisant996** [comment]
`cls` is a shell command. The fact that CMD puts a blank line at the top after clearing the screen seems a bit strange to me, but it is what it is and has behaved that way for decades.

Ctrl-L is a feature of the Readline input library, and has behaved that way for decades. Altering the behavior of Readline features would make it inconsistent with Readline and the bash shell, which would tend to disappoint people used to bash, which is a lot of Clink users.

If you want Ctrl-L to behave differently, you could make a macro that does what you want, and bind it to Ctrl-L.

**Comment by wswind** [comment]
Forget about it if it influence too much.  I'm just a little confused about the inconsistent behavior. Thanks for the answer.

**Comment by wswind** [comment]
For others who want the same thing, config this way:
```
notepad %localappdata%\clink\.inputrc

"\C-l": cls
```

**Comment by chrisant996** [comment]
Here is an example script that makes <kbd>Ctrl</kbd>-<kbd>L</kbd> invoke the `cls` command:

### issue398_clear_screen.lua
```lua
function issue398_clear_screen(rl_buffer)
    rl.invokecommand("clink-reset-line")
    rl_buffer:insert(" cls")
    rl.invokecommand("accept-line")
end

rl.setbinding([["\C-l"]], [["luafunc:issue398_clear_screen"]])
```

**Comment by wswind** [comment]
> 

It's working .👍👍
Thanks 😀
