### ISSUE TITLE
Any way to disable microsofts header?

### ISSUE THREAD

**Issue by xFGhoul** [chrisant996/clink#399]
as we all know, every cmd terminal starts with microsofts header
```
Microsoft Windows [Version 10.0.19043.2006]
(c) Microsoft Corporation. All rights reserved.
```
Is there any way I can remove this?

**Comment by chrisant996** [comment]
A quick google search will find multiple ways.

**Comment by fvilers** [comment]
> Is there any way I can remove this?

You can start it using `cmd /K` to hide the copyright notice.
