### ISSUE TITLE
Clear and LS commands not working

### ISSUE THREAD

**Issue by langstonzac25** [chrisant996/clink#401]
I am using Version 1.4.7.524e49.  Only the clear and ls commands are not working the history command works and the completetoin works fine. This happens with the autostart and when i inject it into a cmd session. Not sure what the problem is.
![cmd_mx7m5tNsrQ](https://user-images.githubusercontent.com/101570030/211227884-c7e6a419-39d4-4d33-b0c4-f5f5c1127b5a.png)

Thanks in advance.

**Comment by garoto** [comment]
Clink isn't a bash emulator and/or Windows environment like msys2 or cygwin.

**Comment by chrisant996** [comment]
Clink is not a shell. It doesn't add new commands, and it doesn't turn Windows or CMD into Linux.

Clink injects into CMD and enables scripted prompt customization, scripted completions, and input line editing features.

CMD with Clink is still CMD, but with an enhanced prompt and enhanced input line editor.

If you're looking for a way to use Linux on Windows, consider using the Windows Subsystem for Linux feature of Windows 10 and higher, or using a third party collection of tools such as msys or cygwin.
