### ISSUE TITLE
Add a "--whatsnew" option

### ISSUE THREAD

**Issue by UweKeim** [chrisant996/clink#404]
Loving the `clink update` command ever since it came out, I would love to suggest another option:

```
clink --whatsnew
```

This would ideally print the text that is displayed in the release notes of that version version.

E.g. for version 1.4.9 it would print:

> - Improved the problematic character reporting in the clink-diagnostics command.
> - Fixed measurements for the East Asian ambiguous width characters (this should solve the Cmder problems with lambda in the CMD.exe prompt text, including the space after the lambda).

If this is too "expensive", a low-level solution could be to simple ShellExecute the URL to the release notes of the version.

E.g. for version 1.4.9 you could simply call the URL 

> https://github.com/chrisant996/clink/releases/tag/v1.4.9

With this new option, I could better see whether any new features or fixed were introduced in a new version. Currently I can only see that a new version was released but never bother to take the effort of manually searching and navigating to the GitHub releases page.

Another/additional behavior could be that after an update was installed with `clink update` to print the newest release notes automatically or at lease print the URL to the release notes in the console (still, the `--whatsnew` would be nice to have in addition).

**Comment by chrisant996** [comment]
When an update is available, Clink prints:

```
- To view the release notes, visit the Releases page:
  https://github.com/chrisant996/clink/releases
```

If you're using a terminal such as Windows Terminal or ConEmu that allow clicking on URLs on the screen, then you can already simply clink on the Clink URL that's on the screen.

So, I think you're asking for `clink update` to re-print the URL, in case the user ran `clink update` without having been told that an update was available.

**Comment by UweKeim** [comment]
Thanks, Chris, usually I do not see the update available messages at all. Having clink on approx. 20+ PCs/servers I never could figure out when the "update available" message is actually printed.

I would estimate that I saw this message in about 5% or less of the cases when an update was actually available.

Usually I log in and randomly enter `clink update` and be happily astonished if an update is available.

This is an excerpt from my today's update:

```cmd
C:\Users\ukeim>clink update
Checking latest version...
Downloading latest release v1.4.9...
Expanding zip file...
Updating registry keys...
Updated Clink to v1.4.9.

C:\Users\ukeim>
```

Here, I could imagine that after the line `Updated Clink to v1.4.9.` there is another line: `See https://github.com/chrisant996/clink/releases/tag/v1.4.9 for release notes`.

As you said, I could simply click that line in Terminal.

BTW: Notepad++ does something similar: After an update that next time it starts up, a text document with the release notes of the just installed version is opened automatically.

**Comment by chrisant996** [comment]
There is a setting that controls how often it checks for updates; refer to docs for details.

Probably in the cases where an update is available but Clink didn't tell you, it's because it's brand new and the last check was too recent to check again.

**Comment by chrisant996** [comment]
_After_ upgrading to Clink v1.4.10, then _subsequent_ updates will print the Release page URL after a successful update.

I don't think a `clink --whatsnew` is particularly beneficial, since it isn't very discoverable, and it's really just the same as having a bookmark to the Clink repo or the Clink Releases page.  But if the new behavior doesn't meet the need quite right, then please let me know how/why not.

**Comment by UweKeim** [comment]
Awesome, thank you very much, Chris!
