### ISSUE TITLE
vi-search (/) does not search in history - regression in 1.4.7

### ISSUE THREAD

**Issue by harig** [chrisant996/clink#405]
1. clink mode with vi keybindings/mode set as default input mode. 
2. / mapped  to vi-search, and n, N repeats that search (default)
3. If clink has some history entries, from vi-command mode, typing "/item<Enter>" searches for "item" in history, This can be repeated with n/N. (On pressing / the search prompt is shown, then you type "item" and press Enter)
4. In 1.4.7 doing the above does not search within history, it shows some random (?) unrelated match.

Works as mentioned above until 1.4.6 build. After that (in 1.4.7) I've to use Ctrl-R/S from any of the vi modes to search likewise.

**Comment by chrisant996** [comment]
I'll take a closer look in the morning, but I would expect that it works the same as bash now, and works how Readline is meant for it to work.

This is the change from the release notes:

- Enabled Readline's support for non-incremental vi-mode search (<kbd>N</kbd>, <kbd>n</kbd>) to search for a shell pattern using `fnmatch()`, as Posix specifies.

I'll double check whether somehow there's a bug in Readline.  All I did was tell the Readline library that the `fnmatch` function was available.  But maybe there's somehow a glitch in the `fnmatch` function.

**Comment by chrisant996** [comment]
Confirmed:

It turns out there are _**two**_ forms of `fnmatch()`, with the parameters in opposite orders.
Readline expects one order, and the fnmatch I used as reference uses the opposite order.

Swapping the order makes it work as expected.

Thanks for reporting this!

**Comment by harig** [comment]
Verified the fix in 1.4.10; thank you for the quick turnaround.
