### ISSUE TITLE
Unable to hook ReadConsoleW in kernelbase.dll

### ISSUE THREAD

**Issue by JayCroghan** [chrisant996/clink#408]
I get no history, no history command and this is the log output on latest Windows 11

 4440 do_inject                  185 System: ver=6.2 0.0 arch=9 cpus=16 cpu_type=8664 page_size=4096
 4440 do_inject                  190 Version: 0.4.9
 4440 do_inject                  191 DLL: C:\clink\0.4.9\clink_dll_x64.dll
 4440 do_inject                  193 Parent pid: 29740
 4440 check_dll_version           52 DLL version: 00000004 0009b2fe
 4440 do_inject_impl             283 Creating remote thread at 00007FF8D9D295D0 with parameter 0000016F5C600000
29740 set_rl_readline_name        58 Setting rl_readline_name to 'cmd.exe'
29740 hook_trap_veh              120 VEH hit - caller is 00007FF7F8E34A11.
29740 hook_jmp                   408 Attemping jump hook.
29740 hook_jmp                   409 Target is kernelbase.dll, ReadConsoleW @ 00007FF8D8A55550
29740 hook_jmp_impl              351 Attempting to hook at 00007FF8D8A55550 with 00007FF8BC0E63A0
29740 hook_jmp_impl              360 Unable to match instruction 245C8948
29740 hook_jmp                   415 Jump hook failed.
29740 apply_hook_jmp              73 Unable to hook ReadConsoleW in kernelbase.dll
29740 hook_trap_veh              125 Hook trap 00007FF8BC0E62D4 failed.

**Comment by chrisant996** [comment]
You're using the very old v0.4.9 from 6 years ago:

```
4440 do_inject 190 Version: 0.4.9
```

That version of Clink is from the mridgers repo, which has been abandoned for 6 years.

You're reported it in the new chrisant996 repo, which is actively maintained and is currently on v1.4.11.

If you upgrade to the version of Clink available in this repo's [Releases](https://github.com/chrisant996/clink/releases) page then it will be able to inject.

**Comment by chrisant996** [comment]
P.S.  v1.4.11 automatically migrates your old profile (settings and history) and should be compatible with your existing scripts.

(And if you happen to run into any problems upon upgrading, please open a new issue with the details, and I'll help get it working smoothly again.)

**Comment by JayCroghan** [comment]
Thank you so much. I had no config or history so nothing to migrate :)
