### ISSUE TITLE
how to switch through variations ?

### ISSUE THREAD

**Issue by tiddu** [chrisant996/clink#409]
suppose this is in history in uneven order

rclone config
start "" "abc""
rclone set
rclone abc
powershell abc
rclone xyz

i want to type rclone and then switch in between the variations like config , set , etc etc

how to do that?

**Comment by chrisant996** [comment]
Maybe you're looking for the `history-search-backward` and `history-search-forward` commands.

[Customizing key bindings](https://chrisant996.github.io/clink/clink.html#keybindings) in the docs is a good place to start teaching to learn how to customize key bindings and what commands are available.

You didn't say what keys you'd like to use, but if you'd like to use <kbd>Up</kbd> and <kbd>Down</kbd>, then the [Sample .inputrc file](https://chrisant996.github.io/clink/clink.html#sample-inputrc-file) includes an example of binding the commands to those keys.
