### ISSUE TITLE
No way to accept suggestion (as far as I know)

### ISSUE THREAD

**Issue by Fischchen** [chrisant996/clink#410]
As far as I found, there is no way to accept the suggestion (in gray) .
![image](https://user-images.githubusercontent.com/61012902/213927925-e6ddb368-3e33-46af-a6ea-cae568881d47.png)
When running the `complete` or `menu-complete` command, it just completes to a path or gives a list of paths in the current directory. 
![image](https://user-images.githubusercontent.com/61012902/213928015-00db3dae-7523-4e06-ae83-bf4649972375.png)
I've also not found anything about this in the docs. Is this an oversight, or have I missed something?

I'm running this in Windows Terminal and CMD.

**Comment by chrisant996** [comment]
@Fischchen you closed the issue, so maybe you already found the answer.

When searching for "accept" in the docs, the first match is in the section about how suggestions work:

https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest
