### ISSUE TITLE
CLINK_HISTORY_LABEL doesn't work since v1.3.18

### ISSUE THREAD

**Issue by unuunn** [chrisant996/clink#411]
Hi, I use the environment variable `CLINK_HISTORY_LABEL`
I set it after `clink inject`,
recently discovered that history is written to the shared file `clink_history`.
Rolling back, I found that the last working version was `v1.3.17`.

If you run the command, the `clink history` command, the history file is created, but the record still goes to the general `clink_history`
The `clink info` at this time shows the correct history file from the `CLINK_HISTORY_LABEL` variable.

I checked with my own settings and with the default, the behavior is the same.

Notes
If I set `CLINK_HISTORY_LABEL` before starting `clink inject` it works correctly.
`clink-reload` doesn't help
`clink history compact` and etc doesn't help

Steps to reproduce: 
```bat
clink.bat
SET CLINK_HISTORY_LABEL=abc123
echo some command for history
REM clink_history-abc123 still doesn't exist
clink history
REM clink_history-abc123 is created
echo some command for history
REM the record is stored in the clink_history
```

Windows 11 (10.0.22621.1105)

**Comment by chrisant996** [comment]
Thank you for reporting this, and especially thank you for the detailed analysis!

And DOH!

Commit 191807b089eb66a0ec4f7371dd7fc3895727936f broke it.  When I did a search and replace I didn't notice a side effect.  I use CLINK_HISTORY_LABEL, but I happen to set it before the first prompt, so the problem didn't manifest for me.

v1.4.13 will include a fix.
