### ISSUE TITLE
is there a way to use an interactive history list?

### ISSUE THREAD

**Issue by ina6ra** [chrisant996/clink#412]
Thanks for the great tool.
Interactive completion list doesn't work when I press `Ctrl+Space`.

Adding `clink-fzf` and then pressing `Ctrl+r` worked as expected.
- [chrisant996/clink-fzf: Fzf integration for Clink](https://github.com/chrisant996/clink-fzf)

![image](https://user-images.githubusercontent.com/48197/214726513-d129ac83-35b9-4ca9-8bcd-d423a3e135d3.png)

Please correct me if the two work the same.
I also added `fzf` to use `clink-fzf`, so I'd be happy if I didn't need two.

Environment
- OS: Windows 11 Pro Insider Preview 22H2 25276.1000
- clink Version: v1.4.13

**Comment by chrisant996** [comment]
Sorry, it's unclear what behavior you're expecting.  Can you clarify?

> Interactive completion list doesn't work when I press `Ctrl+Space`.

What happens instead?

What is desired to happen?
- Do you want it to invoke `fzf` completion?
- Do you want it to invoke the `clink-select-complete` command for Clink's built-in interactive completion?

When you press <kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>/</kbd> and then press <kbd>Ctrl</kbd>-<kbd>Space</kbd>, what command does it say is bound to <kbd>Ctrl</kbd>-<kbd>Space</kbd>?

> I also added `fzf` to use `clink-fzf`, so I'd be happy if I didn't need two.

What is meant by "I also added `fzf`"?  What does "`fzf`" there refer to?  Is it a repo?  Or a script?  Or a program?

If "`fzf`" means the `fzf.exe` program, then yeah `fzf` is a program, and to integrate it with a shell a script such as `clink-fzf` is needed.

**Comment by chrisant996** [comment]
> Adding `clink-fzf` and then pressing `Ctrl+r` worked as expected.

That's not "completion".  That's "history".

Are you trying to view an interactive history list?  If so, then try <kbd>F7</kbd>.

Also, these topics in the documentation may help answer some of the questions:
- [How Completion Works](https://chrisant996.github.io/clink/clink.html#how-completion-works)
- [Key Bindings](https://chrisant996.github.io/clink/clink.html#gettingstarted_keybindings)
- [Bindable Commands](https://chrisant996.github.io/clink/clink.html#bindable-commands)

**Comment by ina6ra** [comment]
Sorry for the lack of explanation.

What I'm hoping for is the behavior in the video below.
Press `Ctrl+Space` to start the history list and enter cd to filter from the list.
https://youtu.be/1a5NiMhqAR0?t=113

The operation of `F7` cannot narrow down the list, so it is an operation different from the purpose.

If clink's `Ctrl+Space` doesn't behave the same, no need to fix it.
My goal has been achieved using `clink-fzf`.

**Comment by chrisant996** [comment]
@ina6ra The video in the link is for using fzf for history.  It is not about "completion".

The <kbd>F7</kbd> key is bound to the `win-history-list` command, and its purpose is to behave like the built-in <kbd>F7</kbd> key in plain CMD windows.

If you want a history popup with incremental searching, bind a key to the `clink-popup-history` command.  For more info, start with [Key Bindings](https://chrisant996.github.io/clink/clink.html#gettingstarted_keybindings) and [Popup Windows](https://chrisant996.github.io/clink/clink.html#popupwindow) in the documentation.

**Comment by chrisant996** [comment]
(I've changed title to reflect that this was a question for help, not a bug report.)
