### ISSUE TITLE
the letter C not typing unless its in caps lock

### ISSUE THREAD

**Issue by NickTheHuy** [chrisant996/clink#416]
i need sometime to type the letter "c" but it just doesnt let me unless i make it uppercase or copy paste it from other source and its quite annoying

**Comment by chrisant996** [comment]
I've never heard of anything like that before.  I think you're saying <kbd>Shift</kbd> doesn't work for <kbd>C</kbd>, and only <kbd>CapsLock</kbd> works for <kbd>C</kbd>.  Clink relies on the OS for Shift and CapsLock handling.  

Can you share the following additional info to help me investigate?

- What code page is reported when you run `chcp`?
- Does it make a difference whether the Left or Right Shift key is held?
- Does it make a difference whether the on-screen software keyboard is used?
- What is the current language configured in Windows? (Windows Settings > Time & Language > Language > Windows Display)
- What is keyboard layout is selected in Windows (Windows Settings > Time & Language > Language > Keyboard)
- What terminal program is being used?  Is <kbd>Shift</kbd>-<kbd>C</kbd> bound to something else, or has it been unbound?

Also, try this, which will show what the OS is giving to Clink about the input keypresses:
1. Run `clink echo --verbose`.
2. Type <kbd>Shift</kbd>-<kbd>C</kbd>.  What is printed about the keypress?
3. Type <kbd>CapsLock</kbd> then <kbd>c</kbd>.  What is printed about the keypress?

**Comment by NickTheHuy** [comment]
shift and C works i meant that i cant type the letter c now in the cmd because of clink.

**Comment by chrisant996** [comment]
> shift and C works i meant that i cant type the letter c now in the cmd because of clink. 

Oh, ok, thanks for correcting my understanding. I need all the same information I mentioned previously.  Except press `c` instead of `Shift-c`.

**Comment by NickTheHuy** [comment]
chcp:
Active code page: 862
it doesnt make a difference whether the Left or Right Shift key is held
i dont have an on-screen software keyboard 
language is english US
Keyboard layout is same
terminal is only windows cmd and clink

**Comment by chrisant996** [comment]
@NickTheHuy Also, try this, which will show what the OS is giving to Clink about the input keypresses:
1. Run `clink echo --verbose`.
2. Type <kbd>c</kbd>.  What is printed about the keypress?
3. Type <kbd>CapsLock</kbd> then <kbd>Shift-c</kbd>.  What is printed about the keypress?

**Comment by NickTheHuy** [comment]
2:
key event:  ___ __  flags=0x00000020  char=0x0063  vk=0x0043  scan=0x002e  "C"
"c"
3:
shift-c gives key event:  S__ __  flags=0x00000030  char=0x0043  vk=0x0043  scan=0x002e  "C"
"C"
CapsLock gives key event:  ___ __  flags=0x000000a0  char=0x0043  vk=0x0043  scan=0x002e  "C"
"C"


alt shit / and c gives c : key is not bound

**Comment by chrisant996** [comment]
> alt shit / and c gives c : key is not bound

Aha!  Something has unbound the `c` key.
Normally it is bound to `self-insert`.

Can you share your `.inputrc` file?
There may be a mistake in a custom key binding in it.

**Comment by NickTheHuy** [comment]
where can i get the .inputrc?

**Comment by chrisant996** [comment]
> where can i get the .inputrc?

@NickTheHuy run `clink info` to find the location.

**Comment by NickTheHuy** [comment]
# Some common Readline config settings.

set colored-stats                 on   # Turn on completion colors.
set colored-completion-prefix     on   # Color the typed completion prefix.

# Some config settings that only work in Clink.

$if clink
set search-ignore-case            on   # Case insensitive history searches.
set completion-auto-query-items   on   # Prompt before showing completions if they'll exceed half the screen.
$endif

clink set clink.default_bindings windows




this?

**Comment by chrisant996** [comment]
@NickTheHuy that is the right kind of file. But it doesn't contain any key bindings, so that makes me wonder whether it's the right file.

Something has set one or more key bindings, and at least one of them has been done incorrectly, which is why the `c` key isn't working.

We need to find what is changing the key bindings.

Can you share the output from `clink info`?

Also, what Lua scripts do you have installed?  It's possible that a Lua script could be changing key bindings.

**Comment by NickTheHuy** [comment]
C:\Users\nikur>clink info
version          : 1.4.15.439299
session          : 8544
binaries         : C:\Program Files (x86)\clink
state            : C:\Users\nikur\AppData\Local\clink
log              : C:\Users\nikur\AppData\Local\clink\clink.log
default settings : C:\Program Files (x86)\clink\default_settings
settings         : C:\Users\nikur\AppData\Local\clink\clink_settings
history          : C:\Users\nikur\AppData\Local\clink\clink_history
scripts          : C:\Program Files (x86)\clink ; C:\Users\nikur\AppData\Local\clink
default_inputrc  : C:\Program Files (x86)\clink\default_inputrc
inputrc          : %clink_inputrc%
                     (unset)
                 : state directory
                     C:\Users\nikur\AppData\Local\clink\.inputrc
                     C:\Users\nikur\AppData\Local\clink\_inputrc
                 : %userprofile%
                     C:\Users\nikur\.inputrc   (LOAD)
                     C:\Users\nikur\_inputrc
                 : %localappdata%
                     C:\Users\nikur\AppData\Local\.inputrc
                     C:\Users\nikur\AppData\Local\_inputrc
                 : %appdata%
                     C:\Users\nikur\AppData\Roaming\.inputrc
                     C:\Users\nikur\AppData\Roaming\_inputrc
                 : %home%
                     C:\Users\nikur\.inputrc   (exists)
                     C:\Users\nikur\_inputrc

**Comment by NickTheHuy** [comment]
omg idk why but when i installed clink it didnt give me full inputrc but now i just copy pasted the readline/readline/examples/Inputrc from your repo to the inputrc and it worked

**Comment by chrisant996** [comment]
The .inputrc file is not something that's installed.

It's something you create, to customize Clink or bash or other programs that use the Readline library.

At some time, you must have created a .inputrc file, and set some key bindings in it, and one of more of the key bindings was written incorrectly.

You don't need a .inputrc file unless you want to customize certain things.

By overwriting the .inputrc file that had existed, now there's no way to do further troubleshooting to find out what had been wrong.

I'm glad you got it working, though.

**Comment by nurpax** [comment]
I don't know what it is about my .inputrc, but I'm on a copy&pasted .inputrc too and hit this exact same problem with click on Windows 10.  It worked around it by adding

```
# WARA for https://github.com/chrisant996/clink/issues/416
"c": self-insert
```

at the end of my .inputrc.  I don't understand how "c" might get unbound but unbound it is if I don't do the above:

```
C:\Users\nurpax>  # hitting shift-alt-/
c : key is not bound
```

**Comment by chrisant996** [comment]
@nurpax That's very interesting.  Can you share the contents of your .inputrc file that correspond with the problem occurring?

**Comment by nurpax** [comment]
Sure, it's basically the default:

```
# Some common Readline config settings.

set colored-stats                 on   # Turn on completion colors.
set colored-completion-prefix     on   # Color the typed completion prefix.

# Some config settings that only work in Clink.

$if clink
set search-ignore-case            on   # Case insensitive history searches.
set completion-auto-query-items   on   # Prompt before showing completions if they'll exceed half the screen.
$endif

clink set clink.default_bindings bash

# WAR for https://github.com/chrisant996/clink/issues/416
"c":  self-insert
```

If I leave the last line out, 'c' doesn't work.  It's really funny.

I wonder if there's some weird version conflict.  I did first install Clink for ConEmu like in their instructions.  I then uninstalled ConEmu completely and installed Clink using the standard Windows installer.

**Comment by chrisant996** [comment]
Where did this line come from?
It's the mistake.

```
clink set clink.default_bindings bash
```

That is something to type as a command line at the CMD shell prompt.

It has nothing to do with .inputrc files.
It doesn't belong in a .inputrc file, just like `mkdir foo` or `doskey wh=where $*` or `start MyDocument.docx` wouldn't belong in an .inputrc file.

In .inputrc file syntax ([Readline Key Bindings](https://chrisant996.github.io/clink/clink.html#readline-key-bindings)), any line that doesn't start with `set` is interpreted as a key binding directive.

Since the line has no `:`, it will **unbind** a key.
Since `clink set clink.default_bindings bash` is not the name of a key, the Readline library tries its best to interpret the nonsensical input, and it uses the first letter as the name of the intended key to unbind, so `c`.

So, the line instructs the Readline library to unbind `c`.
The same thing will happen in `bash` in Linux if you add a line like that to .inputrc.

(Or `caksdjhglkashdgluhasdfgiluh` will have the same effect, or even just `c`.)

**Comment by nurpax** [comment]
I added it as I wanted to try this option. It didn’t occur to me that it was wrong as there was no error message. 

What’d be the right way to configure this option for clink? Where should I save this?

**Comment by chrisant996** [comment]
It's a command. Run it. That means type it at the command prompt.
