### ISSUE TITLE
Preview the whole line expanded instead of individual expansions at cursor

### ISSUE THREAD

**Issue by Destroy666x** [chrisant996/clink#420]
Would be nice to have a command or something to check the whole line expanded before sending/expanding it to make sure it's fully correct, in case it refers to a long line (which currently are shortened with `...` to fit single line below) or few expansions like `!-1 & !-2 & !-3 & !-4`.

I don't know what the best way of showing the preview would be considering it can be long, but I guess something similar to long completion list with scrollable `--More?--` would fit.

**Comment by chrisant996** [comment]
@Destroy666x there are many commands for that listed in the [Clink Commands](https://chrisant996.github.io/clink/clink.html#clink-commands) section under the [Bindable Commands](https://chrisant996.github.io/clink/clink.html#bindable-commands) topic. Look for the command names that begin with "clink-expand-".

I'll add a mention of a couple of the expansion commands in the [Using History Expansion](https://chrisant996.github.io/clink/clink.html#using-history-expansion) section.

**Comment by chrisant996** [comment]
Added mention in the docs in commit 1312bc1f19bc06654654aa8c161fb79c06566d63.

**Comment by Destroy666x** [comment]
Ah, I am aware of these and they were reasonably findable in the documentation compared to some other things, but for some reason I thought Ctrl + Z isn't working well for them. I recall trying it with few commands and it not working, but I tried it again now and it's fine and easy enough indeed. So I'll close it until the issue shows up again, if it was a clink issue in the 1st place as I was also configuring e.g. ConEmu at that time.
