### ISSUE TITLE
Bash-style autocomplete not working in Windows 11

### ISSUE THREAD

**Issue by ekraihan** [chrisant996/clink#433]
I have been using the old mridgers clink on Windows 10 and it has been working well. I recently updated to Windows 11 and suddenly the bash-style tab completion stopped working. I tried upgrading to this project's clink, but I am still getting the Windows "one at a time" tab completion. Is this a known issue?

Thanks!

**Comment by chrisant996** [comment]
I think you probably installed using the setup .exe, and you probably didn't uncheck the "Use enhanced defaults" box.

I think your question is the first thing the [Getting Started](https://chrisant996.github.io/clink/clink.html#getting-started) section of the documentation explains.

**Comment by ekraihan** [comment]
I think that answers my question! I re-installed without the advanced options and I get the default bash behavior. Thanks for pointing out the docs. Closing.
