### ISSUE TITLE
Request: clink update command writes full version string to registry to stop confusing WinGet

### ISSUE THREAD

**Issue by CrushBug** [chrisant996/clink#434]
I would like to request that the command line update for clink write the full version to the registry, instead of just the first 3 values of the version number. If I install clink from the installer it is written correctly, but if I just update via the command line, WinGet is confused and states that an update is available. Here is what I see:
```
Name            Id                  Version   Available
Clink v1.4.20   chrisant996.Clink   1.4.20    1.4.20.236aba
```
I have confirmed that this WinGet update message line goes away if I manually edit the "DisplayVersion" entry in the Uninstall entry and change it from "1.4.20" to "1.4.20.236aba".

Not a high priority item, just something that would be nice to have.

**Comment by chrisant996** [comment]
Who owns/created the Winget package for Clink?  It wasn't me.

I would think the package regex needs to be defined to be more accurate. Other package managers support that.

**Comment by CrushBug** [comment]
Understood, and until you said, I had just assumed that you had created the package info for WinGet. Thanks for clearing that up. I will do some more digging and see what I can find.

**Comment by CrushBug** [comment]
I have found the author of the package entry for Clink and have commented on his last commit as to the nature of the issue.

WinGet package manifest URL for your reference:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/chrisant996/Clink

**Comment by chrisant996** [comment]
> I have found the author of the package entry for Clink and have commented on his last commit as to the nature of the issue.
> 
> WinGet package manifest URL for your reference:
> https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/chrisant996/Clink

Isn't that an auto generated manifest? Did you find a human owner?

**Comment by chrisant996** [comment]
Also, [this is the most recent commit](https://github.com/microsoft/winget-pkgs/commit/8fbf7df32436185d953ef14a6ad767674cae4aa6), for v1.4.20.
I don't see a comment from you attached to that commit.
Am I looking at the wrong commit?  Have you not published the comment yet?

**Comment by CrushBug** [comment]
I might have commented on the wrong item. I guess I had placed it on the pull request? I might have just gotten my many tabs open, confused as to where I was typing.

https://github.com/microsoft/winget-pkgs/pull/97870

This was the person listed, Vedant - vedantmgoyal2009 - https://github.com/vedantmgoyal2009 - so I am just assuming by the profile that it is a real person.

**Comment by chrisant996** [comment]
The commit has `[bot]` appended to the email address.

But I found a typo in the v1.4.18 manifest, so now I'm not sure it's really being auto-generated.

And weirdly, the v1.4.18 manifest got the version number right (no trailing commit hash).

So I now wonder if someone's been manually writing updates, and doing it incorrectly/inconsistently?

**Comment by pukkandan** [comment]
winget PRs are merged by the bot, which is why it is the committer. It does appear vedantmgoyal2009 is the one who is maintaining the package, using [an automation script](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/f587e9fe4da57ee32518b99655a284d052555562/winget-pkgs-automation). And, like you suspected, they are getting the version [from the download URL](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/f587e9fe4da57ee32518b99655a284d052555562/winget-pkgs-automation) and not the tag

FYI, here's OP's comment on the PR - https://github.com/microsoft/winget-pkgs/pull/97870#issuecomment-1447438300
