### ISSUE TITLE
Path tab-complete doesn't work with switches

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#44]
In vanilla CMD, tab completion for path works even after typing a switch, like here `cd /d C:\Users\abc`, where 'abc' gets completed to 'abcdef' on pressing TAB. 

But when Clink has been injected, TAB doesn't do anything. 

Is there a setting that needs to be configured for this?

**Comment by chrisant996** [comment]
`cd`, `chdir`, `rd`, `rmdir` all have the same problem.  They accept only one argument, so they don't do completion after the first argument.  But their argmatchers didn't include the available flags, so the flags were interpreted as arguments.
