### ISSUE TITLE
Unexpected tab completion fills

### ISSUE THREAD

**Issue by tilkinsc** [chrisant996/clink#440]
Hello,

When I type
```
clink u
```
I see
```
clink update
```

However, when I press tab I get
```
clink uninstallscripts
```

I know pressing right arrow key will fill it correctly, but this is very odd to do.

**Comment by chrisant996** [comment]
> When I type
> 
> ```
> clink u
> ```
> 
> I see
> 
> ```
> clink update
> ```

The `pdate` part should be shown in a dimmed color.
Is the `pdate` part showing up in the same color as the `u` part??

It is the [Auto-suggest](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) feature.
It is not related to TAB completion.

Refer to [Getting Started](https://chrisant996.github.io/clink/clink.html#getting-started) and [Enhanced default settings](https://chrisant996.github.io/clink/clink.html#gettingstarted_enhanceddefaults) for more information.

> However, when I press tab I get
> 
> ```
> clink uninstallscripts
> ```

That is the completion feature.  You're already familiar with it, but for more info you can refer to [How Completion Works](https://chrisant996.github.io/clink/clink.html#how-completion-works).

> I know pressing right arrow key will fill it correctly, but this is very odd to do.

They're two very different features.  The documentations links above explain the features.  The Getting Started section can be very helpful when starting out.

**Comment by tilkinsc** [comment]
Hey thanks for the fast reply.

Yeah, I am very aware of the nature of the situation. Being a linux user, I have experience with terminals autofilling the parameter dimmed. 

Thanks for the offered documentation.

```
autosuggest.strategy=completion
```

Would this mimic the behavior of pressing tab to complete whats shown?

**Comment by chrisant996** [comment]
I'm not sure I have enough info to answer the question.

What behavior do you want?

- TAB cycles through possible completions, and auto-suggest does nothing except show the first match that would be completed?
- TAB does bash/zsh style completion, and auto-suggest shows the first match -- but TAB might insert none/some/all of it depending on the longest common prefix of the available matches?
- Something else?

Setting the strategy to `completion` pulls a suggestion from the first available match.  Depending on your key bindings, the overall behavior will be one of the first two listed above.

RIGHT and TAB are intended to do two different things. It's possible to configure them to do almost the same thing. To me, that seems less useful, but it's configurable so it can be tailored to meet different users' needs and preferences.

(To clarify terminology: Terminals just forward input to programs and display textual output from programs. Shells are responsible for completion and auto-suggestions and input line editing and history and running scripts and so on.)
