### ISSUE TITLE
Does installscripts search subdirectories?

### ISSUE THREAD

**Issue by HeyItsJono** [chrisant996/clink#444]
I just have a quick question RE: `clink installscripts`, I was hoping to find out if this automatically searches subdirectories of the specified directory.

For example, if I run `clink installscripts %APPDATA%/Cmder/config`, where `config` has .lua scripts in it, but also a subfolder `clink-gizmos` with scripts in it, will I need to separately run `clink installscripts %APPDATA%/Cmder/config/clink-gizmos`, or would doing this mean that the scripts in `clink-gizmos` are parsed twice?

**Comment by chrisant996** [comment]
No. It loads scripts from the listed directories. 

If it recursed that would break things and run scripts at load time that shouldn't be run, such as modules\ and completions\ scripts.

**Comment by HeyItsJono** [comment]
Thanks, this is odd, as I currently have a situation where `Cmder/vendor/clink-completions` is being loaded, however it does not exist in my installed clink scripts. `Ctrl+X``Ctrl+Z` shows:

    USER\AppData\Roaming\Cmder\vendor
    USER\AppData\Roaming\Cmder\vendor\clink
    USER\AppData\Roaming\Cmder\config
    USER\AppData\Roaming\Cmder\config\clink-gizmos

But `USER\AppData\Roaming\Cmder\vendor\clink-completions` is also being loaded.
