### ISSUE TITLE
Completions not working

### ISSUE THREAD

**Issue by eggbean** [chrisant996/clink#445]
Hi. I cannot get tab completion working. I have added this to `clink_start.cmd`:

    set CLINK_PATH=%USERPROFILE%\winfiles\Settings\clink-path
    set CLINK_COMPLETIONS_DIR=%USERPROFILE%\winfiles\Settings\clink-completions

I have cloned [clink-completions](https://github.com/vladimir-kotikov/clink-completions) in `%CLINK_COMPLETIONS_DIR%`, but when I, for example, type `git` for the first time, I get this error:

```
C:\Users\jason>git status
loading completion script failed:
C:\Users\jason\winfiles\Settings\clink-completions\git.lua:3: module 'path' not found:
        no field package.preload['path']
        no file 'C:\WINDOWS\System32\lua\path.lua'
        no file 'C:\WINDOWS\System32\lua\path\init.lua'
        no file 'C:\WINDOWS\System32\path.lua'
        no file 'C:\WINDOWS\System32\path\init.lua'
        no file '.\path.lua'
        no file 'C:\WINDOWS\System32\path.dll'
        no file 'C:\WINDOWS\System32\loadall.dll'
        no file '.\path.dll'
stack traceback:
        [C]: in function 'require'
        C:\Users\jason\winfiles\Settings\clink-completions\git.lua:3: in main chunk
        [C]: in function 'dofile'
        {arguments.lua}: in function <{arguments.lua}:2013>
        [C]: in function 'xpcall'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function 'classify'
        {classifier.lua}: in function <{classifier.lua}:63>
        [C]: in function 'xpcall'
        {classifier.lua}: in function <{classifier.lua}:62>
               git
loading completion script failed:
C:\Users\jason\winfiles\Settings\clink-completions\git.lua:3: module 'path' not found:
        no field package.preload['path']
        no file 'C:\WINDOWS\System32\lua\path.lua'
        no file 'C:\WINDOWS\System32\lua\path\init.lua'
        no file 'C:\WINDOWS\System32\path.lua'
        no file 'C:\WINDOWS\System32\path\init.lua'
        no file '.\path.lua'
        no file 'C:\WINDOWS\System32\path.dll'
        no file 'C:\WINDOWS\System32\loadall.dll'
        no file '.\path.dll'
stack traceback:
        [C]: in function 'require'
        C:\Users\jason\winfiles\Settings\clink-completions\git.lua:3: in main chunk
        [C]: in function 'dofile'
        {arguments.lua}: in function <{arguments.lua}:2013>
        [C]: in function 'xpcall'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function 'classify'
        {classifier.lua}: in function <{classifier.lua}:63>
        [C]: in function 'xpcall'
        {classifier.lua}: in function <{classifier.lua}:62>
```

I have also added [clink-zoxide](https://github.com/shunsambongi/clink-zoxide) to `%CLINK_PATH%` but [that isn't working properly either](https://github.com/shunsambongi/clink-zoxide/issues/5#issue-1636608790). I am not sure if that is related.

**Comment by chrisant996** [comment]
I can reply more later, but how did you decide to configure it that way?
That's not how those work, and it's not how the directions say to do it.
I recommend reviewing the directions again, and the documentation of those environment variables.

**Comment by eggbean** [comment]
To answer your question, I was just adding to what I have been doing for years. I have set these other environment variables in the same way in `clink_start.cmd`.

```
set GIT_SSH=%USERPROFILE%\winfiles\bin\plink.exe
set GH_BROWSER="C:\\Program\ Files\\qutebrowser\\qutebrowser.exe"
set LESSHISTFILE=%APPDATA%\_lesshst
set PATH=C:\Program Files\Vim\vim90;C:\Program Files (x86)\GnuPG\bin;%USERPROFILE%\scoop\shims;%USERPROFILE%\winfiles\bin;%USERPROFILE%\winfiles\scripts;C:\Program Files\GitHub CLI;%PATH%
set EDITOR=vim
set LS_COLORS=no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40 ..........
```

Because all these work fine I just assumed that it would work too. Is this wrong for these variables? I'll have another look at the instructions.

**Comment by chrisant996** [comment]
In particular look at docs for the completion dir environment variable.
It's not for pointing at the clink-completions repo.

That repo contains normal scripts that have to run when loaded. Not deferred to when commands are typed. It also contains a completions\ directory, which does get deferred. But all script directories automatically look for deferred scripts under a completions\ subdirectory.

It's why you're getting the errors.

**Comment by chrisant996** [comment]
You could put this in a clink_start.cmd file:
```cmd
set CLINK_PATH=~\winfiles\Settings\clink-path;~\winfiles\Settings\clink-completions
```

The doc section about %CLINK_COMPLETIONS_DIR% has a "Note:" section that specifically says it's not for use with the clink-completions repo, and explains why not.

I don't know anything about zoxide.
