### ISSUE TITLE
Enable previous tab completion behaviour (wait on clarification instead of cycling through choices)

### ISSUE THREAD

**Issue by RexBarker** [chrisant996/clink#449]
In the previous verion of clink (0.4.9), the tab completion stopped at last common character in directory until next clarification.  Now it seems to cycle through the commands like the default windows cmd shell.  Honestly, I preferred the older method where it waits for clarification.  I believe this was more bash-like.  **Is there way to enable this older behaviour?**  Example below:

```
C:\user\me\dir
Tom
Tom_and_Jerry
Tom_and_Jerry_and_Rufus
```

Typing 'T -> Tab" would give the prompt `Tom`. Completion would be by typing the next variant `_`, and then Tab completes to next part with `Tom_and_Jerry`

(I understand this may have been an unintended feature by looking at the current documentation)

**Comment by chrisant996** [comment]
Please see the Getting Started section of the documentation. This is covered there.
