### ISSUE TITLE
How can I cycle through matching command lines in the command history?

### ISSUE THREAD

**Issue by ivanabovin** [chrisant996/clink#450]
Thanks for your great extension!

Do you have any plans to add the ability to switch between multiple possible suggestions?
Like `Tab` key when autocompleting a file or folder name.

**Comment by chrisant996** [comment]
Please describe more about what you have in mind.

**Comment by ivanabovin** [comment]
Hi Chris, I mean Clink shows one suggestion only. And there is no any keyboard shortcut or possibility to choose another one.

Of course I can press `Ctrl`+`R` and search in history. But it is not convenient.

**Comment by chrisant996** [comment]
I understood that.  But what do you have in mind for
- how it should come up with a list of suggestions to choose from
- how many to come up with (they can be expensive to come up with, and turning it into a list will create a lot of complexity and confusion)
- how you expect to choose from them
- etc

That's not how they're meant to work.  See [Auto-suggest](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest).

I will try to predict what you're really trying to get at:
- I think you really mean you want _history_ suggestions, specifically, not suggestions in general (there are many sources/criteria for suggestions, and it's configurable, and it isn't limited to history).
- I think you want a way to cycle through previous/next history entries that match what you've typed so far (auto-suggest can show the first match, when it decides that history is the best source from which to offer a suggestion).
- I think you might be looking for `PgUp` / `PgDn`.

**Comment by ivanabovin** [comment]
Thanks Chris. `PgUp` and `PgDn` is exactly what I was looking for. 🤩
