### ISSUE TITLE
Ctrl + D functionality missing

### ISSUE THREAD

**Issue by Alex313031** [chrisant996/clink#455]
Hi, I have used mr ridgers original one for a long time, and recently I have used your fork. It is fantastic and builds on his work well, especially colors and autocomplete.

However, there is one feature missing in yours that his had, ` Ctrl + D` to close cmd functionality, similar to most linux terminal software. I really liked this because part of my workflow for https://github.com/Alex313031/thorium involves opening and closing alot of cmd windows.

Is there a setting to restore this behaviour, or could you re-add it. If you are not willing to re-add it, do you know *how* one would re-add it, so I can fork yours and make my own builds.

**Comment by garoto** [comment]
```
> clink set cmd.ctrld_exits
        Name: cmd.ctrld_exits
 Description: Pressing Ctrl-D exits session
       Value: False

Ctrl-D exits cmd.exe when used on an empty line.

> clink set cmd.ctrld_exits 1
Setting 'cmd.ctrld_exits' set to 'True'
```

**Comment by Alex313031** [comment]
@garoto nice thank you

**Comment by chrisant996** [comment]
I recommend reading the "Getting Started" section of the documentation.  Even though you've used the old v0.4.9, the current version starts from a complete rewrite by Martin, followed by further enhancements and fixes by myself.  A lot is similar or the same, and a lot has changed.

In particular, the [Common Configuration](https://chrisant996.github.io/clink/clink.html#common-configuration) describes the differences in the "Use enhancements defaults" installation option, which you installed with.  One of the differences is that <kbd>Ctrl</kbd>-<kbd>D</kbd> doesn't default to exiting cmd anymore.  The docs say how to turn that on again.
