### ISSUE TITLE
ERROR: Clink initilization has failed with error code: 0

### ISSUE THREAD

**Issue by JackieZheng** [chrisant996/clink#456]

**Comment by chrisant996** [comment]
You need to share (a lot) more context and information.

**Comment by chrisant996** [comment]
Also, are you using Cmder? If so, the error is actually a known bug in _Cmder_, NOT a problem with Clink.

**Comment by chrisant996** [comment]
Closing since insufficient information is provided, and it looks like a duplicate of a Cmder issue and is not a Clink problem at all.
