### ISSUE TITLE
FinalTerm escape sequences are stripped from prompt filter

### ISSUE THREAD

**Issue by krzysdz** [chrisant996/clink#457]
I'm trying to add shell integration using FinalTerm [escape sequences](https://github.com/gnachman/iterm2-website/blob/master/source/_includes/3.4/documentation-escape-codes.md#shell-integrationfinalterm) following the `OSC 133 ; <something> ST` format, but all these sequences from filter are removed before printing to the terminal.

[`ecma48_code::decode_osc`](https://github.com/chrisant996/clink/blob/17b5a3eeca3cffc258a50e883d13736407547d1f/clink/terminal/src/ecma48_iter.cpp#L129) decodes these sequences as `{ .command = '1', .subcommand = '0', .visible = false }` and all `!visible` OSC codes with the `command` property between 0 and 2 (inclusive) are treated as set console title commands and skipped from the output:
https://github.com/chrisant996/clink/blob/17b5a3eeca3cffc258a50e883d13736407547d1f/clink/terminal/src/ecma48_iter.cpp#L560-L571

A simple example that demonstrates the problem:

```lua
local p = clink.promptfilter(10)
function p:filter(prompt)
    -- OSC 133 sequences from prompt filter are removed before writing to the terminal
    return "\001\x1b]133;D;"..os.geterrorlevel().."\007\002\001\x1b]133;A\007\002"..prompt.." \001\x1b]133;B\007\002"
end

local function command_executed_mark(input)
    -- this works
    clink.print("\001\x1b]133;C\007\002", NONL)
end

clink.onendedit(command_executed_mark)
```

**Comment by chrisant996** [comment]
If they're stripped, then it means Clink doesn't recognize the terminal program, and was forced to fall back to its own built-in terminal emulator.

See the [`terminal.emulation`](https://chrisant996.github.io/clink/clink.html#terminal_emulation) setting.

**Comment by krzysdz** [comment]
I was testing it with Windows Terminal Dev (microsoft/terminal@48eee4d75aef934e97f7831cbcc3335de35c5279, build from [CI](https://dev.azure.com/ms/terminal/_build/results?buildId=457280&view=artifacts&pathAsName=false&type=publishedArtifacts)) with `terminal.emulation = native` and now tested with `emulate` too, but it didn't change anything.

**Comment by chrisant996** [comment]
**I see, yes.  I'll change how it parses OSC codes so it doesn't assume a single digit anymore.**

Also, the sample Lua script has problems -- it is important to remove the `\001` and `\002` sequences from the Lua script:
1. Clink automatically adds `\001` and `\002` characters where needed for the Readline library.  If you manually add them as well, then you're doubling them up as `\001\001` and `\002\002`, and the Readline library can get confused about the width of the prompt and whether/where it wraps to a new line, which can cause garbled output while typing input at the command promtp.
2. In the `clink.print()` case they are literally printed to the terminal (the Readline library is not involved, so they go straight to the terminal without being stripped).

The `\001` and `\002` stuff is specific to Readline, and not to anything else.  Clink automatically handles adding them; you shouldn't add them yourself.

**Comment by krzysdz** [comment]
Thank you and thanks for the remarks regarding `\001` and `\002`!

**Comment by chrisant996** [comment]
It was simpler than I anticipated:  unrecognized OSC codes were accidentally reported as though they were recognized.  But the code that tried to handled recognized OSC codes didn't know what to do with them, so they got accidentally stripped.  The fix is simply to accurately report whether OSC codes are recognized.
