### ISSUE TITLE
Typing ".." in subdirectory of root doesn't work

### ISSUE THREAD

**Issue by rmccampbell** [chrisant996/clink#46]
The `..` shortcut results in an error `'..' is not recognized as an internal or external command, operable program or batch file` in `C:\` or any directory directly below, such as `C:\Users` or `C:\Program Files`. It does work with a trailing slash `..\` however, and more dots like `...` does work. In all deeper directories `..` works without a slash.

**Comment by chrisant996** [comment]
Drat.  Thanks for reporting it!
