### ISSUE TITLE
Clink requires inject and autorun install frequently

### ISSUE THREAD

**Issue by anmsh** [chrisant996/clink#468]
I have clink and clink-completions installed with scoop. I am happy so far. I use Windows Terminal and have set it to be the default terminal.

Off late, I am needing to do "clink inject" manually every few days. I get the following message when Windows Terminal opens.

```cmd
Microsoft Windows [Version 10.0.19045.3086]
(c) Microsoft Corporation. All rights reserved.
The system cannot find the path specified.

C:\Users\anmsh>
```
I figured that clink wasn't loaded when Ctrl-L and Ctrl-D did not work. If I do a `clink inject`, it fixes the problem for a few days. I also do `clink autorun install` along with the `inject`.

Version information for both clink and clink-completion:

```cmd
C:\Users\anmsh>scoop info clink

Name        : clink
Description : Powerful Bash-style command line editing for cmd.exe
Version     : 1.4.28
Bucket      : main
Website     : https://chrisant996.github.io/clink
License     : GPL-3.0-only
Updated at  : 19-06-2023 06:03:26
Updated by  : github-actions[bot]
Installed   : 1.4.28
Binaries    : clink.bat
Notes       : Run 'clink inject' to start clink on the current cmd
              Run 'clink autorun install' to auto start clink

C:\Users\anmsh>scoop info clink-completions

Name        : clink-completions
Description : Completions for various commands through Clink
Version     : 0.4.8
Bucket      : main
Website     : https://github.com/vladimir-kotikov/clink-completions
License     : MIT
Updated at  : 16-05-2023 01:56:03
Updated by  : github-actions[bot]
Installed   : 0.4.8
Suggestions : clink
```

**Comment by anmsh** [comment]
Just checked and the same thing happens on a regular cmd prompt as well.

**Comment by chrisant996** [comment]
It looks like something is wrong with paths on your machine.

It sounds like it's a problem external to clink, which prevents clink from being found by the operating system.

Please share the full output from these commands, which will show how clink is configured.
- `clink info`
- `clink autorun show`

Also, it might be a scoop problem, where scoop isn't found by the operating system.

**Comment by anmsh** [comment]
I can run scoop and associated commands just fine when this occurs. Output for both `info` and `autorun show` commands:

```
C:\Users\anmsh>clink info
version  : 1.4.28.b0080b
session  : 11064
binaries : C:\Users\anmsh\scoop\apps\clink\1.4.28
state    : C:\Users\anmsh\AppData\Local\clink
log      : C:\Users\anmsh\AppData\Local\clink\clink.log
settings : C:\Users\anmsh\AppData\Local\clink\clink_settings
history  : C:\Users\anmsh\AppData\Local\clink\clink_history
scripts  : C:\Users\anmsh\scoop\apps\clink\1.4.28 ; C:\Users\anmsh\AppData\Local\clink ; C:\Users\anmsh\scoop\apps\clink-completions\0.4.8
inputrc  : %clink_inputrc%
             (unset)
         : state directory
             C:\Users\anmsh\AppData\Local\clink\.inputrc
             C:\Users\anmsh\AppData\Local\clink\_inputrc
         : %userprofile%
             C:\Users\anmsh\.inputrc
             C:\Users\anmsh\_inputrc
         : %localappdata%
             C:\Users\anmsh\AppData\Local\.inputrc
             C:\Users\anmsh\AppData\Local\_inputrc
         : %appdata%
             C:\Users\anmsh\AppData\Roaming\.inputrc
             C:\Users\anmsh\AppData\Roaming\_inputrc
         : %home%
             C:\Users\anmsh\.inputrc
             C:\Users\anmsh\_inputrc


C:\Users\anmsh>clink autorun show
Current AutoRun values

  Current user:

    native : "C:\Users\anmsh\scoop\apps\clink\current\clink.bat" inject --autorun
     wow64 : "C:\Users\anmsh\scoop\apps\clink\current\clink.bat" inject --autorun

  All users:

    native : <unset>
     wow64 : <unset>
```

**Comment by chrisant996** [comment]
Does the message "The system cannot find the path specified." happen only when clink fails to get injected?

If so, then it means that the path `C:\Users\anmsh\scoop\apps\clink\current\clink.bat` cannot be found.

I don't know why that path would sometimes not exist, but that sounds like a scoop issue.

Maybe scoop is somehow concurrently updating clink when you launch Windows Terminal, such that the directory or file `C:\Users\anmsh\scoop\apps\clink\current\clink.bat` temporarily doesn't exist?

Sorry, I don't know what to suggest.  The issue seems to be happening outside of Clink.  I can help with issues that happen inside Clink, but when they're happening outside Clink then I'm very limited in how I can try to help.

**Comment by chrisant996** [comment]
Or another possibility could be that maybe your anti-malware software is sometimes blocking Clink from running.  Try checking the anti-malware software's activity log to see what it's blocked recently.  Or try adding an exclusion to avoid blocking Clink.

**Comment by anmsh** [comment]
> Does the message "The system cannot find the path specified." happen only when clink fails to get injected?

Yes. Only when clink fails. I could immediately detect it because I use most common clink keybindings and clink completions.

> Or another possibility could be that maybe your anti-malware software is sometimes blocking Clink from running. Try checking the anti-malware software's activity log to see what it's blocked recently. Or try adding an exclusion to avoid blocking Clink.

This may be a possibility. I will check this and also scoop issues list and get back in a while.
