### ISSUE TITLE
alt-d erases history instead of word

### ISSUE THREAD

**Issue by rmccampbell** [chrisant996/clink#47]
In previous versions of clink (and in bash) alt-d deletes forward a word (same as ctrl-delete). However in 1.1.17 it seems to instead remove the whole line and delete it from the history. Not sure if this is a bug or intentional change, but how can I restore the old behavior?

**Comment by chrisant996** [comment]
> In previous versions of clink (and in bash) alt-d deletes forward a word (same as ctrl-delete). However in 1.1.17 it seems to instead remove the whole line and delete it from the history.

Thank you for reporting this. It was a last minute oversight. I've moved the key binding to <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>D</kbd>.

> Not sure if this is a bug or intentional change, but how can I restore the old behavior?

The documentation covers how to configure Clink, key bindings, and so on. Are there specific questions about the content in the documentation?

**Comment by rmccampbell** [comment]
No, thank you. The old clink documentation was just a markdown file with the word "TODO" so I hadn't even bothered looking at yours but it is very extensive, thanks!
