### ISSUE TITLE
Tab to autocomplete paths jumps to beginning of path and deletes a character if no option is found

### ISSUE THREAD

**Issue by raketenolli** [chrisant996/clink#472]
I'm running Clink v1.4.4.7fe1ca so feel free to close this if the bug (or at least unexpected behavior) has already been resolved.

Let's say I'm in directory `c:\project\foo`.
I want to run a script at `c:\project\bar\baz.py`.

I type `python ..\bar\v<tab>`. Note the typo `v` instead of `b`, which results in no options to autocomplete because there are no files starting with a `v` in the `bar` directory.

Instead of doing nothing, like bash does on a Linux system, the cursor jumps to the beginning of the relative path (the `..`) and deletes one `.`, making me have to add it back, go back to the end of the path, fix my typo etc. This is a lot more cumbersome than the original bash behavior.

Is this a bug or intentional?

**Comment by chrisant996** [comment]
You could check by trying it with the current version.

(It was fixed 3+ months ago in #448.)
