### ISSUE TITLE
Windows 11 no changes with clink

### ISSUE THREAD

**Issue by bedioude** [chrisant996/clink#478]
Hi, oh this is what i want for years, and i did a try, but on Windows 11 there does nothing happen?

Even if i use the `cmd` (and clink included) or open `clink`, after closing and reopening there is still no history.

How to setup the persistent history like bash, please?

**Comment by chrisant996** [comment]
> i did a try, but on Windows 11 there does nothing happen?
> 
> Even if i use the `cmd` (and clink included) or open `clink`, after closing and reopening there is still no history.
> 
> How to setup the persistent history like bash, please?

@bedioude History is enabled by default.  It sounds like something is going wrong.  To make troubleshooting possible, please share more details about what you're doing and what happens.

- What did you try?  Please list the specific steps.
- What was the expected outcome?  What was the actual outcome?
- Try this:
    - Clink the Start menu button.
    - Type "clink", and the installed Clink program shortcut should show up in the list in the Start menu.
    - Double clink the Clink program shortcut.  Share a screen of the text at the top of the cmd window.  Does it show a message saying the Clink version and https address for the repo?
    - Press <kbd>Alt</kbd>-<kbd>H</kbd>.  What happens?  If Clink has been successfully injected into cmd.exe, then that will show a list of key bindings and what they do.
    - Run `clink info` and copy/paste the full output here.
    - Attach the `clink.log` file here.  The location of the log file is listed in the output from `clink info`.

Based on the statements "I did a try" and "nothing happens", maybe an anti-virus system thought it needed to block Clink from running.  But there isn't enough information yet to be able to say anything for sure.
