### ISSUE TITLE
Disabling directory shortcuts

### ISSUE THREAD

**Issue by NotSpaulding** [chrisant996/clink#482]
Is it possible to disable the `-`, `..`, `...` shortcuts? If yes, how? I couldn't find anything about disabling them in the docs.

**Comment by chrisant996** [comment]
There isn't a setting to disable them.  Can you share why you want to disable them?

Do you prefer for them to print an error?  If so, why?
```plain
'..' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by NotSpaulding** [comment]
I dislike how they look mostly, I would rather have the default windows behavior of just throwing an error. I know this is very nit picky. I didn't create this issue to request you create a setting or something, just wanted to ask. Thanks for continuously working on this wonderful program :).

**Comment by chrisant996** [comment]
I'm confused -- if you don't like how they look, then can't you just not use them, and then you won't see them?
