### ISSUE TITLE
Hash in release asset name

### ISSUE THREAD

**Issue by zdm** [chrisant996/clink#484]
Could you please renove hash from asset file name in releases.
It prevents to download from scripts.

```
clink.1.5.4.6f56dd.zip -> clink.1.5.4.zip
```

**Comment by chrisant996** [comment]
Please share more information.  How does it block download?  I haven't experienced or heard of that before.

**Comment by zdm** [comment]
I want to update clink using simple script.
It will download and unpack latest release zip to the local folder, where clink is installed.
I can determive latest version parsing `git rm profile/default_inputrc` output.
Bit you release zip contains hash in the filename - that makes it impossible to construct download url.

Ideally, asset shpuld be namesd as just `clink.zip`, without any additioanal version or hash. ;-)

**Comment by chrisant996** [comment]
Looking at the repo is not a safe or reliable way to determine the version anyway:  I increment the version days or weeks before publishing a new release.  

Also, it's very possible for a script to get the full download URL -- Clink itself uses a script to ask GitHub for the link to the latest download.

https://api.github.com/repos/chrisant996/clink/releases/latest

Using `git rm profile/default_inputrc` is a surprising way to find the version.  You shouldn't need to delete a source file from the repo to find the latest release version.  And if/when I start publishing pre-release versions, then it would start having even bigger problems.

There are many other simpler and safer ways to find the version.

A script should look at the releases, not the sources.  The API URL I shared is the best way to find the current release version and the full download URL for it.

You can examine the Lua script at https://github.com/chrisant996/clink/blob/master/clink/app/scripts/update.lua for how Clink itself finds the URL.

**Comment by zdm** [comment]
I am not sale your software.

You make releases pretty frequent and this is annoying to open github, diwnload and unpack it every time.

I just wanted to save few minutes.

Ok, sorry for dusturbin you.

**Comment by zdm** [comment]
Tp work with json api i need to iuser something more complex, than shell.
Of coutre i can get list of assets uging api, ...
But I preer to keep thing simple.

**Comment by chrisant996** [comment]
> I am not sale your software.
> 
> You make releases pretty frequent and this is annoying to open github, diwnload and unpack it every time.
> 
> I just wanted to save few minutes.
> 
> Ok, sorry for dusturbin you.

Did you turn off the updater that's built into Clink?

When there's a new release, it should tell you, and it should say to run `clink update` to automatically download and install it.

You shouldn't need to write a script, and you shouldn't need to do anything complicated.

See [Automatic Updates](https://chrisant996.github.io/clink/clink.html#automatic-updates) for more on how updates should work.

Can you try that?  If that is having problems, can you describe what you do and what happens?

**Comment by zdm** [comment]
Hmm, I didm't knew about updater.
Will try now.

**Comment by zdm** [comment]
`clink update` works
thank you
