### ISSUE TITLE
How to define another editor in _inputrc?

### ISSUE THREAD

**Issue by vbd** [chrisant996/clink#485]
I feel pretty stupid right now as I am failing to define another editor.

- version  : 1.5.4.6f56dd
- vim.exe and gvim.exe are both in path
- vi mode is set and run
- if I type the command and hit v (= emacs mode = ctrl+x ctrl+e) notepad is started
- clink info:
```
: %userprofile%
             C:\Users\xxx\_inputrc   (LOAD)
         : %home%
             C:\Users\xxx\_inputrc   (exists) 
```
- _inputrc:
```
VISUAL="gvim.exe"
EDITOR="vim.exe" 
```
-  I tried for exe's  with path: with \\, with \\\\, with /
- I tried some inputrc I found on github but mostly for Linux so I can't get it to work

**Comment by chrisant996** [comment]
It looks like you're trying to set environment variables in the inputrc file. That doesn't work in Windows, nor in Linux.  The Clink docs have a section on the syntax and purpose of the inputrc file.

This question is about where to set environment variables.  That doesn't have anything to do with Clink.  You could set them in the Windows system control panel or in a batch script.

**Comment by vbd** [comment]
Thank you for your feedback. `set EDITOR=vim.exe` fixed it. Don't know why I want it to set it in _inputrc. Sorry for PEBKAC.

**Comment by vbd** [comment]
Thank you for your feedback. set EDITOR=vim.exe fixed it. Don't know why I want it to set it in _inputrc. Sorry for PEBKAC.
