### ISSUE TITLE
The OhMyPosh Window Title does not work properly if we add emoji char.

### ISSUE THREAD

**Issue by saumyajyoti** [chrisant996/clink#486]
Please refer to bug https://github.com/JanDeDobbeleer/oh-my-posh/issues/4160 
When adding specific Character as in Theme below.

Using My Custom theme with below Title template.
"console_title_template": "{{.UserName}}@{{.HostName}} 📂{{ .PWD }}",

Please refer comment: https://github.com/JanDeDobbeleer/oh-my-posh/issues/4160#issuecomment-1694607626

**Comment by chrisant996** [comment]
@saumyajyoti I read the issue description, but I don't understand what steps I need to follow to reproduce the issue.

Can you please describe detailed steps for how to reproduce the issue?

**Comment by chrisant996** [comment]
I figured out a way to reproduce it, and without using omp.

**Comment by saumyajyoti** [comment]
Hi @chrisant996 , need to use ohmyposh cmder/clink theme with

 "console_title_template": "{{.UserName}}@{{.HostName}} 📂{{ .PWD }}", settings.

The Window Title wont work with this folder character. Instead this title text will get added to Prompt text.

**Comment by chrisant996** [comment]
(those aren't detailed enough steps -- but I found a way to reproduce it without even using oh my posh, so I don't need steps for oh my posh anymore)

**Comment by chrisant996** [comment]
@saumyajyoti Thanks for reporting this.  The fix will be available in the next published release, probably later this week or next week.

If the prompt string contains `OSC 2 ; string {EMOJI} BEL` then the OSC code is stripped and the `string {EMOJI}` part shows up in the prompt.

The same problem occurs for any OSC code containing any UTF8 content beyond ASCII characters (not just for emoji).

Commit https://github.com/chrisant996/clink/commit/9557d06c8cdf39ad995d8bd18284a71c8c218bec on May 6, 2016 introduced support for OSC codes in the ecma48 parser for escape codes.  It mistakenly used CSI code rules for valid characters for OSC codes, as well.  It's been that way for over 8 years without being noticed/reported.

**Comment by saumyajyoti** [comment]
Thanks @chrisant996  for quick turnaround.
