### ISSUE TITLE
How can I use it in PowerShell

### ISSUE THREAD

**Issue by PearNoDec** [chrisant996/clink#487]
I right-clicked on a directory and opened the PowerSheel window.

**Comment by chrisant996** [comment]
Clink is for use with cmd.exe, not PowerShell.

**Comment by liudonghua123** [comment]
I found another [`clink`](https://github.com/mridgers/clink/issues/74) is also not support (windows) powershell.

**Comment by chrisant996** [comment]
> I found another [`clink`](https://github.com/mridgers/clink/issues/74) is also not support (windows) powershell.

That's the very old version of clink, which was abandoned many years ago.

Clink intentionally does not support PowerShell.  See #277 for more information.
