### ISSUE TITLE
Is there support for pushd deep prompt?

### ISSUE THREAD

**Issue by AngelAGBL** [chrisant996/clink#491]
I want to put the pushd deep in my clink prompt, the equivalent thing in the commom CMD prompt is something like:
"$P$+$G"
Where $P is the path
$+ is the deep of pushd commands
$G is >

So, how can I do this in clink?

**Comment by chrisant996** [comment]
That is known only to cmd, and the only way cmd exposes it publicly is through a prompt that contains `$+`.

[clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) can detect the pushd depth _**IF**_ you put the `$+` at the beginning of the prompt.

**Comment by chrisant996** [comment]
I've added `os.getpushddepth()`, which works when `%PROMPT%` contains exactly one `$+`.

Scripts could already use the approach in https://github.com/chrisant996/clink-flex-prompt/blob/5d139630f8379a56d94b41ada0eed77d7b72f4a5/flexprompt.lua#L1760-L1773, but it's more complicated.

**Comment by AngelAGBL** [comment]
oh thanks a lot for your quick attention!
