### ISSUE TITLE
Stuck at checking latest version

### ISSUE THREAD

**Issue by tismofied** [chrisant996/clink#497]
I was doing some debloating on windows 11 today and may have goofed. Whenever I un `clink update` it says requesting administrator access and it get stuck at checking latest version. 

what could I do to fix this please?

**Comment by tismofied** [comment]
I figured it out. smh lol

**Comment by chrisant996** [comment]
> I was doing some debloating on windows 11 today and may have goofed. Whenever I un `clink update` it says requesting administrator access and it get stuck at checking latest version. 
> 
> what could I do to fix this please?

It sounds like it may be a networking problem.

If you can share the `clink.log` file after getting stuck at checking the latest version, maybe that will offer some clues.

**Comment by tismofied** [comment]
> > I was doing some debloating on windows 11 today and may have goofed. Whenever I un `clink update` it says requesting administrator access and it get stuck at checking latest version.
> > what could I do to fix this please?
> 
> It sounds like it may be a networking problem.
> 
> If you can share the `clink.log` file after getting stuck at checking the latest version, maybe that will offer some clues.

It was network issue.  Got it fixed thank you!
