### ISSUE TITLE
Cursor up should show last command as default

### ISSUE THREAD

**Issue by koppor** [chrisant996/clink#499]
I use `<space>test-dw.pdf` to open a PDF file. When I press <kbd>Cursor up</kbd> at the next prompt, the tool shows the previous "real" command.

```cmd
koppor@DESKTOP-KAK953S c:\TEMP\ltg
$ clink --version
1.5.6.fc63d3

koppor@DESKTOP-KAK953S c:\TEMP\ltg
$  test-dw.pdf

koppor@DESKTOP-KAK953S c:\TEMP\ltg
$ clink --version
```

Maybe, this can be configured. I think, it should be the **default** to show the last "command" - even if it was file-open command.

**Comment by chrisant996** [comment]
@koppor I think you're unhappy that `<space>` explicitly tells Clink to not add the line to the history.

- Are you asking for a list of settings you can change or things you can do differently?
- Or are you asking for the default settings to be changed for everyone?

The `<space>` explicitly tells Clink to not add the line to the history.  See [Saved Command History](https://chrisant996.github.io/clink/clink.html#saved-command-history) for details.

Are you using `<space>filename` to bypass the Executable Completion features?  Have you considered changing the [exec.enable](https://chrisant996.github.io/clink/clink.html#exec_enable) and/or [exec.files](https://chrisant996.github.io/clink/clink.html#exec_files) settings?

If you want history to always save lines, have you considered turning off [history.ignore_space](https://chrisant996.github.io/clink/clink.html#history_ignore_space)?  But then you'd have no way to prevent a line from being saved in the history.

**Comment by koppor** [comment]
It is a user error. From old versions, I was used that I had to put a `space` in front a file to have it opened with the respective viewer. I did not try without. Maybe, that changed the last years. Need to re-train my muscle-memory.

**Comment by koppor** [comment]
Notes:

- [`exec.space_prefix`](https://chrisant996.github.io/clink/clink.html#exec_enable) is also handling the space
- `projects.pdf` is NOT auto completed without space

Consequence: I need to configure `history.ignore_space` being false to match my behavior. (Or set `exec.files` to `true` to have nice ctrl+space behavior, too)

Ranndom thought: Maybe, double space could be the thing for history ignoring to distinguish it from single space for completion? (In my mind: Who uses history-skip that much often? ^^)

**Comment by chrisant996** [comment]
> * `projects.pdf` is NOT auto completed without space

Starting the line with `"` or `.\` will allow completing `projects.pdf`.

> Ranndom thought: Maybe, double space could be the thing for history ignoring to distinguish it from single space for completion? (In my mind: Who uses history-skip that much often? ^^)

There are 3*2 = 6 combinations of things that each interpret a leading space as meaning something special.  Different users will consider different combinations to be "the one" that should get special treatment when there are two leading spaces.

I'll consider changing the `history.ignore_space` setting to allow `off`, `one`, or `two`.  But my initial thought is it makes it overly complicated (for users, for documentation, and for user support here).  There has to be a line somewhere, for declining to add options and complexity.  For the moment, I'm comfortable with setting the line at one space to ignore history.
