### ISSUE TITLE
Add support for Windows Terminal shell completion menu

### ISSUE THREAD

**Issue by mjcarman** [chrisant996/clink#500]
This is more of an FYI than an enhancement request.

As of the v1.19 preview, Windows Terminal includes an [Experimental Shell Completion Menu](https://github.com/microsoft/terminal/wiki/Experimental-Shell-Completion-Menu). The initial implementation is limited and subject to change, but once the API for the suggestions UI is stabilized it would be nice for clink to have an configuration option to use that API instead of writing suggestions to the console. Additionally, it might be beneficial to have clink's needs/use cases considered during the development of the API.

**Comment by chrisant996** [comment]
It's currently only supported for Powershell.  I'm in contact with WT team members.

The protocol is currently pretty fragile.  As the fragility points are addressed, I'll consider how it can be integrated with Clink.

Also, as currently implemented, WT's completion UI doesn't support markup.  Such as displaying a string `stash{0}   "Description about this"` but only inserting `stash{0}`, and a bunch of similar cases.  So, using WT's completion UI will disable a bunch of Clink completion abilities.

**Comment by chrisant996** [comment]
I'll close this for now, but this is worth checking back on periodically.  👍
