### ISSUE TITLE
clink update hangs after elavating permissions

### ISSUE THREAD

**Issue by jtnord** [chrisant996/clink#503]
clink showed an update from 1.5.5 to 1.5.7.

running `clink update` prompts for elevation, but the subsequent window just hangs with `Checking latest version...` 

logs show

```
7bbc ={update.lua}               0 Clink updater: latest release is v1.5.7; install type is zip.
7bbc ={update.lua}               0 Clink updater: update in C:\Users\me\AppData\Local\Temp\clink\updater\v1.5.7.zip is ready to be applied.
7bbc ={update.lua}               0 Clink updater: expanding C:\Users\me\AppData\Local\Temp\clink\updater\v1.5.7.zip into C:\Users\jnord\AppData\Local\Temp\clink\updater\v1.5.7.
7bbc ={update.lua}               0 Clink updater: Permission denied; failed to install file 'CHANGES'.
2498 ={update.lua}               0 Clink updater: latest release is v1.5.7; install type is zip.
2498 ={update.lua}               0 Clink updater: update in C:\Users\myadmin\AppData\Local\Temp\clink\updater\v1.5.7.zip is ready to be applied.
```

**Comment by chrisant996** [comment]
@jtnord Thanks for reporting this.

Can you confirm that you had changed `clink.autoupdate` to either `auto` or `prompt`?

I'm pretty sure it has to be this line in update.lua, which was added by 8bb76c0c7610df1bfb256928093ae70d56301af5 in v1.5.5 as part of the new `auto` and `prompt` modes of the `clink.autoupdate` setting:

```
if not clink._acquire_updater_mutex() then
```

You should be able to work around the problem by running `clink set clink.autoupdate clear` to reset it to the default mode of checking and just printing a message.

But I'm not able to reproduce the hang.  I installed v1.5.5 with "enhanced defaults" and "autorun", ran `clink set clink.autoupdate auto`, ran `cmd` and got a message about a v1.5.7 update being available followed by a popup window asking if I want to update now.  I chose to update now, it asked for elevation, and it successfully installed.

I'll try to figure out how to reproduce the hang.

**Comment by chrisant996** [comment]
@jtnord I figured out how to repro:

1. Run `clink set clink.autoupdate auto`.
2. Start `cmd.exe`, and it pops up a "Clink Update" prompt window.
3. Start another `cmd.exe` _before_ making a choice in the "Clink Update" prompt window.
4. Now choose "Update now" in the "Clink Update" prompt window.
5. Hang.

I'll work on a fix.  It might take a couple of days.

In the meantime you can either:
1. Run `clink set clink.autoupdate clear` to turn off the automatic updating.
2. Don't start more `cmd.exe` processes while the "Clink Update" prompt window is waiting for a choice.

**Comment by chrisant996** [comment]
v1.5.8 has been published with the fix.

Starting when updating _from_ v1.5.8 to a future version, this problem will no longer occur.  But it can still occur when updating _to_ v1.5.8.
