### ISSUE TITLE
clink auto updates when not desired

### ISSUE THREAD

**Issue by EricControls** [chrisant996/clink#504]
clink.autoupdate is set to 'check' but behaves as if it's set to 'auto'.

**Comment by chrisant996** [comment]
@EricControls Thanks for reporting this.

Ugh.  There's a mistake in the logic, and if the `clink.update_interval` has passed, then it accidentally behaves like `auto` if an update is available.

I'll work on a fix.  It may take a couple of days.

**Comment by EricControls** [comment]
> @EricControls Thanks for reporting this.
> 
> 
> 
> Ugh.  There's a mistake in the logic, and if the `clink.update_interval` has passed, then it accidentally behaves like `auto` if an update is available.
> 
> 
> 
> I'll work on a fix.  It may take a couple of days.

Appreciate what you do!

**Comment by chrisant996** [comment]
v1.5.8 has been published with the fix.

After updating to v1.5.8, this problem will no longer occur.  But it can still occur while updating _to_ v1.5.8.
