### ISSUE TITLE
buy me a coffee or equivallent?

### ISSUE THREAD

**Issue by jtnord** [chrisant996/clink#505]
Hi @chrisant996

I'ld really like to say thankyou for you support and efforts here to keep clink alive and working well.

Do you have a https://www.buymeacoffee.com/ or equivalent?

**Comment by chrisant996** [comment]
@jtnord Hey thanks for the appreciation.  ❤

I don't accept anything for working on Clink.  For me it's a strictly non-profit project -- partly "pay it forward" and partly just working on something I wanted for myself.  😎
