### ISSUE TITLE
Which clink should I use? I don't get it

### ISSUE THREAD

**Issue by yrifl** [chrisant996/clink#507]
There is two of them, clink version of chrisant996 and mridgers.

**Comment by chrisant996** [comment]
Mridgers is the original one, which was abandoned about 7 years ago (it stopped at v0.4.9).
Chrisant996 is the current version (it's currently on v1.5.8).

Although the mridgers repo is abandoned, GitHub refuses to allow any changes to it to mark it as abandoned, or to change the Readme.md to point to the new repo.  If you look in the Issues section in the mridgers repo, I've done my best to make it very clear.
