### ISSUE TITLE
Lua code not working?

### ISSUE THREAD

**Issue by yrifl** [chrisant996/clink#508]
```lua
-- Starship Lua. :P
function Run(cmd: table)
    for i, com in ipairs(cmd) do 
        os.execute(com)
    end
end

function Shell() 
    load(io.popen('starship init cmd'):read("*a"))()
end

function Startup()     
    Run({
        "@echo off",
        "cls",
        "setlocal enabledelayedexpansion",
        "@echo on",
        "curl wttr.in/Hi?0",
        "echo %date% %time%"
    })

    Shell()
    
    os.setenv('STARSHIP_CACHE', 'C:\\Users\\singg\\AppData\\Local\\Temp')
end

Startup()
```

This is what my %LocalAppData%/clink/starship.lua code looks like, but somehow it doesn't work (probably the forloop? or the functions?). The `os.execute` works perfectly, I wrote this code so I can easily execute commands when `clink` started, am I missing something that makes this lua code not working?

Very thanks, bloom.

**Comment by yrifl** [comment]
Wait, lmao. Do I need to install lua?

**Comment by yrifl** [comment]
Doesn't work :/ 

What do I do?

**Comment by yrifl** [comment]
Just figure the problem out, I thought lua has a typecheck lmao.

**Comment by chrisant996** [comment]
There's a bigger problem here:

The `Startup` function is trying to emulate a batch script.  It runs `setlocal` and `@echo off`.  But each `os.execute` spawns a whole _new_ `cmd.exe` to execute the specified command.  (There's no way to run commands in the current shell; the CMD shell isn't designed to support that.)

So, the `setlocal` runs in a new cmd.exe, and then the new cmd.exe immediately exits, which ends the setlocal.  The only way to get the behavior of a batch script is to use a batch script.

If you want to run a startup batch script, then [configure a startup batch script](https://chrisant996.github.io/clink/clink.html#gettingstarted_startupcmdscript).  You can't emulate that in Lua, though.

**Comment by yrifl** [comment]
By the way, is there any way to debug the execution of lua? Because its hard to find the problem in the lua code if there wasnt any error traceback.

**Comment by chrisant996** [comment]
> By the way, is there any way to debug the execution of lua? 

Search for "debugger" in the Clink documentation.  Read all the hits.
