### ISSUE TITLE
clink-popup-history crash

### ISSUE THREAD

**Issue by dougbenham** [chrisant996/clink#509]
Upon pressing my hotkey for `clink-popup-history`, the console crashes.

![image](https://github.com/chrisant996/clink/assets/5466350/65b75bcd-ca54-4029-9350-d9c8fbe06df3)

Let me know any additional info you would like.

**Comment by YanjunLee** [comment]
1.5.7 and 1.5.8 crash
1.5.6 OK

**Comment by chrisant996** [comment]
Thanks for reporting this.  I can't reproduce it.  Can you send me either the `clink.dmp` file listed on the screen, or your `clink_history` file and the full output from `clink set`?

**Comment by chrisant996** [comment]
Found it.  The crash happens when `history.time_stamp` is `off` (or when any text popup window has only 1 column of entries).  Will publish a fix soon.

**Comment by chrisant996** [comment]
Fix has been published.

**Comment by dougbenham** [comment]
Legendary.
