### ISSUE TITLE
History between multiple windows terminal tabs

### ISSUE THREAD

**Issue by CrazyWolf13** [chrisant996/clink#512]
Hi
I just found this software and you deserve everything this software is amazing!!!

But I noticed if I enter a command then start a new tab without closing the old, the history is not on the new tab can you fix this?

Huge thanks!

**Comment by chrisant996** [comment]
> But I noticed if I enter a command then start a new tab without closing the old, the history is not on the new tab can you fix this?

Clink is very configurable. Have you looked through the Getting Started section of the documentation, or the section about Saved Command History? Those should answer your question.

**Comment by CrazyWolf13** [comment]
> > But I noticed if I enter a command then start a new tab without closing the old, the history is not on the new tab can you fix this?
> 
> Clink is very configurable. Have you looked through the Getting Started section of the documentation, or the section about Saved Command History? Those should answer your question.

❤️
Gotta say I love this tool.
Sorry did not see the that there is a documentation and so many options.
