### ISSUE TITLE
Bitdefender infected file detected!

### ISSUE THREAD

**Issue by tismofied** [chrisant996/clink#513]
I understand that anti-virus programs might detect files as false positives  so i came here to make sure I a m not really infected.
I looked the discussion section and issues section and I couldn't find a file similar to mine in all peoples posts so I am just wondering if I should be concerned.
The file caught by bitdefender as soon as I opened tabby terminal is 
`Heur.BZC.PZQ.Boxter.794.XXXXXXX` and it was under C:\Users\User\AppData\Local\clink\clink_history.

**Comment by chrisant996** [comment]
There is no way for anyone to guess whether you've got a real infection or not.

But clink_history is not an executable file, so it's very strange to hear a claim about that specific file being "infected". 😉

There is a pinned issue (top of the list) about the fact that anti virus suites periodically raise false positives about Clink.  The way Clink attaches itself into CMD.exe is a technique that some viruses also use.  The technique itself is neither "good" nor "bad".

This is one of the reasons I use code-signing to apply a verifiable digital signature to the Clink executable files.  This enables the OS and users to verify whether the Clink program files are the same as what I published.
