### ISSUE TITLE
Cannot update to latest version

### ISSUE THREAD

**Issue by davidjade** [chrisant996/clink#516]
I cannot update to the latest version on Windows 10, using clink update. I see this

```
Checking latest version...
Downloading latest release v1.5.11...
Requesting administrator access to install update...
Update failed; see log file for details.
```

And the logs show this

```
480 ={update.lua}               0 Clink updater: latest release is v1.5.11; install type is zip.
3480 ={update.lua}               0 Clink updater: downloading https://github.com/chrisant996/clink/releases/download/v1.5.11/clink.1.5.11.08c7e3.zip to C:\Users\DAVID~1.HOM\AppData\Local\Temp\clink\updater\v1.5.11.zip.
3480 ={update.lua}               0 Clink updater: update in C:\Users\DAVID~1.HOM\AppData\Local\Temp\clink\updater\v1.5.11.zip is ready to be applied.
3480 ={update.lua}               0 Clink updater: elevation required to update InstallDir in registry.
4ee8 ={update.lua}               0 Clink updater: latest release is v1.5.11; install type is zip.
4ee8 ={update.lua}               0 Clink updater: update in C:\Users\DAVID~1.HOM\AppData\Local\Temp\clink\updater\v1.5.11.zip is ready to be applied.
4ee8 ={update.lua}               0 Clink updater: expanding C:\Users\DAVID~1.HOM\AppData\Local\Temp\clink\updater\v1.5.11.zip into C:\Users\DAVID~1.HOM\AppData\Local\Temp\clink\updater\v1.5.11.
4ee8 ={update.lua}               0 Clink updater: 2>&1 "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -Command "try { $ProgressPreference='SilentlyContinue' ; Expand-Archive -Force -LiteralPath \"C:\Users\DAVID~1.HOM\AppData\Local\Temp\clink\updater\v1.5.11.zip\" -DestinationPath \"C:\Users\DAVID~1.HOM\AppData\Local\Temp\clink\updater\v1.5.11\" ; echo "CLINK-UNZIP-SUCCEEDED" } catch { echo "CLINK-UNZIP-FAILED" ; echo $_.Exception.Message ; echo "`nALL ERRORS:`n" ; echo $error }"
4ee8 ={update.lua}               0 Clink updater: output from command:
4ee8 ={update.lua}               0 Clink updater:     PowerTab version 1.1.0 PowerShell TabExpansion Library
4ee8 ={update.lua}               0 Clink updater:     Host: ConsoleHost
4ee8 ={update.lua}               0 Clink updater:     PowerTab Enabled: True
4ee8 ={update.lua}               0 Clink updater:     CLINK-UNZIP-FAILED
4ee8 ={update.lua}               0 Clink updater:     A parameter cannot be found that matches parameter name 'DestinationPath'.
4ee8 ={update.lua}               0 Clink updater:     
4ee8 ={update.lua}               0 Clink updater:     ALL
4ee8 ={update.lua}               0 Clink updater:     ERRORS:
4ee8 ={update.lua}               0 Clink updater:     
4ee8 ={update.lua}               0 Clink updater:     Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.
4ee8 ={update.lua}               0 Clink updater:     ...
4ee8 ={update.lua}               0 Clink updater: failed to unzip the latest release.
```

**Comment by chrisant996** [comment]
@davidjade That seems strange.

Can you run these commands and share the output?
- `"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" $PSVersionTable`
- `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command Expand-Archive -?`

I found [this link](https://stackoverflow.com/questions/75326822/expand-archive-giving-syntax-error-in-powershell-v5-1-a-parameter-cannot-be-fou) about a similar-sounding PowerShell issue.  Maybe something on your computer is replacing the built-in Expand-Archive cmdlet?

I can try changing the updater to use `Microsoft.PowerShell.Archive\Expand-Archive`, but that won't help you until after you manually install an update to a version with that change.  And it might not fix the problem.  It sounds like there's something on your machine interfering with the built-in PowerShell Expand-Archive cmdlet.

**Comment by davidjade** [comment]
As it turns out something did replace Expand-Archive. The **PowerShell Community Extensions** module replaced it. I've removed them now as I don't think I even use them anymore at this point. Sorry about that, I didn't realize it was interfering.

Once I did that, the update worked.

**Comment by chrisant996** [comment]
Aha, yes!  I tried lots of internet searches, but hadn't been able to find mention of any things that replaced it.

And in 4.0.0-beta1 on October 17, 2020 they renamed their cmdlet to Expand-PscxArchive, presumably due to compatibility problems.  https://github.com/Pscx/Pscx/issues/15 was opened Dec 2016, and the 4.0 beta Jan 2022 addressed the issue with Expand-Archive.

d3b552ae19dec7bdb16507378ecd2e90ca48c2f8 makes the Clink updater include the module name, to ensure the intended cmdlet is used even if some other module also provides a cmdlet with the same name.

**Comment by chrisant996** [comment]
Thanks for finding the specific cause!  Much appreciated, and it confirms that the change in Clink is appropriate and will avoid similar issues.
