### ISSUE TITLE
Winget

### ISSUE THREAD

**Issue by CrazyWolf13** [chrisant996/clink#518]
Hi

Is winget abandomed?
Or why is it still on 1.4.22 ? Isn't 1.5.11 newest?

**Comment by chrisant996** [comment]
Winget is automatically updated with every release.

Here's the merged pull request for Clink v1.5.11:
https://github.com/microsoft/winget-pkgs/pull/123099

If you add `--verbose-logs --logs` to your winget commands, that can help you troubleshoot what's wrong with winget on your machine.  You may want to open an issue in the winget-cli repo, as the problem you're experiencing is in winget and not in clink.

**Comment by chrisant996** [comment]
Probably winget has gotten into a state where it can only update its index when run as an Administrator.  Try running it as an Administrator and it will probably work.  That's obviously not a good state to be in, but you'll need to contact the winget-cli repo for help.  I see some similar closed issues, such as https://github.com/microsoft/winget-cli/issues/3001 which are probably related, and also there are at least 3 open issues right now about winget being stuck and unable to update its index (but offhand they look like 3 different reasons why).

**Comment by CrazyWolf13** [comment]
Oh I see!

I thought you may have just missed the update winget, but thanks for sharing those links and it indeed was administrator that fixed it.
