### ISSUE TITLE
Have issue to login SunOS 5.11

### ISSUE THREAD

**Issue by anduinpan** [chrisant996/clink#521]
Can login via using ssh command in cmd session. But after create a session, it shows “Authentication denied, please try again. "
SunOS 5.11 , SSH-2.0-Sun_SSH_2.2. All session configs are default.

**Comment by chrisant996** [comment]
@anduinpan I'm sorry that's happening.  That doesn't sound related to Clink, though.

What happens if you do the same thing in a cmd session without Clink?

> after create a session, it shows “Authentication denied, please try again. "

What does "it shows" mean?
Do you mean "ssh shows an error about Authentication denied"?
If so, that's an issue with ssh, not with Clink.

**Comment by anduinpan** [comment]
@chrisant996 I'm a new learner till now. Sorry in advance if it doesn't related to Clink.
> What happens if you do the same thing in a cmd session without Clink?
I can login to the server correctly if use ssh command in cmd like below.
![image](https://github.com/chrisant996/clink/assets/150873328/36e72da0-812d-4db4-8db7-6ab7baa2e8ce)
But after I create a session(all session configs are default) and try to login via the same user & PWD, it shows like below.
![image](https://github.com/chrisant996/clink/assets/150873328/a8ff769d-3894-4e47-b5b6-6f45f281ce33)
At the same time, I use  the same user & PWD to create a session(all session configs are default) in MobaXterm. It can login correctly via the session.
![image](https://github.com/chrisant996/clink/assets/150873328/d79a625a-a14b-473e-b625-9a14702bcf6e)

**Comment by chrisant996** [comment]
This has nothing to do with Clink.

Ssh and Clink are not related at all and have nothing to do with each other.

Nothing in any part of what is shown in the screen shots or steps has anything to do with Clink.

Sorry, and I wish you good luck in your continued learnings!
