### ISSUE TITLE
Creating own aliases

### ISSUE THREAD

**Issue by CrazyWolf13** [chrisant996/clink#526]
Hi
I search a solution that simplifies the process of executing multiple commands at once, basically I use git daily and have to do :

`git add  .`
`git commit -m "message"`
`git push `

very often to test and check things.

Is there any solution inside clink that would allow me to instead type something like `gitpush "added readme"` and then clink would execute cmd 1 cmd2 with the message as argument 2 injected and then cmd 3 while showing the output?

I searched quite a lot through the docs, but I couldn't find anything like this, am I missing the wrong syntax/keyword for this?
I also thought about a batch file, but that probably would get messy pretty quickly.

Huge thanks for any help!

**Comment by chrisant996** [comment]
You're looking for the Windows OS feature [doskey](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/doskey}.  It isn't a Clink question, per se.

**Comment by CrazyWolf13** [comment]
Huge thanks!
Came across this couple of times, but never interpreted it as alias completion, huge thanks for that link, already solved most of the things.

Yeah sure, thought maybe clink has handled this somehow, sorry that I bothered you with this :/

clink_start is great, works quite well with this `doskey gitpush=git add .$tgit commit -m "$*"$tgit push >NUL` however the command is still shown in the terminal even with >NUL, is that expected or a bug?

**Comment by chrisant996** [comment]
> clink_start is great, works quite well with this `doskey gitpush=git add .$tgit commit -m "$*"$tgit push >NUL` however the command is still shown in the terminal even with >NUL, is that expected or a bug?

There are 3 completely separate commands.
1. git add
2. git commit
3. git push

The `>nul` was only added to the third command.
If you want output of all three commands redirected to nul, then you have to redirect each of the commands individually.

**Comment by CrazyWolf13** [comment]
> > clink_start is great, works quite well with this `doskey gitpush=git add .$tgit commit -m "$*"$tgit push >NUL` however the command is still shown in the terminal even with >NUL, is that expected or a bug?
> 
> There are 3 completely separate commands.
> 
> 1. git add
> 2. git commit
> 3. git push
> 
> The `>nul` was only added to the third command. If you want output of all three commands redirected to nul, then you have to redirect each of the commands individually.
> 
> (This is just how CMD works, and how shells in general work.)

Oh sorry, I meant this:
![image](https://github.com/chrisant996/clink/assets/96661824/13bb1f97-60d0-4238-8c0d-316882930537)
To make the doskey command invisible.

**Comment by chrisant996** [comment]
That is not output from the doskey command.

That is CMD echoing what command it's about to run.

Read about the [echo](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/echo) command in CMD.

Since these are questions about how to use CMD in general, I recommend to do some internet searches and reading.

Good luck!
