### ISSUE TITLE
Allow cycling through auto suggestions

### ISSUE THREAD

**Issue by DVLP** [chrisant996/clink#529]
Auto suggestions are awesome, instead of pressing Ctrl + R they are always there, but cannot be cycled though like when pressing Ctrl + R multiple times.

A button is needed to cycle i.e. Ctrl + arrow up/down

**Comment by chrisant996** [comment]
@DVLP I think what you mean is that you want a key to cycle through history lines that match what's been typed so far.  (That's not related to auto-suggestions.)

I think you're looking for the <kbd>PgUp</kbd> and <kbd>PgDn</kbd> keys where are by default bound to `history-backward-search` and `history-forward-search`.

For info on how to change key bindings, see [Customizing Key Bindings](https://chrisant996.github.io/clink/clink.html#keybindings) and [Init File](https://chrisant996.github.io/clink/clink.html#init-file) and [Bindable Commands](https://chrisant996.github.io/clink/clink.html#bindable-commands).

**Comment by DVLP** [comment]
Thanks @chrisant996 this is very useful. Is auto-suggestion simply the last matching history entry?

**Comment by chrisant996** [comment]
> Is auto-suggestion simply the last matching history entry?

No.  Which is why "cycle through all the possible auto suggestions" doesn't make sense.  Unless you mean cycle through the possible "_strategies_", not suggestions.  I recommend reading the documentation about auto suggestions, for more info.

**Comment by DVLP** [comment]
From the user's perspective it doesn't matter how it's called internally. In many cases there can be more than one candidate for the input and it does make sense to be able to go to the next most likely result.

**Comment by chrisant996** [comment]
> From the user's perspective it doesn't matter how it's called internally. In many cases there can be more than one candidate for the input and it does make sense to be able to go to the next most likely result.

I recognize that the auto suggestions feature can be confusing.  It is not intended to be something that provides multiple choices or that could cycle through choices.
