### ISSUE TITLE
Cmder's vendor/clink.lua is no longer loaded

### ISSUE THREAD

**Issue by iulian3144** [chrisant996/clink#53]
Seems that the vendor/clink.lua is no longer loaded starting with [commit dcf44d6370e354237df15116117a85eb8b3cf18f](https://github.com/chrisant996/clink/commit/dcf44d6370e354237df15116117a85eb8b3cf18f).
I would just like to know if this was intended and the reasons behind it.

@daxgames (I assumed you're Cmder's maintainer based on contributions)
I think this could also be handled in Cmder by simply giving the file a different name (e.g. `clink.lua` → `cmder_clink.lua`).
Maybe you could sync with Cmder's maintainer regarding this to avoid future issues. With the [version of clink that cmder is currently using](https://github.com/cmderdev/cmder/blob/9c9eac1875f5de00f17c7964eacbcd9f4be92044/vendor/sources.json#L9) this doesn't occur. I'm using ~~the latest~~ clink version `1.1.19.adf144` and noticed that the completions defined by Cmder are not working anymore.

Another option would probably be to have an exception for clink.lua if the parent dir is vendor but this sounds more like a hack.

Issue fixed with commit [d073df557bf4a80a5949dde90da96f6c9ebbf997](https://github.com/chrisant996/clink/commit/19fa50dbc4d1454d8291365a571adb9daef9ddb5).

**Comment by daxgames** [comment]
We are already working on it.  Clink 1.1.20 should already have a fix.

What versions of Cmder and Link are you using now.

**Comment by iulian3144** [comment]
> We are already working on it. Clink 1.1.20 should already have a fix.
I'll check that out. I think I'll need to fix my comment :).

I am currently using `cmder 1.3.17` and `clink 1.1.19.adf144`
