### ISSUE TITLE
Feature Request: Implement Ctrl+A Shortcut

### ISSUE THREAD

**Issue by mAmineChniti** [chrisant996/clink#532]
I kindly request the implementation of the Ctrl+A keyboard shortcut to move the cursor to the beginning of the input line within clink. This feature aligns with standard user expectations and would significantly improve the overall user experience and productivity/speed.

**Comment by mAmineChniti** [comment]
I appreciate your prompt response to my feature request. Allow me to provide more context on why the Ctrl+A shortcut is essential from a Linux terminal perspective:

1. **Default Behavior in Linux Terminals:**
   - In Linux terminals, Ctrl+A is a widely accepted and default shortcut that moves the cursor to the beginning of the current input line.
   - This behavior is deeply ingrained in the muscle memory of many Linux users, making it a standard expectation.

2. **Correction of Typos and Command Amendments:**
   - Having the ability to quickly move the cursor to the beginning of the line is particularly useful when correcting typos or amending a command.
   - Users often realize a mistake or want to modify the command at the beginning, and Ctrl+A allows for an efficient correction process.

3. **Enhanced Productivity in Command Entry:**
   - When working with lengthy or complex commands, the Ctrl+A shortcut significantly improves productivity.
   - It enables users to swiftly navigate to the start of the input line, reducing the time spent manually positioning the cursor.

4. **Consistency Across Platforms:**
   - Users who work across different platforms, including Linux, expect a consistent experience. Implementing Ctrl+A aligns the behavior with what users are accustomed to in various terminal environments.

**Comment by mAmineChniti** [comment]
Thank you for your help and I apologize for opening a deadend feature request issue.

**Comment by chrisant996** [comment]
@mAmineChniti Just to be clear, the simplest thing to do at this point to switch to "bash" default key bindings is run `clink set clink.default_bindings bash`.  Please try that and see if it resolves the request.
