### ISSUE TITLE
Question: How do I change Right arrow key to only complete one next command part like Shift+Right key? 

### ISSUE THREAD

**Issue by MagicAndre1981** [chrisant996/clink#534]
How do I swap the 2 keyboard combination to only complete next command part with right key and full command with shift+right arrow key?

**Comment by chrisant996** [comment]
You could make some new `"luafunc:"` commands:

```lua
function my_right(rl_buffer)
    local at_end = (rl_buffer:getcursor() > rl_buffer:getlength())
    local command = at_end and "clink-insert-suggested-word" or "win-cursor-forward"
    rl.invokecommand(command)
end
rl.describemacro([["luafunc:my_right"]], "Move cursor forward, or at end of line insert the next suggested word")
rl.setbinding([["\e[C"]], [["luafunc:my_right"]])

function my_shift_right(rl_buffer)
    local at_end = (rl_buffer:getcursor() > rl_buffer:getlength())
    local command = at_end and "clink-insert-suggested-line" or "cua-forward-char"
    rl.invokecommand(command)
end
rl.describemacro([["luafunc:my_right"]], "Extend the selection forward one character, or insert the suggested line")
rl.setbinding([["\e[1;2C"]], [["luafunc:my_shift_right"]])
```

**Comment by MagicAndre1981** [comment]
and how do I load this? 🤔

**Comment by chrisant996** [comment]
I've also added this as an example in the [Lua key bindings](https://chrisant996.github.io/clink/clink.html#luakeybindings) section of the docs.  It was a great question.

**Comment by chrisant996** [comment]
> and how do I load this? 🤔

It's a Lua script.  See [Extending Clink With Lua](https://chrisant996.github.io/clink/clink.html#extending-clink).

If this will be your first time making a Lua script, then here are some quick-start steps.  (These steps will work no matter how you've installed Clink; if I knew more specifics about your setup then I might suggest even simpler steps.)
1. Create a new folder, for example `C:\MyClinkScripts`.
2. Run `clink installscripts "C:\MyClinkScripts"` to make Clink always load scripts from that directory.
3. Save the script text to a file like `C:\MyClinkScripts\my_suggestion_keys.lua`.

New Clink windows will load the script.

**P.S. Note:** This led me to discover a bug in the `autosuggest.hint` setting; it's supposed to hide the "Right=Accept Suggestion" hint if the <kbd>Right</kbd> key isn't bound to one of the default commands.  And it does hide the hint ... but it accidentally still tries to apply the reverse-video coloring for where the "Right" text _would have been_ in the line.  I'm fixing that, but in the meantime you'll need to also run `clink set autosuggest.hint false` if you haven't already done that.

**Comment by MagicAndre1981** [comment]
I never used lua before and so this is all new and confusing. I search for days around this and today I asked it.

This works, but now the rightkey select any part of an url (first https:// till next special cars like . or / )

![image](https://github.com/chrisant996/clink/assets/8274816/ff25bd40-0da6-48e6-8253-4059c547749c)

I would select the complete whole --referer part with 1 right arrow key press.

**Comment by chrisant996** [comment]
> I never used lua before and so this is all new and confusing. I search for days around this and today I asked it.

It's a great question, and I'm glad you asked it.

> This works, but now the rightkey select any part of an url (first https:// till next special cars like . or / )
> ...
> I would select the complete whole --referer part with 1 right arrow key press.

Yes, it's the difference between `clink-insert-suggested-word` and `clink-insert-suggested-full-word`.

Replace the former with the latter in the Lua script.

**Comment by MagicAndre1981** [comment]
> Yes, it's the difference between `clink-insert-suggested-word` and `clink-insert-suggested-full-word`.
> 
> Replace the former with the latter in the Lua script.

perfect, this works. Thanks for the help.
