### ISSUE TITLE
Put a bunch of files in Cmder's profile.d directory and got a CMD batch recursion error

### ISSUE THREAD

**Issue by facile-aliquidron** [chrisant996/clink#536]
error Batch recursion exceeds stack limits

******  B A T C H   R E C U R S I O N  exceeds STACK limits ******
Recursion Count=290, Stack Usage=90 percent
******       B A T C H   PROCESSING IS   A B O R T E D      ******

C:\Users\josel\AppData\Local\cmder\config\profile.d
how do i fix this

**Comment by facile-aliquidron** [comment]
updated to clink v1.6.0

**Comment by chrisant996** [comment]
@facile-aliquidron I don't understand what you're reporting.

The error message is from CMD itself, not from Clink.  The error message means that some batch script called a batch script, which called a batch script, which called a batch script ... etc for a total of 293 times, and CMD decided it's too many levels of nested calls and is nearly overflowing the stack.

What steps do you perform that results in that error?
Which batch script is encountering that error?

Do you mean you updated to Clink v1.6.0 and now you're getting that error when you do something?
Or do you mean you were getting that error, and updating to Clink v1.6.0 made the error go away?

It looks like you're using Cmder.  The issue might be related to how Cmder is configured, and what batch scripts Cmder has been configured to automatically run.

This issue doesn't seem related to Clink.

**Comment by facile-aliquidron** [comment]
the program is running with cmder auto install to me the user... i don't why im getting this error code but i put a whole bunch of files in the profile.d dir and thats all i did

![Screenshot clink](https://github.com/chrisant996/clink/assets/94621905/c0bf29b7-120c-4856-ba76-ad9996628db5)

**Comment by facile-aliquidron** [comment]
never mind the culprit was the init.bat, after taking it out the system only runs this error
![Screenshot 2023-12-11 181039](https://github.com/chrisant996/clink/assets/94621905/f9e2c533-3f2a-466b-8bc0-face68a365a3)

**Comment by facile-aliquidron** [comment]
these where the files i had in the profile.d folder 
![Screenshot 2023-12-11 181450](https://github.com/chrisant996/clink/assets/94621905/7c34cfd4-df74-416a-8a22-5d863da364b4)

**Comment by chrisant996** [comment]
> i don't why im getting this error code but i put a whole bunch of files in the profile.d dir and thats all i did

The question would be, what files did you put in there, and why.

The Cmder documentation says this about the profile.d directory (this is the readme.md file in that directory):

> ## Profile.d Folder
> 
> * Files in this folder named `*.{sh|cmd|ps1}`: Will be executed by the appropriate shell when starting the shell.

> these where the files i had in the profile.d folder

None of those files belong in the profile.d directory, since you don't want to run any of those as shell scripts when starting Cmder tabs.

I would recommend reading about the folder and about each of the scripts, and figuring out a better place to store the scripts.

**Comment by chrisant996** [comment]
(This is a Cmder usage question, and isn't related to Clink at all.)
