### ISSUE TITLE
Installed but no usable inside Terminal

### ISSUE THREAD

**Issue by CrazyWolf13** [chrisant996/clink#542]
Hi I absolutely love this project and as wort in a company where we use the terminal often this thing is a live saver, but after the initial installation I just cannot use clink inside the terminal. Opening clink.bat works. however it's not automatically injected on start.

Installation: Winget
Device: Intune Managed (Domain Joined)
Admin: Local Admin Rights

Could this be related to PATH not being set correctly?

Or have you got any ideas on how I could try to fix this?

**Comment by chrisant996** [comment]
Share the output from each of these:
- `clink info`
- `clink autorun show`

**Comment by CrazyWolf13** [comment]
> Share the output from each of these:
> 
> * `clink info`
> * `clink autorun show`

All clink related commands do not work inside terminal. However it's correctly installed in Program Files (x86)

clink is not recognized as a internal or external command....

**Comment by chrisant996** [comment]
> > Share the output from each of these:
> > 
> > * `clink info`
> > * `clink autorun show`
> 
> All clink related commands do not work inside terminal. However it's correctly installed in Program Files (x86)
> 
> ```clink is not recognized as a internal or external command.... ```

You said it works if you open clink.bat.

Do either of these:

1. Open clink.bat, then run `clink info` and `clink autorun show`
2. Open a terminal tab, then run `c:\Program Files (x86)\Clink\clink info` and `c:\Program Files (x86)\Clink\clink autorun show`

(If that's not the exact path where you installed Clink, then substitute the actual path instead in the commands above.)

**Comment by CrazyWolf13** [comment]
> > > Share the output from each of these:
> > > 
> > > * `clink info`
> > > * `clink autorun show`
> > 
> > 
> > All clink related commands do not work inside terminal. However it's correctly installed in Program Files (x86)
> > `clink is not recognized as a internal or external command.... `
> 
> You said it works if you open clink.bat.
> 
> Do either of these:
> 
> 1. Open clink.bat, then run `clink info` and `clink autorun show`
> 2. Open a terminal tab, then run `c:\Program Files (x86)\Clink\clink info` and `c:\Program Files (x86)\Clink\clink autorun show`
> 
> (If that's not the exact path where you installed Clink, then substitute the actual path instead in the commands above.)

Yeah sorry, missed that.

![image](https://github.com/chrisant996/clink/assets/96661824/3d1f51ba-27b7-41ee-80a7-305e448b08ff)

Autorun seems unset.
Can I manually set it? Or is there a reason why this may not be set automatically?

**Comment by chrisant996** [comment]
How did you install Clink?

Autorun is part of CMD itself, so copying Clink program files onto a computer isn't able to configure autorun.

If you install Clink using the setup .exe installer, then by default the "Autorun" checkbox is checked, which causes the installer to set CMD's Autorun registry key.  (Maybe you unchecked the box.)

Or you can use `clink autorun install` to configure CMD's Autorun registry key.

**Comment by CrazyWolf13** [comment]
> How did you install Clink?
> 
> Autorun is part of CMD itself, so copying Clink program files onto a computer isn't able to configure autorun.
> 
> If you install Clink using the setup .exe installer, then by default the "Autorun" checkbox is checked, which causes the installer to set CMD's Autorun registry key.  (Maybe you unchecked the box.)
> 
> Or you can use `clink autorun install` to configure CMD's Autorun registry key.


Yeah that surely makes sense.
As written above I installed it with winget (winget install --id chrissant996.clink)

Thanks, i'll try with clink autorun install.

**Comment by chrisant996** [comment]
I want the documentation to help people install Clink.

So, did you use the [Installation](https://chrisant996.github.io/clink/clink.html#installation) and [Using Clink](https://chrisant996.github.io/clink/clink.html#using-clink) sections of the documentation?

They cover the question that was asked, so I want to make sure that there wasn't anything misleading or missing.  If you read them, was there something that could have been phrased differently to make it more clear about the Autorun part?

**Comment by CrazyWolf13** [comment]
Yeah huge thanks for helping, sorry that was maybe misleading from my way and I apologise. I was more concerned that some path releated stuff wasn't working due to domain controlled device. Because I can recall explicitly choosing to install with autorun as I had such problems as well on another machine, but figured it out with clink autorun install.

Your Documentations are very well writte, however for a first time user may be a bit overwhelming.

**Comment by CrazyWolf13** [comment]
> Yeah huge thanks for helping, sorry that was maybe misleading from my way and I apologise. I was more concerned that some path releated stuff wasn't working due to domain controlled device. Because I can recall explicitly choosing to install with autorun as I had such problems as well on another machine, but figured it out with clink autorun install.
> 
> Your Documentations are very well writte, however for a first time user may be a bit overwhelming.
> 

"If the Clink install directory isn't in the PATH, then use install_dir\clink in place of clink to run Clink commands. Once Clink is injected into a cmd.exe process, then it automatically sets an alias so that you can simply use clink."

That was probably what cot me concerned about PATH

**Comment by chrisant996** [comment]
> That was probably what cot me concerned about PATH

Got it, thanks.

I was more asking what about the documentation wasn't clear enough that if Autorun is desired but the setup .exe wasn't used for installation, then `clink autorun install` is how to set up Autorun.
