### ISSUE TITLE
How do I disable suggestions?

### ISSUE THREAD

**Issue by devarxify** [chrisant996/clink#545]
Hello, I would like to disable suggestions as I do not like them. Is there any way to do this?
![image](https://github.com/chrisant996/clink/assets/69035413/5c3b812e-518f-4a12-a2e4-0b8fac960001)

**Comment by chrisant996** [comment]
It's almost the first thing listed in the docs.

**Comment by devarxify** [comment]
alright, thank you very much

**Comment by uberubert** [comment]
For the convenience of googlers, here is the command:

`clink set autosuggest.enable false`

I found it under the [Clink Settings section](https://chrisant996.github.io/clink/clink.html#clinksettings)

**Comment by chrisant996** [comment]
I'd recommend the documentation for the feature: [Auto-Suggest](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest).
