### ISSUE TITLE
Extra newline before prompt when using quiet mode

### ISSUE THREAD

**Issue by dalaverd** [chrisant996/clink#547]
I'm experiencing a UI issue where an extra newline is added before the command prompt after setting up Clink to autorun in quiet mode with `clink autorun install -- -q`. This only happens when the `-q` flag is used.

**Details:**
- Clink version: 1.6.1
- OS: Windows 11

**Steps to Reproduce:**
1. Run `clink autorun install -- -q`
2. Open a new command prompt

**Expected Result:**
The prompt begins at the top line without extra newlines.

**Actual Result:**
An extra newline appears above the prompt.

This seems to be a minor cosmetic bug but impacts the initial appearance of the terminal session. Any assistance in resolving this would be appreciated.

**Comment by chrisant996** [comment]
CMD is doing it, not Clink.
See #250 and #398.
