### ISSUE TITLE
`cd -` intercept interferes with `cd` doskey alias

### ISSUE THREAD

**Issue by eggbean** [chrisant996/clink#549]
I have a doskey macro which aliases `cd` to a script for [`CD Deluxe`](https://github.com/m6z/cd-deluxe) (which I've been using for around 15 years) and does some other stuff including setting a `%OLDPWD%` variable which I find useful. I've never been able to get it to fully work, but I realised that it does actually work when I have clink turned off.

I would like to turn off this [`cd -` intercept](https://github.com/chrisant996/clink/commit/81e0e881576a1392aeeac641666c1affe7f426f1), but I cannot see any option for doing this. Is there a way I can achieve this?

**Comment by chrisant996** [comment]
This sounded related to something I saw with cd-deluxe in the past.  I tracked it down to https://github.com/shunsambongi/clink-zoxide/issues/5 which was opened by you, and we had a conversation there.

There isn't a way to turn off directory intercept.

Can you share what isn't working?  With some information about your macros and scripts and what isn't working, it would be possible to fix the problems that they're experiencing.

**Comment by chrisant996** [comment]
Specifically what "doesn't work"?

The only thing I can think of is that you want `cd -` to be handled by your `cd` alias, so that `cdd -` is invoked and the "go to previous directory" is handled by CD-Deluxe instead of by Clink, so that the side effects happen such as setting `%OLDPWD%`.

I think the issue is that in addition to checking for `"cd"` or `"chdir"`, Clink should also first confirm that there isn't a corresponding doskey macro.

Can you share what problem(s) you've encountered?

**Comment by eggbean** [comment]
Sorry, I had to commit some changes before replying.

This is my modified version of the cdd.cmd script ([original is here](https://github.com/m6z/cd-deluxe/blob/master/install/cdd.cmd)):

```
@echo off
set dest=%*
if '%dest%'=='' goto :cdd
if qq%dest:~0,1%%dest:~-1%qq == qq""qq set dest=%dest:~1,-1%
if '%dest:~0,1%' == '~' set dest=%USERPROFILE%%dest:~1%
set dest="%dest%"
set OLDPWD="%CD%"
:cdd
set pushd_tmp=%TEMP%\pushd.tmp
set cdd_tmp_cmd=%TEMP%\cdd.tmp.cmd
pushd > %pushd_tmp%
%~dps0_cdd.exe %dest% < %pushd_tmp% > %cdd_tmp_cmd%
set dest=
%cdd_tmp_cmd%
```
The `set OLDPWD="%CD%"` works in every case apart from when the stdin is `cd -`.

**Comment by eggbean** [comment]
Sorry, I had to commit some changes before replying.

This is my modified version of the `cdd.cmd` script which is aliased to `cd` ([original is here](https://github.com/m6z/cd-deluxe/blob/master/install/cdd.cmd)):

```
@echo off
set dest=%*
if '%dest%'=='' goto :cdd
if qq%dest:~0,1%%dest:~-1%qq == qq""qq set dest=%dest:~1,-1%
if '%dest:~0,1%' == '~' set dest=%USERPROFILE%%dest:~1%
set dest="%dest%"
set OLDPWD="%CD%"
:cdd
set pushd_tmp=%TEMP%\pushd.tmp
set cdd_tmp_cmd=%TEMP%\cdd.tmp.cmd
pushd > %pushd_tmp%
%~dps0_cdd.exe %dest% < %pushd_tmp% > %cdd_tmp_cmd%
set dest=
%cdd_tmp_cmd%
```
The `set OLDPWD="%CD%"` works in every case apart from when the stdin is `cd -`, where the script is bypassed altogether. (This doesn't otherwise disrupt the working of `CD Deluxe` though.)

**Comment by chrisant996** [comment]
Ok thanks. It's the case I guessed. Clink should check whether there's an alias for `cd` that expands to run something other than `cd`, and if so then it shouldn't intercept at all.

Also, it should check for `&` or `|` after the `cd blah_whatever` command, and if present then it also shouldn't intercept.

**Comment by chrisant996** [comment]
I updated the title to describe the issue.

**Comment by eggbean** [comment]
Excellent, thanks.
