### ISSUE TITLE
LS_COLORS error messages

### ISSUE THREAD

**Issue by anotatta** [chrisant996/clink#550]
Update to version 1.61. There is an error messages with "LS_COLORS" environment variables.  clink is still functional but the error messages persist at the end of every command.

The error messages:
readline: LS_COLORS: unrecognized prefix: re
readline: LS_COLORS: unrecognized prefix: co
readline: LS_COLORS: unrecognized prefix: xs

My LS_COLORS is:
no=00:fi=00:di=01;33:ln=01;34:pi=40;33:so=01;35:do=01;35:bd=40;33:cd=40;33:or=40;31;01:ex=01;31:re=;04:co=;01;36:xs=;01;34:*.cmd=01;31:*.bat=01;31:*.exe=01;31:*.com=01;31:*.ps1=01;31:*.dll=01;31:*.sys=01;31:*.tar=01;36:*.tgz=01;36:*.arj=01;36:*.taz=01;36:*.lzh=01;36:*.zip=01;36:*.z=01;36:*.Z=01;36:*.gz=01;36:*.bz2=01;36:*.deb=01;36:*.rpm=01;36:*.jpg=01;35:*.png=01;35:*.gif=01;35:*.bmp=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.cdr=01;35:*.mpg=01;35:*.mp4=01;35:*.wmv=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.txt=01;34:*.pdf=01;32:

**Comment by chrisant996** [comment]
What is the intent of the `re` and `co` and `xs` entries?

Readline and bash have never supported those, and should always report an error.

What program supports those in LS_COLORS, and what do they do?

**Comment by chrisant996** [comment]
P.S.  what version of Clink were you using before you upgraded?  Clink v1.1.0 and greater should have reported error messages about unrecognized prefixes for that LS_COLORS value.  And `bash` should report the same errors.

**Comment by anotatta** [comment]
Unfortunately I forgot what version it was it.  I think it was 1.5.18.  I reinstall 1.5.18 and it's ok.

I think the LS_COLORS was set by [ls for gnu ](https://u-tools.com/msls) using dircolors.exe
The first two maybe RECENT and COMPRESS, the last "xs" I don't know.  

The following is from their html file.
# Highlight recently modified files - underscore
RECENT ;04   # leading semicolon required

# Highlight compressed files - bright cyan
COMPRESSED ;01;36  # leading semicolon required

**Comment by chrisant996** [comment]
@anotatta I figured out what changed:

The `default_inputrc` file was broken until v1.6.1, and so `colored-stats` wasn't enabled, so LS_COLORS wasn't parsed.

But with `colored-stats` set to `on` then `bash` and Readline and Clink all give that error.

You can either change LS_COLORS or add `set colored-stats off` into your `.inputrc` file.

**Comment by anotatta** [comment]
I tried option 2 and 3, they both works.  So, I'll keep the old LS_COLORS and use option 2 set with the three problematic entries remove.  Thanks.

**Comment by anotatta** [comment]
I tried option 2 and 3, they both works. So, I'll keep the old LS_COLORS and use option 2 set with the three problematic entries remove. Thanks.
