### ISSUE TITLE
Powershell Support

### ISSUE THREAD

**Issue by CrazyWolf13** [chrisant996/clink#557]
Hi

**Will we ever get PowerShell support?**

Well I know, I also don't really like the Powershell but I keep seeing Microsoft more and more trying to shift it's users towards Powershell.

And as basically everything that works on cmd also works on Powershell I have thought about switching to mainly using PS via Windows Terminal as there are barely and visual differences and mainly positive aspects of switching to PS.

However the only thing from keeping me still on CMD is ofc. clink.

I searched quite a lot through the Readme, the Docs and Issues, if there has been any official statement yet. Ccould find one, except the old maintainer once trying to add support but then removing it again.

Thanks for this awesome piece of software!

**Comment by chrisant996** [comment]
See #277.

**Comment by chrisant996** [comment]
Also, powershell is open source. If people want to add to it, they can.
