### ISSUE TITLE
injecting into an already running cmd.exe via cmd/bat?

### ISSUE THREAD

**Issue by davehorner** [chrisant996/clink#561]
I don't wish to inject systemwide and would prefer something that could be called from a cmd script or run after selecting a flavor of vsdev cmdline prompt.  running clink opens a new terminal window and I haven't been able to inject into a running cmd.exe.
```
2f0c inject                    608 ---- 2024/02/17 01:35:39.779 -------------------------------------------------
2f0c inject                    609 Injecting Clink...
2f0c inject                    629 *** ERROR ***
2f0c inject                    629 Failed to open process 21192.
2f0c inject                    629 (last error = 87)
```
I would like to be able to turn on clink via a cmd script that I would run after starting cmd.exe.  if it is a must preemptively inject; is there a way to inject with minimal functionality until some other flag/variable is set in the environment?  I ask because I stopped using clink from issues I experienced in the past and I miss it but want to opt in after I've gone through other cmd.exe initialization.

**Comment by chrisant996** [comment]
Have you found the [Usage](https://chrisant996.github.io/clink/clink.html#using-clink) section at the beginning of the documentation?

I think it answers the question.

Do you have questions about it?

**Comment by davehorner** [comment]
it works perfectly find using just clink inject.  maybe I need to slow down and read more docs.  thank you for your fast reply.

**Comment by davehorner** [comment]
When I set path;
```
@echo off
setlocal enabledelayedexpansion

rem Define the directory to add to the PATH
set "directory=C:\Users\dhorner\anaconda3\condabin"

rem Check if the directory is already in the PATH
echo %PATH% | findstr /i /c:"%directory%" >nul
if errorlevel 1 (
    rem If not found, add the directory to the PATH
    set PATH
    set "PATH=%PATH%;%directory%"
    set PATH
) else (
    rem If found, do nothing
    echo Directory already exists in PATH.
)
endlocal

@echo off
rem set PATH=%PATH%;C:\Users\dhorner\anaconda3\condabin
clink inject
set PATH
```
set PATH does not include the variable that was added above the call to inject.

**Comment by chrisant996** [comment]
Because of the `endlocal` which reverts all changes to the environment.

It's just a CMD scripting mistake and isn't related to Clink.  🙂

**Comment by davehorner** [comment]
I removed the endlocal.  Thank you!  However, I am still finding that the path is not coming thru.
```
@echo off
setlocal enabledelayedexpansion

rem Define the directory to add to the PATH
set "directory=C:\Users\dhorner\anaconda3\condabin"

rem Check if the directory is already in the PATH
echo %PATH% | findstr /i /c:"%directory%" >nul
if errorlevel 1 (
    rem If not found, add the directory to the PATH
    set PATH  <-- I verify its not there
    set "PATH=%PATH%;%directory%"
    set PATH    <-- I verify its there.
) else (
    rem If found, do nothing
    echo Directory already exists in PATH.
)

@echo off
rem set PATH=%PATH%;C:\Users\dhorner\anaconda3\condabin
clink inject
set PATH  <-- doesn't run
```
then when run from the injected prompt; it shows the original path.

**Comment by chrisant996** [comment]
This isn't related to Clink, it's just bugs in the batch script.

1. See documentation for [setlocal](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal).
    - `endlocal` happens automatically at the end of the batch script, if there isn't an explicit `endlocal` in the script.
    - You could use the idiom `endlocal & set PATH=%PATH%` to end the `setlocal` scope, but also keep the value of %PATH%.
    - The idiom relies on the fact that CMD expands environment variables in the whole line before running any part of the line, so the `%PATH%` is expanded before the `endlocal` runs, but the `set PATH={expanded value of %PATH%}` runs after the `endlocal`.
2. The `set PATH` at the end isn't reached because `clink` is a batch script; it's `clink.bat`.
    - The Clink executables are `clink_x86.exe` and `clink_x64.exe`, and the `clink.bat` script picks the right one to run based on whether the current `cmd.exe` is 32-bit or 64-bit.
    - Invoking a batch script from inside another batch script does not return to the original batch script.  To return to the original script, use the [call](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/call) command.  `call clink inject`.
    - Adding the `call` keyword makes the final `set PATH` show that the condabin directory is present, which demonstrates that the problems the script is encountering have nothing to do with Clink.

**Comment by davehorner** [comment]
I didn't mean to suggest it was a bug in clink, just looking for a hand.

The idiom works great! It might be worth a note for others.  maybe it's common knowledge.
```
call clink inject
endlocal & set PATH=%PATH% 
```

I appreciate your thoughtful response.  Thank you.

**Comment by chrisant996** [comment]
> I didn't mean to suggest it was a bug in clink, just looking for a hand.

Starting a [Discussion](https://github.com/chrisant996/clink/discussions) is more clear that it's just a request for general help that might be unrelated to the forum.

> The idiom works great! It might be worth a note for others. maybe it's common knowledge.

Since it has nothing to do with Clink, it's hard to imagine where to mention it in the Clink documentation, and it's unclear how readers would find it when it was relevant to whatever they were doing.

Seems like the note belongs in a different forum, perhaps one about CMD scripting instead of about Clink.

**Comment by davehorner** [comment]
Sorry.
