### ISSUE TITLE
Custom profile brings up the "was unexpected at this time" error

### ISSUE THREAD

**Issue by iG8R** [chrisant996/clink#562]
Hello.
I stumbled upon a weird issue.
When I try to change the profile path to my own, clink every time gives an error and stops integrating into cmd.

<img src="https://github.com/chrisant996/clink/assets/11407417/02530bcc-7ec8-4ff6-b40d-62da8e6e0497">

<img src="https://github.com/chrisant996/clink/assets/11407417/6e8897a8-4869-43f1-ba31-fe8a048089a5" width="550">

**Comment by chrisant996** [comment]
Looks like the autorun command misses adding quotes around arguments containing spaces.

https://github.com/chrisant996/clink/blob/master/clink%2Fapp%2Fsrc%2Floader%2Fautorun.cpp#L517
