### ISSUE TITLE
Update self-deletes clink

### ISSUE THREAD

**Issue by baterflyrity** [chrisant996/clink#563]
Hi! 
After last update clink just disappeared from my pc. How can I revert this?

**Comment by baterflyrity** [comment]
@chrisant996 , thanks for reply. Unfortunately, this is not related to AV. Moreover, I almost sure this happened due to the latest Windows update.

Meanwhile, I'd like to know what is correct way to reinstall clink saving all settings, prompt, hooks, etc. just like updater does it.

**Comment by chrisant996** [comment]
> @chrisant996 , thanks for reply. Unfortunately, this is not related to AV. 

Can you share specifically how you determined it wasn't related to AV?

> Meanwhile, I'd like to know what is correct way to reinstall clink saving all settings, prompt, hooks, etc. just like updater does it. Can you please provide some links to manuals?

I don't think there's anything further to document:

Reinstall the program.

The program is completely separate from your profile directory(ies) and your script directory(ies) and etc.  The updater doesn't "reinstall Clink saving all settings", it just updates the program files without touching anything else (there's no way it could find all profiles/scripts that might exist in all locations that you might have them, even if it wanted to).

**Comment by chrisant996** [comment]
> Hi! After last update clink just disappeared from my pc. How can I revert this?

Also, can you share specifically how you determined that Clink disappeared, and what you mean by that?
- Did you verify the Clink program files have been deleted?
- Or do you just mean when you start CMD you no longer see Clink automatically injected?
- Where had Clink been installed?
- If Clink program files got deleted, specifically which ones got deleted?

You've shared two conclusions you reached (Clink disappeared, and not related to AV).
But no other information has been shared, so that makes troubleshooting impossible.
Please share as much specific info as you can.

**Comment by baterflyrity** [comment]
> I don't think there's anything further to document:
> 
> Reinstall the program.

Thanks for the point. Yes, overwriting reinstallation helped.

> Also, can you share specifically how you determined that Clink disappeared, and what you mean by that?

- Did you verify the Clink program files have been deleted? - see below.
- Or do you just mean when you start CMD you no longer see Clink automatically injected? - yes, it really is not injected.
- Where had Clink been installed? - into *C:\Program Files (x86)\clink*, separate from ComEmu.

So... what about the incident? After Windows update failed and computer rebooted I saw that all Windows-related stuff rolled back to preupdate state plus clink disappeared and even browser tabs reverted in past! I consider the issue was in autoupdating clink parallelly with Windows. Also I could not find any AV logs about clink at all. 

Also checked directories:
- *C:\Program Files (x86)\clink* - all executable and icon files are empty (really, nothing is shown in notepad).
-  *C:\ProgramData\clink* - just empty directory.
- *C:\Users\user\AppData\Local\clink* - looks like no disasters here, logs are empty.

After reinstallation (without uninstalling):
- *C:\Program Files (x86)\clink* - all files (except settings) are updated and now work fine.
-  *C:\ProgramData\clink* - still just empty directory.
- *C:\Users\user\AppData\Local\clink* - everything is ok.

**Comment by baterflyrity** [comment]
All in all thanks for this great util. Furthermore, I'd pleased to help to prevent such bugs in further. Tell me if I can provide some more helpful information.

**Comment by chrisant996** [comment]
> After Windows update failed and computer rebooted I saw that all Windows-related stuff rolled back to preupdate state plus clink disappeared and even browser tabs reverted in past!
> ...
> I consider the issue was in autoupdating clink parallelly with Windows. 
> ...
> * _C:\Program Files (x86)\clink_ - all executable and icon files are empty (really, nothing is shown in notepad).

It sounds like you're saying that Windows was installing an OS update, while the OS update was installing you also told Clink to update, and then the OS update failed and started reverting files that were changed while the OS install was happening.

> I'd pleased to help to prevent such bugs in further.

Yeah, that's unfortunate.  It sounds like Clink was a victim, not the cause.  There's nothing for me to fix in Clink -- something outside of Clink did this.
