### ISSUE TITLE
"Syntax error" with cmd /e:off

### ISSUE THREAD

**Issue by Gei0r** [chrisant996/clink#569]
I have a script that runs a cmd shell like this: `cmd.exe /e:off /c "<COMMAND>"`

<pre>
# <b>works without clink:</b>
D:\>cmd.exe /e:off /c "echo a"
a

D:\>clink autorun install
Current AutoRun values
[...]
Clink successfully installed to run when cmd.exe starts (for current user).

# <b>No longer works after installing</b>
D:\>cmd.exe /e:off /c "echo a"
""AMD64"=="x86"" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
# <b>Roughly translated: ""AMD64"=="x86"" can't be syntactically processed at this point.</b>

# <b>Still works without /e:off</b>
D:\>cmd.exe /c "echo a"
a
</pre>

```
$ clink --version
1.6.4.1dd7ec
```

**Comment by chrisant996** [comment]
Thanks for reporting this!  It got broken in v1.3.47 in Oct 2022.
