### ISSUE TITLE
Please make the executable's file version readable from C#

### ISSUE THREAD

**Issue by UweKeim** [chrisant996/clink#573]
(Hopefully this isn't a too weird request)

In some of my scripts in C# I'm trying to read the "FileVersion" Win32 resource from various executables. One of them is CLink.

Usually, I'm doing this:

```C#
...
var version = FileVersionInfo.GetVersionInfo(exeFilePath).FileVersion;
...
```

This usually returns some string like e.g. "1.2.3".

([See reference](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo.fileversion#system-diagnostics-fileversioninfo-fileversion))

Only for CLink this returns an **empty string**. 

After further investigating I do have no _real_ clue on why this happens.

One thing that I discovered (but might be a red herring): when using [Resource Hacker](https://www.angusj.com/resourcehacker/) on "clink_x64.exe", it looks like this:

![image](https://github.com/chrisant996/clink/assets/415439/7d3fe5b0-a307-4a47-abcb-b30f5327b2dc)

Whereas e.g. "httpd.exe" (Apache web server), from which my C# code can read the FileVersion successfully, looks like this:

![image](https://github.com/chrisant996/clink/assets/415439/128c99f5-e1cc-4bb2-8e6d-95cc71f8e566)

The difference I do spot is that the FileVersion seems to appear twice in Apache but only once in CLink.

My current workaround is to use P/Invoke:

```C#
public static class VersionInfoReader
{
	[DllImport("kernel32.dll", SetLastError = true)]
	private static extern IntPtr LoadLibraryEx(string lpFileName, IntPtr hFile, uint dwFlags);

	[DllImport("kernel32.dll", SetLastError = true)]
	private static extern bool FreeLibrary(IntPtr hModule);

	[DllImport("kernel32.dll", SetLastError = true)]
	private static extern IntPtr FindResource(IntPtr hModule, IntPtr lpName, IntPtr lpType);

	[DllImport("kernel32.dll", SetLastError = true)]
	private static extern IntPtr LoadResource(IntPtr hModule, IntPtr hResInfo);

	[DllImport("kernel32.dll", SetLastError = true)]
	private static extern uint SizeofResource(IntPtr hModule, IntPtr hResInfo);

	[DllImport("kernel32.dll", SetLastError = true)]
	private static extern IntPtr LockResource(IntPtr hResData);

	private const uint LOAD_LIBRARY_AS_DATAFILE = 0x00000002;

	public static string GetFileVersionInfo(string exeFilePath)
	{
		IntPtr hModule = LoadLibraryEx(exeFilePath, IntPtr.Zero, LOAD_LIBRARY_AS_DATAFILE);
		if (hModule == IntPtr.Zero)
		{
			throw new InvalidOperationException("Cannot load file.");
		}

		try
		{
			IntPtr hResource = FindResource(hModule, (IntPtr)1, (IntPtr)16); // 16 = RT_VERSION
			if (hResource == IntPtr.Zero)
			{
				throw new InvalidOperationException("Version resource not found.");
			}

			uint size = SizeofResource(hModule, hResource);
			if (size == 0)
			{
				throw new InvalidOperationException("Version resource size is 0.");
			}

			IntPtr hMemory = LoadResource(hModule, hResource);
			if (hMemory == IntPtr.Zero)
			{
				throw new InvalidOperationException("Failed to load resource.");
			}

			IntPtr versionInfo = LockResource(hMemory);
			if (versionInfo == IntPtr.Zero)
			{
				throw new InvalidOperationException("Failed to lock resource.");
			}

			// Skip first 40 bytes, where the length of the VS_FIXEDFILEINFO structure is stored.
			IntPtr fixedFileInfoPtr = IntPtr.Add(versionInfo, 40);

			VS_FIXEDFILEINFO fixedFileInfo = Marshal.PtrToStructure<VS_FIXEDFILEINFO>(fixedFileInfoPtr);

			uint fileVersionMS = fixedFileInfo.dwFileVersionMS;
			uint fileVersionLS = fixedFileInfo.dwFileVersionLS;
			uint major = fileVersionMS >> 16;
			uint minor = fileVersionMS & 0xFFFF;
			uint build = fileVersionLS >> 16;
			uint revision = fileVersionLS & 0xFFFF;

			return string.Format("{0}.{1}.{2}.{3}", major, minor, build, revision);
		}
		finally
		{
			FreeLibrary(hModule);
		}
	}

	[StructLayout(LayoutKind.Sequential)]
	private struct VS_FIXEDFILEINFO
	{
		public uint dwSignature;
		public uint dwStrucVersion;
		public uint dwFileVersionMS;
		public uint dwFileVersionLS;
		public uint dwProductVersionMS;
		public uint dwProductVersionLS;
		public uint dwFileFlagsMask;
		public uint dwFileFlags;
		public uint dwFileOS;
		public uint dwFileType;
		public uint dwFileSubtype;
		public uint dwFileDateMS;
		public uint dwFileDateLS;
	}
}	
```

This succeeds and returns a version string like "1.2.3" but is a lot of code.

## My question

Could you modify the Win32 header of the CLink executables, so that a call to `FileVersionInfo.GetVersionInfo()` succeeds and returns a non-empty FileVersion?

**Comment by chrisant996** [comment]
@UweKeim the [FileVersionInfo](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo?view=net-8.0) has many fields.  Have you explored them?  The major, minor, etc parts are there.  Also the [ProductVersion](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo.productversion?view=net-8.0#system-diagnostics-fileversioninfo-productversion) string field should have a string.

I'll look at adding more fields, but there's nothing "wrong" with Clink's version info.  It sounds like some things are only looking at one specific field (which is language dependent, even) and give up and don't look at any of the other fields.  If these tools expanded how much of the version info they look at, they'd be more robust at identifying versions for more things.

**Comment by chrisant996** [comment]
@UweKeim I've added a few fields.  But this isn't a Clink issue; the issue is in how the FileVersionInfo structure is being interpreted.

Why can't ProductVersion be converted to a Version?
What is doing the conversion?
What goes wrong?
Why can't the language independent numeric fields be used?

All of the tools I've used that get file versions understand the raw language independent numeric fields AND the FileVersion AND ProductVersion.  The documentation about FileVersionInfo isn't consistent with only looking at FileVersion.

I'm curious which tool this is that doesn't understand the documented FileVersionInfo structure and only considers a subset of one specific field.

Also, the FileVersion string is a freeform string and can contain anything; it doesn't have to conform to any particular convention.  It can contain "Alpha 0.2.3a-topicbranch-202403111" for example.

The major/minor/etc fields are numeric fields following a specific convention.

**Comment by UweKeim** [comment]
Thank you very much, @chrisant996. The "tool" you refer to is simply the class library .NET from Microsoft with the [FileVersionInfo.GetVersionInfo()](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo.getversioninfo) method.

I really don't know why they have implemented it the way they have it. 

I've also tried `FileVersionInfo.GetVersionInfo().ProductVersion` and it also returns an empty string.

Hopefully this issue here didn't offend you as it was never my intention to do so. I would like to apologize if it still did.

**Comment by chrisant996** [comment]
@UweKeim per [VERSIONINFO resource](https://learn.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource), some of the strings are "required", and some are "optional".

I never knew any were "required", and I've never encountered anything before that actually treated any of them as "required".  I'm not sure that the "requirement" is actually enforced anywhere except for in the implementation of [FileVersionInfo.GetVersionInfo](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo.getversioninfo?view=net-8.0) (which came many years later).

Every tool I've used before that looks at file version info, or code that directly uses the system API [GetFileVersionInfoW](https://learn.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfow), seems to treat all the strings as optional.

It seems that the C# .NET framework API isn't necessarily behaving in the most compatible manner, but either way the recent commit ec90abba21fa26df772175a1f667a52f142da86e added more strings, and C# no longer refuses to return any of the strings, and is able to return all of the strings now.

Do keep in mind that they are freeform strings, and it isn't reliable to try to parse them to extract numbers.  If code wants to get numbers, then it should use FileMajorPart, FileMinorPart, FileBuildPart, and FilePrivatePart.

**Comment by UweKeim** [comment]
Thank you very much for your detailed research and also the modifications to CLink.

I've actually learned some new things I didn't knew when I initially started writing this issue here. So I'm happy that I'm now a little bit more knowledge than before 😊.

**Comment by chrisant996** [comment]
> I've actually learned some new things ... So I'm happy that I'm now a little bit more knowledged than before 😊.

Same!  I always appreciate the learning opportunities. 😎👍
