### ISSUE TITLE
Multiple uninstall programs exist in clink folder

### ISSUE THREAD

**Issue by CarterLi** [chrisant996/clink#576]
![image](https://github.com/chrisant996/clink/assets/6134068/adc6fa40-a081-484e-8b09-520f144408bf)

Is it expected?

**Comment by chrisant996** [comment]
No, it's not expected.

Please share more about what steps have occurred, to get into this state.

Also, into what folder has Clink been installed?

**Comment by CarterLi** [comment]
I installed clink with setup.exe downloaded in Github releases. Everything is default.

The only special thing (maybe) is that I use Windows on ARM (in a VM)

**Comment by chrisant996** [comment]
@CarterLi can you confirm how you've been updating Clink?  Is it by running `clink update`, or do you download and run the setup exe?

(I would guess you run `clink update`, but I shouldn't assume that, since an assumption could potentially accidentally send me down the wrong path of investigation.)

**Comment by CarterLi** [comment]
> I think you've been running the setup exe each time to install an update

Yes.

> Have you considered using the clink update command instead?

I have networking issues connecting Github directly. I always download things manually via proxy.

**Comment by chrisant996** [comment]
> I have networking issues connecting Github directly. I always download things manually via proxy.

Ah, I'm sorry, that must be frustrating.

Clink v1.6.10 includes a fix in the setup exe, and it will also automatically delete any old leftover uninstall exe files that might still exist.
