### ISSUE TITLE
bash isn't the default shell on macOS

### ISSUE THREAD

**Issue by michael-o** [chrisant996/clink#577]
Apple has replaced bash with zsh many years ago for licensing reasons: https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features

**Comment by michael-o** [comment]
Affected line: https://github.com/chrisant996/clink/blob/master/README.md?plain=1#L3

**Comment by chrisant996** [comment]
Feel free to submit a pull request.

**Comment by michael-o** [comment]
Done
