### ISSUE TITLE
Trojan:Win32/Casdet!rfn false positive

### ISSUE THREAD

**Issue by GF-Huang** [chrisant996/clink#580]
![image](https://github.com/chrisant996/clink/assets/4510984/a45ffc1a-ceeb-4975-b24f-9cd60a5d4efa)

**Comment by chrisant996** [comment]
That's a problem in the anti virus software. It needs to be reported to the anti virus software company. Clink has no control over the anti virus software.

**Comment by chrisant996** [comment]
Also see pinned issue #369.
