### ISSUE TITLE
Windows Defender reports a trojan in Clink 1.6.10 zip

### ISSUE THREAD

**Issue by fstanchina** [chrisant996/clink#585]
Today, I logged in to a machine I don't use often and Windows Defender alerted me that the zip file for Clink 1.6.10 contains Trojan:Win32/Casdet!rfn

I had already upgraded my primary workstation to 1.6.10, so:
- I launched a Defender scan, which found nothing;
- I downloaded the 1.6.10 zip file from the GitHub release page and Defender promptly blocked it.

Looks a lot like a false positive, but it's definitely worth investigating.

**Comment by chrisant996** [comment]
Duplicate. Please read https://github.com/chrisant996/clink/issues/583#issuecomment-2024868016.

**Comment by fstanchina** [comment]
Sorry, I searched but I didn't find the other reports.
