### ISSUE TITLE
Integration with conda

### ISSUE THREAD

**Issue by thisisjaymehta** [chrisant996/clink#586]
It would be great if Clink can show current active environment of conda like zsh does.

Screenshot of zsh shell from my ubuntu system:

![image](https://github.com/chrisant996/clink/assets/31812582/12186f20-5357-4e49-9f98-02a9db52b948)

And when I create a new environment and switch to it:

![image](https://github.com/chrisant996/clink/assets/31812582/d6ade348-78a8-452f-9db7-a1089b508177)

**Comment by chrisant996** [comment]
That's not something that would be part of Clink itself, just like it's not part of zsh or bash or etc.

You're looking for prompt scripts.  Refer to Clink docs for pointers to some popular scripts.

https://chrisant996.github.io/clink/clink.html#popular-scripts

E.g. clink-flex-prompt or oh-my-posh or starship and so on.

**Comment by thisisjaymehta** [comment]
Thanks a lot for guiding me in correct direction.

I was able to do it using clink-flex-prompt
