### ISSUE TITLE
-FLAG:"PATH" Style Completion Not Working

### ISSUE THREAD

**Issue by CampinCarl** [chrisant996/clink#59]
First, huge thanks to the developers for keeping this project alive; it's awesome!

I'm trying to get `-flag:"path"` style completion working, which works in v0.4.9 when a double quote is present. Here's a use case example with Saxonica's XSLT utility, ref: [Saxon Documentation - Running XSLT from the Command Line](https://www.saxonica.com/html/documentation/using-xsl/commandline/)

```
C:\>Transform.exe -xsl:"foo.xsl" -s:"source.xml"
```

1) Command completion works fine, i.e., `transf` + [TAB] = `Transform.exe`
2) Flag completion works (via Lua), i.e., `-xs` + [TAB] = `-xsl:`
3) Path completion does *not* work, i.e., `-xsl:"` or `-xsl:"foo` + [TAB] = `-xsl:"`/`-xsl:"foo` (no path completion)

I think it might be possible to replicate this behavior in Lua? Conceptually, I'm looking for a way to treat the colon as a separator between the `-xsl` flag and the `foo.xsl` argument, similar to the [Linking Parsers](https://chrisant996.github.io/clink/clink.html#linking-parsers) example. The [clink.filematches](https://chrisant996.github.io/clink/clink.html#clink.filematches) function looks suitable for this purpose, but I don't know how to solve the colon issue.

Any advice from the devs/community would be greatly appreciated.

**Comment by chrisant996** [comment]
Makes sense, thanks for the description and context information.

I'll take a look.  Yes, a generator can handle that manually (see `getwordbreakinfo`, or something like that; I forget the exact name offhand).  But this behavior should be built in so that argmatchers get it for free.  Plus, it presents an interesting edge case for input colorization.

**Comment by CampinCarl** [comment]
You're welcome and thanks for taking a look at this. I'll play around with `:getwordbreakinfo()`, though admittedly I'm not expert with Lua (should be fun though!).

**Comment by chrisant996** [comment]
Oh, interesting...  this works for `menu-complete`, just not for `complete`.

**Comment by chrisant996** [comment]
Clink 0.4.9 does _**not**_ work correctly in this case, by the way.  It interprets the quoted string as a separate word as though it were not connected to the `-flag:` string.

For example:
- `net -flag:"`<kbd>Tab</kbd> lists arg1 matches as possible completions:  `accounts`, `computer`, `config`, etc.
- `net -flag:"config" `<kbd>Tab</kbd> lists arg2 matches for `config` as possible completions:  `server`, `workstation`.
- `git -flag:"checkout" `<kbd>Tab</kbd> lists files _plus branch names_ as though `git checkout` had been used.

**Comment by chrisant996** [comment]
Here's what I think is needed:
1. Make the `-flag:"text"` case _not_ be handled by argmatchers, and simply default to file completions.
2. Make the `-flag:` part be colored as a Flag, and make the `"text"` part be colored as Other.
3. Explore adding some lua syntax to supply a match generator for a flag _with no space after it_.  Maybe the `+` operator could be taken over, e.g. `{ "-flag:" + some_function_name }`.
4. Provide some way for a custom classifier to apply a classification to any region in the input line, not just to a pre-parsed word.
5. Provide some way for a custom classifier to apply any arbitrary color to a pre-parsed word or to any region in the input line.

I've opened 3 new issues to track those:
#61 tracks points 1 and 3.
#62 tracks point 2.
#63 tracks points 4 and 5.

Thanks again @CampinCarl for noticing and reporting this!

FWIW, point 3 is "nice to have", but is not required -- I think it shouldn't be very expensive to support, but I can't promise anything just yet.  The reason it isn't strictly required is that custom generators can be written to handle any arbitrarily complex syntax in an input line.  For example, a custom generator handles environment variable completions embedded within words, and the entire argmatcher system is itself just a built-in custom generator.

**Comment by CampinCarl** [comment]
Thanks Chris! Interesting point on v0.4.9. Sounds like it "worked" for what I needed but wasn't actually working as intended. I'll keep an eye on the new issues you've opened.

**Comment by CampinCarl** [comment]
Checking in to say the new build works great for this use case. Thanks!

**Comment by chrisant996** [comment]
Thanks for confirming!
