### ISSUE TITLE
clink does not save command that prefix with space

### ISSUE THREAD

**Issue by iamqiz** [chrisant996/clink#591]
~~if i run "<space>dir"  in cmd , clink does not save this command in history
<space> mean a space~~

if i run ` dir` in cmd , clink does not save this command in history
(there is a SPACE character at the beginning of ` dir`)

**Comment by chrisant996** [comment]
You can't use `<` `space` `>` like that because GitHub interprets it as HTML, and no one can see what you've typed.

So, I'm editing your post to make it readable.

**Comment by chrisant996** [comment]
> if i run ` dir` in cmd , clink does not save this command in history
> (there is a SPACE character at the beginning of ` dir`)

This is intentional.

The documentation section [Saved Command History](https://chrisant996.github.io/clink/clink.html#saved-command-history) explains.

**Comment by iamqiz** [comment]
@chrisant996  I solve it by `clink set history.ignore_space False`.
thank you very much!
