### ISSUE TITLE
[feature request] add a setting for allowing remove leading space 

### ISSUE THREAD

**Issue by iamqiz** [chrisant996/clink#592]
see https://github.com/microsoft/terminal/issues/4189
here is a case
```
C:\Users\pcmsi\tmp>doskey abc=echo 3

C:\Users\pcmsi\tmp>abc
3

C:\Users\pcmsi\tmp> abc
'abc' 不是内部或外部命令，也不是可运行的程序或批处理文件。 ('abc' is not an internal or external command, nor is it a runnable program or batch file.
)
```

**Comment by iamqiz** [comment]
@chrisant996 hello, is there a setting to ignore leading spaces of doskey alias ?

**Comment by chrisant996** [comment]
Yes. Please read the documentation.

**Comment by iamqiz** [comment]
a workaround to strip leading spaces in current line is to
define a key bind in .inputrc :
```
"\e[27;8;65~":set-mark
"\e[27;8;66~":clink-forward-bigword
"\e[27;8;67~":kill-region
"\e[27;8;68~":end-of-line
"\e[27;8;69~":beginning-of-line

"\C-g\C-f":"\e[27;8;69~\e[27;8;65~\e[27;8;66~\e[27;8;67~\e[27;8;68~"
```
then use  `ctrl+g ctrl-f `  to delete leading spaces.
(`\e[27;8;65~` mean `ctrl+shift+alt+a` , `\e[27;8;66~` mean `ctrl+shift+alt+b` ,and so on
`\C-g\C-f` do these action: beginning-of-line > set-mark>clink-forward-bigword >kill-region > end-of-line
)

@chrisant996  will you consider to create a command such as `clink-delete-leading-space` to do that? 🥰

**Comment by chrisant996** [comment]
> will you consider to create a command such as `clink-delete-leading-space` to do that?

Why would it be needed?
1. It seems you've already accomplished what you wanted, using the tools already available.
2. It's confusing why a mechanism to strip leading spaces is desired -- why insert the spaces in the first place, if the intent is to remove them?

**Comment by iamqiz** [comment]
@chrisant996  sometimes the leading spaces will be insert by users accidently; 
 someone hope terminal allow leading space, 
`clink-delete-leading-space` maybe be useful  for them (i guess)

**Comment by chrisant996** [comment]
> @chrisant996  sometimes the leading spaces will be insert by users accidently; 
>  someone hope terminal allow leading space, 
> `clink-delete-leading-space` maybe be useful  for them (i guess)

If spaces were instead accidentally, then the user probably isn't aware that spaces were inserted, and they probably won't press a special key to remove them. 

Input line coloring will typically help make it clear when an alias will not be expanded.

Windows doesn't expand aliases when preceded by a space.  This is generally considered a feature, so that you can prevent using an alias.  For example if you have an alias `dir` that executes for example `eza` or `dir /w`.  Then inserting a space lets you still be able to run literally `dir` when you need to.

**Comment by chrisant996** [comment]
(Also, the issue you cited from the terminal repo says a leaving space is meant to bypass expanding a doskey aliases, but there was a bug where it accidentally didn't.  The bug was fixed a few years ago.  I'm not sure why that issue was cited.  It seems to agree with what I've been saying.)

**Comment by iamqiz** [comment]
@chrisant996 😂sorry, it is my mistake😂
thank you for your  patient explanation.
you let me realize  i misunderstood that issue's intention, 😂 because the word "bypass" is understood as "allow" by me😂 forgive my poor english😂
the example `dir` alias you mentioned above is really a  common use case, for me, i want to use `cd` as a alias to `cd /d`.
i also realize  why clink allow to use a leading semicolon :
![Clip_2024-04-10_06-58-35](https://github.com/chrisant996/clink/assets/48077521/e046a9a4-a666-4a63-ac25-c87e6be3cc75)

 a printable leading char is better than a space to bypass doskey alias 👍

**Comment by chrisant996** [comment]
Try starting `cmd.exe` without Clink.

You will find that in `cmd.exe` doskey aliases are not expanded if they are preceded by a space or semicolon (or several other kinds of punctuation characters).

The only part that's new in Clink is that by default a space prevents adding the command to history.  And that is controllable by the Clink that you found.

So it seems like you're asking me to change how cmd.exe and Windows and the [ReadConsole](https://learn.microsoft.com/en-us/windows/console/readconsole) system API work, and make it behave different from how it's meant to behave.  The stated motivation for such a change doesn't seem compelling.

I'm not going to do that.  It would create even more confusion, and would break some workflows, and would make troubleshooting and support even harder.

**Comment by iamqiz** [comment]
@chrisant996 
i have tried it, you are right!

i no longer hope clink or cmd.exe  to remove leading space , i realized that keeping it is meaningful
