### ISSUE TITLE
Modify Heading 

### ISSUE THREAD

**Issue by VarnaX** [chrisant996/clink#601]
Is that possible to modify this to custom text ?
![image](https://github.com/chrisant996/clink/assets/56477171/426161a9-b009-4f88-ad16-c9099b4076e2)

**Comment by nerzid** [comment]
in cmd, type this
`clink set clink.logo none`

**Comment by VarnaX** [comment]
Is that possible to set custom text?

**Comment by chrisant996** [comment]
> Is that possible to set custom text?
> 

Make a list script that prints text.

**Comment by chrisant996** [comment]
**my_custom_text.lua**, for example in your profile directory:
```lua
print("This is my custom text.")
```

**Comment by VarnaX** [comment]
Really thank you :)
