### ISSUE TITLE
the new `os.setalias` ignore the flags and args

### ISSUE THREAD

**Issue by silisium** [chrisant996/clink#602]
if i have let say:
```lua
os.setalias('grep', 'rg')
```
and run `grep --help`, i get the output you normally get when running `rg` without flags, not the help output.
i had to do this to make it work:
```lua
os.setalias('grep', 'rg'  .. ' $*')
```
which i think should be done implicitly by `os.setalias`

**Comment by chrisant996** [comment]
Aliases are part of the OS.

Run `doskey /?` to learn more. 

The syntax of aliases is well defined, and documented.

If you want to pass the full list of arguments in a specific spot, then you must use `$*`.

Simply, 

```lua
os.setalias('grep', 'rg $*')
```

The alias syntax enables you to also choose to not include args, or to put specific ones in specific spots, e.g. `xyz --port="$2" verb $1`.
