### ISSUE TITLE
No message print when an update is available

### ISSUE THREAD

**Issue by EricControls** [chrisant996/clink#606]
clink.update_interval is '5'
clink.autoupdate is 'check'

Two releases where clink doesn't print an update message. I run a 'clink update' and receive and installs the latest but only if done manually.

**Comment by chrisant996** [comment]
Interval 5 means only check once every 5 days. 

The reason no update message occurred is because you forced an update before the next time it was allowed to check whether any updates were available.

It's only been a day since the latest version was released.

It seems to be working as intended.

**Comment by EricControls** [comment]
What are the odds, wow. I guess I've been manually running a 'clink update' before the 5 day lapses for the last 3 releases... (without knowing there was a release beforehand).

Apologies, @chrisant996 I'll pay a little more attention before posting next time.
