### ISSUE TITLE
Show history filtered by the typed command

### ISSUE THREAD

**Issue by doorbash** [chrisant996/clink#607]
Hello. Is there a shortcut key to display command history based on the typed command? I am aware of the F7 key, but it shows the entire history. I am looking for a feature that provides a list of possible suggestions based on the typed command when I press a key. Is this functionality already included? If not, is there a chance it could be added to Clink in the future?

**Comment by chrisant996** [comment]
It exists and is documented.  I'm not able to share a direct link right now.

**Comment by doorbash** [comment]
I found the solution. The shortcut key for the feature I was looking for is `Alt-Ctrl-Up`. It triggers the `clink-popup-history` command. Thank you for pointing me in the right direction.

**Comment by chrisant996** [comment]
Oh right - I forgot I added a default key binding for it a few months ago I think.

**Comment by chrisant996** [comment]
But you can configure your own key bindings, too.

For example, my own config has it bound to <kbd>PgUp</kbd>
