### ISSUE TITLE
The installer is not copying any files to the newly created %LOCALAPPDAT%\clink directory

### ISSUE THREAD

**Issue by javadba** [chrisant996/clink#609]
As described in the title.  I have tried both running the downloaded installer executable directly as well as doing `winget install clink`. Both of them do create th `clink` directory but no files are copied there:

```
C:\Users\sboesch\AppData\Local>dir clink
 Volume in drive C is Windows
 Volume Serial Number is B22C-F287

 Directory of C:\Users\sboesch\AppData\Local\clink

06/03/2024  05:02 PM    <DIR>          .
06/03/2024  05:02 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  93,832,400,896 bytes free
```

**Comment by chrisant996** [comment]
It's not supposed to copy any files there. 

Did you encounter some other problem, which made you examine that folder? 

What was the other problem?  That's what to discuss instead.

**Comment by chrisant996** [comment]
See the first two topics in the docs:
- [Installation](https://chrisant996.github.io/clink/clink.html#installation)
- [Using Clink](https://chrisant996.github.io/clink/clink.html#using-clink)
