### ISSUE TITLE
What's the diffs to https://github.com/mridgers/clink?

### ISSUE THREAD

**Issue by GF-Huang** [chrisant996/clink#610]

**Comment by chrisant996** [comment]
What does the question mean?

The mridgers version is very old and was abandoned many years ago.

The chrisant996 version has multiple years of changes compared to the mridgers version.

If you're asking how to use git to see the diffs, then clone the chrisant996/clink repo and run `git diff 0.4.9..HEAD`.  But that's going to be a _huge_ set of diffs.

**Comment by GF-Huang** [comment]
Thank you. I just see its last update, not see the last release date.
