### ISSUE TITLE
Request: CTRL+D to exit terminal.

### ISSUE THREAD

**Issue by lschans** [chrisant996/clink#611]
I don't know if it's possible, but the combination of CTRL+D to exit the terminal like we do on Mac and Linux would be very nice.
The amount of times I've used this key combo (automatically and without thinking) in Windows just to not see my terminal window close is beyond countable.

Thanks in advance

**Comment by chrisant996** [comment]
It exists. Refer to the docs. 

Tomorrow I can point to the specific topic if you haven't found it yet.

**Comment by chrisant996** [comment]
https://chrisant996.github.io/clink/clink.html#ctrld_exits

**Comment by chrisant996** [comment]
And this question led me to notice there's a minor doc mistake:  The `cmd.ctrld_exits` setting should have a "*" next to its default value, since when Clink is installed with "Use enhanced defaults" enabled in the setup .exe installer, then the default changes from "True" to "False".

**Comment by lschans** [comment]
Super, I made the setting and it works now. I have to admin I just installed it with all the defaults. Great job on clink by the way it makes my life a lot more sane while working in windows.
