### ISSUE TITLE
Clink messes with git bash autocomplete

### ISSUE THREAD

**Issue by eblis** [chrisant996/clink#619]
I'm using `Clink v1.6.15.626c80` with fzf and if I start Git Bash app (mingw64) every time I try to press `tab` to autocomplete something it "suggests" `luafunc:fzf_complete`.

So for example I type in `host` then press tab, I end up with `hostluafunc:fzf_complete`, and every time I press tab I get another `luafunc:fzf_complete' added to my command line.

**Comment by chrisant996** [comment]
You modified your inputrc file to bind tab in Clink.

But bash uses the inputrc file, too.

You need to use `$if clink` if you want a binding to only affect Clink. 

See the Clink docs on key bindings and inputrc file for details.

**Comment by eblis** [comment]
Thanks, that was it.
I had an `.inputrc` file in clink folder and thought that was the only one, but turns out I created another `inputrc` file in my user folder for the FZF stuff.

I added the `$if` and now everything is fine once more; thanks again.
