### ISSUE TITLE
Problem when is "autorun install" when run a batch script get a "♀" (a extrac char on output -> ♀)

### ISSUE THREAD

**Issue by Mitezuss** [chrisant996/clink#624]
A image:

![0](https://github.com/chrisant996/clink/assets/35956777/4fe84e55-440e-4921-8cb5-c5a0ea905e7d)

that char appear when is running a batch script, like:

```
@echo Off
for /f "delims=" %%i in ('dir "%~1\*.txt" /s /b') do ( echo "%%~i" )
pause
```
only when is "installed" clink (with autorun install option)
how can be fixed ?

Regards

**Comment by chrisant996** [comment]
I cannot reproduce the issue.

```
c:\wbin\clink> test\issue624.cmd c:\tmp\
"c:\tmp\.inputrc.txt"
"c:\tmp\4115292.body.txt"
"c:\tmp\adminstatus_20220928_1412.txt"
```

Can you share more information?

- What version of Clink are you using?
- Can you share the full output from `clink info`?
- How are you running the batch script?
  - Do you type the batch script name and argument at the CMD command line?
  - Do you invoke the batch script through a different program?
  - Or something else?
- Does the `♀` character happen on every line of output from the `for` loop in the batch script, or only on certain lines?

Clink can't affect batch scripts -- it can only affect the prompt and the input line.
CMD doesn't give Clink any opportunities to affect batch scripts (even if Clink wanted to, but it doesn't want to).

Either the effect is coming from something else, or there is more involved than just Clink and the batch script.

**Comment by chrisant996** [comment]
Also, the `♀` character is the "FF" or "Form Feed" character, which tells a printer to scroll to the top of the next page (i.e. when printing onto paper).  Different terminal programs behave differently when the Form Feed character is present.

That's not something Clink ever uses.  But again, Clink isn't active while CMD is running a batch script, so either the effect isn't coming from Clink, or there is more involved than just Clink and the batch script.

**Comment by chrisant996** [comment]
Ok, that's very helpful information.

The issue is occurring when the `for` command spawns a new `cmd.exe` to run the command in the parentheses, for example `('dir "%~1\*.txt" /s /b')`.

That command is printing a Form Feed character before anything else.

Can you run `clink autorun show` and share the output?
