### ISSUE TITLE
Remove new line when injecting clink

### ISSUE THREAD

**Issue by narnaud** [chrisant996/clink#625]
I'm using clink in Terminal, and my current `prompt.spacing` is set to `parse`.

When starting a new terminal session, it always adds a new line (same with `normal`). The only way to remove the new line would be to change the settings to `compact`, but it's a bit too compact for me ;)

![image](https://github.com/chrisant996/clink/assets/469305/e5089604-0131-4476-83c3-694e434c85c6)

Would it be possible to not add this new line only when injecting clink?
Keep the `prompt.spacing` settings the rest of the time.

**Comment by chrisant996** [comment]
Clink is not adding that new line.  It comes from CMD itself.  See issue #488 for a detailed discussion and analysis.

**Comment by narnaud** [comment]
Thx, didn't realize it came from cmd.

**Comment by chrisant996** [comment]
@narnaud In case you might not have noticed yet:  The issue I linked has a [sample script](https://github.com/chrisant996/clink/issues/488#issuecomment-1707545948) for getting rid of the blank line when `clink.logo` is `none`.
