### ISSUE TITLE
clink can not recognize the symbol ^

### ISSUE THREAD

**Issue by Dalton-Liu** [chrisant996/clink#628]
for example, the command : git reset HEAD^

C:\Code\binmake>git reset HEAD^
More?
More?
fatal: ambiguous argument 'HEAD
': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by chrisant996** [comment]
That has nothing to do with Clink.  `^` is a special character in CMD.exe.

Learn more here:
- https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cmd (search for `^` in that page)
- https://stackoverflow.com/questions/20342828/what-does-symbol-mean-in-batch-script
- https://github.com/cmderdev/cmder/issues/840
