### ISSUE TITLE
Does clink use <C - => as any default key binding? 

### ISSUE THREAD

**Issue by Jaehaks** [chrisant996/clink#630]
Thank you for your efforts,

When I set keymap `<c-=>` in neovim, it doesn't work. 
If I open neovim using nvim-qt, it works. but the problem always happens when neovim is opened in windows-terminal

It seems taht `<c-=>` isn't be included in clink keybinding list, because when I confirm the result of binding list with `<A-H>`, I don't find it.
but windows-terminal doesn't have any key bindings also after I remove all keymap settings.

Is there a list of hidden shortcuts that are set by default?

**Comment by chrisant996** [comment]
It sounds like you're asking a question about key bindings in neovim.

Clink has nothing to do with that.

When neovim is running, neovim is receiving input -- not Clink.
