### ISSUE TITLE
permament doskey

### ISSUE THREAD

**Issue by wincmd64** [chrisant996/clink#635]
so i enter **DOSKEY pg=ping google.com -t**
it disappeared at next session
I thought that clink must auto remember it - did I misunderstand?

**Comment by chrisant996** [comment]
Doskey macros are not permanent in Windows. This isn't related to Clink.

**Comment by garoto** [comment]
doskey macros should be loaded at every cmd.exe invocation via a file containing doskey  macros to be used.

I use `clink.autostart` for that:
```
> clink set clink.autostart
        Name: clink.autostart
 Description: Command to run when injected
       Value: C:\Windows\System32\doskey.exe /macrofile=c:\bin\doskey.mac

This command is automatically run when the first CMD prompt is shown after
Clink is injected.  If this is blank (the default), then Clink instead looks
for clink_start.cmd in the binaries directory and profile directory and runs
them.  Set it to "nul" to not run any autostart command.

```

**Comment by wincmd64** [comment]
okey, i created clink_start.cmd in ..\Local\clink\
now, after cmd loaded it shows all strings in it - can it be hiden? And also Clink version, copyright and site infos

**Comment by chrisant996** [comment]
> okey, i created clink_start.cmd in ..\Local\clink\
> now, after cmd loaded it shows all strings in it - can it be hiden? 

You've written a Batch Script for CMD.
By default, CMD echo each command from a Batch Script to the screen. 
To hide each command, start the file with `@echo off`.

> And also Clink version, copyright and site infos

It's a setting.  For more info about settings refer to: 
- [Configuring Clink](https://chrisant996.github.io/clink/clink.html#clinksettings).
- The [`clink.logo`](https://chrisant996.github.io/clink/clink.html#clink_logo) setting.
