### ISSUE TITLE
More secure update code?

### ISSUE THREAD

**Issue by KevinNanson** [chrisant996/clink#636]
I use Clink in a corporate environment and I get a lot of 'false' reports of malicious activity when Clink checks for updates.
I don't know the full details (they don't give that to me), but it appears to be due to being hosted on Pastebin.
Are there other alternatives to using Pastebin?

**Comment by chrisant996** [comment]
Clink is hosted on GitHub.com.
Clink does not use Pastebin at all.

**Comment by chrisant996** [comment]
If the employer has software that is concerned about the update checks, try turning them off.
See [Automatic Updates](https://chrisant996.github.io/clink/clink.html#automatic-updates) for details.
