### ISSUE TITLE
Can CMD show the name of each script that's run?

### ISSUE THREAD

**Issue by darkzbaron** [chrisant996/clink#642]
I launch many batch script . Is there a way you can modify the startup behaviour of clink to show the full path of the running script?

**Comment by harryeffinpotter** [comment]
Wouldn't $~1 do that already?

**Comment by chrisant996** [comment]
> I launch many batch script . Is there a way you can modify the startup behaviour of clink to show the full path of the running script?

I don't understand the question.

Are you asking for a way for Clink to print the name of each Lua script it loads?  That would be very invasive and should not be done. 

Are you asking for a way for Clink to print the string from the [clink.autostart](https://chrisant996.github.io/clink/clink.html#clink_autostart) setting?  No.  That's something the script or command should do itself.

Are you asking something else?  Please describe further and include specific details.

**Comment by chrisant996** [comment]
Are you asking for CMD to show the name of each batch script that CMD runs?  Clink isn't involved in that.  Clink isn't a shell -- the shell is CMD.  Clink adds a scriptable prompt and extensive input line editing capabilities.  Everything else is still CMD.  I don't know of a way to make CMD print the name of every script it runs.

**Comment by darkzbaron** [comment]
@chrisant996  Yes that's it ! Ok noted thanks for the feedback
