### ISSUE TITLE
how to insert next word from auto-suggestion ?

### ISSUE THREAD

**Issue by Mitezuss** [chrisant996/clink#643]
need some configuration to complete word by word using "Tab" ?

for example:

![0](https://github.com/user-attachments/assets/cabbacb8-5253-4aa0-b3e4-f4213b944e71)

Type: **f** and press ??? to complete _first_
next: type **t** and press ??? to complete _two_
next: type **t** and press ??? to complete _tree_

result: first two tree

and write whatever:

first two tree newtext

**Comment by chrisant996** [comment]
Are you looking for the info in the "Completions" box at [Feature Highlights](https://chrisant996.github.io/clink/clink.html#features) in the documentation?

**Comment by chrisant996** [comment]
If not, then please describe what you're doing in more detail.

What have you tried?
What was the result?
What did you want instead?

What is your <kbd>Tab</kbd> key binding?  (Press <kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>/</kbd> and then <kbd>Tab</kbd> to see what's bound to <kbd>Tab</kbd>.)

**Comment by chrisant996** [comment]
> Type f
> ![2](https://private-user-images.githubusercontent.com/35956777/353993170-2bdb0920-84a7-4d7f-8431-9c54fc8a3900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzA0OTAsIm5iZiI6MTcyMjQ3MDE5MCwicGF0aCI6Ii8zNTk1Njc3Ny8zNTM5OTMxNzAtMmJkYjA5MjAtODRhNy00ZDdmLTg0MzEtOWM1NGZjOGEzOTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIzNTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyODYwODIxZDQ0M2JiYTU0NjczNjZjNDhhN2RhNmMyMmQxZGJiNTUzN2YyN2Q5ZjgyMjY5YjJiNGVlNDE5NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E8onxihOlMOCVdW-kFWrb87zefn8tzlP9k_NR7EDNpM)
> 
> if i press -> will have:
> ![3](https://private-user-images.githubusercontent.com/35956777/353993337-d7342f0b-23b5-4e38-9c94-2a2c7419fe12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzA0OTAsIm5iZiI6MTcyMjQ3MDE5MCwicGF0aCI6Ii8zNTk1Njc3Ny8zNTM5OTMzMzctZDczNDJmMGItMjNiNS00ZTM4LTljOTQtMmEyYzc0MTlmZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIzNTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMDhlN2E2NWQ0NDI5YzYzNmQyYWY5YjdjMzFmNzk0MDFjY2Y1YTg0M2Y5MzdlNjNmNTQyMzY0NmE0MTdiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gDKcfuh5dQUMs5ROK1qRROKfCvxbFH9a-bPloYea3qY)
> 
> but what need press to have:
> ![4](https://private-user-images.githubusercontent.com/35956777/353993548-a1f73983-5a8f-450c-b35e-cc4cdbc3c380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzA0OTAsIm5iZiI6MTcyMjQ3MDE5MCwicGF0aCI6Ii8zNTk1Njc3Ny8zNTM5OTM1NDgtYTFmNzM5ODMtNWE4Zi00NTBjLWIzNWUtY2M0Y2RiYzNjMzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIzNTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzhjZTA1OTM1ZGRlMjAzNWNkMDQ5N2U1YTEwZTc0ZWU2N2M1OTE3Yzg5MDI4ODBiMDRiNmEzZjMzZjNiYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G-WXMvT9sZc6JDvL0cNMGy9R6N5SePcqik5u_lc3JRc)

You're confusing [Auto-Suggestions](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) and [Completions](https://chrisant996.github.io/clink/clink.html#how-completion-works).

They're very (very) different features.

You said you type `->` but you must mean that you type the <kbd>Right</kbd> arrow key.

The <kbd>Right</kbd> arrow key is inserting the auto-suggestion (the gray text).
That's not Completion.

You want Completion.
Type <kbd>Tab</kbd> to invoke completion.

You said you want to type <kbd>Tab</kbd> for completion ... but it seems the problem is happening because you're typing <kbd>Right</kbd> instead of <kbd>Tab</kbd>.

**Comment by chrisant996** [comment]
You may want to just turn off the Auto-Suggestion feature.  Refer to the [Auto-Suggestions](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) documentation.

**Comment by chrisant996** [comment]
Ah, now I understand.

<kbd>Shfit</kbd>-<kbd>Right</kbd> inserts the next word from the **auto-suggestion**.

The mention of "complete" and "Tab" made it hard for me to figure out what the question was.
Auto-Suggestions and Completion are different features that work differently.

It's common and understandable to mix up the terminology.  But when the terminology is mixed up, then it can be very hard to figure out what was the intended meaning.  Sorry for not being able to understand.  And I recognize that probably trying to read the Clink documentation through a translator or in a second language probably also makes the documentation hard to use.
