### ISSUE TITLE
Loop bug fatal error

### ISSUE THREAD

**Issue by Mvkbesteu** [chrisant996/clink#645]
Hi, so ive tried to make clink autorun on cmd, but i did a mistake and ran

“clink —autorun set cmd.exe”
This created a infinite and unstoppable loop, of creating cmds and it crashes my pc everytime and autostarts everytime. I tried unininstalling clink but the error is still there.

how do i fix this? I cannot use my pc terminal without crashing my pc
( powershell works )

**Comment by Mvkbesteu** [comment]
I installed it using scoop, i used scoop uninstall + manually removed from scoop however i havent removed from the C:/ Program Files directory, does it store the files there even using scoop?

**Comment by Mvkbesteu** [comment]
Also, youre right that wasnt the exact syntax but it did contain clink autorun and at the end "cmd.exe" not sure how i got it to loop to infinite however.

**Comment by chrisant996** [comment]
> I installed it using scoop, i used scoop uninstall + manually removed from scoop however i havent removed from the C:/ Program Files directory, does it store the files there even using scoop?

I don't know how to interpret those statements.

I can understand why it could have seemed like trying to uninstall Clink might help, but instead that further exacerbated the problem.

You need to delete the CMD AutoRun regkey.

I did a quick internet search for that and found lots of information on how to do that, so I recommend trying that.  I would try to help more, except it's 3 AM in my time zone, and I need sleep.

(The problem at this point has nothing to do with Clink, apart from having used Clink as the way to manually tinker with the CMD AutoRun regkey.  That's dangerous, and I don't recommend manually tinkering with it -- `clink autorun install` is designed to take care of it for you without any manual tinkering or overrides.)

**Comment by Mvkbesteu** [comment]
I understand, and sorry for keeping you up i got a whole different timezone. Ill try to do what you've suggested and let you know later.

Thank you

**Comment by Mvkbesteu** [comment]
Fixed
