### ISSUE TITLE
How to remove startup messages from CMD and Clink?

### ISSUE THREAD

**Issue by Mvkbesteu** [chrisant996/clink#646]

**Comment by Mvkbesteu** [comment]
hi so i've got a question, could i somehow remove those lines at the startup of clink & cmd? so i can keep it more clean?

![image](https://github.com/user-attachments/assets/8b0aff95-5114-4250-8e1f-950e74c4f454)

**Comment by chrisant996** [comment]
The "Microsoft Windows" message is not coming from Clink, it's coming from CMD.
There isn't a way to tell CMD to always automatically suppress it, but the `cmd /k` flag suppresses it in an individual CMD invocation.
Or you could [add a startup script](https://chrisant996.github.io/clink/clink.html#gettingstarted_startupcmdscript) to run `cls` to clear the screen as part of Clink startup.

The copyright message question is covered in #622, #601, #594, #538, #458, #264, or #104.

A good place to start for getting to know Clink and some common configuration is [Getting Started[(https://chrisant996.github.io/clink/clink.html#getting-started).

I've added a new section [Startup Message](https://chrisant996.github.io/clink/clink.html#gettingstarted_logo) in the [Common Configuration](https://chrisant996.github.io/clink/clink.html#common-configuration) section of the documentation.

**Comment by chrisant996** [comment]
> I tried using $$cls at the end of the regkey and even make the terminal open a .bat that clears everything up and starts empty but both break clink for some reason or atleast not clink, but clink and starship it messes with the whole shell is not a starship problem though tried it without it.

A few things:
- Where did `$$cls` come from?  That's not Windows or CMD syntax.
- It's not a good idea to be manually trying to modify the AutoRun regkey.
- Without knowing what things were tried, I couldn't guess at what they were or what was problematic about them.  But the `$$cls` makes it sound like you might be trying to use Linux syntax on Windows.  That might be a contributor to why the experiments are running into problems.

I suggested [using a startup script](https://chrisant996.github.io/clink/clink.html#gettingstarted_startupcmdscript) (read the docs at the link) and having the script run `cls` inside it.  That definitely works.

**Comment by naxl** [comment]
> I tried using $$cls at the end of the regkey and even make the terminal open a .bat that clears everything up and starts empty but both break clink for some reason or atleast not clink, but clink and starship it messes with the whole shell is not a starship problem though tried it without it.

I believe I can share a workaround that has worked well for me. To adjust the Command Prompt shortcut, which can be found in one of the folders under C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs, you can modify the target to %windir%\system32\cmd.exe /k cls.

For adding an entry to the context menu for folders, you can edit the relevant registry key to use the following command as the program to open: C:\Windows\System32\cmd.exe /s /k pushd %V && cls. This will allow you to right-click and open the Command Prompt with your desired arguments.

Also keep in mind the warnings from @chrisant996  in #646 : 5 !

**Comment by neradp** [comment]
Hi, 
my autorun reg key: "C:\Program Files (x86)\clink\clink.bat" inject --autorun **--quiet** --profile ~\clink
clink.bat already calls cmd with \k switch:   start "Clink" cmd.exe /s **/k** ""%~dpnx0" inject %clink_profile_arg%%clink_quiet_arg%"
I set up default terminal app for windows : windows terminal
My cmd window is clean.
