### ISSUE TITLE
Incorrect shell type in the window title: `Windows PowerShell`

### ISSUE THREAD

**Issue by andry81** [chrisant996/clink#648]
If start a clean console window as `cmd.exe`, the title has an incorrect shell type.

OS: `Windows 8.1`

> clink info
```
version          : 1.6.18.80e2a3
injected         : clink_dll_x64.dll
system           : 6.3.09600.20778
codepage         : 1251
keyboard langid  : 1033
keyboard layout  : 00000409
```

**Comment by chrisant996** [comment]
> If start a clean console window as `cmd.exe`, the title has an incorrect shell type.

Specifically which way is being used to start a clean console window?

If the title bar says "Windows Powershell", then probably Windows Powershell was started, not cmd.exe.

Are you using Windows Terminal?  If so, then by default, starting Windows Terminal opens a Powershell tab.  That's configurable in Windows Terminal and isn't related to Clink.

**Comment by andry81** [comment]
> Specifically which way is being used to start a clean console window?

WIN+R, cmd.exe

> If the title bar says "Windows Powershell", then probably Windows Powershell was started, not cmd.exe.

No, Task Manager shows `cmd.exe`

> Are you using Windows Terminal?

No.

**Comment by chrisant996** [comment]
What is the full output from running `clink autorun show`?

I think there must be another program hooking into CMD AutoRun and changing the window title.

Or, does the issue go away if you turn off checking for updates by running `clink set clink auto update off`?

I do not experience this issue on Windows 8.1, and I've never heard of anything like this.  So I don't have any ready answers, and I'm trying to help you troubleshoot what's going on.

**Comment by andry81** [comment]
> Or, does the issue go away if you turn off checking for updates by running `clink set clink auto update off`?

Seems this is the cause.

**Comment by chrisant996** [comment]
> > Or, does the issue go away if you turn off checking for updates by running `clink set clink auto update off`?
> 
> Seems this is the cause.

That's strange; I'm not able to reproduce that on Windows 8.1.
There must be something more involved as well, which we haven't found yet.

What is the output from `clink autorun show`?

**Comment by chrisant996** [comment]
I finally found a way to reproduce the issue where Windows PowerShell on Win8.1 alters the title bar and doesn't restore it.  It seems to be an issue in PowerShell v4.0 that comes with Win8.1.  It does not occur in PowerShell v5.0 or higher, which come with Win10 or higher.

I'm adding a workaround to block PowerShell from being able to alter the title bar in the first place.
