### ISSUE TITLE
Cannot compile clink-1.1.23 source code in VS2017

### ISSUE THREAD

**Issue by jackL999** [chrisant996/clink#65]
I have been unable to compile the source code using any of the build types. The following shows errors in compiling /release /x64 in Visual Studio 2017. Do you have any project specific environment variables set?

**Problems are located in the following three files**
..\clink-1.1.23\clink\terminal\src\win_screen_buffer.cpp
..\clink-1.1.23\clink\app\src\history\history_db.cpp
..\clink-1.1.23\clink\lua\src\os_api.cpp

**Microsoft Docs on compile error codes and their definitions**
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-errors-c2000-c3999?view=msvc-150

**List of Specific Errors**

**Severity	Code	Description	Project	File	Line	Suppression State**
Error (active)	E0020	identifier "ENABLE_VIRTUAL_TERMINAL_PROCESSING" is undefined	clink_terminal	C:\Users\JL\Source\Repos\clink-1.1.23\clink\terminal\src\win_screen_buffer.cpp	116	_[note this error might be caused by not including the header debug.h where this identifier is defined]_
Error	C2672	'std::lower_bound': no matching overloaded function found	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1321	
Error	C2780	'_FwdIt std::lower_bound(_FwdIt,const _FwdIt,const _Ty &,_Pr)': expects 4 arguments - 3 provided	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1321	
Error	C3536	'nth': cannot be used before it is initialized	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1322	
Error	C2678	binary '!=': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1322	
Error	C2100	illegal indirection	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1322	
Error	C2664	'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>> std::vector<_Ty,std::allocator<_Ty>>::erase(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>)': cannot convert argument 1 from 'int' to 'std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>'	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1324	
Error	C2672	'std::lower_bound': no matching overloaded function found	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1334	
Error	C2780	'_FwdIt std::lower_bound(_FwdIt,const _FwdIt,const _Ty &,_Pr)': expects 4 arguments - 3 provided	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1334	
Error	C3536	'nth': cannot be used before it is initialized	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1335	
Error	C2678	binary '!=': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1335	
Error	C2100	illegal indirection	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1335	
Error	C2664	'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>> std::vector<_Ty,std::allocator<_Ty>>::erase(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>)': cannot convert argument 1 from 'int' to 'std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>'	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1336	
Error	C2065	'ENABLE_VIRTUAL_TERMINAL_PROCESSING': undeclared identifier	clink_terminal	c:\users\JL\source\repos\clink-1.1.23\clink\terminal\src\win_screen_buffer.cpp	116	
Error	C2660	'SetConsoleMode': function does not take 1 arguments	clink_terminal	c:\users\JL\source\repos\clink-1.1.23\clink\terminal\src\win_screen_buffer.cpp	116	
Error	C2039	'SystemStatusFlag': is not a member of '_SYSTEM_POWER_STATUS'	clink_lua	c:\users\JL\source\repos\clink-1.1.23\clink\lua\src\os_api.cpp	572	
Error	C2660	'lua_pushboolean': function does not take 1 arguments	clink_lua	c:\users\JL\source\repos\clink-1.1.23\clink\lua\src\os_api.cpp	572	
Error	LNK1181	cannot open input file 'C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\bin\release\clink_app_common_x64.lib'	clink_app_dll	C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\bin\release\clink_dll_x64.lib'	clink_app_exe	C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\bin\release\clink_app_common_x64.lib'	clink_test	C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\LINK	1

**Comment by chrisant996** [comment]
The first thing I see is that `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is undefined.

That suggests that the Windows SDK being used to compile the project is out of date. What Windows SDK version is being used?

**Comment by jackL999** [comment]
It was SDK 8.1 which is the default generated by premake5 vs2017. I have now changed everything to SDK 10.0.17763.0 . Rebuilding /final /x64 reduced the number of errors down to just two now. What STL are you using?

**Severity	Code	Description	Project	File	Line	Suppression State**
**Error (active)	E0304**	no instance of function template "std::lower_bound" matches the argument list	clink_app_common	C:\Users\JL\Source\Repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1321	
**Error (active)	E0304**	no instance of function template "std::lower_bound" matches the argument list	clink_app_common	C:\Users\JL\Source\Repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1334

**Comment by jackL999** [comment]
It was SDK 8.1 which is the default generated by premake5 vs2017. I have now changed everything to SDK 10.0.17763.0 . Rebuilding /final /x64 reduced the number of errors down 17 including 3 link errors. What STL are you using?

**Severity	Code	Description	Project	File	Line	Suppression State**
Error	C2672	'std::lower_bound': no matching overloaded function found	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1321	
Error	C2780	'_FwdIt std::lower_bound(_FwdIt,const _FwdIt,const _Ty &,_Pr)': expects 4 arguments - 3 provided	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1321	
Error	C3536	'nth': cannot be used before it is initialized	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1322	
Error	C2678	binary '!=': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1322	
Error	C2100	illegal indirection	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1322	
Error	C2664	'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>> std::vector<_Ty,std::allocator<_Ty>>::erase(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>)': cannot convert argument 1 from 'int' to 'std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>'	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1324	
Error	C2672	'std::lower_bound': no matching overloaded function found	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1334	
Error	C2780	'_FwdIt std::lower_bound(_FwdIt,const _FwdIt,const _Ty &,_Pr)': expects 4 arguments - 3 provided	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1334	
Error	C3536	'nth': cannot be used before it is initialized	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1335	
Error	C2678	binary '!=': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1335	
Error	C2100	illegal indirection	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1335	
Error	C2664	'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>> std::vector<_Ty,std::allocator<_Ty>>::erase(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>)': cannot convert argument 1 from 'int' to 'std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>'	clink_app_common	c:\users\JL\source\repos\clink-1.1.23\clink\app\src\history\history_db.cpp	1336	
Error	LNK1181	cannot open input file 'C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\bin\final\clink_app_common_x64.lib'	clink_app_dll	C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\bin\final\clink_dll_x64.lib'	clink_app_exe	C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\LINK	1	
Error	LNK1181	cannot open input file 'C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\bin\final\clink_app_common_x64.lib'	clink_test	C:\Users\JL\Source\Repos\clink-1.1.23\.build\vs2017\LINK	1

**Comment by chrisant996** [comment]
I've been using VS 2019 with latest Win10 SDK and latest MSVC SDK and STL.

When I get a chance I'll see if I can update the premake script to have correct dependencies for VS 2017, or possibly to use older downlevel stuff if necessary.  Though std::lower_bound doesn't seem like it should be version dependent...  🤨

**Comment by chrisant996** [comment]
Compiles cleanly now with VS2017 and Win8.1 SDK.
