### ISSUE TITLE
Update fails with Clink 1.6.19

### ISSUE THREAD

**Issue by d4k0** [chrisant996/clink#652]
I use [Cmder](https://github.com/cmderdev/cmder), which uses Clink internally. Today I used the `clink update` command to update from version 1.6.18 to 1.6.19, which worked.

However, when I now run `clink update` on version 1.6.19, I get the following error message:
```
~clink~/app/update.lua:106: attempt to index local 'line' (a number value)
The update attempt failed for an unknown reason.
```

The cause could be related to the following change:

https://github.com/chrisant996/clink/commit/261467549ca4473a5706155f12ee84e7c8d3e9b7

**Comment by chrisant996** [comment]
Oh man.  Thanks for reporting this.  I'll fix it ASAP.

**Comment by chrisant996** [comment]
Ugh.  I've deleted the v1.6.19 to prevent it from getting updated onto any more computers while waiting for v1.6.20 to finish building and uploading.

Any computer that has already updated to v1.6.19 will require a manual update, since the updater got broken.  😧

**Comment by d4k0** [comment]
Thanks for the quick fix!

**Comment by MagicAndre1981** [comment]
I also see this, here winget allows me to update:

```
C:\Windows\System32>clink update
~clink~/app/update.lua:106: attempt to index local 'line' (a number value)
The update attempt failed for an unknown reason.

C:\Windows\System32>winget upgrade --id chrisant996.Clink -e
Gefunden Clink [chrisant996.Clink] Version 1.6.20
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://github.com/chrisant996/clink/releases/download/v1.6.20/clink.1.6.20.00f214_setup.exe
  ██████████████████████████████  2.35 MB / 2.35 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert
```

**Comment by jczanfona** [comment]
How to manual update?

**Comment by MagicAndre1981** [comment]
> How to manual update?

under Windows 10 or 11 open cmd.exe as admin and run the command I've posted.

`winget upgrade --id chrisant996.Clink -e`

or download the installer as mentioned by Dr-Sparx

**Comment by chrisant996** [comment]
> > How to manual update?
> 
> under Windows 10 or 11 open cmd.exe as admin and run the command I've posted.
> 
> `winget upgrade --id chrisant996.Clink -e`
> 
> or download the installer as mentioned by Dr-Sparx

That only works if you originally used winget to install Clink.

**Comment by chrisant996** [comment]
# How to manually update Clink:

It depends on how you originally installed Clink.

- If you got Clink as part of Cmder, then download the latest zip file from https://github.com/chrisant996/clink/releases, and extract the files into your %CMDER_ROOT%\vendor\clink directory.
- If you installed Clink by running the Clink setup.exe program, then download the latest setup.exe file from https://github.com/chrisant996/clink/releases, and run it.
- If you used winget to install Clink, then use winget to update Clink.
- If you used scoop to install Clink, then use scoop to update Clink.
- If you installed Clink by extracting files from the Clink zip file, then download the latest zip from https://github.com/chrisant996/clink/releases and extract the files into your Clink program files directory (i.e. the same place where you extracted them originally).
