### ISSUE TITLE
Clink incorrectly shows certain commands as quoted

### ISSUE THREAD

**Issue by gamer191** [chrisant996/clink#654]
The command `echo "hi^"&calc"` will show everything after the word "echo" as quoted (yellow). This is incorrect, because the quotes escape the escape character, leaving the 2nd quote unescaped

This could be a minor security issue, as users could hypothetically be social engineered into running a command with an escaped end quote

**Comment by chrisant996** [comment]
Thanks for reporting this.

This led to finding lots of subtle quirks in parsing of `^` and `"` and `@` in various contexts.

**Comment by chrisant996** [comment]
Several recent commits have fixed this, and various related quirks.
