### ISSUE TITLE
Error in update.lua Script: Attempt to Index Local 'line' (a Number Value) at Line 106

### ISSUE THREAD

**Issue by naxl** [chrisant996/clink#655]
Issue Description:

I've been encountering the following error message each time I open the Command Prompt since this morning:

```
coroutine failed:
~clink~/app/update.lua:106: attempt to index local 'line' (a number value)
```

Could you please advise on how to resolve this issue?

**Comment by chrisant996** [comment]
Duplicate. Refer to #652.

**Comment by naxl** [comment]
Done! I've successfully upgraded to version 20. I realize I should have done this before raising an issue, but better late than never. Thanks for the fix!
