### ISSUE TITLE
the default ocmmand line experience allows wildcard based autocompletion on hitting tab key but after installing clink it doesn't

### ISSUE THREAD

**Issue by amithegde** [chrisant996/clink#656]
I usually use wildcard to autocomplete for example `*.zip` and hit tab to auto complete and then iterate over avaiable matches. After installing clink, this doesn't work any more. Please help look into.

**Comment by chrisant996** [comment]
Refer to [How Completion Works](https://chrisant996.github.io/clink/clink.html#how-completion-works).

**Comment by hutcho** [comment]
> I usually use wildcard to autocomplete for example `*.zip` and hit tab to auto complete and then iterate over avaiable matches. After installing clink, this doesn't work any more. Please help look into.

Yeah the clink default is a very different to how windows does tab. To return it back to normal, you have to manually turn off the clink "executable completion" behavior by running `clink set exec.enable false`

**Comment by chrisant996** [comment]
> > I usually use wildcard to autocomplete for example `*.zip` and hit tab to auto complete and then iterate over avaiable matches. After installing clink, this doesn't work any more. Please help look into.
> 
> Yeah the clink default is a very different to how windows does tab. To return it back to normal, you have to manually turn off the clink "executable completion" behavior by running `clink set exec.enable false`

It sounded like the OP installed Clink without Enhanced Defaults (maybe via winget or scoop), and wants menu-complete style of completion that works with wildcards and cycles through matches, instead of the bash style completion.

**Comment by amithegde** [comment]
> It sounded like the OP installed Clink without Enhanced Defaults (maybe via winget or scoop)

I installed via winget. wildcard based autocomplete works well for my workflow because the project I work on has many .sln files and hard to remember names. I just go to the directory enter *.sln, hit tab and then enter to open it.

**Comment by chrisant996** [comment]
> > It sounded like the OP installed Clink without Enhanced Defaults (maybe via winget or scoop)
> 
> I installed via winget. wildcard based autocomplete works well for my workflow because the project I work on has many .sln files and hard to remember names. I just go to the directory enter *.sln, hit tab and then enter to open it.

Yes.  The documentation link I shared covers the topic.
