### ISSUE TITLE
Incremental tab completion on auto-suggestion

### ISSUE THREAD

**Issue by chambm** [chrisant996/clink#658]
I love clink, thanks for maintaining it!

I often call executables that are several folders deep with different arguments. Clink often correctly autosuggests previous commands that start with those paths, but my only options at that point are to either accept the whole suggestion (including arguments) or continue typing all the folders until I can do traditional directory-contents-based tab completion. It would be even more helpful if I had a button that accepted the auto-suggestion incrementally, e.g. one space-separated token at a time, or one `char[] *args` token at a time if it's easy enough to process quoted tokens.

**Comment by chrisant996** [comment]
The documentation on the feature has that info. 🙂

**Comment by hutcho** [comment]
Use `ctrl+right arrow` instead of just `right arrow`

**Comment by chambm** [comment]
Fantastic! I did try lots of Ctrl/Alt/Shift combinations but evidently not the Ctrl-Right arrow one. :) I also read the docs but not the right one!
