### ISSUE TITLE
Not recieving 'a' key is down

### ISSUE THREAD

**Issue by trevorchaney** [chrisant996/clink#661]
I'm not able to input the 'a' key by itself. It appears to blink but nothing is written to the terminal. I can press 'A' (shift+a) and that registers but not 'a' by itself. I don't know if there is something wrong with my configuration. I have 'clink', 'clink completion', and 'clink flex prompt' installed and they were working fine in the past. I have tried the following

- Uninstall and reinstall
- Different version other than latest
- Different keyboard layout
- Install from different package managers (scoop and chocoloty)
- Different terminal applications (windows term and cmd)

I haven't done any configurations to clink other than running the flex prompt setup script

**Comment by chrisant996** [comment]
It sounds like there's likely a syntax error in a custom key binding.  But you said you haven't done any configuration in a `.inputrc` file. 

Try running `clink echo` and then press <kbd>a</kbd>.
What is printed on the screen after you do that? 
(Press <kbd>Ctrl-C</kbd> to exit from `clink echo` when finished.)

**Comment by trevorchaney** [comment]
- 'clink echo'
Type a key to see its key sequence string.
Press Ctrl+C when finished.
"a"
"a"
"a"
"b"
"b"
"b"
"A"
"A"
"A"
"B"
"B"
"B"
"\C-C"

- 'alt+shift+?'
W:\ ❯                                                                                                        1 20:09:51
A-? : clink-what-is -- Show the key binding for the next key sequence input.  If a numeric argument is supplied, the
raw key sequence string is shown instead of the friendly key name
W:\ ❯                                                                                                        1 20:09:51
a : key is not bound
W:\ ❯ 

- 'clink info'
PS C:\Users\tlc> clink info
version  : 1.6.21.f97375
session  : 5040
binaries : C:\Users\tlc\scoop\apps\clink\current
state    : C:\Users\tlc\AppData\Local\clink
log      : C:\Users\tlc\AppData\Local\clink\clink.log
settings : C:\Users\tlc\AppData\Local\clink\clink_settings
history  : C:\Users\tlc\AppData\Local\clink\clink_history
scripts  : C:\Users\tlc\scoop\apps\clink\current ; C:\Users\tlc\AppData\Local\clink ; C:\Users\tlc\scoop\apps\clink-flex-prompt\0.17;C:\Users\tlc\scoop\apps\clink-completions\0.5.4
inputrc  : %clink_inputrc%
             (unset)
         : state directory
             C:\Users\tlc\AppData\Local\clink\.inputrc
             C:\Users\tlc\AppData\Local\clink\_inputrc
         : %userprofile%
             C:\Users\tlc\.inputrc   (LOAD)
             C:\Users\tlc\_inputrc
         : %localappdata%
             C:\Users\tlc\AppData\Local\.inputrc
             C:\Users\tlc\AppData\Local\_inputrc
         : %appdata%
             C:\Users\tlc\AppData\Roaming\.inputrc
             C:\Users\tlc\AppData\Roaming\_inputrc
         : %home%
             C:\Users\tlc\.inputrc   (exists)
             C:\Users\tlc\_inputrc
system   : 10.0.22631.4037
codepage : 1252
keyboard langid : 1033
keyboard layout : 00010409

Found that C:\Users\tlc\.inputrc was loaded with a single line
alias hello='echo "Hello, World!"'

Apologizes, I removed that file and everything works again. I think I was looking at another program and wasn't aware that was being loaded by clink

**Comment by chrisant996** [comment]
Ah, yes, the .inputrc file has a very specific and limited format.  Shell commands cannot be inserted into that file, as it is not a shell script.

I'm glad it was fairly easy to track down!
