### ISSUE TITLE
color.env_variables option

### ISSUE THREAD

**Issue by nikitarevenco** [chrisant996/clink#666]
Hi, I would love to be able to specify in my config file a color for env variables like `%userprofile%` to stand out from other text.

**Comment by chrisant996** [comment]
Something like this?

If so, I would probably make it part of clink-completions, instead of building it directly into Clink.

#### _highlight_envvars.lua_
```lua
settings.add("color.envvars", "", "Color for environment variables")

local ev = clink.classifier(1)
function ev:classify(commands) -- luacheck: no unused
    local color = settings.get("color.envvars") or ""
    if color ~= "" and commands and commands[1] then
        local line_state = commands[1].line_state
        local classifications = commands[1].classifications
        local line = line_state:getline()
        local in_out = false
        local index

        for i = 1, #line do
            if line:sub(i, i) == "%" then
                in_out = not in_out
                if in_out then
                    index = i
                else
                    local value = os.getenv(line:sub(index + 1, i - 1))
                    if value then
                        classifications:applycolor(index, i + 1 - index, color)
                    else
                        in_out = true
                        index = i
                    end
                end
            end
        end
    end
end
```

**Comment by chrisant996** [comment]
P.S. I learned surprising things:

```cmd
C:\Foo> set "a b=hello"
C:\Foo> echo %a b%
hello

C:\Foo> echo %userprofile^%
%userprofile^%
C:\Foo> set userprofile^^=world
C:\Foo> echo %userprofile^%
world

C:\Foo> for %a in (abc def) do echo %a
abc
def
C:\Foo> set "a in (abc def) do echo =mercy! "
C:\Foo> for %a in (abc def) do echo %a
mercy! a was unexpected at this time.
```

Cmd.exe's environment variable parsing seems to be very simple and consistent.  /shrug

**Comment by nikitarevenco** [comment]
> ```batchfile
> set "a in (abc def) do echo =mercy! "
> ```

thanks for this!

tbf biggest mindblower to me is that env variables can have spaces in them

**Comment by chrisant996** [comment]
I'm adding it to clink-gizmos.

It can't handle delayed expansion.

**Comment by nikitarevenco** [comment]
> I'm adding it to clink-gizmos.
> 
> It can't handle delayed expansion.

oh ok ok!

**Comment by chrisant996** [comment]
I'll also look at adding some Lua APIs to be able to show expansion hints below the input line -- similar to what Clink does for [History Expansion](https://chrisant996.github.io/clink/clink.html#using-history-expansion).

Once APIs have been added, then the script can be extended to also show what an environment variable expands to, when the cursor is on the environment variable in the input line.

(And doskey aliases will be able to show expansion hints, and maybe even argmatchers might be able to show syntax hints for an argument position.)

**Comment by chrisant996** [comment]
@nikitarevenco The input hints stuff is close to being ready for release.

If you're interested to do some beta testing, let me know and I can send you a beta version.

**Comment by nikitarevenco** [comment]
> @nikitarevenco The input hints stuff is close to being ready for release.
> 
> If you're interested to do some beta testing, let me know and I can send you a beta version.

thanks for letting me know! I'm currently away and also not using Windows anymore..

I appreciate your work, best of luck!

**Comment by chrisant996** [comment]
"Input hinters" are introduced in 36286e2ec20a5907403c786262e00882e5bf5a93 and enable Lua scripts to show text under the input line.  For example, a new script in the clink-gizmos repo is able to use an input hinter to show the value of the environment variable under the cursor.
