### ISSUE TITLE
is there any way to use fzf as history list (ctrl + r)?

### ISSUE THREAD

**Issue by axeprpr** [chrisant996/clink#668]
is there any way to use fzf as history list (ctrl + r)?
https://github.com/junegunn/fzf
![image](https://github.com/user-attachments/assets/1ddcea36-4e06-45de-988d-9bf9692d2486)

**Comment by chrisant996** [comment]
Yes.  Refer to the Clink documentation.

[Popular Scripts](https://chrisant996.github.io/clink/clink.html#popular-scripts)
