### ISSUE TITLE
Set different history file location

### ISSUE THREAD

**Issue by parasiteoflife** [chrisant996/clink#669]
Please add a way to set the history file location that can be applied for the running instance of cmd. I'd like to keep commands separated from the main history file, I understand we can use `CLINK_PROFILE` but that sets the entire profile path, I want to use the same configurations, only the history file should be different.  

There is one env var for the settings (`CLINK_SETTINGS`), could you please add one for the history file?

**Comment by chrisant996** [comment]
I'm potentially open to that.

First, can you explain further?
Why does the directory need to be different?
Have you considered using [`CLINK_HISTORY_LABEL`](https://chrisant996.github.io/clink/clink.html#multiple-master-history-files)?

**Comment by chrisant996** [comment]
@parasiteoflife Can you respond to the questions?
