### ISSUE TITLE
How to disable inserting ^C  when Ctrl-C is pressed?

### ISSUE THREAD

**Issue by Abject-Web** [chrisant996/clink#674]
When Ctrl-C is pressed while the text cursor is on some text, it inserts a ^C. So `echo` becomes `e^Co`.
This seems to be introduced in 1.3.14. Is there anyway to disable it (at least when the cursor is in the middle of some text)?

**Comment by chrisant996** [comment]
It's controlled by Readline's [echo-control-characters](https://chrisant996.github.io/clink/clink.html#configechocontrolcharacters) configuration variable, which is `on` by default.

Fixing a variety of bugs in <kbd>Ctrl</kbd>-<kbd>C</kbd> handling got it working how Readline intended.  And at that point, it began to do the same thing as in bash, which is to by default print `^C`.

Turn off the configuration variable with the following line [in your .inputrc file](https://chrisant996.github.io/clink/clink.html#init-file):

```inputrc
set echo-control-characters off
```

**Comment by Abject-Web** [comment]
That worked, thanks!
