### ISSUE TITLE
[Question] How to install for PowerShell

### ISSUE THREAD

**Issue by milen-prg** [chrisant996/clink#678]
I use Windows 11 Pro 64bit Terminal, in cmd Clink works excellent. Is it possible to work also in PowerShell, where even the command clink is not recognizable:

PS C:\Users\User\Downloads\temp> clink
clink: The term 'clink' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by chrisant996** [comment]
Duplicate of #671.
