### ISSUE TITLE
Wanted: animated GIF showing some Clink features

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#68]
Wanted: animated GIF showing some Clink features, to be linked in the Readme.md and in the [Clink site](https://chrisant996.github.io/clink/).

Ideally two (or more) images:
1. One animated GIF showing attractive stock behavior (`complete`, maybe searching history via <kbd>Ctrl</kbd>+<kbd>R</kbd>, or a couple other commonly desirable behaviors).
2. Another image or images showing some of what's possible with some script addons, such as clink-completions or Oh My Posh! or z.lua or etc.

This is something I'll get around to at some point, but if the community would like to help this could be a good opportunity.

**Comment by rashil2000** [comment]
![hmm3](https://user-images.githubusercontent.com/46838874/110321387-9c5f9b00-8037-11eb-8ad4-5a05decb5878.gif)

This one shows basic autocomplete, path completion, Emacs-mode editing options, reverse-i-search, syntax-highlighting etc.

![hmm3](https://user-images.githubusercontent.com/46838874/110322796-a8e4f300-8039-11eb-9cc9-b7c71cc7b9a3.gif)

This one shows the external scripts cmder-powerline-prompt and clink-completions.

Let me know if I need to make anything else :)

**Comment by chrisant996** [comment]
Thank you for the prototype images!  They helped me identify some things:

I would like 2 images, around the size of the image at [mridgers/clink](https://mridgers.github.io/clink/).  They should compactly demonstrating a small number of features.  If it needs descriptive captions then it's overly complex -- the images should be glanceable.  I don't want real user names in them (I might create an account called "yourname" if I wanted to show something about c:\users, but I would probably just avoid it).  When showing completion capabilities, it should not show more than 2 lines of matches (make concise use of the visual media and viewers' cognitive attention).  The images should focus on clink itself, since they are for the clink site home page; showing 10-20 lines of output from other programs blurs the message of the screenshots.

One image will use only things built into clink and/or Windows -- it's for illustrating clink's abilities, not other programs, so that visitors can quickly understand what clink can do for them, to help them decide whether they're interested in trying it out.

Another image can be slightly more inspirational in nature, and show a few simple ways that clink can integrate with other programs.  These don't necessarily have to be in the image, but to illustrate the general kind of things I might have in mind here a few possibilities:  git status integration in a prompt, oh-my-posh prompt, fzf filtering (--height would have to be small), argmatcher capabilities i.e. generating matches for arguments and coloring the input line.

I will take a stab at it this afternoon and see if I can put together the first one.  I don't know for sure if I'll even use the second one.  For example maybe instead it would be better to have a 2- or 3-line animated image that cycles through several sample prompt configurations.  In fact, that does sound "right" for the clink site home page -- I'll try to put together a sort of animated collage this afternoon.

Thanks @rashil2000 for the time and thought putting together those images.  I can use them as-is, but they have been very helpful for figuring out what I'm looking for.  It's often easier to analyze something that exists, than to create something new from nothing.
