### ISSUE TITLE
Is the Clink supported or integrated(cmd.exe) within an APPX package??

### ISSUE THREAD

**Issue by win-19** [chrisant996/clink#683]
Hello, @chrisant996 Chris Antos

In an Electron app, if we try to use Clink inside the app or call cmd.exe, we face restrictions imposed by the sandboxing of the APPX package.

"We've encountered an issue with the Clink , which enhances cmd.exe. This limitation arises due to the sandboxing restrictions of the APPX format, which blocks the direct execution of native shell executables like cmd.exe. Since Clink relies on this integration, its functionality is restricted within the APPX environment.

Also when we created a .exe build with the electron app and installed our app with the clink library it was working fine but similarly, when we created an appx build with the electron app and installed our app with the clink library it's not working.

We also tried adding capabilities (Broad file System Access, runfulltrust, internet(client & Server)) and then we created an appx build with the electron app and installed our app with the clink library still not working.

Can you please tell us if is it possible to use or work the Clink library with the appx package?

**Comment by chrisant996** [comment]
You're asking me to spend hours learning about APPX and your specific app.  That doesn't seem realistic.

But Clink isn't a "library".  It's an executable which invasively injects a remote thread into a CMD.exe process.

You said APPX doesn't allow you to run CMD.exe.  If that's accurate, then that's the problem -- not Clink.

**Comment by chrisant996** [comment]
Also "it's not working" doesn't give my any information at all for troubleshooting.  If you share specific information and ask specific questions, I can probably help answer them.  But I can't just do all the work for you, especially when given zero actual information.  😉
