### ISSUE TITLE
Please make documentation easier to read when English isn't the reader's first language

### ISSUE THREAD

**Issue by NewUserHa** [chrisant996/clink#688]
there are hugh amount of users of `cmd`, `clink` has many features that can do, 
it would be good if `clink` has a homepage that demonstrates what it can do, and provides an easy to use get start. 

like https://starship.rs/presets having a page shows all the built-in prompt/theme that can let user know features, and make it easily choose and switch
like https://github.com/chrisant996/clink-flex-prompt. can make this built-in and set as default style, since it requires no extra overhead .exe to run each time
like https://github.com/chrisant996/clink-themes the repo is called themes but at the same time contained `.clinkprompt` and the readme section for installation of it statemented `2. clink installscripts c:\repos\clink-themes` but missing `3. use "clink config theme use ...` and `clink config prompt use ...`, and note "installscripts actually updates searching path in registry for clink" to get rid of unnecessary folder scan from clink 
like https://github.com/chrisant996/clink-gizmos and https://github.com/vladimir-kotikov/clink-completions these powerful functions should be in the homepage and make it built-in to let use to select from to enable, it is less than KBs and requires no disk space, this can make it easy to get start to use for new users 
like https://github.com/chrisant996/clink-fzf its readme says already being replaced by clink-gizmos, the repo itself can be achieved.to avoid confuse

**Comment by chrisant996** [comment]
> there are hugh amount of users of `cmd`, `clink` has many features that can do, it would be good if `clink` has a homepage that demonstrates what it can do, and provides an easy to use get start.

It has one.  I don't know why you're having trouble finding it.  The link to it is listed on the main github page of this repo.

> like https://starship.rs/presets having a page shows all the built-in prompt/theme that can let user know features, and make it easily choose and switch

Well sure.  Would you like to help make that?  Why does it have to be me who spends many hours to do that?  This is open source.

> like https://github.com/chrisant996/clink-flex-prompt. can make this built-in and set as default style, since it requires no extra overhead .exe to run each time

No.  For so many reasons, no.

> like https://github.com/chrisant996/clink-themes the repo is called themes but at the same time contained `.clinkprompt` and the readme section 

Both *.clinktheme and *.clinkprompt files go in the themes\ subdirectory.  I'm sorry you dislike the name and conventions I chose.  I don't have a problem with my decisions on that; they're not perfect, but they work and keep things simple.

> for installation of it statemented `2. clink installscripts c:\repos\clink-themes` but missing `3. use "clink config theme use ...` and `clink config prompt use ...`, 

Refer to the {More Information](https://github.com/chrisant996/clink-themes#more-information) section which points the reader at the actual Clink documentation.  And how did someone find the clink-themes site without knowing anything about `clink config prompt use` etc?

You're welcome to submit a PR with changes you'd like to see to the documentation, and I'll review and consider them.

> and note "installscripts actually updates searching path in registry for clink" to get rid of unnecessary folder scan from clink

The instructions are meant to be simple to write and simple to follow.  Can you explain why you're concerned about other people having an "unnecessary folder scan"?  What is the measured runtime cost of that extra folder scan?  Have you tried running [ProcMon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) to observe what file system accesses happen silently behind the scenes in programs?  I don't think the "unnecessary folder scan" is as bad as you might think.  If you have data to show otherwise, please share details.

> like https://github.com/chrisant996/clink-gizmos and https://github.com/vladimir-kotikov/clink-completions these powerful functions should be in the homepage 

I can't tell if you haven't found the Clink documentation, or if you haven't read it, or if you're saying you want it to be restructured, but aren't providing concrete feedback about how you want it structured.

https://chrisant996.github.io/clink/clink.html#popular-scripts

> and make it built-in to let use to select from to enable, it is less than KBs and requires no disk space, this can make it easy to get start to use for new users

I appreciate that you like some of the scrripts that have been shared so much that you want them to be built in.  But no, building all these repos directly into Clink is not what Clink is about, and would create a bunch of other problems.  Not to mention being a large amount of additional work for me, with little actual value (you might be forgetting that not everyone wants all of the scripts, and I'd have to add a lot of customization features for people to be able to individually turn on/off specific scripts and features, since if they're built in then that makes it much harder to disable built-in functionality).

I don't know why you'd suggest that building in a bunch more files and code into Clink "requires no disk space".  Of course it requires disk space, because they're included.  Data takes disk space.  Furthermore it would force everyone to have that disk space consumed.  And then some people will complain and want the things removed, to save disk space and to not force on them things they didn't want.

> like https://github.com/chrisant996/clink-fzf its readme says already being replaced by clink-gizmos, the repo itself can be achieved.to avoid confuse

[Note the "if" clause](https://github.com/chrisant996/clink-fzf/#:~:text=If%20you%20use%20clink%2Dgizmos%2C).  You're assuming everyone who wants to use fzf also wants everything in clink-gizmos.  But that isn't the case.

**Comment by NewUserHa** [comment]
it's just one purpose to make it better 
I installed clink before but hadn't thought clink has so many features. for example github.com/chrisant996/clink/issues/206 also agrees.

> It has one. I don't know why you're having trouble finding it. The link to it is listed on the main github page of this repo, and in many other places.

of course have read https://chrisant996.github.io/clink/ but compared to https://ohmyposh.dev/ https://starship.rs/, clink does not lose to them on features 

> No. For so many reasons, no.

this is to similar to https://ohmyposh.dev/docs/themes https://starship.rs/presets/ but for cmd

> Refer to the [More Information](https://github.com/chrisant996/clink-themes#more-information) section which points the reader at the actual Clink documentation. And how did someone find the clink-themes site without knowing anything about clink config prompt use etc?

release note of v1.7.2 "...The new [clink-themes](https://github.com/chrisant996/clink-themes) repo is a site where .clinktheme and .clinkprompt files can be shared (see [Contributing](https://github.com/chrisant996/clink-themes#contributing) for details on how to contribute your own themes and prompts)."

> Can you explain why you're concerned about other people having an "unnecessary folder scan"?

the common open source software eg vim neovim and even oh-my-posh and starship, use a config file on disk to control the settings, while clink also support file config, but the registry explanation only exists in documentation, while commonly users just used the command from the readme like extracted to some random folders

> or if you're saying you want it to be restructured, but aren't providing concrete feedback about how you want it structured.

those are extensions that rich clink more, it can be like https://ohmyposh.dev/ https://starship.rs/ to list them on main page

> I don't know why you'd suggest that building in a bunch more files and code into Clink "requires no disk space".

it's just one possible method to make clink more easy to use. it's only ~300kb after extracted, compared to the binaries compiled by golang. bundle with installer, or make it easy for users and new users to know and to download, and to enable the functions, will increase the Convenience to get start to use 

> [Note the "if" clause](https://github.com/chrisant996/clink-fzf/#:~:text=If%20you%20use%20clink%2Dgizmos%2C). You're assuming everyone who wants to use fzf also wants everything in clink-gizmos. But that isn't the case.

fzf.lua can also be downloaded individually from https://github.com/chrisant996/clink-gizmos, it can reduce the need to read another readme to know if any difference underhood  for non english users

**Comment by chrisant996** [comment]
> it's just one purpose to make it better I installed clink before but hadn't thought clink has so many features. for example github.com/[/issues/206](https://github.com/chrisant996/clink/issues/206) also agrees.

Yes, I know.  This is open source.  I welcome contributes.  I don't always welcome requests for me to a bunch of additional work that anyone else could do instead.

<br/>

> > > like https://github.com/chrisant996/clink-flex-prompt. can make this built-in and set as default style, since it requires no extra overhead .exe to run each time
> >
> > No. For so many reasons, no.
> 
> this is to similar to https://ohmyposh.dev/docs/themes https://starship.rs/presets/ but for cmd

I think you misread my replies.

I said "No" in response to "make clink-flex-prompt built into Clink".

I said "Would you like to help make that?" in response to "having a page shows all the built-in prompt/theme".

<br/>

> > Refer to the [More Information](https://github.com/chrisant996/clink-themes#more-information) section which points the reader at the actual Clink documentation. And how did someone find the clink-themes site without knowing anything about clink config prompt use etc?
> 
> release note of v1.7.2 `...The new [clink-themes](https://github.com/chrisant996/clink-themes) repo is a site where .clinktheme and .clinkprompt files can be shared (see [Contributing](https://github.com/chrisant996/clink-themes#contributing) for details on how to contribute your own themes and prompts).`

The release notes mention `clink config prompt use` and `clink config theme use`.

I'm not going to redundantly document the same info in lots of places that the reader has already read.  Or if the reader hasn't read the documentation, then that's not my problem.  😉

<br/>

> > Can you explain why you're concerned about other people having an "unnecessary folder scan"?
> 
> the common open source software eg vim neovim and even oh-my-posh and starship, use a config file on disk to control the settings, while clink also support file config, but the registry explanation only exists in documentation, while commonly users just used the command from the readme like extracted to some random folders

That didn't answer my question about why you're concerned about "unnecessary folder scan".  You're giving a theoretical concern -- I'm saying it is not an actual real world concern, and that you cannot even notice the difference.  And that if you use ProcMon to look at file system accesses, you may learn surprising things about performance.  If you think the "unnecessary folder scan" is a problem, show the data and analysis to support the theoretical claim.

I'm not going to document all 13 ways you can tell Clink how to find various kinds of files.  I picked one that's easy to write and easy to follow.

<br/>

> > or if you're saying you want it to be restructured, but aren't providing concrete feedback about how you want it structured.
> 
> those are extensions that rich clink more, it can be like https://ohmyposh.dev/ https://starship.rs/ to list them on main page

They're already listed.  There is tons of stuff that can be configured.  I cannot fit everything into a tiny spot in the Getting Started section.  It has links to more info.  The information is already overwhelming to people, and you're suggesting to add even more, and you don't seem to have noticed the links that already exist.  I think you're kind of proving my point.  😉

> > I don't know why you'd suggest that building in a bunch more files and code into Clink "requires no disk space".
> 
> it's just one possible method to make clink more easy to use. it's only ~300kb after extracted, compared to the binaries compiled by golang. bundle with installer, or make it easy for users and new users to know and to download, and to enable the functions, will increase the Convenience to get start to use

I don't know what you're trying to say.  Golang has nothing to do with the Clink script repos that you want me to build into Clink.

Just like bash and zsh and fish haven't build every theme and every prompt and every function and every plugin and etc into those shells.

Clink is built to be modular.  If you want additional scripts, add them.

<br/>

> > [Note the "if" clause](https://github.com/chrisant996/clink-fzf/#:~:text=If%20you%20use%20clink%2Dgizmos%2C). You're assuming everyone who wants to use fzf also wants everything in clink-gizmos. But that isn't the case.
> 
> fzf.lua can also be downloaded individually from https://github.com/chrisant996/clink-gizmos, it can reduce the need to read another readme to know if any difference underhood for non english users

I empathize with reading a foreign language.  The request is too invasive and creates too many problematic side effects.

**Comment by chrisant996** [comment]
I appreciate the feedback.

All of the things have been discussed multiple times in the past, and I'm not going to discuss them further here, except for the new request "show screenshots of themes in the online documentation".

I agree it would be great to have that in a web page, without needing to run `clink config theme list` and `clink config theme show` and etc.  But it's a lot of additional time and effort to create that web page and make screen shots and etc.

I welcome help from someone who would like to contribute to the Clink project in that way.  It gets tiring to be doing 100% of the work myself, and only receive requests to do even more work.  I'd like help once in a while.

**Comment by chrisant996** [comment]
> and note "installscripts actually updates searching path in registry for clink" to get rid of unnecessary folder scan from clink

Also, the suggestion makes a mistaken assumption that no Lua scripts will be added to the main repo directory.

But at least one script will be added, to include some functions which prompts can use.  Such as `get_virtualenv_text()` and `get_duration_text()` and so on.

The choice of suggesting `clink installscripts` was very intentional.  And the cost is in microseconds, or maybe milliseconds if you have a slow rotational drive instead of a solid state drive.

(And there are good reasons to not build that script directly into Clink.)

**Comment by NewUserHa** [comment]
I found `installscripts` is heavily used in `clink`, it works very well, no lantency.
the original post text mainly says about writing registry now days but since auto_run also needs to write registry to work, write registry has no issue

**Comment by chrisant996** [comment]
> the original post text mainly says about writing registry now days but since auto_run also needs to write registry to work, write registry has no issue

It's a one-time write to the registry, and takes microseconds.

And the registry reads take microseconds (or less).

And there are _TONS_ of registry reads and file system reads happening that have nothing to do with Clink.

In modern computing systems, these are not performance concerns.  30 years ago they were, and maybe even 25 years ago.  But not in modern times.

**Comment by plutonium-239** [comment]
I might be able to help with the displaying included themes and prompts - although not right away.
I think a simple 
```md
## heading 
one-line description 
image
``` 
should do the job

Would you like those to be on the homepage itself or part of a markdown file that we link to? (since the homepage doesn't have any images currently)

**Comment by chrisant996** [comment]
> I might be able to help with displaying the included themes and prompts, although not right away.
> I think a simple 
> ```md
> ## heading 
> one-line description 
> image
> ``` 
> should do the job (similar to starship; oh-my-posh doesn't give descriptions)
> 
> Would you like those to be on the homepage itself or part of a markdown file that we link to? (since the homepage doesn't have any images currently)

@plutonium-239 Thanks for offering!  That's a good question...  Probably a new linked markdown file is best (similar to how the clink-themes repo does it).  After they're in, then I can easily copy (or move??) them into the documentation site as well.

This is probably obvious, but use Windows Terminal when making the images, for best results with icons and colors.

**Comment by plutonium-239** [comment]
@chrisant996 yes, I use wt exclusively 

Btw, should I be using the default theme (in wt - Campbell) while taking the screenshots, or does it not matter? (if all colors are true color codes not ansi ones which depend on the terminal's set colors)

**Comment by chrisant996** [comment]
> Btw, should I be using the default theme (in wt - Campbell) while taking the screenshots, or does it not matter? (if all colors are true color codes not ansi ones which depend on the terminal's set colors)

It's another good question...!

Campbell seems reasonable -- I don't think there's any objective "right" or "wrong" color theme (though Solarized probably wouldn't be ideal for samples 😉).

For scale and sizing purposes, probably 80 columns is ideal?  And font size between 10-12pt?  I'm open to other thoughts...

<br/>
<br/>

_Eventually it could be interesting to include a demo of a couple prompts using Light color themes (or Blue, e.g. with the Tomorrow Night Blue.clinktheme), and maybe even corresponding terminal color theme files or json snippets.  But that gets complicated quickly, and I'm not sure I want Clink docs to include tutorials about color themes and how ANSI colors work and how to configure various different terminal programs.  Anyway, these can wait for later (and maybe/probably never)._

**Comment by chrisant996** [comment]
I've added an `--all` flag to show all themes or prompts (commit 56954879b7e1afe8e78b1496fd833531956cbc77):

- `clink config theme show --all`
- `clink config prompt show --all`

The flag loops through all installed themes or prompts and shows each one.  It's not as convenient as a web page for seeing previews.  But it can do something a web page cannot, which is show previews for all installed themes/prompts, including ones that aren't part of the Clink distribution.

I'm considering maybe adding previews into the Clink documentation, but there's a catch:  Currently the Clink documentation is a single file and has no images.  If I were to add images then copying only clink.html would result in breaking the documentation file, and that's not ok.  I'm considering alternatives -- for example, maybe the clink.html file could have a link to a web page listing previews.

**Comment by chrisant996** [comment]
The doc updates are live here:  https://chrisant996.github.io/clink/clink.html#custom-prompts

I'd still like to find a way to strip unused characters from the font (without a ton of effort) to reduce the downloaded bytes.  But overall it's worth publishing as-is in the meantime.
