### ISSUE TITLE
is it possiable to disable clink in child cmd.exe

### ISSUE THREAD

**Issue by iamqiz** [chrisant996/clink#700]
I put ` clink inject ` in my cmd autorun bat to run clink automatically,
and due to that cmd autorun will be ran by `for /f ` comand (see https://ss64.com/nt/syntax-autoexec.html),
so this increase the time consumption of  `for /f` command 

so i hope `clink inject` do nothing in child cmd.exe that is started by `for /f`,
it it possible ?
thanks!
ref:
https://stackoverflow.com/questions/62849024/make-batch-for-f-ignore-registry-autorun
> You can use the for /f command to parse the output of a command by placing a back-quoted between the parentheses. It is treated as a command line, which is passed to a child Cmd.exe. The output is captured into memory and parsed as if it is a file.

> Unfortunately, for /F uses cmd /C to start sub-commands, in contrast to pipes (|), which use cmd /S /D /C for either side, and /D disables such auto-start things…  – aschipfl

**Comment by iamqiz** [comment]
actually, `clink inject ` have lower time consumption than other many `doskey` commands in cmd autorun batch file,
so this problem is not very serious😀

**Comment by chrisant996** [comment]
`clink inject` checks whether the `cmd.exe` instance was started with a command line that will cause it to become interactive.  If not, then the `clink inject` command cancels and does not actually inject Clink.  See [source code here](https://github.com/chrisant996/clink/blob/8e4e56728744058379d045ece90d0e088dfd626e/clink/app/src/loader/inject.cpp#L330-L357).

**Comment by chrisant996** [comment]
P.S.  You are using a custom approach to making Clink autorun.  That's perfectly fine.

But if you used Clink's built-in autorun capability then you could have used `set CLINK_NOAUTORUN=1` at the beginning of your batch script to make the autorun cancellation run even more quickly (and add `set CLINK_NOAUTORUN=` at the end of the batch script to restore normal autorun behavior).  Or if you change your `clink inject` to `clink inject --autorun`, then you could use the `CLINK_NOAUTORUN` environment variable even with your custom autorun mechanism.

**Comment by iamqiz** [comment]
@chrisant996  good idea! thanks! 
by setting a variable before `for` or at the beginning of batch script, I can skip all autorun commands(including clink) when call `for` just check that variable is set or not in autorun bat file.
