### ISSUE TITLE
`clink update` reports `Already up-to-date` even if has no internet

### ISSUE THREAD

**Issue by andry81** [chrisant996/clink#702]
If try to block `powershell.exe` and `clink*.exe` in a firewall or disconnect the adapter, then anyway it reports `Already up-to-date`.

**Comment by chrisant996** [comment]
You didn't say what you expect it to do instead.

It's working as intended:
The latest version it found in earlier checks is the same as the version you're already running.
So it treats the network (or etc) error as non-fatal, and it reports that the latest version it knows about is the same as the version you're using.

If you look in the `clink.log` file then you'll see the errors that maybe you might have been hoping to see.

The `clink update` command is not meant to help with network diagnostics, etc.
If there's an ongoing problem with the network or blocked software, then that's something to troubleshoot outside of Clink.

**Comment by andry81** [comment]
> You didn't say what you expect it to do instead.

Report a connection error?

**Comment by chrisant996** [comment]
For more context on why it behaves this way, see [here](https://github.com/chrisant996/clink/issues/441#issuecomment-1740413871) and [here](https://github.com/chrisant996/clink/issues/441#issuecomment-1740476085).

(Also see [here](https://github.com/chrisant996/clink/issues/528#issuecomment-1834072924).)
