### ISSUE TITLE
Make it more clear in docs how to add "autorun" lua files  

### ISSUE THREAD

**Issue by AntonBogun** [chrisant996/clink#703]
I tried pretty much everything I could think of to get the lua file I made in a custom folder to autorun on clink start and almost went into despair but then searched for for .clinkprompt mentions and then found *a single line* (except in the changelog) mentioning, *without even having the word autorun*, to add the file into `CLINK_CUSTOMPROMPT`.

That is the only time `CLINK_CUSTOMPROMPT` is mentioned throughout the entire doc, and verbatim:
- To activate a custom prompt, run `clink config prompt use prompt_name` which will load and use the named prompt, as well as update the settings accordingly in the current Clink profile. Or set the `CLINK_CUSTOMPROMPT` environment variable to the name or full path and filename of a .clinkprompt file.

This only implicitly states that it would end up autorunning the lua file, and to an untrained eye may resemble just a way to alternatively run the lua file after startup.

I reckon it would be good to reword this in a clearer way.

**Comment by AntonBogun** [comment]
Also, it is unclear if it is also necessary to expose the folder in which the .clinkprompt file is in through the other methods mentioned in the docs, or if simply specifying `CLINK_CUSTOMPROMPT` on its own is enough.

**Comment by AntonBogun** [comment]
Also, does clink provide any nice way to load macro .bat files? I tried to look through the docs but didn't seem to find anything related. And I don't believe the lua scripting can do everything that a macro definition can based on the docs (unless I'm missing something).

The typical method of adding autorun persistent macro files also involves overwriting the autorun registry, which I saw contained the startup for clink so I imagine this is something clink ought to expose.

**Comment by chrisant996** [comment]
> I tried pretty much everything I could think of to get the lua file I made in a custom folder to autorun on clink start 

Where is the "custom folder"?  I think you must have somehow missed [Location of Lua Scripts](https://chrisant996.github.io/clink/clink.html#lua-scripts-location).

It's the first thing in the [Extending Clink With Lua](https://chrisant996.github.io/clink/clink.html#extending-clink) section, so I don't know how to make the documentation more clear.

The `CLINK_CUSTOMPROMPT` documentation has nothing to do with your situation, other than by specifying a full path to a Lua file you worked around the fact that Clink has no knowledge of your custom folder, unless you tell Clink about the custom folder.  Refer to [Location of Lua Scripts](https://chrisant996.github.io/clink/clink.html#lua-scripts-location) for more info.

**Comment by chrisant996** [comment]
> Also, does clink provide any nice way to load macro .bat files? I tried to look through the docs but didn't seem to find anything related. And I don't believe the lua scripting can do everything that a macro definition can based on the docs (unless I'm missing something).
> 
> The typical method of adding autorun persistent macro files also involves overwriting the autorun registry, which I saw contained the startup for clink so I imagine this is something clink ought to expose.

I've never heard "macro .bat file" before.  Maybe you mean a batch script that runs `doskey` commands; but a batch script can run any commands and isn't limited to just running `doskey`.

[Startup Cmd Script](https://chrisant996.github.io/clink/clink.html#gettingstarted_startupcmdscript).

> The typical method of adding autorun persistent macro files also involves overwriting the autorun registry

Run `clink autorun --help` for help on the `clink autorun` command.

Do whatever you would normally do to modify CMD's AutoRun regkey, and then run `clink autorun install` to registry to _**also**_ autorun Clink.
