### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by tapochek666** [chrisant996/clink#707]
How to run clink without a profile?

**Comment by chrisant996** [comment]
Not possible.

**Comment by tapochek666** [comment]
It's a pity

вс, 24 нояб. 2024 г. в 10:40, Chris Antos ***@***.***>:

**Comment by tapochek666** [comment]
I'm talking about this text
![https___qiita-image-store s3 ap-northeast-1 amazonaws com_0_1670622_ec6ff182-87fb-e851-8521-2eaf67f29a55](https://github.com/user-attachments/assets/4212f33b-87bb-456b-9e16-268f8a88a911)

**Comment by tapochek666** [comment]
That's it. I figured it out myself. Who knew that it was called "Startup Message"... I removed it with the command "clink set clink.logo none". You can close the this issue.
