### ISSUE TITLE
[Feature Request] Separate Environment Variable for History File Location

### ISSUE THREAD

**Issue by ss005** [chrisant996/clink#708]
First of all, thank you for creating such an awesome project! 
I've been using clink, flex-prompt, and clink-completions, they are really great, save lot of time and make terminal so much enjoyable.

Coming to this feature request:
I am aware that this feature has been requested before, and CLINK_PROFILE environment variable is already there to configure location for all clink profile related files.
However, I mainly want to synchronize the history file across multiple computers so I can easily access previously used commands from any machine.

Currently, I achieve this by setting the CLINK_PROFILE location to a folder in OneDrive.
This works but with some issues:
- All profile-related files, including temporary files e.g. clink_history_12345, clink_history_12345.removal etc, are synced to OneDrive which I don't need.
- Sync conflicts and errors: OneDrive tries to sync all the files including temporary files that are in use, leading to sync errors
- Recycle bin clutter: these temporary/.removals files occasionally end up in the recycle bin due to the sync process I believe

To address these issues, I propose for a separate environment variable (probably CLINK_HISTORY_FILE) for synchronizing history.

Thank you! Let me know if there is any way to achieve this or any additional details are needed.

**Comment by chrisant996** [comment]
Related:  #233, #310, #385, #669

**Comment by ss005** [comment]
Thank you for your detailed explanation, it helped me realize this is more complex than I assumed initially, specially while multiple computers are used at the same time.

> Commands from one computer aren't necessary relevant or usable on another computer.

Maybe this is my specific use case, but I often find myself repeatedly using the many long commands across multiple computers and history/auto-completion helps a lot in this case when I switch PC (I don't have to save those command somewhere or find again on internet and everything is backed up, _so convenient_).

I think I should investigate more about this before making further suggestion, meanwhile I'll explore to create some custom script for my specific use case. This feature request can be closed for now.

Thank you once again!
