### ISSUE TITLE
`~` does not expand in `cd`

### ISSUE THREAD

**Issue by jtnord** [chrisant996/clink#709]
tab no longer(/does not) expands `~` when used with a `cd` command (cmd.exe).

steps to reproduce

`cd ~<tab>`

expected output

`cd c:\users\username`

actual

`cd ~`

note that `cd ~\` does autocomplete/expand and replace with the expected output.

the tilde does cause expansion with `dir` and other commands.
(I am not entirely sure this is a regression, but I do have a recollection of this working in the past)

**Comment by chrisant996** [comment]
Thanks for reporting this.

The regression was introduced in v1.3.36 while fixing a different tilde issue.

**Comment by rodboev** [comment]
This doesn't appear to work:

C:\>cd ~
The system cannot find the path specified.
