### ISSUE TITLE
Exe tutorial/guide recommendation. (Feature request).

### ISSUE THREAD

**Issue by marklwembe** [chrisant996/clink#71]
Can anyone recommend a guide/tutorial on how to make a setup.exe file kind of like the ones [mridgers](github.com/mridgers/) had for v0.1 to v0.4.9 of Clink. I would really appreciate it. I have only a basic knowledge of C but I would love to use this as a learning opportunitiy.

**Comment by chrisant996** [comment]
Clink uses NSIS to produce an installer.
- If you're looking for how to generate installers for something else, consider reading up on NSIS.
- If there's an unstated request to generate an installer for Clink, I've been intentionally not publishing the installer yet, but Clink's premake5 scripts do have the ability to produce an installer.
