### ISSUE TITLE
Why does TAB say "The system cannot find the path specified"?

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#714]
_Originally posted by @rodboev in https://github.com/chrisant996/clink/issues/709#issuecomment-2562043899_

This doesn't appear to work:

```
C:\>cd ~<tab>
The system cannot find the path specified.
```

cd ~\ does work:

```
C:\>cd C:\Users\Rod\.apt\

C:\Users\Rod\.apt>
```

Not sure why it changes to the first folder in the user folder.

**Comment by chrisant996** [comment]
_Note: I moved this to a new issue, because it's a very different problem than issue 709._

<br/>

> This doesn't appear to work:
> 
> ```
> C:\>cd ~<tab>
> The system cannot find the path specified.
> ```

@rodboev You have <kbd>Tab</kbd> bound to some command that is trying to run a program, but the program does not exist.

Maybe you installed either clink-fzf or clink-gizmos and configured Clink to use the `fzf` program for completions, but the `fzf` program is not in your system PATH?

If you'd like help figuring out what's going wrong, please share the following:
- Your `.inputrc` file.
- The full output from running `clink set`.

> cd ~\ does work:
> 
> ```
> C:\>cd C:\Users\Rod\.apt\
> 
> C:\Users\Rod\.apt>
> ```
> 
> Not sure why it changes to the first folder in the user folder.

This is normal and correct.

Because <kbd>Tab</kbd> does completion; expanding `~` is just a side effect.

- When pressing <kbd>Tab</kbd> after only `~` (without a `\` after it) there is only one possible matching completion, so it gets immediately inserted.
- When pressing <kbd>Tab</kbd> after `~\` means "complete files or directories under the `~` directory".  And since the `~` got expanded, it has the effect of both expanding the `~` and also inserting a completion.

**Comment by rodboev** [comment]
I don't have a `.inputrc` file on disk, and `clink set` returns:

```
argmatcher.show_hints             True
autosuggest.async                 True
autosuggest.enable                True
autosuggest.hint                  True
autosuggest.original_case         True
autosuggest.strategy              match_prev_cmd history completion
clink.autostart
clink.autoupdate                  check
clink.colorize_input              True
clink.customprompt
clink.default_bindings            windows
clink.logo                        full
clink.max_input_rows              0
clink.paste_crlf                  crlf
clink.path
clink.popup_search_mode           find
clink.promptfilter                True
clink.update_interval             5
cmd.admin_title_prefix
cmd.altf4_exits                   True
cmd.auto_answer                   off
cmd.ctrld_exits                   False
cmd.get_errorlevel                True
color.arg                         bold
color.arginfo                     sgr 38;5;172
color.argmatcher                  sgr 1;38;5;40
color.cmd                         bold
color.cmdredir                    sgr 38;5;172
color.cmdsep                      sgr 38;5;135
color.comment_row                 sgr 38;5;87;48;5;18
color.common_match_prefix
color.description                 sgr 38;5;39
color.doskey                      sgr 1;38;5;75
color.executable                  sgr 1;38;5;33
color.filtered                    bold
color.flag                        sgr 38;5;117
color.hidden                      sgr 38;5;160
color.histexpand                  sgr 97;48;5;55
color.horizscroll                 sgr 38;5;16;48;5;30
color.input                       sgr 38;5;214
color.interact                    bold
color.message                     default
color.modmark
color.popup
color.popup_border
color.popup_desc
color.popup_footer
color.popup_header
color.popup_select
color.popup_selectdesc
color.prompt
color.readonly                    sgr 38;5;28
color.selected_completion         sgr 7
color.selection                   sgr 38;5;16;48;5;179
color.suggestion
color.unexpected                  default
color.unrecognized                sgr 38;5;203
comment_row.hint_delay            500
comment_row.show_hints            False
debug.log_output_callstacks       False
debug.log_terminal                False
directories.dupe_mode             add
doskey.enhanced                   True
exec.aliases                      True
exec.associations                 False
exec.commands                     True
exec.cwd                          True
exec.dirs                         True
exec.enable                       True
exec.files                        False
exec.path                         True
exec.space_prefix                 True
files.hidden                      True
files.system                      False
history.auto_expand               True
history.dont_add_to_history_cmds  exit history
history.dupe_mode                 erase_prev
history.expand_mode               not_quoted
history.ignore_space              True
history.max_lines                 25000
history.save                      True
history.shared                    False
history.show_preview              True
history.sticky_search             False
history.time_format               %F %T
history.time_stamp                show
lua.break_on_error                False
lua.break_on_traceback            False
lua.debug                         False
lua.path
lua.strict                        True
lua.traceback_on_error            False
match.coloring_rules
match.expand_abbrev               True
match.expand_envvars              True
match.fit_columns                 True
match.ignore_accent               True
match.ignore_case                 relaxed
match.max_fitted_matches          0
match.max_rows                    0
match.preview_rows                5
match.sort_dirs                   with
match.substring                   True
match.translate_slashes           auto
match.wild                        True
prompt.async                      True
prompt.spacing                    normal
prompt.transient                  off
readline.hide_stderr              False
terminal.adjust_cursor_style      True
terminal.color_emoji              auto
terminal.differentiate_keys       False
terminal.east_asian_ambiguous     auto
terminal.emulation                auto
terminal.mouse_input              auto
terminal.mouse_modifier
terminal.raw_esc                  False
terminal.scrollbars               True
terminal.use_altgr_substitute     False
```

I haven't changed any defaults, I don't know what `clink-fzf` or `clink-gizmos` are. Let me know if I can provide more info. Thanks.

**Comment by chrisant996** [comment]
@rodboev This is very surprising and mysterious, so I wonder if there may be additional context that hasn't been identified yet.

Can you please share a few things:

1. Can you share the full output from running `clink info`?
2. Can you describe how you installed clink?
    - Did you manually extract files from the .zip file?  If so, where did you put them?
    - Did you install clink by running the setup .exe installer?
    - Did you install clink by using `scoop` or `winget`?
    - Did you install clink by installing Cmder?
    - Did you install clink by installing Tabby?
3. Does the problem still happen after you ran `clink update` and start a _new_ cmd window?
4. Can you confirm that the following steps are how you encounter the problem?
    1. Install a fresh copy of Clink, with no additional scripts and no additional configuration.
    2. Start a cmd window.
    3. Type `cd ~` and then press <kbd>Tab</kbd>, and immediately the text is printed "The system cannot find the path specified." before any other keys are pressed (especially without pressing <kbd>Enter</kbd>).

**Comment by chrisant996** [comment]
@rodboev Do you have something installed that replaces the `cd` command?  Such as a tool like z.lua or zoxide or CD-Deluxe or another directory changing tool?

If yes, which one?  Maybe that tool is intercepting something or having some kind of problem?

**Comment by rodboev** [comment]
Negative, the `cd` command is the native Windows 10 command:

```
C:\Users\Rod>where cd
INFO: Could not find files for the given pattern(s).
```

**Comment by chrisant996** [comment]
The issue in 709 is completely different and unrelated to whatever you encountered.

In 709, it simply wasn't expanding the ~ before listing matching files.  And since "~" is meaningless on Windows, the list of matching files ended up empty.

In your case, it's trying to run some other program when you press TAB.  That's very strange indeed, and it's not something Clink does unless specifically configured by installing other scripts.

It will have to go in the "mystery" bucket.

**Comment by rodboev** [comment]
At the moment, when I press `TAB` after typing `cd ~` it expands the `~` to `C:\Users\Rod\`. Based on your response I'm not clear if that's the expected behavior or not, but I thought #709 was saying that it was.

**Comment by chrisant996** [comment]
> At the moment, when I press `TAB` after typing `cd ~` it expands the `~` to `C:\Users\Rod\`. Based on your response I'm not clear if that's the expected behavior or not, but I thought #709 was saying that it was.

That is the expected behavior. 

The text "The system cannot find the path specified" is unrelated to 709.  Since the problem disappeared and is working as expected now, it isn't possible to troubleshoot what was happening before.  But whatever was happening is unrelated to 709.
