### ISSUE TITLE
clink breaks my prompt

### ISSUE THREAD

**Issue by dodmi** [chrisant996/clink#74]
Hi, my PROMPT var is
`$E]0;$E]9;8;"USERNAME"$E\@$E]9;8;"COMPUTERNAME"$E\ /CMD 10.0/$E\$E[m$P$S$E[36m$Q$E[m$G$E]9;12$E\`

This should place `<user>@<machine> /CMD 10.0/` to the window title and only `<Drive:\Dir> =>` at the prompt.
This works fine in my (ConEMU) console, until I'm using clink.
Then the title is modified correct, but the prompt is shown as `]9;8;"USERNAME"@<machine> /CMD 10.0/<Drive:\Dir> =>`.
I tried to disable prompt parsing (clink set clink.promptfilter false), but this has no effect. I've also tried to set terminal emulation to native (but this had, as expected, no effect in ConEMU).

Also at the end of the window, my command line gets stumbled. This is maybe caused by the faulty parsing of the ANSI prompt sequences.

This is a screenshot of my cmd window, showing both problems (I've tab completed `clink set clink.promptfilter`)

![image](https://user-images.githubusercontent.com/4572946/108100138-cef42480-7085-11eb-902b-f17a14149716.png)

**Comment by chrisant996** [comment]
Readline documentation states that all ANSI escape codes to be surrounded by `\x01` and `\x02` to tell Readline what parts of the prompt are invisible versus visible.

Clink helps out by detecting a large set of standard ANSI escape codes and automatically adding `\x01` and `\x02`.

But the prompt string here is using escape codes that aren't standard:  `$E]` codes are not standard and are implemented differently by different hosts.  You can use them, but you need to manually surround them with `\x01` and `\x02`.

**Comment by chrisant996** [comment]
With that said, I may be able to extend Clink to recognize some non-standard escape codes.  The risk is that other hosts may interpret the codes differently, and sometimes in incompatible ways.

I'll at least do some research about the specific codes you've listed, and see if there's general consensus about how the codes should be implemented by hosts.

**Comment by chrisant996** [comment]
Ok, what I can do is at least make Clink detect ConEmu's non-standard escape codes when running inside ConEmu, and automatically surround them with `\x01` and `\x02`.

**Comment by chrisant996** [comment]
Should be fixed by b18ff164fa4c9031a01ffc0acb1bcaa5cf5c4c1d.

v1.1.31 will include the fix.

**Comment by dodmi** [comment]
Hi,
first thank you for your quick answer and efforts. And thank you for implementing this :)

So actually, I thought, I was using this as it should be used on Microsoft systems with ConEMU (and it worked until I found clink could improve my user experience with cmd.exe a lot). 

The example for accessing environment variables is actually from [ConEMU's prompt tips](https://conemu.github.io/en/CmdPrompt.html) in combination with [ConEMU's ANSI codes](https://conemu.github.io/en/AnsiEscapeCodes.html).

I admit, my prompt makes really heavy use of the given possibilities...
I'm looking forward to the new release.

**Comment by dodmi** [comment]
Hi, just a short feedback: Works like a charm :)
Thank you again for implementing a fix!
