### ISSUE TITLE
crash when history file contains a line longer than 8192 characters

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/clink#78]
clink info:
version  : 1.1.34.d161e9
session  : 20808
binaries : C:\Users\<user>\scoop\apps\clink\current
state    : C:\Users\<user>\AppData\Local\clink
log      : C:\Users\<user>\AppData\Local\clink\clink.log
settings : C:\Users\<user>\AppData\Local\clink\clink_settings
history  : C:\Users\<user>\AppData\Local\clink\clink_history
scripts  : C:\Users\<user>\scoop\apps\clink\current ; C:\Users\<user>\AppData\Local\clink
inputrc  : %clink_inputrc%
             (unset)
         : %userprofile%
             C:\Users\<user>\.inputrc
             C:\Users\<user>\_inputrc
         : %localappdata%
             C:\Users\<user>\AppData\Local\.inputrc
             C:\Users\<user>\AppData\Local\_inputrc
         : %appdata%
             C:\Users\<user>\AppData\Roaming\.inputrc
             C:\Users\<user>\AppData\Roaming\_inputrc
         : %home%
             C:\Users\<user>\.inputrc
             C:\Users\<user>\_inputrc

clink log and dump:
[clink.zip](https://github.com/chrisant996/clink/files/6073347/clink.zip)

_Originally posted by @windedge in https://github.com/chrisant996/clink/issues/66#issuecomment-789392695_

**Comment by chrisant996** [comment]
@windedge can you clarify some things?

I think you stated that it crashes on `clink inject`.  Can you please clarify/confirm that?  The crash dump appears to indicate that the crash occurred after having entered a command line, sometime after `clink inject`.

I'm not able to reproduce a crash in Clink.  Are there any additional steps or information that could be shared to help track this down?

The crash dump doesn't appear to reveal any clues to what is happening, but the log file has a potential clue:  the last thing in the log file is an attempt to compact the history file.

1. Does it crash every time, or was it a one time occurrence?
2. Would you be willing to share the `clink_history` file and the `clink_settings` files?

**Comment by windedge** [comment]
1 & 2. in cmd.exe, it crash every time after "clink inject" and execute other command , like "dir".

![image](https://user-images.githubusercontent.com/27651/109768008-510e4c80-7c33-11eb-85d4-68cd710c8f19.png)

3. ```clink_settings``` :
``` conf
# name: Breaks into Lua debugger on Lua errors
# type: boolean
lua.break_on_error = True

# name: Enables Lua debugging
# type: boolean
lua.debug = True
```

**Comment by chrisant996** [comment]
Great, thanks, @windedge, that fits with what I see in the crash dump.  Unfortunately the crash dump only captures the exact point at which the crash happens, and it doesn't reveal anything about what led up to the crash.

There is a "time travel debugging" tool that can capture everything leading up to the crash, which helps tremendously in tracking down mystery issues like this one:

Would you be comfortable following steps [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record) to attach to the cmd.exe process and capture a Time Travel Trace of the problem? The steps require WinDbg Preview ([install from here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-install-preview)).

1. Install WinDbgPreview
2. Start cmd.exe
3. Follow the **"Attach to a process"** procedure from [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record) and attach to the cmd.exe (it's the _second_ procedure listed in that article).
4. Run `clink inject`
5. Run `dir`
6. Stop the trace recording after it crashes

And then upload the resulting `cmd*.run` file so I can debug it.

**Comment by windedge** [comment]
The file is too large, I have to upload to other file sharing website, check link below:
https://filetransfer.io/data-package/xNfW8T3f#link

**Comment by chrisant996** [comment]
Thank you!  The file captured the problem.  I can see some kind of memory corruption occurring, and I'll keep analyzing to track down precisely where and why.

I used VS2019 v16.8.6 to compile the code, and yesterday v16.9 was released which has a compiler code gen fix for an issue that looks similar to the corruption I'm seeing.  There's a chance this might be a compiler issue, but it's too soon to say for sure.

I'm still working on narrowing the range of time during which the corruption occurs.  Eventually I'll get it to 0 and will know what's happening, but this is a tricky one and is involving a lot of slogging through assembly language code and tracing values and they move between registers and memory locations over time.  It's straightforward, but goes slowly.

What I don't understand at all is why I'm not experiencing the same crash on my computer.  I'll also do some live debugging to see if the corruption is observable on my computer as well, and perhaps just gets lucky and doesn't crash.

**Comment by chrisant996** [comment]
UPDATE:  Aha, some kind of corruption is happening while loading the `clink_history` file.

Would it be possible to upload your `clink_history` file?  While I won't need it to track down what's going wrong, it will likely make it possible for me to reproduce the crash locally, and therefore will help in validating the fix.

**Comment by chrisant996** [comment]
Found it.  Stack corruption is introduced due to overrunning a buffer by 1 byte, when a history file contains a line that is >= 8192 characters long.

On 2020/11/03 in v1.1.2-alpha (0ac3f2f770b0fd62ee124b90d2bcf53cc2777b4d), I fixed a different history file bug and accidentally introduced this one along the way.

I'll fix it, and a regression test, and then publish a new build.  Due to the testing and validation, it could take an extra day or so.

**Workaround:**

In the meantime, you can make it stop crashing if you manually edit the `clink_history` file and delete any lines that are super long -- to be safe, delete any lines longer than 8100 characters.

**Comment by windedge** [comment]
It won't crash after reduce the ```clink_history``` file, thanks for your quick response, and wait for your update.

**Comment by chrisant996** [comment]
Thank you for reporting this, and I appreciate very much your time and effort collecting the time travel trace!
