### ISSUE TITLE
clink.log is not deleted when Cmder injects Clink

### ISSUE THREAD

**Issue by mariograz** [chrisant996/clink#80]
I know there is a --nolog arguement, is it possible to add a "log=0" in the settings file to disable logging?

**Comment by chrisant996** [comment]
It might be.

Can you describe the motivation behind the request?

What problem is caused by logging, that makes it desirable to permanently disable logging?

**Comment by chrisant996** [comment]
@mariograz Can you describe the motivation behind the request?  What problem is caused by logging?

**Comment by mariograz** [comment]
Sorry It took so long to get back to you, I was unexpectedly away.

I use cmder, and they've recently integrated this clink fork. I don't have a need for logging especially since things are working great.

While the current log file doesn't seem to grow large all that fast, it's just another log file that will need to be managed. 

I think it makes more sense to make logging disabled by default, and if its needed it can be turned on.

As a work around, I tried to use the --nolog argument, but I'm unable to grok where cmder calls clink.

I'm also not looking to make a bunch of work for anyone.

**Comment by chrisant996** [comment]
The log gets deleted and recreated -- its growth is not unbounded.  It doesn't seem to need to be "managed".

I much prefer it to be on always, so that when there's a problem, I can simply say "run clink info to find the log file and attach it".  I have to think about the cost to me, for supporting Clink, and having logging always enabled reduces my personal cost of maintaining Clink.

**Comment by mariograz** [comment]
My log file doesn't seem to be deleted & recreated when I close the shell. It seems to grows about 10-20k every time I execute cmder. Is there a different interval that I should expect it to be refreshed? 

This might not be your issue, it could just be a cmder issue.

I agree with you to have it always on, that definitely would help with support requests.

**Comment by chrisant996** [comment]
`clink inject` tries to delete the log file each time.  So that if no other Clink instances are running, the log gets deleted/created anew.  If any Clink instances are already using the log file, then deletion will fail.

Could it be that there is another Clink instance running?  If you reboot the computer and start a new Clink session, does that start the log file over fresh?

**Comment by mariograz** [comment]
I've restarted the PC & then deleted the existing log file (clink.log). then I ran cmder twice, closing it fully between runs and making sure there were no cmd or clink instances in the process window.

It does not look like the file was deleted, or attempted to be deleted between executions.
I've attached the log file here-
[clink.log](https://github.com/chrisant996/clink/files/6125804/clink.log)

**Comment by mariograz** [comment]
Ok- So I might have wasted your time somewhat. I used procmon.exe to see what was happening, and I noticed that when clink.exe tried to access clink.log the API result was REPARSE.
That reminded me that I keep the cmder configuration directory (Which contains the clink.log file) in a hardlinked location. I believe this is causing old behavior with the logfile recreation api call. 

![image](https://user-images.githubusercontent.com/10872062/110852524-7b3dbb00-8280-11eb-885d-8365b6ad304b.png)

I'm sorry about that.

**Comment by chrisant996** [comment]
Aha!  It isn't the hardlink.

Cmder overrides the default Clink profile directory.
`clink inject` builds an application context to inject into cmd.exe, using the overridden profile directory.
However, when `clink inject` deletes the `clink.log` file, it uses _its own_ application context by mistake -- it should have used the _injected_ application context for that particular operation.

Thanks for discovering and reporting this!
