### ISSUE TITLE
[Feature Request] Support autocompletion when using git alises

### ISSUE THREAD

**Issue by ovasquez** [chrisant996/clink#83]
As the title says; I think this would be a very good addition for Cmder.

- This was initially reported in the Cmder repo here: https://github.com/cmderdev/cmder/issues/1495
- And they were instructed to report it in the Clink repo, however that seems to be unmaintained: https://github.com/mridgers/clink/issues/517

**Comment by chrisant996** [comment]
Can you please clarify?

The [clink-completions](https://github.com/vladimir-kotikov/clink-completions) repo already supports autocompleting git aliases, and has since 94b6a712d632c43497fc4e91404d98e07281609f in July 2015.

If git is not on the PATH then that won't work

**Comment by chrisant996** [comment]
Oh, you're not asking for aliases to autocomplete.  You're asking for the _arguments_ of git aliases to autocomplete the same as if an alias were not used.  Got it.

That isn't something Clink can do anything about.  The scripts in the [clink-completions](https://github.com/vladimir-kotikov/clink-completions) repo control that, and they would need to be updated.  Has the issue been reported there yet?
