### ISSUE TITLE
Restoring "use_altgr_substitute" setting like it was in clink 0.4.9 ? Very convenient for EU keyboards.

### ISSUE THREAD

**Issue by Gilles-Maisonneuve** [chrisant996/clink#84]
Good afternoon,
Would it be possible to re-enable / re-create the 'use_altgr_substitute' functionality in the "clink-settings" file ?
I am using French / Belgian-French keyboards and for us the AltGr-E expands in the Euro (€) character. Therefore when trying to expand the environment variables at the console (let say %WINDIR% or %USERPROFILE% for example) it does not expand it, but just insert a '€' at the end of it.
This was particularly convenient in previous 0.4.9 release.
I understand of course that this is not one of your major concern, but really that would be helpful in a future release when you have time (checking each user's %USERPROFILE% by "echo %USERPROFILE% prior to entering a command instead of just checking it while typing the command on the spot with CTRL-ALT-E, is annoying).

Thank you nevertheless for your very nice tool, bringing back the emacs-edit mode of our ancient Unix shells (ksh set -o emacs...); It's a real pleasure to benefit from your very dedicated work.

Have a good day.

Gilles, from Brussels.

**Comment by chrisant996** [comment]
Hi @Gilles-Maisonneuve and thank you for bringing this up.

I'm in the US where our keyboards don't have a physical AltGr key, and I'm having some trouble finding good technical information about detecting AltGr.  Maybe you can help me clear up some confusion?

- Do you have a physical AltGr key, or is another physical key (or combination) mapped to AltGr?  Which key is mapped to AltGr?
- Are you using any special tools to map AltGr key, or does Windows automatically handle it?

I think you might mean that your keyboard is set up to simulate AltGr when Ctrl+Alt are pressed together.
Are you saying that you press Ctrl+Alt+E and Clink interprets it as AltGr+E?
Or are you saying that you press AltGr+E and Clink interprets it as Ctrl+Alt+E?
Or maybe you're saying something else?

I apologize for my confusion -- I've always been curious about AltGr but have never gotten around to learning the technical details about it (since there seems to be no way for me to use it with a US keyboard).

**Comment by chrisant996** [comment]
Also, are you asking for `use_altgr_substitute` = `0`?  Or = `1`?

**Comment by chrisant996** [comment]
Oh, or are you saying you want the following?
- Set `use_altgr_substitute` = `0`
- And make Clink interpret LeftAlt+LeftCtrl as _**not**_ the AltGr substitute, but instead as LeftAlt+LeftCtrl?

**Comment by chrisant996** [comment]
Also, I can't figure out how to test this:
- I have a physical US keyboard.
- My locale is set to US.
- My keyboard layout is set to **French**.

Using **clink v0.4.9** with use_altgr_substitute = `1`:
- RightAlt+E = Euro.
- RightAlt+RightCtrl+E = Euro.
- LeftAlt+LeftCtrl+E = Euro.

Using **clink v0.4.9** with use_altgr_substitute = `0`:
- RightAlt+E = Euro.
- RightAlt+RightCtrl+E = Euro.
- LeftAlt+LeftCtrl+E = Euro.

I see no difference in behavior when use_altgr_substitute is on or off.
So I wonder if it's not possible for me to test it with a physical US keyboard??

**Comment by chrisant996** [comment]
Fixed by d9b13fd9e548d4b3af27d9c537c8b03471c28c21.

**Comment by Gilles-Maisonneuve** [comment]
Good afternoon Christian,
1. I have an old AZERTY IBM AT keyboard I succeeded to plug in my USB port, I am going to try to send you a picture of it later on. YES it has an ALTGR physical key right to the space-bar (while the only ALT key is on the left of the space-bar). There are 2 (left and right) CTRL keys on the bottom far left and far right of the keyboard.
2. NO : what I am saying is that, - under CMD console using CLINK - I would like to be able to enable a setting that CANCEL the possibility for the [both left and right]CTRL-ALT[there is only one ALT, the left] sequence to MEAN "ALTGR". Because on most Western European keyboards (French, Belgian, Italian, Spanish, I guess German but not sure) we have one ALTGR key which is the one at the right of the spacebar and is, as far as I remember an US AT keyboard your secondary (right) ALT key. 
So I would like it to be possible to disable the sequence left|right-CTRL-leftALT to be equivalent to ALTGR so that it does not produce extended European chars but rather execute a US-keyboard-like command (such as CTRL-ALT-E = expand var) while retaining the ALTGR key (should be US right-ALT) to produce extended chars (such as € or @ [ALTGR-à]...).
3. the setting in 0.4.9 to get that was specifically "use_altgr_substitute = 0".

See:
C:\Users\gm>REM ALTGR- é " ' ( - è _ ç à ) =
C:\Users\gm>REM give
C:\Users\gm>REM        ~ # { [ | ` \ ^ @ ] }
C:\Users\gm>REM So ALTGR key is needed.
C:\Users\gm>REM But CTRL-ALT-E on %USERPROFILE%
C:\Users\gm>REM gives
C:\Users\gm>REM C:\Users\gc
C:\Users\gm>REM This is because the altgr setting is set to 0:
C:\Users\gm>grep -i altgr c:\PROGRA~2\clink\043213~1.9\profile/settings
# name: Support Windows' Ctrl-Alt substitute for AltGr
# Windows provides Ctrl-Alt as a substitute for AltGr, historically to support
# keyboards with no AltGr key. This may collide with some of Readline's
use_altgr_substitute = 0

C:\Users\gm>REM With use_altgr_substitute=0, pressing CTRL-ALT does NO longer
C:\Users\gm>REM produce the same thing as pressing the ALTGR key.

Am I a little bit clearer now ?

Look, my keyboard is the same as this one (the picture is in English qwerty, mine is azerty):
http://www.seasip.info/VintagePC/Images/1391406.jpg (from wikipedia)
or this one (German):
https://upload.wikimedia.org/wikipedia/commons/f/f2/IBM_Model_M_1391403_keyboard.jpg

I was unable to find a French 1986 AT AZERTY keyboard picture but the layout is the same as this one, except that mine does not have Windows keys nor local-menu (right-click) key.
http://www.ibt.ca/v2/items/btc5121w/images/azerty_1.jpg

The point is only to show you that on European keyboard (English or Grench or German on the pictures) we have ALT on the left of the spacebarre and ALTGR on the right while you in the US have on an AT 1986 2 alt keys, like on this picture:
https://upload.wikimedia.org/wikipedia/commons/3/34/IBM_Model_M5-2.png

Did this help ?

Have a good evening, let me know if I need to improve my answer.

Gilles

Look at the alt and altgr keys.

**Comment by Gilles-Maisonneuve** [comment]
sorry wrong fonts in answer. I don't know why and was unable to edit it back to correct.

**Comment by Gilles-Maisonneuve** [comment]
Oops, sorry I was late and the time it took me to write you a proper answer you already have finished to answer and to code.
My bad timing, excuse me.
Thank you for your help, and have a nice week end.

**Comment by chrisant996** [comment]
I appreciate very much the detailed and informative reply, thank you!

Does the updated Clink behave as expected?  It seems to in my testing, but I'm only able to test it with an emulated keyboard so it's possible that a real AltGr keyboard might function slightly differently or something.

Thank you for reporting this and helping me learn about AltGr!

Chris

**Comment by chrisant996** [comment]
I found a bug in how Clink v0.4.9's `use_altgr_substitute` = `0` behaves.  It seems to work ok with a keyboard layout that has <kbd>AltGr</kbd>, but it accidentally breaks the <kbd>RightAlt</kbd> key in general on other keyboard layouts.

I have a fix that will be published this evening.  The fix makes it so the new `terminal.use_altgr_substitute` = `False` setting _only_ affects <kbd>AltGr</kbd> substitute key combinations (i.e. <kbd>LeftAlt</kbd> + either <kbd>LeftCtrl</kbd> or <kbd>RightCtrl</kbd>), without affecting any other key combinations.

**Comment by Gilles-Maisonneuve** [comment]
Good evening Christian,
1. yes, thank you, the enhancement works like a charm. AltGr still acts perfectly to provide the appropriate regular US character one needs to program (~@#{}[]| and \) and also the Western European chars (€ÀÉÙÑ...);
2. Never been able to detect 0.4.9 AltGr bug, as I did not work on a PC (Win) with a native US keyboard since the end of the '80s, but only on Unix servers, where, obviously, no one has the need for the clink emulation. As a native keyboard user you are much more aware of that kind of things. I guess that is due to the fact that the right ALT key might have been treated by 0.4.9 in a undifferenciated way as always been AltGr then.

So, for me, the new feature is already bugfree with the current (1.1.38.8e7887) version. But, of course, the main audience being US keyboard users, your new version will certainly be much appreciated.

Thank you very much for your help and patience. And congratulations for the rapidity of your coding.

Have a nice week end.
Gilles
