### ISSUE TITLE
[BUILD] undeclared identifier ENABLE_VIRTUAL_TERMINAL_PROCESSING when building version 1.1.37.61b9a3 of clink_test project

### ISSUE THREAD

**Issue by jackL999** [chrisant996/clink#85]
The clink_test project fails to compile when using vs2017. It produces the error "ENABLE_VIRTUAL_TERMINAL_PROCESSING is an undeclared identifier" at line 74 of main.cpp 
SetConsoleMode(h, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);

A quick fix is to change the project's Windows SDK from 8.1 to 10.0.x.  In the Windows 10 SDK, ENABLE_VIRTUAL_TERMINAL_PROCESSING is defined in consoleapi.h as 0x0004

**Comment by chrisant996** [comment]
Oops.  I'll rearrange things slightly.  The intent is that Clink should compile cleanly with Win 8.1 SDK, but I don't build that configuration so occasionally I'll accidentally break it.  That particular identifier has a workaround for Win 8.1 elsewhere, and I'll apply a similar workaround in clatch.*.

**Comment by chrisant996** [comment]
Fixed by d63a5964eff8751f30fbb59015113914dcc00ffe.
