### ISSUE TITLE
Setting `history.save` to False also disables interactive history in subsequent sessions

### ISSUE THREAD

**Issue by zx64** [chrisant996/clink#94]
In the version of clink I used previously (0.4.9), history saving was disabled by setting `history_file_lines = -1` (0 meant "no limit").

This would ultimately get passed through to https://github.com/mridgers/clink/blob/2fd2c2bbad3820c5e4e39b200a9b6e5d893ddf54/clink/dll/history.c#L68

I noticed this is where the new preference is checked: https://github.com/chrisant996/clink/blob/b2ef0315dbee3ce1795e57856190f9dd5cb54f7f/clink/app/src/host/host.cpp#L593
and checking what was in 1.0a shows it always initialised the history database: https://github.com/mridgers/clink/blob/823d841bc5c38a83c3cc0991c1f3ff8099d83fb5/clink/app/src/host/host.cpp#L125 however I'm not familiar with how 1.0a handled disabling saving history so this might be an unimportant detail.

**Comment by chrisant996** [comment]
Thanks, I can reproduce the issue.

1.0a did not support disabling saving history; I added that in 3a338f7bddfe06afc48661734ce457ddda928e79.

I'll investigate and fix, thanks!

**Comment by zx64** [comment]
Can confirm the fix works for me, thanks!
