### ISSUE TITLE
Clink unable to tab complete with files in folder

### ISSUE THREAD

**Issue by trungking** [chrisant996/clink#95]
When using clink, it is unable to tab complete file name in a directory.
You can check the video attached.

https://user-images.githubusercontent.com/18730477/112933572-51263d00-914a-11eb-8711-727ab8f84fdf.mp4

**Comment by chrisant996** [comment]
That seems to be operating as intended and documented, but please confirm by checking what `clink set exec.enable` says.  Consider turning that setting off, if its behavior is undesirable.

I encourage reading the documentation, and offering constructive feedback on how to improve the documentation.

Thank you!
