### ISSUE TITLE
Wrong setting string

### ISSUE THREAD

**Issue by Speravir** [chrisant996/clink#96]
In clink documentation both [online](https://chrisant996.github.io/clink/clink.html) and the file shipped with the program there is a setting `history.dont_add_to_history_cmds` documented, but using this will leave to an error message.
```
ERROR: Setting 'history.dont_add_to_history_cmds' not found.
```
Turns out it has to be in singular form: `history.dont_add_to_history_cmd`.

So either the documentation should be adjusted or the setting itself, or if possible an alias should be added.

**Comment by chrisant996** [comment]
Oops. I'll update the html documentation file.

**Comment by chrisant996** [comment]
Actually I ended up deciding to increase the max length to 32 so the name can be accurate (it should be plural).  And I added assertions to prevent similar future mistakes.
