### ISSUE TITLE
Compilation of ebc3290 in vs2017 produces error C2039: 'min': is not a member of 'std'  in file word_classifications.cpp(103)

### ISSUE THREAD

**Issue by jackL999** [chrisant996/clink#97]
The problem is easily solved by adding 
#include < algorithm >
 to the file word_classifications.cpp

**Comment by chrisant996** [comment]
Thanks!  It should use `min<unsigned int>` instead.  Clink doesn't use `std::min` or `std::max` and has its own `min<>` and `max<>` templates that can be explicitly typed, avoiding troublesome explicit casts.

**Comment by chrisant996** [comment]
Fixed by c411444727356c82f20b69ef712649313e36ffb7.
