### ISSUE TITLE
Set profile path via env variable

### ISSUE THREAD

**Issue by sebthom** [chrisant996/clink#98]
The clink documentation says I can launch clink with --profile to specify a custom path for the profile.

I am using clink with [conEmu](https://conemu.github.io/en/TabCompletion.html). There I have no option to specify the --profile path as it directly uses the clink dll.

So I wonder if you could maybe add the possibility that the profile path can be specified via an environment variable, e.g. CLINK_PROFILE_ROOT

**Comment by chrisant996** [comment]
It already can be.

But Cmder already sets the profile path. Overriding Cmder's profile path would create problems in Cmder. And it isn't possible to have two different profile directories at the same time.

Can you describe the motivation for wanting to use a different profile directory? Maybe there's another way to solve whatever problem has been identified.

**Comment by sebthom** [comment]
I am not using cmder (and don't plan to use). I am only using conEmu which I want to use in a portable way which requires me to be able to specify the path for the clink profile.

**Comment by sebthom** [comment]
This is the only option I see in conEmu regarding clink. There is no possibility to specify any arguments:
![image](https://user-images.githubusercontent.com/426959/114076519-0a9db480-98a7-11eb-9d0d-98c29af63a79.png)

**Comment by chrisant996** [comment]
Oh, I see.  ConEmu has some hard-coded built-in stuff that just internally adds a `clink inject` command with some pre-defined options.

Instead of using that checkbox, you can invoke `clink inject --profile your_directory` directly.  Run it as part of the startup commands for the task.  See the Clink docs for more information about how to start Clink.

**Comment by sebthom** [comment]
That worked. Thanks!
